### ISSUE TITLE
TEST: granát

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#1]
Predmet granát bude teba otestovať v hre, či správne funguje a či je preložené všetko ako má byť vrátane údajných dvoch módov použitia... hod a kotúlanie.

**Comment by Honzixx** [comment]
Granát jsem otestoval, funguje tak, že se dá hodit vrchem nebo po přepnutí se hodí po zemi (kutálení).
Přeložený a funkční je. https://snag.gy/STgupa.jpg
