### ISSUE TITLE
Translate LIP float male generic

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#100]
cestina\sound\character\male\
cestina\sound\character\male\unique\target_suspect_#.lip

**Comment by miracleflame** [comment]
-"Jesus!"
+"Ježíš!"

-"Oh my god!"
+"Můj bože!"

-"What's wrong?"
+"Co se děje?"

-"Uh, where the hell am I?"
+"Kde to k čertu sem?"

-"What am I doing here?"
+"Co tady dělám?"

-"What's going on?"
+"Co se deje?"

-"What the! Wha... what's up?"
+"Co to! Co... Co se stalo?"

-"Uh, man!"
+"Pane jo!"

-"Get out of my head! Argh!"
+"Vypadni z mý hlavy!"

"Ugh- argh- ugh- get- get out of my head!"
+"Vypa- vypadni z mý hlavy!"

-"Uh, they're gone."
+"Je pryč."

-"I lost 'em."
+"Stratil jsem stopu."

-"Hey, where'd they go?"
+"Hej, kde jseš?"

-"Shit, can't find 'em."
+"Sakra, nevím, kde je."

-"Uh, damn it!"
+"Zatraceně!"

-"Oh, well."
+"Tak nic."

-"Ekh, oh whatever."
+"Tak tedy co už."

-"Hey, stop right there."
+"Hej, zůstaň, kde jseš."

-"Freeze!"
+"Ani hnout!"

-"Hey, hold it!"
+"Hej, stůj!"

-"Hey, you there, stop!"
+"Hej, ty tam, stůj!"

-"STOP!"
+"Stůj!"

-"Uh, they're gone."
+"Je pryč."

-"Hey, I know you're around here!"
+"Hej, vím, že tu někde jseš!"

-"Come on!"
+"No tak!"

-"You can't hide from me!"
+"Přede mnou se neukryješ!"

-"Whaa..?"
+"Co..?"

-"Hey, who's there?"
+"Hej, kdo je tam?"

-"'Someone there?"
+"Je tam někdo?"

-"Who's that?"
+"Kdo je to?"

-"Hey, is someone there?"
+"Hej, je tam někdo?"

-"Who's that, who's there?"
+"Kdo to byl, kdo je tam?"

-"Oh, what's that?"
+"Co to je?"

**Comment by maarten93** [comment]
-"Jesus!"
+"Ježíš!"
+"Ježíši!"

-"Oh my god!"
+"Můj bože!"

-"What's wrong?"
+"Co se děje?"
+"Co se stalo?"




-"Uh, where the hell am I?"
+"Kde to k čertu sem?"
+"Kde to k čertu jsem?"

-"What am I doing here?"
+"Co tady dělám?"

-"What's going on?"
+"Co se deje?"

-"What the! Wha... what's up?"
+"Co to! Co... Co se stalo?"
+"Co to! Co... co se stalo?"

-"Uh, man!"
+"Pane jo!"

-"Get out of my head! Argh!"
+"Vypadni z mý hlavy!"

"Ugh- argh- ugh- get- get out of my head!"
+"Vypa- vypadni z mý hlavy!"

-"Uh, they're gone."
+"Je pryč."

-"I lost 'em."
+"Stratil jsem stopu."
+"Ztratil jsem stopu."

-"Hey, where'd they go?"
+"Hej, kde jseš?"
+"Hej, kde jsi?"

-"Shit, can't find 'em."
+"Sakra, nevím, kde je."
+"Sakra, nevím kde je."

-"Uh, damn it!"
+"Zatraceně!"

-"Oh, well."
+"Tak nic."

-"Ekh, oh whatever."
+"Tak tedy co už."
+"O nic nejde"

-"Hey, stop right there."
+"Hej, zůstaň, kde jseš."
+"Hej, zůstaň kde seš."

-"Freeze!"
+"Ani hnout!"

-"Hey, hold it!"
+"Hej, stůj!"

-"Hey, you there, stop!"
+"Hej, ty tam, stůj!"

-"STOP!"
+"Stůj!"

-"Uh, they're gone."
+"Je pryč."

-"Hey, I know you're around here!"
+"Hej, vím, že tu někde jseš!"
+"Hej, vím že tu někde seš!"

-"Come on!"
+"No tak!"

-"You can't hide from me!"
+"Přede mnou se neukryješ!"
+"Přede mnou se neschováš!"

-"Whaa..?"
+"Co..?"

-"Hey, who's there?"
+"Hej, kdo je tam?"

-"'Someone there?"
+"Je tam někdo?"

-"Who's that?"
+"Kdo je to?"

-"Hey, is someone there?"
+"Hej, je tam někdo?"

-"Who's that, who's there?"
+"Kdo to byl, kdo je tam?"

-"Oh, what's that?"
+"Co to je?"

**Comment by soulcharmer** [comment]
jen par drobnych uprav:

-"What's going on?"
+"Co se deje?"
+"Co se děje?"

-"Get out of my head! Argh!"
+"Vypadni z mý hlavy!"
+"Vypadni z mé hlavy!"

"Ugh- argh- ugh- get- get out of my head!"
+"Vypa- vypadni z mý hlavy!"
+"Vypa- vypadni z mé hlavy!"

-"Hey, where'd they go?"
+"Hej, kde jseš?"
+"Hej, kde jsi?"
+"Hej, kde je?"

-"Ekh, oh whatever."
+"Tak tedy co už."
+"O nic nejde"
+"O nic nejde,"

-"Hey, stop right there."
+"Hej, zůstaň, kde jseš."
+"Hej, zůstaň kde seš."
+"Hej, už ani krok."

-"Hey, I know you're around here!"
+"Hej, vím, že tu někde jseš!"
+"Hej, vím že tu někde seš!"
+"Hej, vím že tu někde jsi!"



diky
