### ISSUE TITLE
Translate LIP float monster

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#101]
cestina\sound\character\monster\*

**Comment by miracleflame** [comment]
-speaker_name Ghost
+speaker_name Duch

-"Don't you dare touch me!"
+"Neopovažuj se mně dotýkat!"

-"Stand back!!!"
+"Drž se stranou!!!"

-speaker_name Vampire
+speaker_name Upír

-"Lost 'em."
+"Je pryč."

-"'Came behind 'em."
+"Zaostal jsem"

-"Arrgh... Where'd they go?"
+"Kde je?"

-"What was that?"
+"Co to bylo?"

**Comment by soulcharmer** [comment]
-speaker_name Ghost
+speaker_name Duch

-"Don't you dare touch me!"
+"Opovaž se mě dotknout!"

-"Stand back!!!"
+"Už ani krok!!!"

-speaker_name Vampire
+speaker_name Vampír

-"Lost 'em."
+"Je pryč."

-"'Came behind 'em."
+"Jsem tu pozdě."

-"Arrgh... Where'd they go?"
+"Kde je?"

-"What was that?"
+"Co to bylo?"
