### ISSUE TITLE
VV dlg replika 301

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#102]
{	301	}{	Teď pracuje v Kotli hříchu. Je to blondýna. [quickly, snidely]A ještě má na zádech vytetované zlomené srdce. Její umělecké jméno je Stydlivka. Víc se snad ani prozradit nemohla.	}{	Teď pracuje v Kotli hříchu. Je to blondýna. [quickly, snidely]A ještě má na zádech vytetované zlomené srdce. Její umělecké jméno je Stydlivka. Víc se snad ani prozradit nemohla.	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{		}{	}{	}{	}{	}{	}{	}{		}

Nejako mi to tam nesedí. Nemalo by tam byť "Víc JseM snad ani prozradit nemohla.	"?

**Comment by soulcharmer** [comment]
She works over at the Sin Bin now. Her hair's blonde - [quickly, snidely]on top, broken heart tattoo on the small of her back. Dances under the name Chastity... as if **that** wasn't a dead giveaway.

VV nemluvi o sobe, ale o tom jmene, ktere se da prelozit taky jako Cistota (coz by ale znelo hrozne) a odkazuje na to, ze Chastity jako lovkyne "cisti" svet od vampiru.

Not a bug :)
