### ISSUE TITLE
Rozšírenie repa o samostatnú utf8 a 1250 verziu

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#103]
Považujem už za nevyhnutné rozšíriť repo o čiste pracovnú východziu verziu kompletne v utf8 bez rozdielu, kde sa bezproblémovo bude diffovať a trackovať a doplniť konverziu do 1250, ktorá bude prechodným spracovaním do font friendly podoby prekladu. Tomu sa prispôsobia všetky skripty.

**Comment by miracleflame** [comment]
@soulcharmer chcem Ťa poprosiť o dve veci, ak sa bude dať

1. cp konverzné skripty *.sh doplň o podmienku, aby nespracovávali *.mp3, *.vcd a *.wav

2. LIP skripty *.rb ukončia proces spracovania pokiaľ natrafia na problém typu, že vrchný riadok lipu nezačína úvodzovkami... máme tam úmyselne označených zopár lipov (príklad cestina_1250\sound\character\male\sabbat_thug\target_suspect_1.lip), kde vrchný riadok začína slovom CITOSLOVCE a na týchto súboroch sa skript zasekne a ukončí. Našim zámerom je, aby tieto súbory preskočil (neupravil platný počet znakov vo PHRASE) a aby pokračoval v spracovaní ďalších lipov až do konca... Dalo by sa to opraviť?

**Comment by soulcharmer** [comment]
co znamena BUGGED v ./cestina_1250/sound/character/male/officer/target_reacquired_1.lip  ?

**Comment by soulcharmer** [comment]
kdyztak pls commity vyse otestuj na testovaci vetvi nebo mimo repo - melo by to jet

**Comment by miracleflame** [comment]
O BUGGED pojednávam v #98 

translate_lip.rb som otestoval a funguje skvele.

Niečo sa mi stalo so spúšťaním .sh 
bash: ./1250_dump.sh: Permission denied
bash: ./UP+1250_dump.sh: Permission denied

Keď skúsim vykopírovať textový obsah do nového súboru random.sh a spustím ten, vôbec nič sa nestane.

**Comment by miracleflame** [comment]
Oprava unixových práv zabrala, len nechápem, jak je možné, že keď si identický skript vytvorím u seba v notepade++, tak to nič nerobí.

Vo výnimke bola chybka, ale to som už opravil 65292e081b3179c467557790f12cf84db2dbf0b0 Každopádne už to všetko komplexne spolu fachá a celé repo sa dá ovládať skriptami od bodu A až do skompilovania inštalačky bez akýchkoľvek manuálnych zásahov. Tiket uzavrený.
