### ISSUE TITLE
Preformulovať cestina\sound\area\downtown\malkavian\dictation_message_5.lip

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#105]
...v snahe vyhnúť sa zalomeniu práve tesne pred slovom "účinný", čo spôsobí nevykreslenie znaku ú

"Po letech výzkumu mé choroby v izolaci jsem zjistil, že jí zdaleka netrpím jen já. Vskutku, město je domovem pro celou společnost podobně postižených jedinců, se kterými jsem teprve nedávno navázal kontakt. Z pochopitelných důvodů jsou poměrně značně odměření, ale potvrdili mi, že skutečně jde o vampirismus... vyskytující se v mnoha děděných liniích, každá s řadou pozoruhodných příznaků, jako je neviditelnost nebo dokonce jistá podoba lykantropie. V průběhu mnoha oficiálních setkání s vládnoucím sborem této tajné společnosti... jsem dospěl k závěru, že jejich elementární porozumění vampirickému stavu... je žalostně nedostatečné a je zatížené paranoiou a pseudo-náboženskými dogmaty, ze kterých by se nejednomu Turkovi zatočila hlava. Věru jsem je zaujal výsledky svého výzkumu a výřečností, s jakou jsem je prezentoval - typický představitel mé vampírské linie bývá zřejmě daleko od suchopárného vyjadřování. Oslovil jsem je dokonce natolik, že mi ve své vládě nabídli úřad - a vypadá to na poměrně významné místo - myslím, že bych ho měl přijmout. Kdyby nic jiného, poskytne mi pozici s velkým přehledem, ze které budu moci pozorovat epidemiologii naší choroby v plné šíři, a tím snad též rychleji vyvinout účinný lék."

**Comment by soulcharmer** [comment]
jasny, proste pouzijeme synonymum a problem zmizi :-)

Jeste jsem tam udelal par dalsich drobnych uprav, tak to zkoukni a prevezmi cele. Diky!


"Po letech výzkumu mé choroby v izolaci jsem zjistil, že jí zdaleka netrpím jen já. Vskutku, město je domovem pro celou společnost podobně postižených jedinců, se kterými jsem teprve nedávno navázal kontakt. Z pochopitelných důvodů jsou poměrně značně odměření, ale potvrdili mi, že skutečně jde o vampirismus... vyskytující se v mnoha děděných liniích, každá s řadou pozoruhodných příznaků, jako je neviditelnost nebo dokonce jistá podoba lykantropie. V průběhu mnoha oficiálních setkání s vládnoucím sborem této tajné společnosti... jsem dospěl k závěru, že jejich elementární porozumění vampírskému stavu... je žalostně nedostatečné a je zatížené paranoiou a pseudo-náboženskými dogmaty, ze kterých by se nejednomu Turkovi zatočila hlava. Věru jsem je zaujal výsledky svého výzkumu a výřečností, s jakou jsem je prezentoval - typický představitel mé vampírské linie bývá zřejmě dalek suchopárného vyjadřování. Oslovil jsem je dokonce natolik, že mi ve své vládě nabídli úřad - a vypadá to na poměrně významné místo - myslím, že bych ho měl přijmout. Kdyby nic jiného, poskytne mi pozici s velkým přehledem, ze které budu moci pozorovat epidemiologii naší choroby v plné šíři, a tím snad též rychleji vyvinout efektivní lék."
