### ISSUE TITLE
Nepřeložené texty a korektura

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#108]
Ahoj, tak zatím mám pár nálezů, tak snad to zde vypíšu správně. Vše až na poslední jsou chyby v dialozích a hraju za ženu Toreador s češtinou UP Plus.

1. Jack v tutoriálu opravit předložku "ta" aby bylo "na" ve větě:
Krysožroutko. Hej, mně to nevadí, ale jen abys věděla, kulturní vampírská společnost se ta tyhle věci dívá
svrchu.
https://snag.gy/lSn7Md.jpg

2. Gimble v SM vlastník obchodu s protézama. jedna věta nepřeložená:
Ah! An eager participant! Very good. Just give me few moments to get my equipment ready, and then come on in and we´ll get started...
https://snag.gy/0TVrj9.jpg

3. Tereza v SM. V dialogu jsou na výběr 2 odpovědi se stejnou větou, tak by to tu druhou větu chtělo předělat ve smyslu omluvy. Tereza na tu druhou možnost reaguje né tak rozzuřeně. Věta, která je tam tedy dvakrát pod sebou jako naše volba:
Aspoň jsem ti přinesla ten zatracenej krám z hotelu! Vem si ho!
https://snag.gy/HP49zh.jpg
Předělal bych tu druhou větu na něco jako:
Byla to chyba, mrzí mě to. Ale mám pro tebe tu věc z hotelu! Tady máš!

4. Venuše v Centru města. Je špatná jedna naše odpověď:
Dík. A zbav se toho otravnýho turnikétu, až můžeš.
https://snag.gy/1gheKd.jpg

Pokud to už nemáte opravené, mám návrh:
Dík. A zbav se toho otravnýho turniketu, než se vrátím.

5. Pisha v Centru města. V naší odpovědi je špatně druhá věta:
Morálnost? Nasrat na něj. Pobavme se radši o těch artefaktech, cos zmiňovala.
https://snag.gy/57qS6W.jpg

Návrhy opravy druhé věty:
Seru na ni. Kašlu na ni.

6. Postava Jumbles v Centru města, je to takový vrátný v questu s morovou nákazou. Jedna jeho nepřeložená věta:
I see. Welcome to brotherhood. The Bishop will see you upstairs.
https://snag.gy/1lTN7q.jpg

7. Nines Rodrigez v Centru města. Není chyba v překladu, ale při této větě Nines nemluví, ale měl by.
Co si pamatuju, tak to dělala chybějící uvozovka ve zdrojáku, která ohraničuje text. Věta je:
Nic takovýho... A opakuju, mládě, dávej si pozor, kde něco takovýho říkáš - koleduješ si o nakládačku. Už od svýho uchvácení bojuju za to, aby L.A. bylo svobodný. A po té době jsem jeden z mála, co nezradili ani nepřeběhli na jinou stranu. Prostě nejstarší veterán na bojišti.
https://snag.gy/An8Kdx.jpg

8. Postava The Tzimisce v Hollywoodu v questu s hororovou kazetou nemá přeložený žádný text vlevo nahoře (jako když rádio). Pro dohledání dám něco z těch textů, ale celkem je tak 3-6 vět:
Ahh, hello young cainite.
Tell me childe, is my appearance that frightening, or is it my knowledge of you that is so unnerving?
https://snag.gy/YHquhQ.jpg

To je vše, doufám, že jsem to sem zapsal správně. Všechny tyto chyby mám i nascreenované, kdyby bylo třeba, zašlu na mail ;-)

**Comment by miracleflame** [comment]
1. opravené na "na"

2. použitý preklad z line111_col_e.lip

3. dôkladne porovnané s UP verziou a pridaná drobná úprava (**treba otestovať a oscreenshotovať**)

**4. nechám na zváženie @soulcharmer** 
pôvodne: Thanks. And get rid of that annoying turnstile, will you?

**5. nechám na zváženie @soulcharmer** 
pôvodne: Morality? Screw him. Let's talk about those artifacts you mentioned.
Je to replika charakteru s nízkou Lidskostí na toto od Pishe:
The kine's fate was sealed the moment he entered. Do not waste time debating the morality. If a man walks into a tiger's domain, it may result in his being devoured. So it has.
Čiže Screw him je odvolávka na zavraždeného chlapíka.

6. použitý preklad z line21_col_e.lip

7. pridané VCD a MP3 pre female

8. pridal som nejaké lipy, ktoré by to mali vyriešiť  (**treba otestovať**)

Díky za dobré postrehy. Je lepšie kúskovať to do samostatných issues pre každý jeden prípad, než takto všetky naraz. Screenshoty sú najlepšie na odchytávanie chýb, kvôli presným citáciám. K tomuto by sa mi hodili screeny k bodu 8. 

V rámci otestovania samotnej opravy je dobré mať porobené savy pred danou chybou. Na základe commitu  	4701aa3 si môžeš zoznam upravených súborov skopírovať z repa do hry a otestovať orpavu. Počítaj s tým, že sa tam rozbijú znaky s diakritikou, lebo pre správne zobrazovanie diakritiky je potrebné prehnať texty viacerými skriptami, ktoré ich upravia do fontfriendly podoby. Ale v rámci testovania opravy sa neoplatí preháňať to všetko skriptami.

**Comment by Honzixx** [comment]
Přidal jsem screeny do tématu, dále budu zakládat samostatná témata ;-)

**Comment by Honzixx** [comment]
body 3, 7, 8 testováno:
3. vznikla chyba, v konverzaci skončím zde s anglickou větou, když ji zvolím, ukončí se konverzace a mohu ji začít znova. Takže k původnímu problému na otestování se ani nedostanu.
https://snag.gy/PrehEw.jpg

7. Ninesovi stále chybí mluvící animace u  této věty, nedošlo k žádné změně.
https://snag.gy/An8Kdx.jpg

8. Tzimisce teď ten horní text v rohu nemá vůbec, a navíc postava neotvírá ústa když mluví, ani v konverzaci.
https://snag.gy/WJrYfP.jpg
https://snag.gy/MNfcsK.jpg

**Comment by miracleflame** [comment]
3. Hmmm, to je nejaká blbosť, ide o úplne inú repliku než akých vychádzali opravy v commitoch. Ani som neobjavil v čom by tam mal byť problém, Hádam to konverzia do fontfriendly formátu vyrieši.
Použi cestina_fontfriendly\dlg\santa monica\therese.dlg

7. Uisti sa, že máš naozaj máš line241_col_f.mp3 a line241_col_f.vcd v Unofficial_patch\sound\character\dlg\main characters\nines\

8. lipy skutočne nie sú použiteľné bez toho, aby prešli konverziami do fontfriendly podoby.
Použi cestina_fontfriendly\sound\character\dlg\hollywood\andrei\*

**Comment by Honzixx** [comment]
Tak otestoval jsem vše kromě 4 a 5, k tomu se ještě Soulchamer nevyjádřil. Už chápu, proč má mít každá chyba své téma, začínám se v těch souborech trochu ztrácet :-D Bohužel jsou všechny dialogy rozbité nejspíš stejným způsobem. Vše jsem zkoušel několikrát, i jsem několikrát znovu bral upravené soubory odsud, abych něco nevynechal ;-) @miracleflame 

1. hned na začátku dialogu vyskočí toto, a po volbě se dialog ukončí. https://snag.gy/rpPuL4.jpg

2. za Gimblim se nedostanu přes telefonát, který je teda asi součástí dialogu při setkání s touto postavou.
    vyskočí mi toto, nelze ani ukončit, zůstane to zaseklé. https://snag.gy/St7zUr.jpg

3. s Terezou je to stejné, akorát mě to pustí přes jednu větu https://snag.gy/gcTGJE.jpg a dál skončí opět zde https://snag.gy/uUvz0n.jpg . Použil jsem cestina_fontfriendly\dlg\santa monica\therese.dlg

6. Jumbles stejná chyba https://snag.gy/OcYX1K.jpg

7. Nines stále přeskočí rovnou na volbu v dialogu bez animace a mluvení. Pro upřesnění, stane se to po zvolení "2. To vypadá, že ty jseš princ mezi Anarchy." https://snag.gy/rTDpA0.jpg a naskočí stejná věta bez té animace a mluvení https://snag.gy/LOW9tx.jpg . Tyto soubory sem si tam nakopíroval line241_col_f.mp3 a line241_col_f.vcd .

8. Tzimisce stále nemá text vlevo nahoře a nepohybuje ústy. Nepohybuje ústy ani první větu v dialogu, ale dále už mluví normálně. Takže se nic neopravilo ani po pužití souborů z cestina_fontfriendly\sound\character\dlg\hollywood\andrei. Bral sem tyto 4 soubory line11_col_e.lip, line187_col_e.lip, line21_col_e.lip, line251_col_e.lip .

**Comment by miracleflame** [comment]
Výborne... až na to, že bod 3 sa mi nechce lúbiť, ale tak to asi Wesp zamýšlal vo svojom UP.
A bod 8 je už po konverzii skriptami, takže tam sa to posralo. Ale moja chyba, východzia čeština musí byť v UTF-8, aby to všetko prešlo, ako má. Opravené, netreba testovať, viem, že to bude dobré.

Tak už len body 4 a 5 @soulcharmer

**Comment by soulcharmer** [comment]
ad 4: hrac se tam muze vratit jeste pred triggerem, ktery turniket odstrani a taky ta replika by nemela pusobit jako rozkaz - presnejsi bude tohle:

"Dík. A zbav se toho otravnýho turniketu, až budeš moct."

A jeste tam vidim jednu chybku ve Venusine replice:

co závodí  -> co soutěží


ad 5: Ta odpoved odkazuje na typka, kteryho Pisha sejmula, ne na moralnost. Ale jde to napsal jasneji:

"O jaké morálnosti? Dostal, co mu patřilo. ... "


Diky moc

**Comment by miracleflame** [comment]
5: Mnoho dialógov má check úrovne Humanity, obvyke >5 a <5 (ale aj iné) a podľa toho vyberie typ hlášky, pričom samozrejme menej než 5 dáva bezcharakterné evil hlášky a naopak nad 5 dáva humánne hlášky. A toto je presne ten prípad, keď sa táto možnosť zobrazí len pri charakteroch s Humanity <5, takže aj replika by mala byť patrične evil... "screw him" mi teda nepríde ako ekvivalent "dostal, co mu patřilo". :D

**Comment by Honzixx** [comment]
Máš pravdu Míro. Beru, že to má být evil, protože nízká humanity. Teď, už znám to odvolání na toho týpka a dává to smysl, tak jak to je napsaný. Ale na poprvé mi to přišlo matoucí a spíš sem to spojil s tou morálností. Co to třeba přepsat, aby to bylo dvrďácký a zároveň jasně bylo vidět odvolání na toho týpka? např. Morálnost? Seru na toho kripla!

**Comment by soulcharmer** [comment]
Jako rozumim vam, ale repliky pro nizky humanity check hlavne vyjadruji postoj hrace, v tomto pripade nezajem o osud obeti.

Pokud se nepletu, postava hrace tuto obet ani neznala, takze neni velky duvod snazit se jeho dikci sponovat do zbytecne nenavisti nebo se snazit, aby to bylo co nejvic "evil" :-)

Humanity check neni ve hre ani videt, takze uz to, ze se replika lisi, obvykle staci. A v tomto pripade je "screw him" pomerne indiferentni odpoved ve smyslu "co je mi po nem" nebo "je mi fuk, co se s nim stalo".

Jako herni postava jsme prisli za Pishou delat byznys a pokud se ji mezitim nekdo pripletl do cesty, je nam to s nizkou lidskosti sumak. Eskalovat to kriplama nebo vykricnikama mi prijde prehnane...

Snad to dava smysl. Bud tam nechte tu puvodni verzi nebo vemte mou opravu vyse, ale toto je opravdu detail.

diik

**Comment by Honzixx** [comment]
Trochu sem to asi přehnal, pravda :-D Necháme to teda tak, jak to je původně?

**Comment by miracleflame** [comment]
5. bez zmeny
