### ISSUE TITLE
Ming Xiao chybí mluvení

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#111]
Tady u Ming Xiao v konverzaci stejná chyba jako u Ninese. Tato věta je bez animace mluvení, místo aby tu větu odříkala, prostě to přeskočí rovnou do konverzace, tak jak to je na screenu.
https://snag.gy/eQqRLJ.jpg

**Comment by miracleflame** [comment]
@Honzixx prosím otestuj. Určite si vlož oba súbory do Unofficial_patch\sound\character\dlg\main characters\mingxiao\

**Comment by Honzixx** [comment]
Otestováno, je to opravené. @miracleflame
