### ISSUE TITLE
Nelze dokončit quest "Unesena"

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#113]
Nelze dokončit hlavní dějový quest "Unesena" v Čínské čtvrti, kde je potřeba pro postavu "Wong Ho" zachránit jeho dceru "Kiki". Zkusil jsem to splnit bez nainstalované češtiny a quest dokončit jde, tím jsem obešel tento bug a budu pokračovat ve hře dál.
Zkusím to popsat a doplnit screenama tak, aby to dávalo smysl :-)

Konverzace s Kiki https://snag.gy/EB3X9S.jpg 
po první https://snag.gy/f30Wgx.jpg i druhé https://snag.gy/j3TfZA.jpg možnosti volby se udělá zápis do žurnálu, že jsem Kiki našel a mám se vrátit za Wong Ho.
Ale jakmile dojdu za Wong Ho pro dokončení questu, otevře se jen tento krátký dialog, jako kdybych Kiki ještě nenašel https://snag.gy/QMEWOZ.jpg .
Místo toho tam má správně naskočit tento dialog a quest se dokončí https://snag.gy/KC1W2u.jpg .

**Comment by miracleflame** [comment]
@Honzixx prosím otestuj. Malo by to byť fixnuté.

**Comment by Honzixx** [comment]
Bohužel zase rozbitý dialog, jako u ostatních, asi je opravdu potřeba ty dialogový soubory udělat finálně.
Vyskočí mi pouze toto, Kiki to sice pustí ven, ale neudělá se ani zápis do žurnálu:
https://snag.gy/xlFC4y.jpg
