### ISSUE TITLE
Chunk nepřeložená věta

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#115]
Našel jsem u Chunka v Centru města (ostraha ve Venture tower) jednu nepřeloženou větu:
https://snag.gy/lKpPDH.jpg

**Comment by miracleflame** [comment]
@soulcharmer na revíziu

{	491	}{	Not supposed to open the doors for anyone, sorry there, chief.	}{	Not supposed to open the doors for anyone, sorry there, missy.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	491	}{	Nemám prý nikomu otevírat, je mi líto, šéfiku.	}{	Nemám prý nikomu otevírat, je mi líto, sleèinko.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
gud :)
