### ISSUE TITLE
#75

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#126]
Stahl jsem si češtinu už s opravami #75, ale chyby co to opravuje ve hře pořád jsou.

**Comment by miracleflame** [comment]
51e7146e0f28248bec86d4fc1262b3a13f4de66b

**Comment by miracleflame** [comment]
Ak to berieš z cestina_fontfriendly tak tam to ešte nie je, najprv to musí zbehnúť konverznými skriptami, ale v pracovnej češtine to už máme opravené. Díky. :)
