### ISSUE TITLE
Jack u divadla

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#127]
kdo jseš zač?

https://snag.gy/pyox82.jpg

**Comment by miracleflame** [comment]
akú opravu navrhuješ?

**Comment by maarten93** [comment]
Ta otázka mi přijde dost kostrbatá, podle mě by bohatě stačilo něco jako kdo jsi.

**Comment by miracleflame** [comment]
@soulcharmer pravda, v origináli je len "Who are you?" ale mala by to byť primeraná reakcia na
[laughing at something no one else thinks is funny]What a scene, man! Hoo-wee! Then they just plop ya out here like a naked baby in the woods. [chuckle]How 'bout that? Ah... look, kiddo, this is probably a lot for you to take in, so uh, why don't you let me show you the ropes. Whaddya say?

**Comment by Honzixx** [comment]
"Ty jseš kdo?" mi přijde taky lepší ;-)

**Comment by soulcharmer** [comment]
"A ty jseš kdo?"


diky za report
