### ISSUE TITLE
Instalator

### ISSUE THREAD

**Issue by soulcharmer** [soulcharmer/gog_bloodlines_cz#13]
Mel by nabizet vsemozne kombinace cestiny, doplnku z UP Plus atd. a soucasne byt co nejmensi, zejmena tedy neduplikovat v sobe zadne textury.

**Comment by miracleflame** [comment]
Mám pripravený inštalátor, ale kvôli veľkosti súboru mi ho Git nedovolil uploadnuť. Nazdielal som ho cez Google.

Beta verzia minimalistickej inštalačky, naskriptované v NSIS:

Fíčury:
1. ličenčné uvítanie license.txt
2. výber komponentov "Překlad, textury, fonty" (povinne) a "Rozšíření o Unofficial Patch 9.5 PLUS CZ" (dobrovoľne)
3. autodetekcia cesty inštalácie s možnosťou Procházení
4. autoinštalácia fontov do systému
5. po dokončení opisná výzva na reboot kvôli fontom

Požiadavky:
- kompilácia vyžaduje nainštalovaný NSIS a http://nsis.sourceforge.net/FontName_plug-in
- FonName plugin sa nainštaluje chybne, treba presunúť NSIS\Plugins\FontName.dll do NSIS\Plugins\x86-ansi\
- základ češtiny treba mať predpripravený vo foldri "basic" a doplnok plus aj s češtinou pod foldrom "plus"

**Comment by miracleflame** [comment]
Prekopal som celý inštalátor do Modern UI 2 s grafikou a detailnými popismi inštalačných možností.

@soulcharmer prosím zreviduj texty:

    !insertmacro MUI_DESCRIPTION_TEXT ${basic} "Překlad je určený pro verzi hry, která obsahuje Neoficiální Patch 9.6 BASIC (standardne GOG release). Přeloží do češtiny s diakritikou všechny textury, dialogy, menu a popisy."
	!insertmacro MUI_DESCRIPTION_TEXT ${plus} "Doinstaluje rozšíření PLUS pro Neoficiální Patch 9.6 v češtine. Krom jiného obsahuje Historie a titulky pro hlasy v hlavě a vysílaní rádia. Osobitní instalaci anglické verze Unofficial Patch 9.6 PLUS nevyžaduje!"

**Comment by miracleflame** [comment]
Pridaná poistka pre prípad, že nejaké VTMB fonty už sú v systéme nainštalované (staršie/poľské...), pretože štandardne makro na inštaláciu fontov neprepisuje už existujúce fonty, iba pridáva nové v prípade, že neexistujú.

Tento update efektívne odinštaluje fonty pred ich inštaláciou.

**Comment by miracleflame** [comment]
to do:
- správne pomenovať výsledné meno súboru
- zrevidovať
`!insertmacro MUI_DESCRIPTION_TEXT ${basic} "Překlad je určený pro verzi hry, která obsahuje Neoficiální Patch 9.6 BASIC (standardne GOG release). Přeloží do češtiny s diakritikou všechny textury, dialogy, menu a popisy."
!insertmacro MUI_DESCRIPTION_TEXT ${plus} "Doinstaluje rozšíření PLUS pro Neoficiální Patch 9.6 v češtine. Krom jiného obsahuje Historie a titulky pro hlasy v hlavě a vysílaní rádia. Osobitní instalaci anglické verze Unofficial Patch 9.6 PLUS nevyžaduje!"`

**Comment by miracleflame** [comment]
ref #399

**Comment by soulcharmer** [comment]
poprosim o header2.png (pruhledny) a wizard.bmp (cerveny)

**Comment by soulcharmer** [comment]
revize textu


 "Překlad je určený pro verzi hry, která obsahuje Neoficiální Patch 9.7 BASIC obsažený přímo ve verzi hry, která je dostupná na GOG.com. Počeštěné jsou i s diakritikou všechny textury, dialogy, ovládací prvky a popisky."

 !insertmacro MUI_DESCRIPTION_TEXT ${plus} "Doinstaluje rozšíření PLUS pro Neoficiální Patch 9.7 v češtine. Kromě jiného obsahuje dodatečné profily pro vytváření postav (historie) a titulky pro hlasy v hlavě a vysílaní rádia. Samostatnou instalaci anglické verze Unofficial Patch 9.7 PLUS nevyžaduje!"

**Comment by miracleflame** [comment]
@soulcharmer 
Upravené texty sú príliš dlhé a nevmestia sa do zobrazovacieho políčka. Prvý popis by malo byť aspoň o jedno slovo kratší a druhý popis asi aj o 6-7 slov.

**Comment by soulcharmer** [comment]
ok

"Překlad je určen pro verzi hry s Neoficiálním Patchem 9.7 BASIC, která je dostupná na GOG.com. Počeštěné jsou i s diakritikou všechny textury, dialogy, ovládací prvky a popisky."

 "Doinstaluje rozšíření PLUS pro Neoficiální Patch 9.7 v češtine. Kromě jiného obsahuje dodatečné profily pro vytváření postav (historie) a titulky pro hlasy v hlavě a vysílaní rádia. Samostatnou instalaci anglické verze Unofficial Patch 9.7 PLUS nevyžaduje!"

"Rozšíření PLUS pro Neof. Patch 9.7 v češtine. Obsahuje např. historie pro vytváření postav nebo titulky pro vysílání rádia. Samostatnou instalaci anglické verze nevyžaduje!"

**Comment by miracleflame** [comment]
Dobrý!
