### ISSUE TITLE
Videopáska popis

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#130]
Nezobrazuje se znak procent v popisu
https://snag.gy/Z2yetz.jpg

**Comment by miracleflame** [comment]
Font reálne neobsahuje znak percenta kupodivu. Našiel som podobný font a skopíroval znak percenta odtiaľ.

Treba otestovať skrz novú inštalačku češtiny.

**Comment by Honzixx** [comment]
V nové instalaci češtiny už znak procent je, kazeta otestována a je to opravené.
https://snag.gy/OErs25.jpg
