### ISSUE TITLE
Předzvěst zobrazuje špatný zisk efektu

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#133]
Předzvěst zobrazuje špatný zisk i ztrátu efektu pro úrovně 2, 3, 4, 5
https://snag.gy/utvIT7.jpg         správně má být: důvtip +1 vnímavost +1
https://snag.gy/F8A2Mj.jpg       správně má být: důvtip +2 vnímavost +1
https://snag.gy/fmxEqd.jpg       správně má být: důvtip +2 vnímavost +2
https://snag.gy/gQOl4B.jpg       správně má být: důvtip +3 vnímavost +3

to samé zase mínusy při ztrátě efektu

**Comment by miracleflame** [comment]
To je chyba UP, prítomná aj v EN verzii.. Prejdem to s Wespom.

**Comment by miracleflame** [comment]
Wesp to vysvetlil tak, že engine zobrazuje vždy len posledný pridaný efekt prikumulovaný k predošlým. Čiže inými slovami iba zmenu oproti predošlej úrovni. Zdá sa, že to je neopraviteľné. Každopádne je to predmet UP a nie prekladu.

NATERAZ NEOPRAVENÉ
