### ISSUE TITLE
/dlg/downtown la/bomberman.dlg 

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#134]
Ve Venturské věži, když princ ovládá policistu.
Hádám, že tam je úmyslně ta latinská hláška "a bien tot", ale nestálo by za to přeložit ji, nebo dát překlad do hranaté závorky? Taky bych změnit "Tik, tik, tik..." na "Tik, tak, tik...", u nás se teda tiká takto :-)
https://snag.gy/cPvyNO.jpg
https://snag.gy/cpeDoW.jpg

**Comment by miracleflame** [comment]
@soulcharmer 

{	11	}{	Tick, tick, tick... ŕ bientôt[a bee-en toe], Kindred.	}{	Tick, tick, tick... ŕ bientôt[a bee-en toe], Kindred.	}{	#	}{	npc.SetDisposition("Joy", 3)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	11	}{	Tik, tik, tik. . . a bien tot[a bee-en toe], našinče.	}{	Tik, tik, tik. . . a bien tot[a bee-en toe], našinko.	}{	#	}{	npc.SetDisposition("Joy", 3)	}{		}{	}{	}{	}{	}{	}{	}{		}

**Comment by soulcharmer** [comment]
to je francouzstina ( lacroixova materstina )

"Tik, tak,... sbohem[a bee-en toe], našinče/našinko."

diky
