### ISSUE TITLE
Taxikář nepřeložená věta

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#136]
Taxikář ve finální jízdě nemá přeloženou tuto větu.
https://snag.gy/Jdt6RM.jpg

**Comment by miracleflame** [comment]
@soulcharmer 
Inak je to odpoveď na otázku
Kdo vlastně jste? Jak to, že tolik toho víte?

-{	521	}{	I drive people to their destination. That is who I am.	}{	I drive people to their destination. That is who I am.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
 +{	521	}{	Vozím lidi do jejich cíle. To jsem já.	}{	Vozím lidi do jejich cíle. To jsem já.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
"Vozím lidi tam, kde potřebují být. To je mé poslání."

A jestli je tam opravdu

"Jak to, že tolik toho víte?"

tak to pls oprav na 

"Jak to, že toho tolik víte?"


diky za report
