### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#137]
V závěrečných titulcích je napsané GOG release UP 9.5 ale máme verzi 9.6 ;-)
https://snag.gy/t61xrQ.jpg

**Comment by miracleflame** [comment]
A Wesp už má na stole UP 9.7, tak som zvedavý, kedy sa to dostane na GOG. Budú tam celkom markatné zmeny, za ktorými stojím aj ja... generic postavy budu o hodne výraznejšie reagovať svojimi hláškami na prítomnosť hráča... Väčšinu textu už tu máme predpripraveného v tiketoch 83 - 101.

@soulcharmer zakomponujeme nejako do credits aj beta testerov?

**Comment by soulcharmer** [comment]
Jasne, ze je tam pridame.

Ale kdo vi kolik jeste prijde verzi, nez to bude vsechno hotovo - takze to mozna pocka na release, coz?

next :)

**Comment by miracleflame** [comment]
@Honzixx @maarten93 
Nazdar chlapi... potvrďte, pod akým menom chcete figurovať v credits. Bez vášho vyjadrenia tam bude nick ako je tu na GitHube.

**Comment by Honzixx** [comment]
Ahoj. 
Jan "Honzixx" Kratochvíl
