### ISSUE TITLE
Mercurio pozměnit větu

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#138]
Na konci hry, kdy už se pohybuju pouze taxikem a zajedu za Mercuriem nakoupit, vyskočí tento dialog.
https://snag.gy/RCP6sg.jpg

"Rádo se stalo." nedává smysl, protože tomu nic nepředchází, navrhuju změnu na "Rád pomůžu."
I kdyby měla věta návaznost také jinde v dialozích s Mercuriem, než jen zde, tak se to touto změnou nerozbije. Ale nikde jinde sem tu větu nenašel.

**Comment by miracleflame** [comment]
@soulcharmer ide o starting line, takže by to nemalo pôsobiť naväzujúco...
{	521	}{	Always a pleasure. What's tonight's order?	}{	Always a pleasure. What's tonight's order?	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	521	}{	Je mi potěšením. Co si dáš dneska?	}{	Je mi potěšením. Co si dáš dneska?	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
"Rád tě zase vidím. Co si dáš dneska?"

diky za report
