### ISSUE TITLE
Ming Xiao - středník

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#140]
Středník je tam záměrně, nebo má být místo něj čárka?
https://snag.gy/RvumFd.jpg

**Comment by miracleflame** [comment]
Je to tak isto aj v anglických súboroch, aj významovo to tam sedí ako ukončenie vety s okamžitou náväznosťou.

@soulcharmer chceš na tom niečo meniť?

{	261	}{	Neither need you fear for the Kuei-jin soldiers; you have proven yourself a worthy champion and we are honored to have you as ours. I had so hoped your path would lead back to me.	}{	Neither need you fear for the Kuei-jin soldiers; you have proven yourself a worthy champion and we are honored to have you as ours. I had so hoped your path would lead back to me.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	261	}{	A nemusíš se bát ani kuei-jinských vojáků; prokázal jsi, že jsi úctyhodný bojovník a pro nás je ctí mít tě mezi sebou. Moc jsem si přála, aby tě tvá cesta zavedla zpět ke mně.	}{	A nemusíš se bát ani kuei-jinských vojáků; prokázala jsi, že jsi úctyhodná bojovnice a pro nás je ctí mít tě mezi sebou. Moc jsem si přála, aby tě tvá cesta zavedla zpět ke mně.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
teda vy me zasobujete, kdy se podle vas dostanu k tem radiim :-)?

Ten strednik je spravne, ale jestli to chcete esteticky vylepsit, muzete misto stredniku vetu ukoncit a pokracovat novou...

**Comment by miracleflame** [comment]
Chceme redukovať počet commitov, tak ja to tak nechám a uzatvorím... gramaticky mi to tam sedí lepšie než bodka. V prípade núdze tiket existuje.
