### ISSUE TITLE
Konec za kuei-jiny - nepřeloženo

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#141]
Nepřeložena princova slova ;-)
https://snag.gy/s3AUQM.jpg

**Comment by miracleflame** [comment]
@soulcharmer použitý preklad z DLG, ale jak to prerobiť do unisex formy?

You traitor! Do you know what you've done! Siding with those devils over your own kind! They're going to kill us all! Do you understand? You've sealed our fate!

"Zrádče! Víš vůbec, cos provedl? Zpaktovat se s těmi ďábly na úkor vlastní rodiny! Všechny nás zabijí! Chápeš to? Všem jsi nám to zpečetil!"

**Comment by Honzixx** [comment]
Přidám nápad, pro představu ;-)
"Jsi zrádce! Víš vůbec, jaké to bude mít následky? Zpaktovat se s těmi ďábly na úkor vlastní rodiny! Všechny nás zabijí! Chápeš to? Všichni našinci to mají zpečetěné!"

**Comment by soulcharmer** [comment]
"Zrádče! Máš ponětí, jaké to bude mít následky? Spolčit se s těmi ďábly na úkor vlastní rodiny! Všechny nás pobijí! Nedochází ti to? Osud našinců je zpečetěn."


diky za report
