### ISSUE TITLE
Konec za Anarhy nebo za sebe - přeložit

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#145]
Pokud se rozhodnu otevřít sarkofág, princ pak nemá přeložené co říká.
Je to tam dvakrát za sebou, akorát jednou je tam "Stop!" a podruhé "Stooooop!"
https://snag.gy/JFbcMW.jpg
https://snag.gy/mKDiPy.jpg

**Comment by miracleflame** [comment]
Použitý preklad z dlg
