### ISSUE TITLE
Rosa-věštkyně na pláži

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#146]
Místo a teď poslouchej se více hodí a teď mluv.

https://snag.gy/HmnvoK.jpg

**Comment by miracleflame** [comment]
@soulcharmer 
{	72	}{	A hundred? I'll give you twenty. Here's my question.	}{	A hundred? I'll give you twenty. Here's my question.	}
{	72	}{	Sto dolarů? Dám ti dvacet. A teď poslouchej.	}{	Sto dolarů? Dám ti dvacet. A teď poslouchej.	}

**Comment by maarten93** [comment]
A teď poslouchej. se podle mě moc do té věty nehodí, postava se jí ptá, 
když to přeložím doslovně tak říká, Tady je moje otázka.

**Comment by soulcharmer** [comment]
je to kapanek kostrbate, pac pred samotnou otazkou je jeste Rosina replika, pokud se nepletu.

Nejjednodussi mi prijde tu vetu proste vyhodit, je tam ponekud zbytečná:

"Sto dolarů? Dám ti dvacet."


diky za report
