### ISSUE TITLE
Copper - na pláži

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#147]
Místo: Můžeš se pokusit a nenechat se svým stavem zlomit.
Třeba něco takového: Nenech se zlomit svým stavem

https://snag.gy/9Spa8g.jpg

**Comment by miracleflame** [comment]
@soulcharmer tvoja parketa

{	62	}{	Můžes se pokusit a nenechat se svým stavem zlomit.	}
{	62	}{	You can try not to let your condition defeat you.	}

**Comment by soulcharmer** [comment]
"Můžeš na sobě zapracovat a nenechat se tím zlomit."

ty dve dalsi repliky bych taky kapku potunil, kdyz uz je vidim:

"Můžeš přestat otravovat. Sbohem"   (tzn. bez "Ale")

"Přesně tak, prostě máš pech. Měj se."

diky
