### ISSUE TITLE
czen2 a nonidentical3

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#15]
Ja som vedel, že sa na niečo zabudlo. Ešte ostalo toho celkom dosť k prekladaniu. 

1. anglické súbory z pôvodnej češtiny, ktoré sú ale zjavne restornuté a používané
2. niektoré súbory, čo sú navyše pridané v UP 9.5

**Comment by miracleflame** [comment]
Všetko pripravené na revíziu... niektoré veci som uložil ako utf8, aby sa to lepšie kontrolovalo. Po úprave to treba uložiť zas do cp1250.

aa830ba9b9bccf0c3e099e7fe3362fe00676430e
dfb71e08356064d1d52981bef3f060ebd8c0f188
0323bd6e2a2b38e3723b4fc6d5a46c05672da262

**Comment by soulcharmer** [comment]
ty dva preklepy z a839b02 jsou spravene
