### ISSUE TITLE
E na pláži

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#153]
Bezva. A kdo jste vlastně za lidi?
Trochu těžkopádná věta.
Bezva. a co tu lidi vlastně děláte? nebo možná Bezva. a co tu vlastně děláte? 

https://snag.gy/8jRFHD.jpg

**Comment by miracleflame** [comment]
@soulcharmer 

{	191	}{	You should try up there, through that chain-link gate. Couple of nasty looking blokes come out there couple o' times a night.	}{	You should try up there, through that chain-link gate. Couple of nasty looking blokes come out there couple o' times a night.	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	192	}{	Thanks. Can I ask you a few more questions?	}{	Thanks. Can I ask you a few more questions?	}{	311	}{	G.E_Thin == 1	}{	}{	}{	}{	}{	}{	}{	}{	May I mine your gray matter?	}
{	193	}{	Cool. Now who are you guys, exactly?	}{	Cool. Now who are you guys, exactly?	}{	11	}{	G.E_Thin == 0	}{	}{	}{	}{	}{	}{	}{	}{	Tell me the tale of this thin little group.	}


{	191	}{	Zkus to tam nahoře za tou drátěnou brankou. Několik drsně vyhlížejícíh týpku tudy chodí každou noc.	}{	Zkus to tam nahoře za tou drátěnou brankou. Několik drsně vyhlížejícíh týpku tudy chodí každou noc.	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	192	}{	Dík. Můžu se ještě na něco zeptat?	}{	Dík. Můžu se ještě na něco zeptat?	}{	311	}{	G.E_Thin == 1	}{	}{	}{	}{	}{	}{	}{	}{	Mohu zalovit v tvé šedé kůře?	}
{	193	}{	Bezva. A kdo jste vlastně za lidi?	}{	Bezva. A kdo jste vlastně za lidi?	}{	11	}{	G.E_Thin == 0	}{	}{	}{	}{	}{	}{	}{	}{	Pověz příběh této malé mdlé skupiny...	}
{

**Comment by soulcharmer** [comment]
opravy:

"Zkus to nahoře za tou drátěnou brankou. Několik drsných týpků tam chodí každou noc."

"Bezva. A vy jste co za partu?"

dik za report
