### ISSUE TITLE
Příručky - Moc složité

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#154]
Když je příručka složitá, je místo tlačítka "Použít" napsáno "Moc složité", což je v pořádku.
Ale když je příručka nepoužitelná, protože danou vlastnost už máme na vyšší úrovni, hláška "Moc složité" tam nesedí. Hádám, že je "Moc složité" společné pro obě situace. Co to udělat univerzální?
Např. "Nelze použít"
https://snag.gy/YCvkBX.jpg

**Comment by miracleflame** [comment]
@soulcharmer napadajú mi takéto riešenia:
Nevhodné
Nepřimeřené

**Comment by soulcharmer** [comment]
"Nelze použít" je univerzální, ale stírá hranice mezi oběma stavy a proto muze byt matouci.

Veslo by se toto?

"Mimo tvou úroveň"

**Comment by soulcharmer** [comment]
tak jeste

"Mimo úroveň"

mi prijde, ze dava vic info, nez genericke "nelze pouzit"

co vy na to?

**Comment by miracleflame** [comment]
Ja som za... Keby sme sa mali držať originálu, tak by to malo byť 
Nečitelné

**Comment by Honzixx** [comment]
"Mimo úroveň" je podle mě super, i lepší než "nečitelné".
