### ISSUE TITLE
Flynt kotel hříchu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#159]
možná by se mi hodilo něco z ponuky
                                              z nabídky
https://snag.gy/TiytEO.jpg

**Comment by miracleflame** [comment]
Flynn.dlg fix #157 			c1e2b70

**Comment by Honzixx** [comment]
Ještě tam vidím chybku "Možná by se mi hodilo něco z nabídky, ukaž. co máš."
Za slovem "ukaž" nemá být tečka
