### ISSUE TITLE
Preklad textúr

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#16]
Toto sú textúry s anglickým textom:

**[materials\hud\barter_loot\bart_icon_flynn.ttz](https://snag.gy/AZmy3D.jpg)
[materials\hud\barter_loot\bart_icon_slater.ttz](https://snag.gy/FhgDu7.jpg)
[materials\hud\barter_loot\bart_icon_tseng.ttz](https://snag.gy/jxgFQM.jpg)
[materials\hud\barter_loot\bart_icon_vandal.ttz](https://snag.gy/0nOHdY.jpg)
[materials\hud\disciplines\animalism.ttz](https://snag.gy/QqYRHo.jpg)
[materials\hud\disciplines\auspex.ttz](https://snag.gy/4KeSHu.jpg)
[materials\hud\disciplines\bloodheal.ttz](https://snag.gy/8uygRn.jpg)
[materials\hud\disciplines\Bloodheal_Base.ttz](https://snag.gy/5fcZSt.jpg)
[materials\hud\disciplines\blood_strength.ttz](https://snag.gy/zj2WdS.jpg)
[materials\hud\disciplines\celerity.ttz](https://snag.gy/SaWDmQ.jpg)
[materials\hud\disciplines\dementation.ttz](https://snag.gy/wvNMef.jpg)
[materials\hud\disciplines\dominate.ttz](https://snag.gy/cyFtsm.jpg)
[materials\hud\disciplines\fortitude.ttz](https://snag.gy/BL0sEF.jpg)
[materials\hud\disciplines\obfuscate.ttz](https://snag.gy/VBX8Z0.jpg)
[materials\hud\disciplines\presence.ttz](https://snag.gy/3ySR7B.jpg)
[materials\hud\disciplines\protean.ttz](https://snag.gy/cCxzS6.jpg)
[materials\hud\disciplines\thaumaturgy.ttz](https://snag.gy/osIMJB.jpg)
[materials\interface\pop_ups\dialog_presence.ttz](https://snag.gy/yHPLhI.jpg)
[materials\interface\sewermap\groutmansion.ttz](https://snag.gy/EC40Op.jpg)
[materials\interface\sewermap\groutmansionhl.ttz](https://snag.gy/CDPuBL.jpg)
[materials\models\character\npc\unique\hollywood\slater\vb_cg_slater_body.ttz](https://snag.gy/jVYNOy.jpg)
[materials\models\items\garys_film\garys_film.ttz](https://snag.gy/WK52J4.jpg)**
[materials\models\items\garys_tape\garys_tape.ttz](https://snag.gy/El6Pvo.jpg)
**[materials\models\scenery\structural\warrens\warr_00_map.ttz](https://snag.gy/W75jKN.jpg)
[materials\models\scenery\structural\warrens\warr_01_sign.ttz](https://snag.gy/h3CXnr.jpg)**
[materials\signs\animated.ttz](https://snag.gy/BRA5Em.jpg)

**Comment by miracleflame** [comment]
Aktualizoval som zoznam s priamym náhľadom textúr.
Na hrubo som preložil... [Salter je tu](https://snag.gy/Y0gT7n.jpg)

**Comment by miracleflame** [comment]
Textúry považujem za preložené...

Nasledujúce by som neprekladal:
materials\models\items\garys_tape\garys_tape.ttz (sedí s pôvodným prekladom Jock Shot)
materials\signs\animated.ttz (poster nad moje photoshop skilly)

Ak by niečo malo byť preložené ináč, daj vedieť... napr. cedula warr_01_sign.ttz

**Comment by soulcharmer** [comment]
Ty ikony disciplin myslim byly ty puvodni, ktere se nakonec nepouzily ve prospech tech kulatych...

materials\hud\disciplines\dominate.ttz  -> Dominance

 materials\models\character\npc\unique\hollywood\slater\vb_cg_slater_body.ttz  ->  vždy   se utři   dvakrát

 materials\models\scenery\structural\warrens\warr_00_map.ttz  -> Mapa kanalizace a vodních cest
vodní tok -> vodní cesta

jinak ty labely v originale neprectu (legenda a prostredek mapy), ale tam kde mas cesky "vodni tok" se zda, ze anglicky je to "sewer lines", takze to bys mel obracene.

materials\models\scenery\structural\warrens\warr_01_sign.ttz   ->  
Em.release valve :  Bezpečnostní ventil
Hollywood water mngmt :  vodohospodářský úřad Hollywoodu

a ten text dole:

Výrazem "zákon vztahující se k úřadu nebo činnosti veřejného správce" se rozumí takový zákon, který specificky platí pro osoby s oprávněním vykonávat veřejnou správu a který přímo nebo nepřímo: předepisuje povinnost veřejnému správci; nebo určuje působnost veřejného správce.

Výrazem "zneužití" se rozumí takové nakládání s majetkem, které je v rozporu s: ujednáním, na jehož základě veřejný správce majetek spravuje; pracovní smlouvou nebo přísežným slibem veřejného správce; aplikovatelným zákonem.

**Comment by miracleflame** [comment]
Opravy:
[materials\hud\disciplines\dominate.ttz](https://snag.gy/b4OLx8.jpg)
[materials\models\character\npc\unique\hollywood\slater\vb_cg_slater_body.ttz](https://snag.gy/6yViBg.jpg)
[materials\models\scenery\structural\warrens\warr_00_map.ttz](https://snag.gy/Ufs9C5.jpg)
[materials\models\scenery\structural\warrens\warr_01_sign.ttz](https://snag.gy/AnpPhI.jpg)

Disciplíny sú použité v hre cez klávesové menu F4. Myslím, že to tak bolo odjakživa.
