### ISSUE TITLE
radio jistiny

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#161]
Nepřeložené radio, myslím že když jsem tu byl předtím tak to bylo česky.

https://snag.gy/TXif8S.jpg

**Comment by Honzixx** [comment]
Na rádia už jsou tikety #77 - #81 , narazíš na to ještě vícekrát, není potřeba už rádia hlásit. 
Soulcharmer to bude překládat ;-)
