### ISSUE TITLE
Jack tutorial - přeložit

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#167]
nepřeložená věta
https://snag.gy/Icux5Y.jpg

**Comment by miracleflame** [comment]
@soulcharmer 

{	1003	}{	I'm too weak to play the game the way it was meant to be played.	}{	I'm too weak to play the game the way it was meant to be played.	}{	1006	}{		}{		}{	}{	}{	}{	}{	}{	}{	A weakling like myself can't complete the game.	}

{	1003	}{	Já jsem příliš slabý na to, abych hrál hru podle pravidel.	}{	Já jsem příliš slabá na to, abych hrála hru podle pravidel.	}{	1006	}{		}{		}{	}{	}{	}{	}{	}{	}{	Tintítko jako já nezvládne tuto hru.	}

**Comment by soulcharmer** [comment]
{ 1003 }{ Nemám na to, abych tu hru hrál podle pravidel. }{ Nemám na to, abych tu hru hrála podle pravidel. }{ 1006 }{ }{ }{ }{ }{ }{ }{ }{ }{ Měkkota jako já nezvládne tuto hru. }

diky
