### ISSUE TITLE
romero

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#169]
Tak jak ti to vysávání krve jde od ruky?
Tak co, jak se ti daří vysávat krev?

https://snag.gy/df5SQR.jpg

**Comment by miracleflame** [comment]
@soulcharmer 

{	301	}{	How's that whole bloodsucking thing working out for you?	}
{	301	}{	Tak jak ti to vysávání krve jde od ruky?	}

**Comment by soulcharmer** [comment]
{ 301 }{ Jak ti frčí všechno to nasávání krve? }

diky
