### ISSUE TITLE
televize hlasatel

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#173]
EZNÍKEM>ŘEZNÍKEM

https://snag.gy/08opqn.jpg

**Comment by miracleflame** [comment]
Toto neni ani tak preklep ako trampoty spojené s diakritikou. V zdrojovom texte sa Ř náchádza, ale nešťastou náhodou ním začína slovo na novom riadku po zalomení. Z nejakého dôvodu to engine nezobrazí.

Riešením je vetu preformulovať, aby zalomenie vyšlo ináč, alebo slovo aby nezačínalo zvláštnym znakom.

@maarten93 prosím otestuj opravu po konverznom dumpe, @Honzixx ak to nebude bez savu problém, skontroluj prosím aj na tvojom rozlíšení (vyjde to ináč).

**Comment by maarten93** [comment]
tady to pomohlo.
https://snag.gy/lLvFkB.jpg

**Comment by maarten93** [comment]
Řádek končí nej na dalším má být účinější, bohužel ú se nezobrazuje.

https://snag.gy/RH40oE.jpg

**Comment by Honzixx** [comment]
@maarten93 nemohl bys to prosím  ještě otestovat v rozlišení 1600x900? V mých savech nemám ten správný čas, kdy se tato zpráva vysílá.

**Comment by maarten93** [comment]
@Honzixx jasně až se dostanu do centra tak to vyzkouším, taky už ten save nemám

**Comment by maarten93** [comment]
1600x900  https://snag.gy/uW5Ewn.jpg   vypadáto dobře
