### ISSUE TITLE
Daimonori

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#174]
Divotvorství Damage 140%
Divotvorství Poškození 140%
https://snag.gy/B7Za9X.jpg

**Comment by miracleflame** [comment]
Toto bude ťažké vystopovať...

Inak @maarten93 ak môžeš, testuj za inú postavu, prosím. Tremere už mamé rozohrané, tak nech sa pokryje, čo najviac postáv... Ideálne by sa nám najviac hodil test za Nosferatu ženu Plus alebo Ventrue ženu Plus... prípadne hocijakú ženu Basic.

Díky za report.

**Comment by maarten93** [comment]
Ok rozehraji to znovu za Nosferatu ženu Plus
