### ISSUE TITLE
mitnick

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#175]
Moh' bych vás nechat bejt>mohl
Odsud jsem nemoh' nic dělat>nemohl

bohužel screen nemam.

**Comment by miracleflame** [comment]
@soulcharmer 

{	11	}{	Wha? Oh, yeah... hold on a sec... oh my god. Are you kidding me? What are you using for security down there, a Trash-80? Ugghh! Guys, it's called encryption. This is too easy. I'd let you off the hook, but stupidity always brings out the asshole in me.	}

{	11	}{	Co? No jasně... tak moment... to mě poser. To má být vtip? Co to tam máte na bezpečnost? Commodora? Bože, říká se tomu šifrování. Tohle je moc lehký. Moh' bych vás nechat bejt, ale diletantizmus ve mně pokaždý probudí hajzla.	}

**Comment by soulcharmer** [comment]
tohle neni bug, tohle je Mitnick :-)

nebudeme prece pospisovnovat kecy nosferatskyho hackera ;) tohle je tam schvalne
