### ISSUE TITLE
CD-Rom Metalhead Industries

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#176]
podle e-mailu viz: https://snag.gy/2Bh0Gq.jpg by v Metalhead Industries měl být CD-Rom pro garyho, podle, http://vtmb.wikia.com/wiki/Metalhead_Industries má být v trezoru, jenže tam není místo toho tam je https://snag.gy/E7BqC8.jpg , úkol se dá dokončit i s tímto předmětem, jen by to chtělo pozměnit ten e-mail.

**Comment by miracleflame** [comment]
Moc moc dobrý postreh! Aj také nezrovnalosti sa môžu vyskytovať v starom preklade po rozšírení na Plus a treba mať na to oko.

@soulcharmer toto budeš chcieť určite preložiť po svojom:

Bude cely tvuj vymenou za jedno nicotne datove cedecko.
It's all yours for the low, low price of the wooden pull toy prop from The Glittering.

**Comment by soulcharmer** [comment]
"Bude cely tvuj vymenou za jednu nicotnou rekvizitu v podobe tahaci hracky."

Je Glittering realne misto ve hre? Nic mi to nerika...

**Comment by miracleflame** [comment]
Domnievam sa, že ide o filmovú rekvizitu z fiktívneho filmu The Glittering.

**Comment by Honzixx** [comment]
Nic mi to jako místo neříká. Nebude The Glittering myšlený spíš jako název filmu, představení apod.?

**Comment by maarten93** [comment]
Až na fotku vše ostatní co Gary chce souvisí s filmem.

**Comment by maarten93** [comment]
@miracleflame Ještě místo melo by byt v>mela by byt v

**Comment by miracleflame** [comment]
Vlastne som to zatvoril nejako unáhlene. Stále tam nemáme ten Glittering, @soulcharmer ?

**Comment by soulcharmer** [comment]
Netreba, je to obskurni reference na neco, co ve hre ani neni. Delame to pro cesko(slovenske) publikum :)
