### ISSUE TITLE
imalia

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#177]
mojem>mým
nejsem si jistý, ale neměl by být za hle místo čárky vykřičník?
https://snag.gy/Zya2fT.jpg

**Comment by miracleflame** [comment]
V origináli to je neprerušovaná veta ešte aj bez čiarky
{	211	}{	Well, I had just won Guy magazine's "The Most Ridiculously Hot Chick in the Known Universe" award, and when I came home after the ceremony, lo and behold Gary was sitting there on my couch with a martini in his hand. You fill in the blanks.	}

Opravené mojem. dík.
