### ISSUE TITLE
Victor Rosselini

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#180]
nepřeloženo.

https://snag.gy/YbkwgJ.jpg

**Comment by miracleflame** [comment]
@maarten93 @soulcharmer 
Poprosím test a revíziu.
"Pojď Mario, jdeme domů."

**Comment by maarten93** [comment]
už je to ok

https://snag.gy/lSWIwk.jpg

**Comment by soulcharmer** [comment]
diky
