### ISSUE TITLE
Předzvěst(5)

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#181]
na páté úrovni má dávat +3 důvtip a vnímavost http://vtmb.wikia.com/wiki/Auspex myslím že to ukazuje +1 od druhé úrovně až po pátou.

https://snag.gy/oXnxMw.jpg

**Comment by Honzixx** [comment]
Už je na to tiket #133

**Comment by miracleflame** [comment]
@maarten93 spravil si niečo zvláštne, že už ti píše aj vnímavost aj důvtip?

**Comment by maarten93** [comment]
Tak na levlu 5 schopnosti na které to mam to to píše oboje dvoje.
