### ISSUE TITLE
Nosferatu intro.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#185]
Intro se zastaví na stejném místě a dál nepokračuje zkoušeno2x

nejdřív se objevý záběr na podlahu
https://snag.gy/kVhpNY.jpg

a potom na garyho a dál nic.
https://snag.gy/UQ2Irb.jpg

konzole hlásí tohle.
https://snag.gy/VuSwzc.jpg

**Comment by miracleflame** [comment]
Hmmm. veľmi zvláštne chyby tu reportuješ, ktoré s češtinou zrejme nesúvisia... Nerobil si nejaké modovanie?
Skús odzálohovať a premazať Unofficial_Patch\maps\graphs\*.loc

**Comment by maarten93** [comment]
Mody žádný nemám jen hru z gogu + češtinu s patch plus, odstranění .loc s intrem nepohlo, ještě že jde přeskočit, na tento problém jsem zatím narazil jen u nosferatu.

**Comment by maarten93** [comment]
Tak už to jde, odinstaloval jsem češtinu s plus patchem a pak je znovu nainstaloval a už to šlo.
