### ISSUE TITLE
Trip za nosferatu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#191]
Mám kámoše co se zabývá sochařením na živém
Sochařením na živém je trochu zvláštní slovní spojení, co se tím vůbec myslí? (cosplay, dělá masky, chirurgické/pastické úpravy, nebo něco takového: https://cs-cz.facebook.com/kampomaturite/videos/10153469287082736/)

https://snag.gy/JxqFR5.jpg

**Comment by miracleflame** [comment]
@soulcharmer 
{	481	}{	Good evening. Whoa! Nice work on the face there. I got a friend who's into the body sculpting scene, goes to conventions and stuff, ya know. Not my thing, but uh... I can appreciate it. Nice job with the ears there, especially. That's rad, dude.	}
{	481	}{	Dobrý večer. Wow, to je dobrá práce na tom obličeji. Mám kámoše, co se zabývá sochařením na živém, jezdí na akce a tak. Nic pro mě, ale dokážu to ocenit. Pěkný výtvor, hlavně ty uši. To je síla.	}

**Comment by soulcharmer** [comment]
"Dobrý večer. Páni, to je dobrá práce na tom obličeji. Mám kámoše, co dělá extrémní plastiky, jezdí na akce a tak. Nic pro mě, ale... dokážu to ocenit. Pěkný výtvor, hlavně ty uši. To je síla."

diky za report
