### ISSUE TITLE
Klávesové zkratky

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#192]
v prvním sloupci jsou zkratky očíslovány 1až 5, v tom druhém čísla chybí nemělo by tam být 6 až 10 ?

https://snag.gy/1r2RD7.jpg

**Comment by miracleflame** [comment]
Pravda, ale to nie je záležitosť prekladu. Tým sa musí zaoberať Wesp v UP.
Chyby tohto tipu môžeš reportovať na
https://forums.planetvampire.com/bloodlines-tech-support/
