### ISSUE TITLE
recepční nemocnice

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#193]
To mě mrzí, ale stejně musíte počkat, než na vás dojde řada.
To mě mrzí, ale stejně budete muset počkat, než na vás dojde řada.
https://snag.gy/3JpNXe.jpg

**Comment by miracleflame** [comment]
Nevidím problém v použitom čase.

**Comment by maarten93** [comment]
ve hře je: To mě mrzí, ale stejně budeme muset, až na vás dojde řada

Byl jsem líný to psát když je to na screenu
