### ISSUE TITLE
Nicka nebo Phil?

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#196]
tento komentář se objeví když osvobozuji Lili z krevní banky, vypadá to že ho říká Phil předtím než ho vysaje.

Phil: http://vtmb.wikia.com/wiki/Phil

https://snag.gy/yAIBEW.jpg

**Comment by miracleflame** [comment]
originál
sound\character\male\blue_blood\
Scrubs

Možno je to použité aj pre iný charakter... 
Je niečo zlé na tom, že je tam označenie Nicka?

**Comment by maarten93** [comment]
ne nejspíš to nevadí, jen jsem si všiml že tam je jiné jméno než má ta postava co to říká.

**Comment by Honzixx** [comment]
Nechal bych tam Nicku, protože Phila ve vedlejší místnosti můžeme zabít, ještě před touto částí. Toto je potom jiný lékař.

**Comment by miracleflame** [comment]
Myslím, že presne to mal na zreteli aj Wesp, keď ho pomenoval Scrubs.

Ponecháme, ale díky sa dobrý postreh.
