### ISSUE TITLE
Vandal

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#197]
číhával jsem u pastičky na myši až sklapne.
číhaval není slovní tvar od slova číhat viz:https://www.pravidla.cz/pravopis/29494-cihat.html

číhal jsem u pastičky na myši až sklapne
to až sklapne mi tam taky úplně nesedí možná tam dát: a čekal až sklapne.
https://snag.gy/CpKvDR.jpg

**Comment by soulcharmer** [comment]
ja vedet, ze to existuje jako nedokonava forma:

https://nlp.fi.muni.cz/projekty/wwwajka/WwwAjkaSkripty/morph-analyser.cgi?jazyk=0&slovo=%E8%EDh%E1vat&akce=3&kodovani=0

formalni kodifikace nedokaze zachytit vsechno, ale replika by asi sla vylepsit.

@miracleflame : vytahnes mi pls original?

**Comment by miracleflame** [comment]
{	231	}{	It's a mesmerizing liquid, isn't it? The color, the bouquet, the form. When I was a kid, I used to wait for the snap of the rat trap. It would trickle out of the animal's face and ooze just far enough to coagulate around the cheese... a poetic death.	}{	It's a mesmerizing liquid, isn't it? The color, the bouquet, the form. When I was a kid, I used to wait for the snap of the rat trap. It would trickle out of the animal's face and ooze just far enough to coagulate around the cheese... a poetic death.	}{	#	}{	npc.SetDisposition("Joy", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
"Je to fascinující šťáva, že? Ta barva, aroma, konzistence. Když jsem byl děcko, čekával jsem u pastiček na myši, až sklapnou. Krev dotekla z hlavy zvířete dost daleko, aby se srazila kolem nastraženýho sýra. Půvabná smrt."

diky
