### ISSUE TITLE
Paní domu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#198]
Před ' Áno, Je >Ano, je
'né>ne
https://snag.gy/eIhCvJ.jpg

Navíc v tam mimo Wong Hoa, nikdo jiný není tak nechápu kdo to říká

**Comment by Honzixx** [comment]
Jo, nad tím, sem se taky pozastavil. Ale jelikož číňani mají domy takový papírový, tak to může být jakože přes zeď nebo přes patro.

**Comment by miracleflame** [comment]
Duplikát #112 
Tipujem, že ide o záznamník.

**Comment by maarten93** [comment]
@miracleflame Jen pro zajímavost, paní domu je ta recepční co přivolává výtah https://snag.gy/IgS5qX.jpg
I když tedy v tom případě přijde divné že se ten rozhovor odehrává v jiném patře, asi papírové podlahy.

**Comment by miracleflame** [comment]
Asi bude celkom na mieste premenovať ju všade na Recepční alebo hostesku. V orgináli je Hostess.

**Comment by maarten93** [comment]
https://snag.gy/1ZbPYI.jpg
Áminusunderstandingřaha....... ?

**Comment by miracleflame** [comment]
Hah.. dobrý bug, pobavil )) opravené

@soulcharmer hosteska alebo recepční?

**Comment by soulcharmer** [comment]
Hosteska

diky
