### ISSUE TITLE
Hlasatel televize 2

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#202]
stejný problém jako ve zprávě s řezníkem.
Zde chybí "ú" na začátku řádku --> "útočí"
https://snag.gy/5fb6Nw.jpg

**Comment by miracleflame** [comment]
@Honzixx otestuj opravu, prosím.

**Comment by Honzixx** [comment]
testováno, je to v pořádku 1600x900 i 1920x1080
https://snag.gy/NJryLP.jpg
https://snag.gy/DxRwyz.jpg
