### ISSUE TITLE
mandarin

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#203]
Řádek končí nej na dalším má být účinější, bohužel ú se nezobrazuje.

https://snag.gy/RH40oE.jpg

**Comment by miracleflame** [comment]
@maarten93 otestuj pokus o opravu prosím, ideálne vo viacerých rozlíšeniach.

**Comment by maarten93** [comment]
1600x900   https://snag.gy/ADe1Uw.jpg
1600x1200 https://snag.gy/YqQxsa.jpg
1920x1080 https://snag.gy/rTuCAf.jpg


na 1600x900 je to pořád, ostatní rozlišení co jsem zkoušel jsou v pohodě

**Comment by miracleflame** [comment]
@maarten93 toto už by malo byť dobre, otestuj, prosím.

**Comment by maarten93** [comment]
už to je ok
1600x900  https://snag.gy/ZPjJzK.jpg
