### ISSUE TITLE
Skelter

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#206]
text mimo rámeček

https://snag.gy/XDhL5g.jpg

**Comment by miracleflame** [comment]
@soulcharmer Príliš veľa í a á v riadku no... ďalšia chuťovka okolo diakritiky... treba preformulovať

{	171	}{	Nemusím na ostatní cenit tesáky, abych si připadal dobře. Maškaráda je jen blbá kamarillská nálepka - jinak s ní nemám problém. Žít a nechat žít. I tak máme dost svých starostí.	}
{	171	}{	I don't need to bare my fangs to feel good about myself. The Masquerade is a fruity Camarilla label; other than that I got no problem with it. Live and let live - we got enough to worry about.	}

**Comment by soulcharmer** [comment]
pomuze tohle?

"Nemusím na ostatní cenit tesáky, abych si připadal dobře. Maškaráda je jen blbá kamarillská nálepka - jinak mi nevadí. Žít a nechat žít. Máme dost svých starostí."

**Comment by miracleflame** [comment]
@maarten93 otestuj prosím, či to je lepšie.

**Comment by maarten93** [comment]
Zlepšilo se to, ale pořád je malá část textu mimo.
https://snag.gy/6Wjtzp.jpg

A ještě jsem si při testování všiml:
https://snag.gy/Mde6vg.jpg
Ta krev je změť řetězů, která tě bude držet v područí
Nemělo by tam být?      které tě boudou držet v područí
Ty řetězy tě drží ?

**Comment by miracleflame** [comment]
K tým řetezom.. myslím, že určite.
a line 171 som skrátil z
Žít a nechat žít
na
Ži a nech žít

To by malo definitívne pomôcť a významovo to nič nenarúša.
@soulcharmer Tvoje vyjadrenie?

**Comment by maarten93** [comment]
https://snag.gy/o2aS70.jpg Text už nepřesahuje, ale je tam Ži a nech žít> Žij a nech žít, snad to tak vyjde moc místa tam už není.

**Comment by soulcharmer** [comment]
@miracleflame "ži" tam byt nemuze, cesky je to stejne "žij"  a 'zit a nechat zit' je idiom.

jeste jsem to drobne zkratil:
"Nemusím na všechny cenit tesáky, abych si připadal dobře. Maškaráda je jen blbá kamarillská nálepka, jinak mi nevadí. Žít a nechat žít. Máme dost svých starostí."

@maarten93 nedrzi te retezy, ale zmet retezu a zmet je zenskeho rodu, takze bez opravy.

Diky

**Comment by miracleflame** [comment]
@maarten93 poprosím test

**Comment by maarten93** [comment]
https://snag.gy/jcblek.jpg
Už je to dobré

**Comment by maarten93** [comment]
@miracleflame  ještě @maarten93 nedrzi te retezy, ale zmet retezu a zmet je zenskeho rodu, takze bez opravy.

Diky

viz výše

**Comment by miracleflame** [comment]
Ešteže to tu niekto dôkladne sleduje a vie ma zastaviť, keď sa ponáhlam. :D

**Comment by maarten93** [comment]
@miracleflame to už je pracovní deformace.
