### ISSUE TITLE
nines nepřeloženo

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#207]
nepřeloženo
https://snag.gy/FsBadI.jpg

**Comment by miracleflame** [comment]
@soulcharmer 

{	111	}{	[Can't hear]What? Hang on a sec. [Turns to the bar]SHUT UP! [bar gets quieter]As I was saying, all this, the life we lead - it's a mess. It's older than this city, this country, who knows how long this shit's gone on.	}
{	111	}{	[Can't hear]Co říkáš? Sekundu... [Turns to the bar]SKLAPNĚTE! [bar gets quieter]Jak jsem řekl, tohle všechno, tento život co vedem - stojí to za prd. Je to starší než tohle město, tato krajina, kdoví jak dlouho se to už táhne.	}

{	112	}{	Go on.	}{	Go on.	}{	131	}{	}{	}{	}{	}{	}{	}{	}{	}{	MORE!	}
{	112	}{	Pokračuj.	}{	Pokračuj.	}{	131	}{	}{	}{	}{	}{	}{	}{	}{	}{	JEŠTĚ!	}

{	113	}{	Is this going to take long?	}{	Is this going to take long?	}{	121	}{	}{	}{	}{	}{	}{	}{	}{	}{	Do you plan to imprison me with your blathering for infinity plus two?	}
{	113	}{	Bude to na dlouho?	}{	Bude to na dlouho?	}{	121	}{	}{	}{	}{	}{	}{	}{	}{	}{	Máš v plánu věznit mě svým tlacháním na věčnost plus dvě?	}

**Comment by maarten93** [comment]
@miracleflame Ještě mě napadlo, nešlo by udělat, aby když zařve SKLAPNĚTE tak bar doopravdy na chvýli utichl? 
Protože normálně hudba hraje dál a kravál z mluvení taky pokračuje

**Comment by miracleflame** [comment]
To je možno aj dôvod, prečo to v pôvodnej hre nebolo, lebo tam nezodpovedal ten efekt. Ale Wesp v rozšírení Plus oživuje mŕtve assety, ktoré mnoho razy pôsobia nasilu a navyše (viď Jack tutorial "Radši popojdeme o kus dál...").

Takáto funkcionalita by si vyžadovala určite skript, aj to je otázne, či by to sadlo presne na moment, kedy povie Shut up. Každopádne to je téma pre Wespa na Unofficial Patch.

**Comment by soulcharmer** [comment]
{ 111 }{ [Can't hear]Cože? Moment. [Turns to the bar]DRŽTE HUBY! [bar gets quieter]Jak už jsem říkal, tohle všechno, to, jak fungujeme... je to chaos. Je to starší než tohle město, než celá tahle země, kdo ví, jak dlouho už to trvá. }

{ 112 }{ Pokračuj. }{ Pokračuj. }{ 131 }{ }{ }{ }{ }{ }{ }{ }{ }{ VÍCE! }

{ 113 }{ Bude to na dlouho? }{ Bude to na dlouho? }{ 121 }{ }{ }{ }{ }{ }{ }{ }{ }{ Chceš mě uvěznit svým tlacháním na věčnost plus dvě? }
