### ISSUE TITLE
recepční hotel

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#208]
PANE BO-!>PANE BOŽE!

https://snag.gy/HSZnDK.jpg

**Comment by miracleflame** [comment]
@soulcharmer 

{	61	}{	Huh? Oh my Go- ... Ugghh! Someone call the CDC! It's one of the plague victims! Get away from me!	}
{	61	}{	Pane bo--! Zavolejte někdo epidemiologa! Je tu další oběť moru! Držte se ode mě dál!	}{	Pane bo--! Zavolejte někdo epidemiologa! Je tu další oběť moru! Držte se ode mě dál!	}{	#	}{	npc.SetDisposition("Disgust", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}

Ja by som tam keď tak pridal nejaké citoslovce hnusu, čo ho donúti nedokončiť slovo.

**Comment by soulcharmer** [comment]
{ 61 }{ Proboha! Zavolejte hygienu! Je tu další oběť moru! Nepřibližujte se! }
