### ISSUE TITLE
Jezebel Locke's key nosferatu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#209]
asi taky nesouvisí s češtinou, ale klíč od apartmánu nejde získat, ostatní klany si o něj řeknou na recepci, ale nosferatu  si ho musí vytisknout přes počítač a to nefunguje. 

tady je video jak by to mělo fungovat od 4:28 https://www.youtube.com/watch?v=tea3DnGlm74

zároveň by už mělo být opraveno v Unofficial Patch 5.6 +Fixed broken Empire hotel card printer usage and made it plus only. viz:  https://www.gamefaqs.com/boards/914819-vampire-the-masquerade-bloodlines/45241628

**Comment by miracleflame** [comment]
@maarten93 Máš odzálohovaný anglický folder Unofficial_Patch? Skúsil by si to s ním?
Prípadne mi pošli save na miracle.flame@gmail.com prosím.

**Comment by maarten93** [comment]
Tak bez češtiny to jde zkoušeno na čisté gog basic
předtím jsem měl k tomu češtinu a plus patch
https://snag.gy/6kmQ39.jpg
https://snag.gy/1Lx5ar.jpg
https://snag.gy/hszq6r.jpg

**Comment by maarten93** [comment]
@miracleflame s češtinou nejde kliknout na tiskárnu nezobrazí se ikona vypínače

**Comment by miracleflame** [comment]
Toto by to malo opraviť... skús.

**Comment by maarten93** [comment]
pořád nejde

**Comment by miracleflame** [comment]
Máš v Unofficial_Patch\vdata\hackterminals\empire_lobby_computer.txt ten riadok "runscript"	"cardPrinterEnablePlus()"? Možno bude treba použiť save ešte pred prvým načítaním mapy.

**Comment by maarten93** [comment]
https://snag.gy/hTysIg.jpg
musel sem použít save ještě před hotelem už to jde

**Comment by miracleflame** [comment]
Výborne, dobrý report.
