### ISSUE TITLE
Jack v baru - opravit

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#211]
"tvojem" --> "tvým" kroku
A ještě bych nahradil "málem" --> "skoro" (a ví skoro o každým tvým kroku?)
https://snag.gy/i9fE2M.jpg

**Comment by miracleflame** [comment]
Vy snád usilujete o to, aby všetky tie podivné charaktery v hre rozprávali čiste spisovne. :D 
No neviem, @soulcharmer rovnaká otázka, ako v #179 mám opraviť všetky výskyty "tvojem" na repe?

**Comment by Honzixx** [comment]
To né, musejí tam být určitý slangy, vulgarita, osobní slovník jednotlivců apod.
Ale Jack nikde takto nemluví, aby to byl slang. Příjde mi "tvojem" v celé větě jako pěst na oko :-D
Je to jen můj názor

**Comment by soulcharmer** [comment]
ok, dame

"... a ví málem o každým tvým kroku?"

@miracleflame spis bych se kouknul na ty vyskyty, kde pripadne davaji smysl a kde ne

diky
