### ISSUE TITLE
Jack v baru 2 - opravit

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#212]
Myslím, že tam má být "zombici" místo "zombii"
https://snag.gy/yq4t8s.jpg

**Comment by miracleflame** [comment]
Myslím, že to je 5. pád slova zombie, nie zombice.

**Comment by Honzixx** [comment]
Tak pak by tam mělo být normálně "zombie"

**Comment by miracleflame** [comment]
@soulcharmer Na kom, na čem, na zombie?

**Comment by Honzixx** [comment]
podle mě je to neskloňovatelné cizí slovo, takže zombie ve všech pádech. Uvidíme co na to @soulcharmer :-)

**Comment by soulcharmer** [comment]
jo, "zombie" je opravdu nesklonne...

a ted se jdu venovat jinemu tiketu :-)

diik
