### ISSUE TITLE
Princ

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#218]
věta "Dokážeš vůbec postihnout důsledky svých činů?" je zvláštní, hlavně slovo "postihnout".
nemělo by to být spíš něco jako "Uvědomuješ si důsledky svých činů?" nebo "Dokážeš si představit jaké budou následky?"
https://snag.gy/SrEfwD.jpg

**Comment by miracleflame** [comment]
{	531	}{	[Enraged]Co jsem ti říkal?! Celá policie už o tom ví! Dokážeš vůbec postihnout důsledky svých činů? Takováto pohroma bude v očích každého smrtelníka zavánět nadpřirozenem! Dokonce ani Sabbati by nebyli tak lehkomyslní!	}

{	531	}{	[Enraged]What did I tell you?!? It's all over the police radio! Do you comprehend the consequences of your actions? This kind of exposure reeks of the supernatural in mortal eyes! Even the Sabbat aren't this careless!	}

**Comment by soulcharmer** [comment]
{ 531 }{ [Enraged]Co jsem ti říkal?! Celá policie už o tom ví! Chápeš vůbec důsledky svých činů? Takováto publicita bude v očích každého smrtelníka zavánět nadpřirozenem! Dokonce ani Sabbati by nebyli tak ledabylí! }

diky
