### ISSUE TITLE
Tančící vlkodlaci.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#220]
Otevírej dvere vlkodlakovi v oblacich casto.

Tahle věta by chtěla opravit, a chtě lo by to tam zakomponovat něco jako: tady/zde
v angličtině to tam je: Open doors # here often, to the werewolf in the sky.
To zde je podstatná část té nápovědy
https://snag.gy/2X6shr.jpg

https://snag.gy/0idKpz.jpg

**Comment by miracleflame** [comment]
Open doors here often, to the werewolf in the sky.
In the end the ending, you'll manage to pass by...

Otvírej dveře tady často a uvidíš vlkodlaka v oblacích.
Na závěr budeš moci koncem projít...

**Comment by miracleflame** [comment]
luckypc oprava easter eggu #221			
06f658e

**Comment by miracleflame** [comment]
@soulcharmer ešte na toto mrkni, prosím.

**Comment by soulcharmer** [comment]
tento easter egg si nevybavuju. A jeste se to ma rymovat.

Bude fungovat tohle?

"Otvírej zde dveře často vlkodlakovi v oblacích.
A na konci konců bude průchod v rukou tvých..."

**Comment by miracleflame** [comment]
Môže byť. To pridal Wesp v UP. Na YT sú videá o tom ako to funguje.
