### ISSUE TITLE
kompilace-komplikace

### ISSUE THREAD

**Issue by 3Dtisk** [soulcharmer/gog_bloodlines_cz#226]
Ahoj, 
chtěl jsem si zahrát hru a při tom otestovat češtinu, Jenomže mám problém s kompilací, nedá se nějak dostat k už zkompilované verzi, prosím? případně, nenašla by se nějaká dobrá duše, která by mi poslala zkompilovanou verzi? 
PS: omlouvám se, že to píši do issues, ale nenašel jsem jiný způsob, kterak kontaktovat autora :)

**Comment by maarten93** [comment]
Zdravím,
Instalátor se zkompiluje sám po spuštění compile.cdm , ale musíš si nainstalovat tohe:   http://nsis.sourceforge.net/Download musíš to mít nainstalované v C:\Program Files (x86)\NSIS a potom nainstalovat http://nsis.sourceforge.net/FontName_plug-in , který se nainstaluje na špatné místo a je potřeba ručně přesunout do: "NSIS\Plugins\FontName.dll" do "NSIS\Plugins\x86-ansi\"  postup je napsaný v gog_bloodlines_cz/Instalator/notes.txt

**Comment by 3Dtisk** [comment]
No, to jsem udělal, ale nepremává. :-/

**Comment by maarten93** [comment]
Pokud je všechno udělané dobře tak se vytvoří Beta06Cestina_VTMBup96.exe  ve složce Instalator, stejná složka jako je compile.cdm a tím se teprve spustí instalace češtiny, 
https://snag.gy/HDn4dv.jpg Tady na obrázku instalátor a compile.cdm
https://snag.gy/czdSWh.jpg  Všechny součásti češtiny musí být na disku
https://snag.gy/eKDJIx.jpg NSIS musí být naistalován v program files (x86)
https://snag.gy/7u2MnE.jpg FontName.dll musí být umístěno na správném místě 
https://snag.gy/ybOzVo.jpg pokud je vše v pořádku tak se na kompilátoru musí na konci zobrazit tohle

**Comment by miracleflame** [comment]
@3Dtisk ak by ešte bolo treba pomôcť, napíš na miracle.flame@gmail.com
