### ISSUE TITLE
DMP-Death Mask Productions a MS- Maska Smrti

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#229]
Někde je použito Ms a jinde DMp

https://snag.gy/0tvE7Z.jpg MS

https://snag.gy/mhHrOT.jpg DMP

**Comment by Honzixx** [comment]
Páni ty jedeš, super postřehy. Budu se muset více snažit ☺
Sjednotil bych to podle toho, jaký název produkce je přímo na nahrávkách kazet

**Comment by maarten93** [comment]
Jo máš pravdu, na kazetě DMP, koukám že jsem napsal MS jako Masky smrti, ale je to jenom Maska smrti.
https://snag.gy/kZ9nON.jpg

**Comment by maarten93** [comment]
https://snag.gy/Oaz4yF.jpg Maska smrti
https://snag.gy/8Cu37U.jpg MS
https://snag.gy/vzskSj.jpg MS
https://snag.gy/pDqK1E.jpg MS
https://snag.gy/PFBSN7.jpg Masku smrti a MS
https://snag.gy/HlL5Kv.jpg MS
https://snag.gy/VvtGLo.jpg DMP napsáno na dveřích
https://snag.gy/mv08fZ.jpg MS
https://snag.gy/iLtSGn.jpg MS

MS nebo maska smrti je ve hře použito častěji.

**Comment by miracleflame** [comment]
Ešte než sa pustím do prerábania textúr, @soulcharmer napadá ti nejaký lepší preklad Death Mask Production v zmysle, Studio Maska Smrti, SMS napríklad?

**Comment by soulcharmer** [comment]
Hm, "death mask" je posmrtná maska, to tam uniklo

Takze bych dal proste

Death Mask Production -> Posmrtná maska

diky

**Comment by miracleflame** [comment]
Všade opravené + [textúra](https://snag.gy/v4j96X.jpg)
