### ISSUE TITLE
chrlič

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#232]
Tot divadlo je mé
Toto
Ještě ta budova vypadá spíše jak kino než divadlo.
https://snag.gy/1mZKWq.jpg

**Comment by miracleflame** [comment]
@soulcharmer  ono je to fakt kino http://www.tclchinesetheatres.com/
poprerábam to?

**Comment by soulcharmer** [comment]
ani ne, cekal bych, ze ten chrlic je z doby, kdy kina jeste nebyla, takze z jeho pohledu je to spis spravne.

ale diky za opravu toho preklepu
