### ISSUE TITLE
Mercurio Zbraně?

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#240]
Nevím jestli je to schválně, ale chtěl jsem po Mercuriovi plamenomet, ale on místo toho sehnal odstřelovací pušku.

**Comment by miracleflame** [comment]
To bude niečo ako s tou tahací hračkou... repliku poprosím

**Comment by maarten93** [comment]
https://snag.gy/45KaB6.jpg
https://snag.gy/vNpW5r.
Asi se to bude špatně zkoušet protože to trvá dlouho než nějakou zbraň sežene.
Navíc plamenomet by měl být, k dispozici až po Italian Dinner: http://vtmb.wikia.com/wiki/Flamethrower
A tem jsem se ještě nedostal.

**Comment by maarten93** [comment]
Tak že to nespíš bude tím, ale na výběr už tam je hned od začátku a pamatuji se že jsem mu říkal že chci plamenomet.

**Comment by maarten93** [comment]
The sniper rifle is restored content that affects the gameplay and therefore only available in the plus version of the Unofficial Patch!

**Comment by miracleflame** [comment]
Myslím, že neexistuje nejaká spojitosť medzi dialógmi a tým, čo sa objaví v repertoári.
Dialógy majú svoju osobitnú požiadavku na fázu hry, kedy sa sprístupnia.
Repertoár má svoju vlastnú požiadavku na fázu hry, kedy sa sprístupnia, obvykle o niečo vyššiu než majú dialógy.

To vyvoláva dojem, že Mercurio s odstupom času zháňa to, na čo sa hráč pýtal, ale je to len kozmetický trik. V skutočnosti sa repertoár aktualizuje bez ohľadu na absolvované dialógy.

Uvidíš časom, či sa plameňomet objaví po Italian Dinner.

Tiket zatvorím. Dík za každý postreh, vždy je to zmysluplné. ;)
