### ISSUE TITLE
modelová občanka a Spletitá síť 

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#241]
Tyto dva úkoly jde splnit jen pokud se spletitá síť -(část divadlo) dokončí než se začne plnit modelová občanka, nebo se splní modelová občanka, předtím než se získá zadání úkolu spletitá síť -(část divadlo). Pokud jsou v žurnálu oba dva úkoly, modelová občanka i spletitá síť -(část divadlo) a modelová občanka se dokončí před spletitou sítí -(část divadlo), tak se úkol spletitá síť -(část divadlo) nedá dokončit. Je to z důvodu nedostatku web kamer v inventáři. Na modelová občanka se potřebují tři kamery, ale dostanu jen jednu, což by tolik nevadilo, kamery jdou umístit i když je v inventáři nemám, na spletitou síť -(část divadlo) potřebují jednu kameru a dostanu jen jednu kameru, kterou musím mít v inventáři aby jsem ji mohl umístit.

To znamená že pokud mám oba dva úkoly najednou, mám v inventáři jen dvě kamery, když umístím kamery v modelové občance (jsou to tři různá místa), použijí dvě kamery z inventáře + jednu kameru kterou v inventáři nemám(tady to nevadí) a pak když jdu na úkol spletitá síť -(část divadlo) už žádnou další kameru nemám a proto nejde umístit(tady jí musím mít v inventáři).

https://snag.gy/VLCq2Y.jpg tady je žurnál s oběma úkoly.
https://snag.gy/oty3br.jpg 2 bezdrátové kamery.
https://snag.gy/cZaLCj.jpg tady místo v divadle kam se má umístit kamera.
https://snag.gy/d0kHpm.jpg jenže už nemám v inventáři žádnou kameru.
https://snag.gy/lTYbtQ.jpg jediný způsob jak ve hře problém obejít.

**Comment by Honzixx** [comment]
Zkusil bych to i bez češtiny, jestli originál UP dává taky málo kamer na "Modelovou občanku". Klidně se na to můžu podívat já dneska.

**Comment by miracleflame** [comment]
Je dosť pravdepodobné, že to je buggy situácia, ktorá prišla s UP ako už býva zvykom. Pretože pôvodne hráč dostával ku questu modelová občanka tri kamery. S UP teraz dostáva namiesto dvoch kamier nejaké dva úplne mimo misu predmety, o ktorých ani nebola reč, jmenovku a pomačkaný kalich.. aspoň mne to tak vyšlo v hre za Tremere. Ale ktovie... možno bude jednoduchie skúsiť to s EN súbormi než hrabať sa v nich, porovnávať a hľadať odchýľku, ktora možno ani neexistuje.

**Comment by Honzixx** [comment]
Tak v EN to dává normálně 3 kamery https://snag.gy/YXOzVA.jpg . 

Hádám, že v dialogu jsou spínače, tak zde je část konverzace:
tady 1. příjmu quest https://snag.gy/YjXfnK.jpg 
a na to se udělá zápis v žurnálu a dostanu kamery https://snag.gy/raHKsu.jpg

V CZ je to jak říkáš Miro, dostanu 3 různý itemy a v nich jen jednu kameru.

Stejná část konverzace v CZ:
tady 1. příjmu quest https://snag.gy/0BDoZS.jpg
a na to se udělá zápis v žurnálu a dostanu 3 itemy https://snag.gy/RKfqAm.jpg
https://snag.gy/fyvStU.jpg
https://snag.gy/vMfm4G.jpg

**Comment by miracleflame** [comment]
Toto určite bolo treba fixnúť... ale ešte nie je isté, či to pomôže predísť kolízii s divadlom. @maarten93 otestuješ to prosím?

**Comment by maarten93** [comment]
https://snag.gy/9q4bVk.jpg 
https://snag.gy/r5ZgP9.jpg ted už dá správně tři kamery, a ty ostatní předměty, tam už vůbec nejsou
https://snag.gy/AxB1Ra.jpg akorát nefunguje diakritika, ale to je asi tím že je složka braná přímo ze souboru čeština.
Ještě vyzkouším, to divadlo.

**Comment by maarten93** [comment]
https://snag.gy/buRV7Q.jpg teď už jsou správně v inventáři 4 kamery.
https://snag.gy/1fB7Ot.jpg po rozmístění všech kamer v bytě Tawni, pořád zbude jedna kamera v inventáři.
https://snag.gy/rTulIM.jpg 
https://snag.gy/iMpeU8.jpg
V divadle už jde umístit bez problémů.

**Comment by miracleflame** [comment]
Výborne... tá diakritika je kvôli tomu, ako píšeš.
