### ISSUE TITLE
mcfly - ženský tvar

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#242]
Tady by to chtělo hodit ženskou variantu "oba dva" --> "obě dvě". Mluví o mně a Heather.
https://snag.gy/kfabFK.jpg
je to oběť, kterou Heather přivede domů: /dlg/generic/mcfly.dlg

**Comment by miracleflame** [comment]
Konečne hlásenie tohto typu. Takých som čakal najviac.

**Comment by Honzixx** [comment]
Ono toto je první, kde není ženský tvar, na které sem zatím narazil. Určitě jich ještě pár bude ;-)
