### ISSUE TITLE
Bezdomovec Bill

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#243]
Nevím, jestli se to už náhodou neřešilo, kdyžtak se omlouvám, jestli to tak je schválně, nebo už opraveno :-)
"moh´" --> "mohl" v /dlg/downtown la/tin_can_bill.dlg 
https://snag.gy/MwQKjV.jpg

**Comment by maarten93** [comment]
Ta samí je i u Mitnicka ten taky používá moh s apostrofem.

**Comment by miracleflame** [comment]
To sa v #175 zatvorilo ako intended.
Niektorí tak rozprávajú.
