### ISSUE TITLE
Mapa kanalizace v čínské čtvrti.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#244]
https://snag.gy/GWxczH.jpg tady chybí křížek zde stojíte, jako je na mapách jinde třeba tady: https://snag.gy/5KzuSN.jpg

**Comment by miracleflame** [comment]
Aha... ani na origináli to nie je.
Kde presne by to tam malo byť?

**Comment by maarten93** [comment]
Nejsem u pc takže to přesně neřeknu, ale přibližně  tam jak je budova 3

**Comment by miracleflame** [comment]
Mám to.. opravím.
