### ISSUE TITLE
Ming Xiao 2 ?

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#246]
https://snag.gy/K5C69j.jpg
Musím jít někam přesáhnout tyhle kidy. Nashle.
                            přestát
                            
Nevím, ale tahle odpověď, mi tam úplně nesedí.

**Comment by Honzixx** [comment]
a ještě tvrdé Y "kidy" --> "kydy"

**Comment by maarten93** [comment]
Jo, to jsem nějak přehlíd

**Comment by miracleflame** [comment]
Mne to tam sedí úplne. Ale kidy treba opraviť.

{	121	}{	On the contrary, it is another chance for us to find our place in the universe, a chance for transcendence. We are not damned, not burdened with an ancient guilt, as in the legend of your biblical progenitor.	}
{	127	}{	Uh, I'm transcending out of this bullshit. Later.	}

**Comment by miracleflame** [comment]
Ešte by to možno @soulcharmer chcel nejako vylepšiť.. napríklad Potřebuju jít přesáhnout tyhle kydy.

**Comment by soulcharmer** [comment]
teda ale pekne se v tom nimrate :-)

{ 127 }{ Uf, musím se jít povznést nad tyhle kydy. Nashle. }

diky za report

**Comment by miracleflame** [comment]
Len pre ujasnenie, znamená to, že aj tú predchádzajúcu vetu upravím na...?
Právě naopak. Je to pro nás druhá šance objevit své místo ve vesmíru, šance dosáhnout povznesení. Nejsme zatracení a zatížení nějakým prastarým hříchem, jak je tomu v legendě o vašem biblickém praotci.

**Comment by soulcharmer** [comment]
jo aha, uz to vidim. 

"Právě naopak. Je to pro nás další příležitost najít své místo ve vesmíru, šance povznést naši existenci. Nejsme zatracení a zatížení nějakým prastarým hříchem, jak je tomu v legendě o vašem biblickém praotci."

diky
