### ISSUE TITLE
Lassiter Killmatic/IMI Uzi

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#247]
http://vtmb.wikia.com/wiki/Lassiter_Killmatic

https://snag.gy/berz2L.jpg
Uzi byla vyvinut jako   vyvinuta

**Comment by miracleflame** [comment]
V basic je Lassiter Killmatic mužského rodu, v Plus premenovaný na Uzi. To je moja chyba pri úprave textov na Plus formát. Díky.

**Comment by maarten93** [comment]
@miracleflame Mám staženou češtinu po poslední úpravě, ale stejně tam pořád mám tuhle chybu.

**Comment by miracleflame** [comment]
To je tým, že som neurobil konverzný dump pre UP_Plus_CZ_fontfriendly/vdata/items/item_w_uzi.txt ale aj k tomu dojde, keď budem najbližšie robiť dumpy. Chyba sa každopádne považuje za opravenú.
