### ISSUE TITLE
Televize u Tawi

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#250]
https://snag.gy/PIWSJo.jpg
Televize u Tawi v bytě je zaplá, ale nejsou k ní titulky ani zvuk

**Comment by miracleflame** [comment]
Takáto funkcionalita TV na mape hw_tawni_1.bsp nikdy ani nebola, ale napíšem Wespovi, že by to bolo príjemné oživenie tejto dead&mute lokácie. Dík.
