### ISSUE TITLE
Chybná úroveň mizení při ztrátě efektu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#251]
https://snag.gy/Fv9mWw.jpg  mizení úrovně 1 selhalo: útočení.
https://snag.gy/AQKgR8.jpg já mam ale mizení na 5.

**Comment by Honzixx** [comment]
Zajímavé, mně mizení u Malka ukazuje normálně, teď jsem to testnul na všech úrovních. Že by to u Nosferatů a Malkavianů nebyla tatáž disciplína?
screen lvl 5 https://snag.gy/5r4YKb.jpg

**Comment by maarten93** [comment]
To je divné, pak se na to zkusím víc podívat, ale dnes už nemám čas.

**Comment by miracleflame** [comment]
Použil som najnovšie súbory prekladu a v novej hre za Nosferatu female, historie Kleopatra, čo ovplyvňuje Mizení som si nacheatoval
giftxp 50
togglechareditor
a otestoval piatu úroveň bez problémov všetko ako má byť.
@maarten93 keby sa ti to opakovalo a zistil by si v čom je problém, určite tento tiket znovu otvor a napíš.

**Comment by maarten93** [comment]
@miracleflame přišel jsem na to kdy se to děje, když jsem neviditelný a cestuji mezi lokacemi tak, hned po načtení postava automaticky vytáhne zbraň a zaútočí a tehdy se to napíše.

**Comment by maarten93** [comment]
https://www.dropbox.com/s/oda9ur34ruoo93d/vampire%202017-02-20%2020-20-58-57.avi?dl=0

**Comment by miracleflame** [comment]
Tak to je pekná súhra rozličných náhodilostí a Wesp by na to určite povedal, že to je limitácia enginom a nič sa s tým nedá spraviť, alebo nestojí za tú námahu.
