### ISSUE TITLE
kurýr za rychlýma prachama - buglej

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#252]
Kurýr zůstane po dialogu stát na místě, přitom má utéct. 
Nemohu to ani nijak ukončit a zůstanu zaseklý s ním.
https://snag.gy/2Lna85.jpg
https://snag.gy/Xgari7.jpg

**Comment by maarten93** [comment]
mě to fungovalo normálně, ale podobný problém jsem měl tady: https://github.com/soulcharmer/gog_bloodlines_cz/issues/185
Skus odinstalovat češtinu a plus patch tak a bys měl jen čistou, gog basic verzi.
A vyzkoušej jestli to potom půjde, pak znova nainstaluj plus patch a češtinu.

**Comment by Honzixx** [comment]
To už sem taky zkusil s čistou instalací. Ještě to vyzkouším párkrát i na různých uložených pozicích

**Comment by miracleflame** [comment]
@Honzixx Ešte skús zmazať **Unofficial_Patch\maps\graphs\hw_hub_1.ain** a Unofficial_Patch\maps\graphs\hw_hub_1.loc ale budeš museť začať od savu ešte pred príchodom do HW.

**Comment by Honzixx** [comment]
Zvláštní, pomohlo to smazání souborů hw_hub_1 + načtení Hollywoodu znova. A to i v původní sestavě hry, ve které se chyba vyskytla.  Díky :-)
