### ISSUE TITLE
dlg diff revize

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#253]
@soulcharmer nie, že by si mal neviem koľko času, ale možno výzva, ktorá by ťa bavila viac než preklady...

Moc by nám pomohol skript, ktorý spraví diff dvoch dlg súborov s takouto podmienkou:
Keď obsah medzi prvým ohraničením {} v riadku sa rovná v oboch súboroch (inými slovami nájdi line s tým istým číslom), potom zobraz rozdiel obsahu v 4. 5. a 6. ohraničení {} (čiže inými slovami urob diff linkovania na iný line, diff podmienky line a diff akcie danej line).

Príklad:
Sprav diff hrubo vyznačných častí pre line 4 medzi českým a anglickým dlg.
{	4	}{	Ty jseš vůdce bratrstva Devátého kruhu?	}{	Ty jseš vůdce bratrstva Devátého kruhu?	}{	**21**	}{	**not IsClan(pc, "Malkavian")**	}{	**G.Vick_Q2 = 1**	}{	}{	}{	}{	}{	}{	}{	}

Toto by nám brutálne pomohlo zabezpečiť, že naše dlg budú bezchybne zodpovedať najnovšej UP verzii.

**Comment by miracleflame** [comment]
Alternatíva:
Porovnal by som to ručne pomocou Bloodline Dialogue editor, ktorý si nadizajnoval, ale neviem ako naformulovať search string pre custom filter. Chcel by som vyfiltrovať len riadky, kde Condition (piaty bracket) alebo Action (šiesty bracket) sú non-empty. Tento postup by mi však neumožnil nájsť rozdiely v linkovaní (štvrtý bracket), ale lepšie než nič, pokial by skript nebol.

**Comment by miracleflame** [comment]
Darí sa mi porovnávať to pomocou Excelu. Vložím dlg do hárku s delimiterom } a prebytočné stĺpce odstránim. Ešte si zháňam plugin, ktorý mi urobí diff hárkov. Takže požiadavku na teraz pozastavujem.

**Comment by miracleflame** [comment]
Downtown zdiffovaný. Na revíziu:

boris.dlg
malk
{	92	}{	I find this unacceptable, and you'll find yourself defenseless.	}
{	92	}{	To považuji za nepřijatelné a ty se považuj za zranitelného.}

dema.dlg
"{	37	"			"{	51	"	"{	Intimidate 4	"	"{	"	"{	"	"{	"	"{	"	"{	"	"{	"	"{	"	"{	**Out. Of the way. Mortal.**	"
**Jdi. Z cesty. Smrtelníku.**

tutorial_security_guard.dlg
{	25	}{	**With me at your side you may have a chance.**	}{	61	}{	Presence 1 & G.Patch_Plus == 1	}
{	25	}{	**Se mnou po vašem boku máte šanci.**	}{	61	}{	Presence 1 & G.Patch_Plus == 1	}

{	26	}{	No, but if SWAT comes, they'll drive the gunmen down here. You want that?	}{	No, but if SWAT comes, they'll drive the gunmen down here. You want that?	}{	31	}{	Persuasion 1	}{	}{	}{	}{	}{	}{	}{	}{	**I did nothing, but the good guys will bring the bad guys down here.**	}
{	26	}{	Ne, ale jestli přijede zásahovka, zažene ty střelce sem. To chcete?	}{	Ne, ale jestli přijede zásahovka, zažene ty střelce sem. To chcete?	}{	31	}{	Persuasion 1	}{	}{	}{	}{	}{	}{	}{	}{**Já nic. Ale správňáci zaženou záporáky sem dolů.**	}

So can we go now?
Tak už můžem jít?

{	62	}{	Go ahead.	}{	Go ahead.	}
{	62	}{	Až po vás.	}{	Až po vás.	}

{	63	}{	Radši zůstaňte tady, může to být pro vás nebezpečné.	}{	Radši zůstaňte tady, může to být pro vás nebezpečné	}{	0	}{	}{	G.Tut_Secg = 3; FindPlayer().HumanityAdd( 1 )	}{	}{	}{	}{	}{	}{	}{	Nenásledujte mě, pokud chcete žít.	}


venus.dlg
{	52	}{	Yeah, being an angel sucks.	}{	Yeah, being an angel sucks. 	}{	61	}{	}{	}{	}{	}{	}{	}{	}{	}{	Indeed, and I won't become an angel anyway.	}
{	52	}{	Jo, být andělem stojí za prd. }{	Jo, být andělem stojí za prd. }{	61	}{	}{	}{	}{	}{	}{	}{	}{	}{	Vskutku. A ze mě anděl stejně nebude. 	}

**Comment by miracleflame** [comment]
killer.dlg
{	150	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	0	}{	}{	G.Killer_Hostile = 1	}{	}{	}{	}{	}{	}{	}{	**Die, clanless one!**	}
{	150	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	0	}{	}{	G.Killer_Hostile = 1	}{	}{	}{	}{	}{	}{	}{	**Zemři, bezeklanný!**	}

knox.dlg
{	132	}{	A který vampír z tebe udělal ghúla?	}{	A který vampír z tebe udělal ghúla?	}{	621	}{	G.Mercurio_Quest != 2 and G.Knox_Master == 0	}{	G.Knox_Master = 1	}{	}{	}{	}{	}{	}{	}{	**What creature spawned you, golden ghoul?**	}
{	132	}{	A který vampír z tebe udělal ghúla?	}{	A který vampír z tebe udělal ghúla?	}{	621	}{	G.Mercurio_Quest != 2 and G.Knox_Master == 0	}{	G.Knox_Master = 1	}{	}{	}{	}{	}{	}{	}{	**Který našinec tě povolal, zlatý ghúle?**	}

mercurio.dlg
{	655	}{	I'm no sniper, but show me the rest of your stuff.	}{	I'm no sniper, but show me the rest of your stuff.	}{	0	}{	G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	I like to meet people up close. And I need toys for that.	}
{	655	}{	Nejsem snajpr, ale ukaž mi své ostatní zboží.	}{	Nejsem snajperka, ale ukaž mi své ostatní zboží	}{	0	}{	G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	Nejradši to mám zblízka. A na to potřebuji hračky.	}

vandal.dlg
{	192	}{	Forget I said anything. I don't need your blood.	}{	Forget I said anything. I don't need your blood.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	You lost your gold, little blood slave. I am no longer here.	}
{	192	}{	Zapomeň, že jsem něco řekl. Nepořebuji tvou krev.	}{	Zapomeň, že jsem něco řekla. Nepořebuji tvou krev.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Přišel si o své zlato, malý otroku krve. Už tady nejsem.	}

**Comment by miracleflame** [comment]
Tak som dokončil veškeré diffovanie dlg súborov a opravil, čo som našiel. Tieto sú už updatnuté na 9.7. Z commitov je vidieť konkrétne zmeny, aj keď posledných 5 súborov som upravoval priamo v Exceli kvôli vyčerpanosti a zmeny nie sú v celej tej spleti patrné. Ešte prejdem tikety, čo sa bude dať opraviť a zbehnem dump.

@Honzixx @maarten93 poprosím vás po dumpe otestovať tých posledných 5 postáv z diffov, či sa s nimi dá zahájiť zmysluplný dialóg. Môžete mi aj zbežne opraviť gramatiku v prekladoch vyššie, nech to @soulcharmer potom už len narýchlo prejde.

**Comment by maarten93** [comment]
Downtown zdiffovaný. Na revíziu:

boris.dlg
malk
{	92	}{	I find this unacceptable, and you'll find yourself defenseless.	}
{	92	}{	To považuji za nepřijatelné a ty se považuj za zranitelného.}

dema.dlg
"{	37	"	"{	51	"	"{	Intimidate 4	"	"{	"	"{	"	"{	"	"{	"	"{	"	"{	"	"{	"	"{	Out. Of the way. Mortal.	"
Jdi. Z cesty. Smrtelníku.

tutorial_security_guard.dlg
{	25	}{	With me at your side you may have a chance.	}{	61	}{	Presence 1 & G.Patch_Plus == 1	}
{	25	}{	Se mnou po vašem boku máte šanci.	}{	61	}{	Presence 1 & G.Patch_Plus == 1	}

{	26	}{	No, but if SWAT comes, they'll drive the gunmen down here. You want that?	}{	No, but if SWAT comes, they'll drive the gunmen down here. You want that?	}{	31	}{	Persuasion 1	}{	}{	}{	}{	}{	}{	}{	}{	I did nothing, but the good guys will bring the bad guys down here.	}
{	26	}{	Ne, ale jestli přijede zásahovka, zažene ty střelce sem. To chcete?	}{	Ne, ale jestli přijede zásahovka, zažene ty střelce sem. To chcete?	}{	31	}{	Persuasion 1	}{	}{	}{	}{	}{	}{	}{	}{Já nic. Ale správňáci zaženou záporáky sem dolů.	}

So can we go now?
Tak už můžem jít?
Tak už můžeme jít?

{	62	}{	Go ahead.	}{	Go ahead.	}
{	62	}{	Až po vás.	}{	Až po vás.	}

{	63	}{	Better stay here, it is too dangerous for you.	}{	Better stay here, it is too dangerous for you.	}{	0	}{	}{ G.Tut_Secg = 3; FindPlayer().HumanityAdd( 1 )	}{	}{	}{	}{	}{	}{	}{	Follow me not, if you want to live.	}
{	63	}{	Radši zůstaňte tady, může to být pro vás nebezpečné.	}{	Radši zůstaňte tady, může to být pro vás nebezpečné	}{	0	}{	}{	G.Tut_Secg = 3; FindPlayer().HumanityAdd( 1 )	}{	}{	}{	}{	}{	}{	}{	Nenásledujte mě, pokud chcete žít.	}

venus.dlg
{	52	}{	Yeah, being an angel sucks.	}{	Yeah, being an angel sucks. }{	61	}{	}{	}{	}{	}{	}{	}{	}{	}{	Indeed, and I won't become an angel anyway.	}
{	52	}{	Jo, být andělem stojí za prd. }{	Jo, být andělem stojí za prd. }{	61	}{	}{	}{	}{	}{	}{	}{	}{	}{	Vskutku. A ze mě anděl stejně nebude. }

**Comment by maarten93** [comment]
killer.dlg
{	150	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	0	}{	}{	G.Killer_Hostile = 1	}{	}{	}{	}{	}{	}{	}{	Die, clanless one!	}
{	150	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	0	}{	}{	G.Killer_Hostile = 1	}{	}{	}{	}{	}{	}{	}{	Zemři, bezeklanný!	}

killer.dlg
{	150	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	0	}{	}{	G.Killer_Hostile = 1	}{	}{	}{	}{	}{	}{	}{	Die, clanless one!	}
{	150	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	Jseš ostuda našinců. Chcípni, kaitife!	}{	0	}{	}{	G.Killer_Hostile = 1	}{	}{	}{	}{	}{	}{	}{	Zemři, bezklanný!	}

knox.dlg
{	132	}{	A který vampír z tebe udělal ghúla?	}{	A který vampír z tebe udělal ghúla?	}{	621	}{	G.Mercurio_Quest != 2 and G.Knox_Master == 0	}{	G.Knox_Master = 1	}{	}{	}{	}{	}{	}{	}{	What creature spawned you, golden ghoul?	}
{	132	}{	A který vampír z tebe udělal ghúla?	}{	A který vampír z tebe udělal ghúla?	}{	621	}{	G.Mercurio_Quest != 2 and G.Knox_Master == 0	}{	G.Knox_Master = 1	}{	}{	}{	}{	}{	}{	}{	Který našinec tě povolal, zlatý ghúle?	}

mercurio.dlg
{	655	}{	I'm no sniper, but show me the rest of your stuff.	}{	I'm no sniper, but show me the rest of your stuff. }{	0	}{	G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	I like to meet people up close. And I need toys for that.	}
{	655	}{	Nejsem snajpr, ale ukaž mi své ostatní zboží.	}{	Nejsem snajperka, ale ukaž mi své ostatní zboží	}{	0	}{ G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	Nejradši to mám zblízka. A na to potřebuji hračky.	}

mercurio.dlg
{	655	}{	I'm no sniper, but show me the rest of your stuff.	}{	I'm no sniper, but show me the rest of your stuff. }{	0	}{	G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	I like to meet people up close. And I need toys for that.	}
{	655	}{	Nejsem odstřelovač, ale ukaž mi své ostatní zboží.	}{	Nejsem odstřelovačka, ale ukaž mi své ostatní zboží	}{	0	}{ G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	Nejradši to mám zblízka. A na to potřebuji hračky.	}

vandal.dlg
{	192	}{	Forget I said anything. I don't need your blood.	}{	Forget I said anything. I don't need your blood.	}{	0 }{	}{	}{	}{	}{	}{	}{	}{	}{	You lost your gold, little blood slave. I am no longer here.	}
{	192	}{	Zapomeň, že jsem něco řekl. Nepořebuji tvou krev.	}{	Zapomeň, že jsem něco řekla. Nepořebuji tvou krev.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Přišel si o své zlato, malý otroku krve. Už tady nejsem.	}

vandal.dlg
{	192	}{	Forget I said anything. I don't need your blood.	}{	Forget I said anything. I don't need your blood.	}{	0 }{	}{	}{	}{	}{	}{	}{	}{	}{	You lost your gold, little blood slave. I am no longer here.	}
{	192	}{	Zapomeň, že jsem něco řekl. Nepotřebuji tvou krev.	}{	Zapomeň, že jsem něco řekla. Nepotřebuji tvou krev.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Přišel si o své zlato, malý otroku krve. Už tady nejsem.	}

**Comment by Honzixx** [comment]
Tak sem otestoval dialogy Vandal, Mercurio, Knox, Killer, Venus a nenarazil sem na žádný problém ;-)

**Comment by soulcharmer** [comment]
Mam tu drobne upravy a opravy:


Knox.dlg

Který našinec tě povolal, zlatý ghúle?  ->  Který našinec tě stvořil, zlatý ghúle?

Mercurio:

Nejradši to mám zblízka. A na to potřebuji hračky.  -> Nejradši potkávám lidi nablízko. A na to potřebuji hračky.

Vandal:

Zapomeň, že jsem něco řekl. Nepotřebuji tvou krev.  -> Zapomeň na to. Nepotřebuju tvou krev.
Přišel si o své zlato, malý otroku krve. Už tady nejsem. -> Přišel si o své zlato, malý otroku krve. Jsem někde jinde.

boris.dlg, malk
{ 92 }{ To shledávám nepřijatelným a tebe shledávám bezbranným. }

dema.dlg

"Smrtelníku. Jdi. Mi. Z cesty."

tutorial_security_guard.dlg

{ 25 }{ Se mnou po boku to můžete přežít. }{ 61 }{ Presence 1 & G.Patch_Plus == 1 }

{ 26 }{ Ne, ale jestli přijede URNA, zažene ty střelce sem. To chcete? }{ Ne, ale jestli přijede URNA, zažene ty střelce sem. To chcete? }{ 31 }{ Persuasion 1 }{ }{ }{ }{ }{ }{ }{ }{ Nemám s tím nic společného, ale klaďasové naženou zloduchy sem. }

{ 63 }{ Radši zůstaňte tady, je tu na vás moc nebezpečno. }{ Radši zůstaňte tady, je tu na vás moc nebezpečno. }{ 0 }{ }{ G.Tut_Secg = 3; FindPlayer().HumanityAdd( 1 ) }{ }{ }{ }{ }{ }{ }{ Nenásledujte mě, pokud chcete žít. }


venus.dlg

{ 52 }{ Jo, být andělem je na prd. }{ Jo, být andělem je na prd. }{ 61 }{ }{ }{ }{ }{ }{ }{ }{ }{ Vskutku. A já se andělem stejně nestanu. }


diky
