### ISSUE TITLE
chcou

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#254]
cestina/sound/character/male/unique/tseng/float_10.lip
"Gwai lo přilezou a myslí si, že všechno ví. Neví nic. Chcou svatýho Johna Warta. Já nemám svatýho Johna Warta, tupci."

cestina/dlg/Hollywood/samantha.dlg
{ 41 }{ Myslím, že nevíš, co říkáš. My ti pomůžeme. Uvidíš, všichni tě chcou vidět zpátky, tak jak tě známe. Počkej tu. Zajdu si zavolat. Všechno bude zase v pohodě. }

cestina/dlg/Hollywood/misti.dlg
{ 61 }{ A jsme tu. Tak co by se ti tak líbilo? Miluju chlapy, co dokážou říct, co chcou a jak to chcou... }

cestina/dlg/Hollywood/gargoyle.dlg
{ 141 }{ Bezduché stvůry! Stále chcou více moci a více otroků! Měl bych to skoncovat a zabít tě! }

cestina/dlg/downtown la/pisha.dlg
{ 281 }{ Je to Alamutův klíč. Do těch, kteří ti chcou ublížit, vnese hrůzu. Bude pro ně mnohem těžší tě zasáhnout. }

cestina/dlg/main characters/johansen.dlg
{ 41 }{ Proč to dělají? Co je to tady za nesmysl s těmi zbraněmi a kříži a řečech o vampírech. Proč mě tady chcou držet? Co je to za lidi? }

cestina/dlg/main characters/jack.dlg
{ 914 }{ Respektuji našince, kteří vědí, co chcou. }{ Respektuji našince, kteří vědí, co chcou. }

cestina/dlg/chinatown/ji.dlg
{ 382 }{ No mně to může být jedno, když mi dva staří blázni chcou dát všechny svý peníze za mord. }

cestina/dlg/main characters/caine.dlg
{ 81 }{ Zdá se, že je tu mnoho těch, kteří chcou získat Kainovy děti na svou stranu... mnoho těch, co věří, že oni utvářejí osud své krve. Pracujete pro prince LaCroixe, že? }

cestina/dlg/santa monica/bertram.dlg
{ 941 }{ Kamarilla [cam-uh-RILL-uh]funguje. Když necháš vampíry, ať si dělají, co chcou, skončíš u kaitifů[KAY-tiff], co propadají běsu přímo v ulicích, u mdlé krve, co porušuje Maškarádu, a u lovců, co budou čenichat kolem. Zákon a pořádek je našincův kamarád. }

cestina/dlg/downtown la/prince2.dlg
{ 671 }{ Nebuď tak naivní. Kuei-Jinové jsou démoni - podvedli tě - potřebují, abys mi šel po krku. Chcou toto město od chvíle, kdy sem vstoupili, a pokud dosáhnout toho, že se začneme zabíjet mezi sebou, budou to mít mnohem snažší. }

cestina/dlg/downtown la/damsel.dlg
{ 111 }{ Zkusím tě uvést do obrazu. Kamarilla příjímá za své všechny našince, ať chcou nebo ne. Takže když uděláš něco, co nemají rádi, patříš holt do Kamarilly, a schytáš to podle jejich zákonů, ať se ti to líbí nebo ne. }

cestina/dlg/Hollywood/vv.dlg
{ 623 }{ Pokud je ta lovkyně problém, zabiju ji... }{ Pokud je ta lovkyně problém, zabiju ji... }{ 281 }{ G.Velvet_Hunter == 2 and G.Velvet_Quest < 1 }{ }{ }{ }{ }{ }{ }{ }{ Žízním po krvi těch, co chcou tu mou. }

**Comment by soulcharmer** [comment]
cestina/sound/character/male/unique/tseng/float_10.lip
"Gwai lo přilezou a myslí si, že všechno ví. Neví nic. Chcou svatýho Johna Warta. Já nemám svatýho Johna Warta, tupci."

tohle je Tseng, muzeme nechat :)

cestina/dlg/Hollywood/samantha.dlg
{ 41 }{ Myslím, že nevíš, co říkáš. My ti pomůžeme. Uvidíš, všichni tě chcou vidět zpátky, tak jak tě známe. Počkej tu. Zajdu si zavolat. Všechno bude zase v pohodě. }

"... Uvidíš, všichni tě chtějí tak, jak tě známe. ..."

cestina/dlg/Hollywood/misti.dlg
{ 61 }{ A jsme tu. Tak co by se ti tak líbilo? Miluju chlapy, co dokážou říct, co chcou a jak to chcou... }

"Tak co by se ti líbilo? Miluju chlapy, co dokážou říct, co chtějí a jak to chtějí..."

cestina/dlg/Hollywood/gargoyle.dlg
{ 141 }{ Bezduché stvůry! Stále chcou více moci a více otroků! Měl bych to skoncovat a zabít tě! }

"Stále chtějí více moci a více otroků!"

cestina/dlg/downtown la/pisha.dlg
{ 281 }{ Je to Alamutův klíč. Do těch, kteří ti chcou ublížit, vnese hrůzu. Bude pro ně mnohem těžší tě zasáhnout. }

"Do těch, kteří ti budou chtít ublížit, vnese hrůzu."

cestina/dlg/main characters/johansen.dlg
{ 41 }{ Proč to dělají? Co je to tady za nesmysl s těmi zbraněmi a kříži a řečech o vampírech. Proč mě tady chcou držet? Co je to za lidi? }

"Proč mě tady drží?"

cestina/dlg/main characters/jack.dlg
{ 914 }{ Respektuji našince, kteří vědí, co chcou. }{ Respektuji našince, kteří vědí, co chcou. }

"Respektuji našince, kteří vědí, co chtějí."

cestina/dlg/chinatown/ji.dlg
{ 382 }{ No mně to může být jedno, když mi dva staří blázni chcou dát všechny svý peníze za mord. }

"Mně to může být jedno, když mi dva staří blázni chtějí dát všechny svý peníze za mord."

cestina/dlg/main characters/caine.dlg
{ 81 }{ Zdá se, že je tu mnoho těch, kteří chcou získat Kainovy děti na svou stranu... mnoho těch, co věří, že oni utvářejí osud své krve. Pracujete pro prince LaCroixe, že? }

"Zdá se, že je tu mnoho těch, kteří chtějí získat Kainovy děti na svou stranu..."

cestina/dlg/santa monica/bertram.dlg
{ 941 }{ Kamarilla [cam-uh-RILL-uh]funguje. Když necháš vampíry, ať si dělají, co chcou, skončíš u kaitifů[KAY-tiff], co propadají běsu přímo v ulicích, u mdlé krve, co porušuje Maškarádu, a u lovců, co budou čenichat kolem. Zákon a pořádek je našincův kamarád. }

"Když necháš vampíry, ať si dělají, co chtějí, skončíš u kaitifů..."

cestina/dlg/downtown la/prince2.dlg
{ 671 }{ Nebuď tak naivní. Kuei-Jinové jsou démoni - podvedli tě - potřebují, abys mi šel po krku. Chcou toto město od chvíle, kdy sem vstoupili, a pokud dosáhnout toho, že se začneme zabíjet mezi sebou, budou to mít mnohem snažší. }

"chtějí" - i do zenske repliky

cestina/dlg/downtown la/damsel.dlg
{ 111 }{ Zkusím tě uvést do obrazu. Kamarilla příjímá za své všechny našince, ať chcou nebo ne. Takže když uděláš něco, co nemají rádi, patříš holt do Kamarilly, a schytáš to podle jejich zákonů, ať se ti to líbí nebo ne. }

Damsel ma nevymachanou hubu, muzeme nechat :)

cestina/dlg/Hollywood/vv.dlg
{ 623 }{ Pokud je ta lovkyně problém, zabiju ji... }{ Pokud je ta lovkyně problém, zabiju ji... }{ 281 }{ G.Velvet_Hunter == 2 and G.Velvet_Quest < 1 }{ }{ }{ }{ }{ }{ }{ }{ Žízním po krvi těch, co chcou tu mou. }

"Žízním po krvi těch, co chtějí tu mou."


diky
