### ISSUE TITLE
úkoly pro Garyho, špatné pořadí odevzdávání předmětů/e-mailů?

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#256]
https://snag.gy/2fUJCK.jpg První přijde tento e-mail, kde chce CD z metalhead industries.
https://snag.gy/vTLz4r.jpg   V metalhead není CD ale tahací hračka která teď nejde odevzdat.
https://snag.gy/Kj6Sbn.jpg Dal jsem do schránky všechny související předměty a odevzdal jsem fotku nosferatu, ke které mi nepřišel žádný e-mail.
Hračka pořád nejde odevzdat.
https://snag.gy/LaUdz0.jpg a přijde tento e-mail a chce odevzdat kazetu z módní přehlídky.
https://snag.gy/LNr7Qj.jpg odevzdám kazetu z módní přehlídky.
https://snag.gy/DUfnNj.jpg teprve nakonec jde odevzdat hračka a přitom je to hned druhý úkol který gary zadá.
https://snag.gy/SD4YMd.jpg a teprve po odevzdání hračky zmizí související e-mail 14.

**Comment by miracleflame** [comment]
Kým som objavil, v čom je problém tejto fatálnej chyby.........
V konečnom dôsledku bol kvôli môjmu pochybeniu celý haven PC doteraz v režime Basic a to aj keď je nainštalovaná Plus čeština. To spôsobilo, že sa rozbil celý tento quest vrátane #261 a nie len to.

Spravil som diff basic a plus verzie PC a zmeny spočívajú v tomto:
1. načasovanie e-mailov Zahajeni a Prvni tah
2. nový e-mail od princa Recenze Tommyho Flaytona s poďakovaním za vyriešenie a vylepšenie vzťahov s princom o jeden bod
3. štart úplne nového questu Library
4. štart Bertramovho CD questu
5. výrazné rozšírenie plagátového questu od Garyho
6. reminder e-mail LEVNY ROLEX... od Larryho o tom, že má nový arzenál

Dosť slušný náklad výrazných zmien... Našťastie toto všetko by sa malo rozbehnúť samé od seba po nahradení opravenou verziou. Garyho quest však treba začať odznovu a ten začína mailom Princ te chce povysit!

**Comment by miracleflame** [comment]
@Honzixx @maarten93 konverzné dupmy zbehnuté... môžete testovať tikety, na ktorých ste naasajnovaní... hlavne tento s novými questami bude zaujímavý.
