### ISSUE TITLE
Radio chybí titulky.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#257]
https://snag.gy/SRPKg6.jpg
I když mám zapnuté radio a to vysílá nejsou tu žádné titulky.

**Comment by maarten93** [comment]
Video.
https://www.dropbox.com/s/tzluwhbuol8l0ml/vampire%202017-02-20%2016-46-40-75.avi?dl=0

**Comment by miracleflame** [comment]
Nezobrazuje sa to kvôli nepresnému číslovaniu počtu znakov vo fráze, ale zaoberať sa týmto bude mať zmysel, až keď budeme mať finálnu podobu textov... a na tom sa pracuje v tiketoch #77 až #81 
Tam sa postarám o to, aby zobrazovanie fungovalo. Díky za report.
