### ISSUE TITLE
Lu Fang

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#259]
Malý kousek je mimo rámeček

https://snag.gy/Nu4HPo.jpg

**Comment by miracleflame** [comment]
@soulcharmer nejaké úpravy, ktoré by vyústili do iného zalomenia?

{	141	}{	Things get, uhh, how you say, weird. Yeah. Lu Fang no think he trust Ji Wen Ja. Ji Wen Ja act funny - strange! Lu Fang think Ji Wen Ja want to kill him. Ji Wen Ja get shifty eye, you know? Lu Fang notice. Lu Fang read people very well. Ji Wen Ja, he up to no good.	}

{	141	}{	Pokazilo se to. Lu Fang nemyslí, že věří Ji Wen Ja. Ji Wen Ja podivnej. Lu Fang myslí Ji Wen Ja ho chce zabít. Ji Wen Ja má záludný pohled. Lu Fang všímá. Lu Fang číst v lidech moc dobře. Ji Wen Ja chce nějakou levárnu.	}

**Comment by soulcharmer** [comment]
tak treba :

{ 141 }{ Věci se, jak to říkáte... pokazily. Jo. Lu Fang nemůže Ji Wen Ja věřit. Ji Wen Ja chová divně! Lu Fang myslet Ji Wen Ja ho chce zabít. Ji Wen Ja má zrádný pohled. Lu Fang vidí. Lu Fang číst v lidech dobře. Ji Wen Ja chystá křivárnu. }

diky

**Comment by miracleflame** [comment]
@maarten93 na test po dumpoch.

**Comment by maarten93** [comment]
https://snag.gy/4TE1Hb.jpg už je to ok

https://snag.gy/9DkwjN.jpg   spěv>zpěv
