### ISSUE TITLE
zygaena

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#260]
https://snag.gy/o1SlwF.jpg
Podle mě se tam nehodí aby tady v tom rozhovoru měl u sebe napsané jméno, on o sobě tvrdí že není zygaena a nenašel jsem způsob z jak z něj dostat že je. Jediné co řekne je že s zygaena může domluvit schůzku.

**Comment by miracleflame** [comment]
Po prečítaní, v akom duchu sa nesie rozhovor, som zvážil, že na mieste bude označenie Díler.

Súhlas?

**Comment by maarten93** [comment]
j

**Comment by maarten93** [comment]
Ještě česky by to mělo být dealer nebo překupník

**Comment by maarten93** [comment]
http://slovnik.azet.sk/synonyma/?q=d%C3%ADler

**Comment by maarten93** [comment]
https://slovnik.seznam.cz/en-cz/?q=dealer

**Comment by miracleflame** [comment]
Jako ja súhlasím a nerobí mi problém dať to tak, ale myslím si, že by mal rozhodnúť @soulcharmer. Či netreba? Z môjho pohľadu by to bolo len pre dobro veci, keby niekto z vás dostal súhlas, že môže rozhodovať o finálnej podobe prekladov niektorých textov. Napríklad aj tikety #83 až #101 sú prevažne len brebty, kde treba hlavne skonktrolovať gramatiku a základnú štylizáciu, možno by @soulcharmer uvítal, keby sa tým nemusel zapodievať, čo ja viem. Možno aj váš pokus o preklad rádií #77 - #81 by mohol čo to urýchliť, inak neviem, či sa podarí naplniť sľub, že to bude tento rok.

**Comment by maarten93** [comment]
S překladem moc nepomůžu, angličtina není moje silná stránka a v české gramatice taky zrovna nevynikám, ale pokud se najde něco dalšího s čím mohu pomoci, rád přiložím ruku k dílu.

**Comment by soulcharmer** [comment]
"Překupník"

diky
