### ISSUE TITLE
Nosferatu haven  Nosferatu Warrens

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#268]
Nikde jsem v bludišti nenašel úkryt který jsem dostal od garyho po osvobození Barabuse.

https://www.gamefaqs.com/boards/914819-vampire-the-masquerade-bloodlines/42548952
http://vtmb.wikia.com/wiki/Haven

**Comment by miracleflame** [comment]
Teoreticky [tieto dvere](https://snag.gy/RfCbmB.jpg) pod mrakodrapom Venture.

**Comment by maarten93** [comment]
jo dík to je ono. já jsem z toho popisku pochopil ze je to v Nosferatu Warrens
A room underneath the Hollywood Forever Cemetery in the Nosferatu Warrens. (Nosferatu only)

**Comment by miracleflame** [comment]
Trochu to upravím v textoch, nech je to jasnejšie, lebo to je fakt na slepo.
