### ISSUE TITLE
Instalace 

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#271]
Teď jsem si znova stáhl češtinu a při instalaci to vyhodilo tohle: https://snag.gy/EWaFxM.jpg

**Comment by miracleflame** [comment]
Podľa vypísaného tipujem, že problém nastal kvôli tomu, že daný font, ktorý sa pokúša preinštalovať sa práve používa a nedá sa preto odstrániť. Možno je dôvod iný. Skús po reštarte PC. Ak nepomôže , tak znovu skompilovať novú inštalačku. Každopádne bežnému užívateľovi nebude potrebné aktuálne fonty odinštalovávať, lebo zatiaľ žiadne mať nebude.

**Comment by maarten93** [comment]
Dík to pomohlo.
