### ISSUE TITLE
Merkurio

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#272]
Po tom co mě informuje o novém zboží v tomto případě snajperku, tak se mě zeptá jestli mám zájem a když dám že jo tak se ukončí rozhovor a neotevře se nabídka, což si myslím že by měla.

**Comment by miracleflame** [comment]
Tipujem, že si dal "Nejsem snajperka, ale ukaž mi zbytek svého zboží."
Našiel som tam nejaké nezrovnalosti a opravil. Malo by to teraz fungovať ako treba.

**Comment by maarten93** [comment]
https://snag.gy/Te260P.jpg
Myslel jsem 1. To tedy mám
Merkurio se zeptá máš zájem, já dám to tedy mám a rozhovor se ukončí bez otevření nabídky obchodu, což si myslím že je trochu nesmyslné a měla by se zobrazit nabídka.

**Comment by miracleflame** [comment]
Aha... o bunku vedľa.. dík.

**Comment by maarten93** [comment]
@miracleflame A nešel by najít na netu nějaký program který by porovnal mezi sebou český a anglický překlad, hlavně ty spouštěče, protože předpokládám že tam bude takovíhle chyb více.

**Comment by miracleflame** [comment]
Určite, lenže povaha týchto porovnávaných riadkov je taká, že ako odlišnosť ukazuje takmer všetko, takže sa v tom aj tak nijako nevyznáš... preto som otvoril tiket #253 na skript, ktorý by porovnával iba tie bunky, ktoré nás zaujímajú.
