### ISSUE TITLE
e-mail knihovna

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#273]
https://snag.gy/SjDfBg.jpg

Verbuje Lasombra nasince pro sabaty. Pry ho videl zmizet  To zní jak kdyby lasombra byla osoba, co třeba člen klanu Lasombra?  

přihodilo něco naším vzácným moudrostem.    Dal bych tam vědomostem nebo knihám.  

tak se sním sejdi, prosím te, v   > tak se sním prosím te sejdi, v

**Comment by miracleflame** [comment]
@soulcharmer napr.?

"Zdravim te mlade, 
		muj pritel, Gangrel jmenem Scott, ma podezreni, ze tady v L.A. verbuje Lasombra nasince pro Sabbaty. Pry jednoho videl zmizet ve verejne knihovne LA! Ja mam ted jine povinnosti, tak se s nim, prosim te, sejdi v santamonickem obchode s kurivem a zjisti podrobnosti. Prece nechceme, aby se neco prihodilo nasim vzacnym vedomostem, ne? 
Beckett"

**Comment by soulcharmer** [comment]
tam byla chybka, beckett odkazuje na knihy v knihovne LA, kde chce toho z lasombry chytit:

"Zdravim te mlade, muj pritel, Gangrel jmenem Scott, ma podezreni, ze tady v L.A. verbuje nekdo z Lasombry nasince pro Sabbaty. Pry jednoho videl zmizet ve verejne knihovne LA! Ja mam ted jine povinnosti, tak se prosim sejdi se Scottem v santamonickem obchode s kurivem a zjisti podrobnosti. Prece nechceme, aby se neco prihodilo vsem tem sebranym vedomostem, ne?
Beckett"

diky
