### ISSUE TITLE
e-mail - LEVNY ROLEX

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#274]
https://snag.gy/xzFwgV.jpg

so mame > co mame 

Mame mnohem smrtelnejsi matros, vis jako? > Víš že máme mnohem zhavejsi a vice smrtici matros?

A stejne jako ostatni kvalitni LA vlastnici > A stejne jako ostatni  kvalitni vlastnici/prodejci v LA

**Comment by miracleflame** [comment]
"...ain't the only stuff that we got, man! We got much hotter, much deadlier stuff, you know? And like all other quality LA proprietors we get new stock in all the time, so check it out!!!"

"...to neni vsechno, so mame, clovece! Mame zhavejsi, mnohem smrtelnejsi matros, vis jako? A stejne jako ostatni kvalitni  LA vlastnici, mame na sklade porad novy veci, tak to omrkni!!!"

**Comment by soulcharmer** [comment]
"...a to neni vsechno, co mame, clovece! Mame zhavejsi a mnohem drsnejsi matros, vis jako? A stejne jako ostatnim kvalitnim investorum v LA nam chodi na sklad porad novy veci, tak to omrkni!!!"

diky
