### ISSUE TITLE
nines

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#276]
https://snag.gy/c93PJG.jpg
Tys byl na mojem procesu. Vy nejste součást Kamarilly?>Tys byl na mém procesu. Ty nepatříš ke Kamarille?

**Comment by miracleflame** [comment]
{	172	}{	That was rude, sorry. You were at the trial. Aren't you in the Camarilla?	}
{	172	}{	Promiň mi tu drzost. Tys byl na mojem procesu. Vy nejste součást Kamarilly?	}

**Comment by soulcharmer** [comment]
{ 172 }{ Omlouvám se za tu drzost. Byls na mém procesu. Nepatříš taky ke Kamarille? }

diky za report
