### ISSUE TITLE
MOSTRÓZNÍ PIVO

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#278]
https://snag.gy/IHJUxG.jpg
Nemělo by tam být MONSTRÓZNÍ PIVO?

**Comment by miracleflame** [comment]
Na ktorej mape to je?

**Comment by maarten93** [comment]
Santa Monica zavřená kavárna

**Comment by miracleflame** [comment]
Okej takže originál textúra vyzerá [takto ](https://snag.gy/yQuYil.jpg)

Pokúsim sa to opraviť, nemal by to byť problém.
@soulcharmer chcel by si napríklad iný text?
Original: GOLIATH BEER
Čeština: MOSTRÓZNÍ PIVO

**Comment by maarten93** [comment]
Co třeba Goliáš? to je český ekvivalent k Goliath. PIVO GOLIÁŠ?

**Comment by soulcharmer** [comment]
tohle je uroven detailu, ktere mi prijde skoro kontraproduktivni venovat jakykoliv cas :-)

Bud bych to nechal byt a nebo PIVO GOLIAS je taky dobre.

odchazim do jineho tiketu, diky :)

**Comment by miracleflame** [comment]
[Opravené](https://snag.gy/X2CMny.jpg)

**Comment by maarten93** [comment]
@miracleflame dobrá práce
