### ISSUE TITLE
Ash

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#284]
sešel --> zašel
https://snag.gy/GKe24k.jpg

**Comment by miracleflame** [comment]
Myslím, že tam nejde o vyjadrenie ďaleko zájsť.
@soulcharmer návrhy?

{	491	}{	[Doing a famous line from one of his movies]It was as far as I could fall; it was as low as I could go - way past oblivion to a point only described... as "negative zero".	}
{	491	}{	[Doing a famous line from one of his movies]Tak daleko jsem sešel, tak hluboko jsem klesl - cestou zapomnění až k místu zvanému negativní nula...	}

**Comment by soulcharmer** [comment]
tohle je dobre, nechtel jsem 2x opakovat hluboko pro padnout a klesnout... stejne to ma byt pateticky dramaticky a mirne smysluprazdny blabol :)
