### ISSUE TITLE
Ash 2

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#285]
"V Hollywoodu jsem byl jen 10 let, jsem zvědav, jak dlouho tam budu žít, když budu pryč."
odstranil bych v této větě slovo "tam", nemá tam logicky být. Ashe jsem dostal pryč z Hollywoodu aby neumřel v blízké době, protože na něj v klubu čekali lovci.
https://snag.gy/oRqytk.jpg

**Comment by miracleflame** [comment]
{	481	}{	I think that was the last one. Here, this is for your troubles. You know, I only lived in Hollywood for ten years; I wonder how long I'll live on in her after I go. Hmm....	}

@soulcharmer Tak to "her" by som tam fakt nečakal. Vnímajú Hollywood v ženskom rode?
Je to starting line po vyzabíjaní lovcov.

**Comment by soulcharmer** [comment]
jo, to vypada jako chyba v originale nebo se tim mysli LA, protoze z hollywoodu odchazi, ale pak to zase nenavazuje. Takze se to da zjednodusit na:

{	481	}{	Ten byl myslím poslední... Na, tady máš něco za námahu. Víš, v Hollywoodu jsem byl jen deset let. Jsem zvědav, jak dlouho přežiju, až odejdu. Hm...	}


diky za report
