### ISSUE TITLE
Romero - zombie

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#287]
Zde to není tak rušivý jako u #212 ,ale zeptám se.
Nechcete změnit všechny tyto skloňované zombie tvary i u Romera na neskloňované "zombie"?
https://snag.gy/mqy2UB.jpg ale myslím, že toho bylo u Romera víc

**Comment by miracleflame** [comment]
{	61	}{	A dokud to nezjistí, potřebovali dobrovolníka, aby to zafixoval. Tak jsem se přihlásil. Problém je dočasně vyřešen, baron je spokojenej, já si zastřílím po zombiích a ještě za to dostanu krev na další měsíc. Urval jsem si tu moc pěkný místečko.	
{	101	}{	Hej, nechtělo by se ti to tu náhodou na chvilku pohlídat, než si něco zařídím? Neměl bych odsud odcházet, jinak by to mohlo skončit nějakým zombiím holokaustem. Jako jednou, když sem nalezli ti gotici, to nebylo hezký.	
{	Jak zastavím hordy zombií?	}
{	Pusť mě na hordy zombií.	}
{	342	}{	Jak se provede epická bitva se zombiemi?	}
{	Já si chci hrát se zombiemi. Ty si běž hrát své tělesné hry.	}
{	Jsem tu zmasit hordy zombií!	}
{	671	}{	Někdy chlap potřebuje upustit páru a někdy mu v tom vystřelení zombiího mozku z hlavy nepomůže. No tak, jseš taky chlap, chápeš, ne?	}

@soulcharmer tu sú všetky výskyty skloňovaních zombie tvarov... inak sa v hre celkove vo veľkom vyskytuje základný tvar zombie, ale podľa mňa nezaškodia v týchto vypísaných prípadoch ani tvary ako zombíky, zombíci atď.

**Comment by Honzixx** [comment]
Podle mě jsou taky tvary zombíky, zombíci apod. dobré, klidně bych je použil.

**Comment by soulcharmer** [comment]
okej, tu jsou upravy:

{ 61 }{ A dokud to nezjistí, potřebovali dobrovolníka, aby to zajistil. Tak jsem se přihlásil. Problém je dočasně vyřešen, baron je spokojenej, já si zastřílím po zombících a ještě za to dostanu krev na další měsíc. Urval jsem si tu moc pěkný místečko.
{ 101 }{ Hej, nechtělo by se ti to tu náhodou na chvilku pohlídat, než si něco zařídím? Neměl bych odsud odcházet, jinak by to mohlo skončit nějakým zombie holokaustem. Jako jednou, když sem nalezli ti gotici, to nebylo hezký.
{ Jak zastavím hordy zombie? }
{ Pusť mě na hordy zombie. }
{ 342 }{ Jak se provede epická bitva se zombiemi? }   <- Malkavian, to muzeme nechat :)
{ Já si chci hrát se zombiemi. Ty si běž hrát své tělesné hry. }  <- dtto
{ Chci tu zmasit hordy zombií! }   <- dtto
{ 671 }{ Někdy chlap potřebuje upustit páru a někdy mu v tom vystřelení zombie mozku z hlavy nepomůže. No tak, jseš taky chlap, chápeš, ne? }

diky

**Comment by miracleflame** [comment]
Ponechal som pôvodne aj tieto Malkavian hlášky
{ Jak zastavím hordy zombií? }
{ Pusť mě na hordy zombií. }
