### ISSUE TITLE
VV - změnit dotaz

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#290]
https://snag.gy/J0uHNX.jpg 1. volbu bych předělal na "Promluvme/povězme o té lovkyni.",
protože nejdřív mi sice dá info, kde se dotyčná nachází, ale po jejím zabití už VV na toto reaguje pouze "Uh-hmm?" a poté ji hned sděluji, že je lovkyně mrtvá, takže VV nic nepoví.

**Comment by miracleflame** [comment]
Rozumiem, v origináli je tam About the hunting one... a VV potom nehovorí nič, skôr hráč sa vyjadruje o lovkyni.
