### ISSUE TITLE
Tommy - přesvědčování

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#291]
Za Malka ho nemohu přesvědčit ani na úrovni 10 přesvědčování, aby napsal špatnou recenzi na restauraci. 
Zde postup u Malka:
přesvědčování úroveň 6-10 https://snag.gy/tre4Vo.jpg
následuje toto https://snag.gy/mRQz3g.jpg
obě možnosti končí tímto, nenechá se přesvědčit https://snag.gy/BdbUoC.jpg

Zde postup u Toreadora, kde přesvědčování zabere už na úrovni 4:
dám přesvědčování https://snag.gy/IbFcoM.jpg
a vyskočí tyto možnosti https://snag.gy/C8yvco.jpg
minimálně 2. a 3. ho přesvědčí a je hotovo.

Jen info za Malka ho mohu dementovat (funkční) a dosáhnout tak cíle.
Nevím, jestli je to bug, nebo jestli je to záměr, že Malk ho nepřesvědčí.

**Comment by miracleflame** [comment]
Je to tak aj v UP. Spýtam sa Wespa.

**Comment by miracleflame** [comment]
Wesp: Hm, I would guess this is intended as both lines there have no Malkavian dialogue. Maybe Troika wanted to really play the maggot thing out ;).
