### ISSUE TITLE
Gary

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#293]
https://snag.gy/5Reorh.jpg

Noční tma>Noc

**Comment by miracleflame** [comment]
{	171	}{	[Cackles]Liar, liar, pants on fire. You can't kill what you can't see. Try to kill me? The night's got a thousand eyes, boss, and all of them are mine. You wouldn't like it... being watched every second of the rest of your short life.	}

**Comment by maarten93** [comment]
@miracleflame Jen dotaz neměl by Gary mluvit ve verších?

**Comment by miracleflame** [comment]
Až na zaužívanú riekanku "Liar, liar, pants on fire.", ktorá bola preložená takisto českým idiomom, som inde nič také nepostrehol. Či máš niečo konkrétne na mysli?

**Comment by maarten93** [comment]
Jen mě to tak na padlo když za ním poprvé přijdeš tak taky říká, nějakou říkanku,  
Začal jsem to cítit v kříži, něco nekalého se k nám blíží. A pak podle toho když říká, Liar, liar, pants on fire. You can't kill what you can't see. Try to kill me?

**Comment by miracleflame** [comment]
Občas niečo také dá, ale mám dojem, že @soulcharmer bral na to ohľad pri prekladaní.
