### ISSUE TITLE
Dveře zrcadlově otočený nápis

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#298]
Z přední strany dveří je tento nápis pouze nouzový východ https://snag.gy/DJuKAE.jpg
Z druhé strany je taky, ale zrcadlově otočený https://snag.gy/b7ulZm.jpg

**Comment by miracleflame** [comment]
K textúram mi, prosím ťa, píš aj presnú lokáciu, pokiaľ by si náhodou nevedel rovno presné meno súboru. Dík.

**Comment by maarten93** [comment]
V tomto případě je to v divadle nocturne v centru L.A. ale myslím že tyto dveře jsou celkem častý

**Comment by miracleflame** [comment]
Nahlásil som to Wespovi... Je to chyba enginu, dvere si ťahajú tú istú textúru. Moje navrhované riešenie je celú ceduľku odstrániť, lebo je aj tak nečitateľne hnusne low-res.

**Comment by miracleflame** [comment]
Wesp: Hm, I'll see if I can put another EXIT decal on top of this...
