### ISSUE TITLE
Zrevidovat dlg z unp95

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#3]
zoznam suborov:
        new file:   cestina/dlg/generic/doll5.dlg
        new file:   cestina/dlg/giovanni/bodyguard5.dlg
        new file:   cestina/dlg/main characters/heather_dead.dlg
        new file:   cestina/dlg/santa monica/smoke.dlg
        new file:   cestina/dlg/santa monica/thug.dlg

doll5.dlg

Finally a masculine fighter just after my taste!
Konečně svalnatý bojovník přesne dle mé chuti!

I see your scary scar and I really like it.
Koukám na tvou šílenou jízvu a vážně se mi líbí.

Hello brother, want to get some man on man action?
Ahoj bratře, nemáš chuť na trochu akce muže s mužem?

Nechce si to bratr rozdat s tím, co stojí před ním?

Hi Tong, are you lonely tonight?
Zdar Tongu, jsi dnes osaměly?

Will the lonely Tong join our multitude?
Přidá se osamělý Tong k naší rozpolcenosti?

Sorry, mistook you for someone else.
Promiň, s někým jsem si tě spletl.

My voices told me they know you, but they don't.
Hlasy v mé hlavě mi řekli, že tě znaj, jenže neznaj.

I love the strong silent types. Come here!
Miluji silné a tiché typy. Pojď sem!

Silent but lovely. Let us rub our bodies together in a special way!
Tichý, za to rozkošný. Pojďme třít naše těla o sebe zvlášním spůsobem!

The hell I care.
Mám na háku.

I'm crazy, you don't want to know what I'll do to you!
Jsem šílený, nechci vědet, co ti udělám!

Oh, it can't be worse than what already happened to me!
Nemůže to být horší než to, co se mi už stalo!

I am back.
Jsem zpět.

Here we are again.
Už jsme tady zas.

heather_dead.dlg

Oh Heather. I will never forget you!
Ach, Heather. Nikdy na tebe nezapomenu!

Oh little morsel. You have forever a place in my broken brain!
Ach , malý zajíčku. Navždy máš své místo v mém rozbitém mozku!

Nobody kills my ghoul and lives!
Nikdo nevyvázne živ, pokud zabije mojí ghůlku.

Killing my pet is asking for trouble!
Kdo zabije mé zvířátko si koleduje o malér!

Great. Now I'll have to find me another slave.
Bezva. Teď si musím najít jinou otrokyni.

No no no, now I need to find me another pet!
Ne ne ne, teď si musím najít jiné zvířátko!

smoke.dlg

Good evening to you.
Přejí vám dobrý večer.

Hello, I'm looking for Scott. He might have left me a note or something.
Zdravím, hledám Scotta. Možná mi nechal vzkaz nebo něco.

Hi Thomas, I am looking for the Scott wolf.
Ahoj Thomasi, hledám vlka Scotta.

Just looking around.
Jenom se rozhlížím.

I-I'm sorry, I can't help you.
Je-je mi líto, nepomůžu vám.

Thanks. I'll just look around for a clue then...
Děkuju. Podívám se tedy po stopách...

Thanks for nothing. I'm sure the wolf wrote me a letter!
Děkuju za nic. Určite nám tady vlk nechal dopis!

No problem, I already found what I wanted!
Žádný problém, už jsem našel, co jsem hledal!
Žádný problém, už jsem našla, co jsem hledala!

I was right as I always am, at least sometimes.
Měli jsme pravdu jako vždy, alespoň občas.

I beg your pardon?
Račte prominout?

Sometimes he is a man, sometimes he is a wolf.
Někdy je to chlap, jindy zase vlk.

No, I-I really don't understand you.
Ne. J-já vám vážne nerozumím.

Oh dear! Are - are you not well?
Božíčku! Jste - jste nemocný?
Božíčku! Jste - jste nemocná?

It's only a weird hobby of mine. I'm looking for Scott.
Jenom mám takové divné hobby. Hledám Scotta.

It's nothing, excuse me.
To nic, omluvte mě.

thug.dlg

Hey where you goin' man?
Hej, kam si myslíš, že jdeš, chlape?
Hej, kam si myslíš, že jdeš, slečinko?

This is none of your business, trust me.
Do toho tě nic není, věř mi.

Your brain does not need to know.
Tvůj mozek to nepotřebuje vědět.

Do you want to stop me or what?
Hodláš me zastavit nebo co?

Don't stop me now, I'm having a good time!
Těd mě nezastavuj, dobře se bavím!

Don't you dare threaten me, mortal!
Neopovažuj se mi vyhrožovat, smrtelníku!

I don't know myself and neither will you.
Já se neznám a ty taky ne.

You will not bother me.
Nebudeš mě obtěžovat.

I'll just move along, okay?
Jenom procházím kolem, dobrá?

My brain will move its body.
Můj mozek odsune mé tělo.

I'll let you go this time man.
Pro tentokrát tě nechám projít, chlape.
Pro tentokrát tě nechám projít, slečno.

Yeah, good for you.
Jo, dobře děláš.

I will leave and leave you behind.
Půjdu a nechám tě za sebou.

I don't wanna talk to you. Move!
Nechci s tebou mluvit. Padej!

Don't hurt me man!
Neubližuj mi!

I can't because I'm gone.
Nemůžu, protože jsem pryč.

I won't.
Neublížím.

**Comment by soulcharmer** [comment]
hotovo
