### ISSUE TITLE
Quest - Odchrličovací služba

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#300]
U tohoto questu nesedí zápis do žurnálu. Regentovi jsem slíbil, že neprozradím to, že on je tvůrcem golema. Po zabití golema tuto skutečnost Izákovi neřeknu, ani nemám v dialogu možnost to říct (podle mě chyba č.1 - u Toreadora jsem možnost nahlásit regenta měl). 
Ovšem zápis v žurnálu tvrdí, že jsem regenta naprášil a že není potřeba za regentem chodit. (chyba č.2)
Když však za regentem příjdu a řeknu, že je golem mrtví, poděkuje mi za to, že to bylo diskrétně.
Zde screeny jak to jde vše popořadě:
žurnál po zabití golema - https://snag.gy/NBtcE7.jpg
oznámím to Izákovy (volba 3) - https://snag.gy/BCTm2I.jpg
zvolím 1 - https://snag.gy/5O2RvC.jpg pokračuje zde - https://snag.gy/0FGWA7.jpg
pokus nahlásit regenta - https://snag.gy/pR7YeD.jpg a skončí zde - https://snag.gy/2im3Nz.jpg konec.

nebo zvolím 2 - https://snag.gy/MH8B9V.jpg a dialog se myslím ukončí.

ve všech případech se udělá tento zápis do žurnálu - https://snag.gy/rXqO2s.jpg
ale mohu jít za regentem a ten mi poděkuje, že jsem mlčel:
zde volba 2 - https://snag.gy/9mlauf.jpg
jeho reakce - https://snag.gy/QYg3lO.jpg
pokračuje - https://snag.gy/Pgh5qd.jpg
nový zápis v žurnálu - https://snag.gy/p3ugrX.jpg

**Comment by miracleflame** [comment]
Žalovanie na regenta som riešil v tikete #114 
Zdá sa, že problém je komplexnejší...
poprosím vás @Honzixx aj @maarten93 ak sa ukáže, že niečo nepracuje ako by zrejme malo, vždy to otestujte aj s EN súbormi. Ja mám pôvodný EN folder Unofficial_Patch premenovaný na xUnofficial_Patch a keď to potrebujem prehodiť tak len český premenujem na xxUnofficial_Patch a z EN xUnofficial_Patch odstránim to x-ko. Vybavené... keď to chcem vrátiť, zas tam doplním to x-ko a z xxUnofficial_Patch odstránim dve x-ká. Preverenie, či ide o chybu UP alebo češtiny mi to uľahčí hodne, keď viem že nemusím porovnávať CZ a EN, ak je chyba aj v EN.

**Comment by Honzixx** [comment]
Omlouvám se, mám taky více Unofficial_Patch složek pro testy, ale dnes mě to nějak nenapadlo. Ještě to sjedu v EN.

**Comment by Honzixx** [comment]
Tak v originál GoG verzi to funguje jak má. Správný zápis v žurnálu, když Izákovi neřeknu o regentovi, a regent se dá i nahlásit. Není tam jen Malkavianské "Neřeknu, neřeknu" :-)
povím Izákovi o mrtvém golemovi, tady dám kteroukoliv volbu https://snag.gy/k1txOZ.jpg
následuje tento zápis v žurnálu https://snag.gy/pkWqme.jpg
nebo nahlásím regenta https://snag.gy/ehvA4R.jpg následuje https://snag.gy/ZuIxXo.jpg
Izákova reakce https://snag.gy/kyDEMe.jpg
a nový zápis v žurnálu https://snag.gy/fWjIVg.jpg

**Comment by miracleflame** [comment]
Toto mi absolútne nedáva žiadny logický zmysel, na základne našich súborov to nie je možné dosiahnuť. Ale ani diff nemenil nič na riadkoch, ktorých sa to týka. Použil si presne ten istý save pri testovaní EN verzie, na ktorej to funguje, ale z toho istého savu to nejde s češtinou?

**Comment by Honzixx** [comment]
Ano stejný save na obojí testování

**Comment by miracleflame** [comment]
Prosím, skús otestovať teraz po veľkých diffoch.

**Comment by Honzixx** [comment]
Teď po diffech už to jde všechno dobře, zápisy v žurnálu jsou správně a regent jde nabonzovat :-)

**Comment by miracleflame** [comment]
Díky bohu. :D
