### ISSUE TITLE
člen klanu Lasombra

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#302]
https://snag.gy/TxzHjZ.jpg
Bez animace a zvuku

**Comment by miracleflame** [comment]
Mie som si istý, či to zaberie, preto treba otestovať. Stačí si tam hodiť novopridaný súbor

**Comment by maarten93** [comment]
Teď už to jde, ale přijde mi zvláštní že se použil zvukový soubor pro Andreje.

**Comment by maarten93** [comment]
Nevím jestli to nějak souvisí ale teď jsem, prošel knihovnu potřetí a poprvé se mi stalo že při odchodu byla ve výtahu, ta potvora z tč snuff kazety, ten obličej z rukama.

**Comment by miracleflame** [comment]
Aj samotný dialóg sa ťaha zo súboru Andrei, zvuk ide zo sound\character\boss\andrei\ čo je dosť neštandardné pre dialógy. Ten zvuk mi príde ako nejaké prvé generálky dabérov, ktoré sa odvtedy storazy prerobili. Wespov restoration zázrak.

**Comment by maarten93** [comment]
@miracleflame jo a ten zvuk ztlumený tak to asi bude tím
