### ISSUE TITLE
The lasombra

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#303]
https://snag.gy/Cso1g4.jpg
Nepřeložené jméno při souboji, ale Lasombra bych tam nenechával, jednak je to název klanu a za druhé se tak jmenuje zakladatel Antediluvian Lasombra, což předpokládám že tahle postava není http://whitewolf.wikia.com/wiki/Lasombra_(Antediluvian)

**Comment by miracleflame** [comment]
Dám tam Náborář Lasombry. Keby niekto niečo, tiket znovu otvorte.

**Comment by maarten93** [comment]
@miracleflame přemýšlel jsem nad tímhle: http://whitewolf.wikia.com/wiki/Ductus 

ale ten náborář je asi lepší.

**Comment by miracleflame** [comment]
Ductus asi nikomu nič nepovie, len zarytým zasvätencom a k tomu by po správnosti mal byť vysvetľujúci záznam v loading tips ako to je u iných pojmov. Neviem, či je vôbec zrejmé, že má túto "hodnosť či status".
