### ISSUE TITLE
PC kanalizace

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#304]
V kanalizaci při pátrání po klanu Nosferatu je špatně první příkaz "pumpa l18a" nebo co to je :-D
nemohu to ani zadat https://snag.gy/thIXsZ.jpg

**Comment by maarten93** [comment]
@Honzixx to by mělo být pumpa 118a   
a mělo by to jít mě to šlo.

**Comment by maarten93** [comment]
I když je pravda že teď naposledy jsem šel jinudy

**Comment by miracleflame** [comment]
Na monitore je prasklina, ktorá deformuje, ako to vyzerá, ale je to 118a.
