### ISSUE TITLE
The Tzimisce

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#305]
nepřeložené jméno bose. Nejsem si jistý, ale neopravovali jsme to už?
https://snag.gy/Vmj8Yz.jpg

**Comment by maarten93** [comment]
@Honzixx j to už se opravovalo a myslím že když jsem to hrál tak už to jméno bylo opravený.

**Comment by miracleflame** [comment]
Na repe už sa The Tzimisce nenachádza. bolo to opravené v tikete #233
