### ISSUE TITLE
L.A. SUN - vystřižené

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#306]
je to chyba, nebo je ta pravá spodní  část novin vystřižená normálně? je to v kanalizaci kousek po souboji s Tzimiscem https://snag.gy/Du0Jjx.jpg
a ještě jedny https://snag.gy/rXHyBW.jpg

**Comment by miracleflame** [comment]
Background image to berie z hud/signs/newspaper_clipped1 
Názov nasvedčuje, že to je asi zámer, aj keď to vyzerá pekne na prd. UP to tak má tiež.
