### ISSUE TITLE
Poslední uzel

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#307]
Je v Basic taky rozšířený úkol s plakátem pro gariho? pokud ne tak by v trezoru v kamikazi zen měly být peníze.

Ale v up plus, je tam schválně jmenovka, kterou po mě gary chce po tom co dodělám ty první čtyři základní úkoly, ale v e-mailu se píše že musíš ukrást z trezoru peníze, který tam nejsou. Takže by to chtělo ten email přepsat.

třeba: Musíš se do něj dostat a vykrást ho 

https://snag.gy/ET4iIM.jpg

**Comment by miracleflame** [comment]
Plagátový quest je aj v basic ale pozostáva z menšieho počtu úloh a plagátov. Menovka však nie je súčasťou.

Original verzia e-mailu je takto a aj pre basic: You better break into it and take something. Put 'em off the scent.

Opravím to vo všetkých na něco ukrást
