### ISSUE TITLE
Engine eror

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#311]
https://snag.gy/h5ljGo.jpg
dnes se mi stalo už podruhé pokaždé při načítání uložené pozice pokaždé jiná lokace.

**Comment by miracleflame** [comment]
Opakované načítanie opakuje tú istú chybu?

**Comment by maarten93** [comment]
ne to ne spadne celá hra a když to zkusím znovu tak už to jde, jen tohle předtím nedělalo až dneska.

**Comment by miracleflame** [comment]
Táto hra je plná záhad, to už aj Wesp povedal... Lepší liek než reštart PC preinštalovanie hry a češtiny neexistuje. Na toto by ani Wesp nepovedal nič iné.
