### ISSUE TITLE
Meč s širokou čepelí vs Meč Tal',mahe'Ra ?

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#312]
https://snag.gy/R6hJiN.jpg - Meč s širokou čepelí

https://snag.gy/EGuXti.jpg - Meč Tal',mahe'Ra

Nevím jak fungují všechny mechaniky ve hře, ale podle mě má Meč s širokou čepelí lepší statistiky než Meč Tal',mahe'Ra , ale přesto zraňuje méně.
Jediné co má  Tal',mahe'Ra lepší je Základní zranění Base Damage: The absolute minimum of damage this weapon will do (unless it's soaked).

https://www.gamefaqs.com/pc/914819-vampire-the-masquerade-bloodlines/faqs/35207

https://www.dropbox.com/s/754nombmyygrwbo/vampire%202017-02-24%2021-01-04-15.avi?dl=0

**Comment by miracleflame** [comment]
Na ľudí by bol Meč s širokou čepelí silnejší, ale proti supernaturals má len polovičný účinok. naproti tomu Meč Tal',mahe'Ra spôsobuje spalujúce zranenie, čo je na konci popisu, takže ho supernaturals nevyblokujú.
