### ISSUE TITLE
Lidskost?

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#313]
Nejspíš je to na wespa.
Nevím jestli je to tak schválně, ale v klubu Glazura během přestřelky zabili civilistu aniž bych ho škrábnul , ale lidskost to sebralo mě.

**Comment by miracleflame** [comment]
Odreportoval som a keď bude odpoveď, napíšem sem.

**Comment by miracleflame** [comment]
Wesp: I'm aware of this but I assume this is intentional. After all you starting a fight got these civilians killed!
