### ISSUE TITLE
????

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#314]
Předtím jsem si toho nevšiml, tak si myslím že je to nový, někdy se místo jména zobrazí ????

https://snag.gy/mVdASQ.jpg
Ještě jsem si to všiml v restauraci rudý drak, ale tam sem to nestihl vyfotit.
myslím že se to zobrazuje u postav typu muž, žena a gangster...

**Comment by miracleflame** [comment]
Nemyslím si... vždy a aj v tomto prípade je to fixne nastavený speaker_name... V restauraci Rudy drak to mohlo byť lebo som objavil alernatívne Hosteskyne lipy, kde je speaker_name ???
V beachhouse na útese v SM to má jeden gangster.
Toto tu odfotené berie texty z foldra male\unique\tongie\ tak neviem, ako ich mám pomenovať... Tong gangster?

**Comment by Honzixx** [comment]
Mám pocit, že zrovna tady podle screenu jsem měl za Toreadora samé jména "Muž" a žádné "???".
Všichni jsou to ti samí gangsteři, tak bych tam dal buďto všude "Muž" nebo "Gangster".

**Comment by maarten93** [comment]
co tohle? Tongy - čínské zločinecké skupiny

**Comment by miracleflame** [comment]
takže nahradím
speaker_name ???
za
speaker_name Tongy
tak?

**Comment by maarten93** [comment]
A nebo možná jen tong? 
Jak jsou pojmenovaní v Glazuře?

**Comment by maarten93** [comment]
voják tongů?
Podle:  The hatchet men, also known to outsiders of the Chinatown as highbinders, were the salaried soldiers of the tongs. These soldiers most likely were from the Chinese lower classes, as many were uneducated and less “motivated” to become a law-abiding citizen of any country. Allegedly, 20% of each of the tong's membership population was said to be the professional soldiers

**Comment by miracleflame** [comment]
Určite Tong, našiel som aj iné lipy z garáž, kde je speaker name Tong.
