### ISSUE TITLE
Krvácející vysací zámek

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#322]
https://snag.gy/UB6Z4Y.jpg
Vím že je to blbost

**Comment by miracleflame** [comment]
Nahlásim to Wespovi, len kde presne to je?

**Comment by maarten93** [comment]
Ten salón kam unesli kiki modrý květ myslím?

**Comment by miracleflame** [comment]
Wesp to nevie zreprodukovať... Pošleš mi svoj posledný quick save na tom mieste, prosím?

**Comment by maarten93** [comment]
Pošlu až zítra večer dnes už se k PC nedostanu

**Comment by maarten93** [comment]
Tak nevím našel jsem nejbližší save, došel jsem k tomu zámku a už to nedělá.
