### ISSUE TITLE
Sídlo giovani venku.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#326]
Za nosferatu, se musím problížit nebo to vymlátit, zvolil jsem plížení, většina postav venku nic neříká když jdu okolo,  ale jedna postava a myslím že to byla tady ta:https://snag.gy/HYILQa.jpg něco krátkého řekne, ale nezobrazí se titulky.

**Comment by miracleflame** [comment]
To by si musel bližšie špecifikovať, ale myslím si, že s najvyššou pravdepodobnosťou išlo o
sound\character\female\blue_blood\giovanni guest 2\float_1-7 ktoré sú v taliančine.

Tu je na mieste otázka, či chceme taliančinu prekladať a ak áno, kto to z odposluchu preloží alebo aspoň prepíše. UP má vo verzii 9.7 titulky ktoré zobrania Female: (Italian language). Neviem, či má zmysel niečo také otitulkovať... podľa mňa nie.

Vaše názory? @maarten93 @soulcharmer @Honzixx

**Comment by Honzixx** [comment]
Pokud bude v UP jen to "(italian language)" tak bych tomu pak dal jen českou podobu "italština" nebo "mluví v italštině". Jinak bych to taky nepřekládal, zase se tam hráč tak dlouho nezdržuje. 
Ale kdyby se ty lipy zobrazovali jako věty nebo slova v italštině, mohli bysme za tu italštinu dát překlad v hranatých závorkách. :-)

**Comment by soulcharmer** [comment]
jestli se nepletu, tak ta italstina neni pro quest nebo hru obecne nikterak podstatna, takze se tim netreba zabyvat.

**Comment by miracleflame** [comment]
Ovšem UP tam stále nanúti caption Female: (Italian language) takže treba rozhodnúť, ako s tým naložiť... Ja sa prikláňam k tomu, aby sa caption zrušil a nezobrazoval, podobne ako u citosloviec.

**Comment by soulcharmer** [comment]
@miracleflame jo, souhlas

**Comment by Honzixx** [comment]
Souhlasím taky.

**Comment by miracleflame** [comment]
Beriem na vedomie a tak isto naložím s čínštinou.
