### ISSUE TITLE
Televize hlasatel

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#328]
https://snag.gy/NzB9Wp.jpg
Dajně>Údajně

**Comment by miracleflame** [comment]
upravil som
"Davy vesničanů v indickém Novém Dillí ukamenovali k smrti policistu, kterého si zaměnili s 'jelením mužem', který je podle nich už týdny terorizoval a údajně byl zodpovědný za záhadnou smrt několika dětí. Tento jelení muž má být více než dva metry vysoký tvor s rohy, který na vesničany útočí v noci. V Novém Dillí prý také přebýval opičí muž, medvědí muž a mimozemšťané, ale všechny tyto zprávy se ukázaly být jen hromadnou hysterií."

na
"Davy vesničanů v indickém Novém Dillí ukamenovali k smrti policistu, kterého si zaměnili s 'jelením mužem', jež je podle nich už několik týdnů terorizoval a údajně byl zodpovědný za záhadnou smrt několika dětí. Tento jelení muž má být více než dva metry vysoký tvor s rohy, který na vesničany útočí v noci. V Novém Dillí prý také přebýval opičí muž, medvědí muž a mimozemšťané, ale všechny tyto zprávy se ukázaly být jen hromadnou hysterií."

@maarten93 poprosím test

**Comment by maarten93** [comment]
https://snag.gy/yZfMU4.jpg na 1600x900 to nepomohlo

**Comment by miracleflame** [comment]
@maarten93 po dumpe snáď už...

**Comment by maarten93** [comment]
https://snag.gy/aN3KZX.jpg už ok, normálně hraji na 1920x1080 kde je to ok,  ale když jsem to testoval na 1600x900 všiml jsem si #344
