### ISSUE TITLE
Main characters dlg diff revize

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#330]
@soulcharmer  nové preklady objavené pri diffovaní. Omrkni to, prosím.

bach.dlg
132	}{	Yeah, whatever.	}{	Yeah, whatever.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Much talk, little sense.
132	}{	Jo, jak je libo.	}{	Jo, jak je libo.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Spousta řečí, žádný smysl.

{	101	}{	Tak to je nepochybně z klanu Malkavian. Nebo bych měl říci, že jsou obě nepochybně z klanu Malkavian.	}{	Tak to je nepochybně z klanu Malkavian. Nebo bych měl říci, že jsou obě nepochybně z klanu Malkavian.	}{	#	}{	npc.SetDisposition("Joy", 3)	}{	G.Beckett_Baron = 1	}{	}{	}{	}{	}{	}{	}{	**Something to look forward to, eh?**	}
{	101	}{	Tak to je nepochybně z klanu Malkavian. Nebo bych měl říci, že jsou obě nepochybně z klanu Malkavian.	}{	Tak to je nepochybně z klanu Malkavian. Nebo bych měl říci, že jsou obě nepochybně z klanu Malkavian.	}{	#	}{	npc.SetDisposition("Joy", 3)	}{	G.Beckett_Baron = 1	}{	}{	}{	}{	}{	}{	}{	**Mám se na co těšit, co?**	}

gary
{	144	}{	Přišel jsem tě zabít.	}{	Přišla jsem tě zabít.	}{	171	}{	}{	}{	}{	}{	}{	}{	}{	}{	**I'm here for your eyes, and your ears, and your face, and your blood.**	}
{	144	}{	Přišel jsem tě zabít.	}{	Přišla jsem tě zabít.	}{	171	}{	}{	}{	}{	}{	}{	}{	}{	}{	**Jsem tu pro tvé oči, tvé uši, tvoji tvář a tvou krev.**	}

{	143	}{	Jsem tu kvůli Ankarskému sarkofágu.	}{	Jsem tu kvůli Ankarskému sarkofágu.	}{	181	}{	}{	}{	}{	}{	}{	}{	}{	}{	**I'm here for the old box.**	}
{	143	}{	Jsem tu kvůli Ankarskému sarkofágu.	}{	Jsem tu kvůli Ankarskému sarkofágu.	}{	181	}{	}{	}{	}{	}{	}{	}{	}{	}{	**Jsem tu kvůli staré krabici.**	}

{	302	}{	Kdo jsi?	}{	Kdo jsi?	}{	341	}{	not IsClan(pc,"Toreador")	}{	}{	}{	}{	}{	}{	}{	}{	**What is your name, face?**	}
{	302	}{	Kdo jsi?	}{	Kdo jsi?	}{	341	}{	not IsClan(pc,"Toreador")	}{	}{	}{	}{	}{	}{	}{	}{	**Řekni své jméno, ksichte.**	}

{	314	}{	Kde je ten sarkofág?	}{	Kde je ten sarkofág?	}{	351	}{	}{	}{	}{	}{	}{	}{	}{	}{	**Where is the box?**	}
{	314	}{	Kde je ten sarkofág?	}{	Kde je ten sarkofág?	}{	351	}{	}{	}{	}{	}{	}{	}{	}{	}{	**Kde je krabica?**	}

heather
{	841	}{	[Sad]... I přesto jsem navěky tvá...	}
{	843	}{	Ále, jsi smrtelná. Moje budeš, jen dokud neeksneš, a pak si budu muset najít jinýho ghúla.	}{	Ále, jsi smrtelná. Moje budeš, jen dokud neeksneš, a pak si budu muset najít jinýho ghúla.	}{	851	}{	G.Heather_Indoors == 0	}{	}{	}{	}{	}{	}{	}{	}{	**No, you will wither and die.**	}
{	843	}{	Ále, jsi smrtelná. Moje budeš, jen dokud neeksneš, a pak si budu muset najít jinýho ghúla.	}{	Ále, jsi smrtelná. Moje budeš, jen dokud neeksneš, a pak si budu muset najít jinýho ghúla.	}{	851	}{	G.Heather_Indoors == 0	}{	}{	}{	}{	}{	}{	}{	}{	**Ne, časem schradneš a zemřeš.**	}

jack
{	1031	}{	Je to čím dál zajímavější, co? Giovanniové, Kuei-jinové... A spousta krve na oltář deset tisíc let starýho muzejního kousku, nemyslíš?	}
{	1033	}{	Ani mi nemluv. Teď už by tam mělo být něco fakt zajímavýho.	}{	Ani mi nemluv. Teď už by tam mělo být něco fakt zajímavýho.	}{	1071	}{	not IsClan(pc,"Malkavian")	}{	G.Jack_Faction = G.Jack_Faction + 1	}{	}{	}{	}{	}{	}{	}{	**Its secret best be serious for the trouble it heaps upon me.**	}
{	1033	}{	Ani mi nemluv. Teď už by tam mělo být něco fakt zajímavýho.	}{	Ani mi nemluv. Teď už by tam mělo být něco fakt zajímavýho.	}{	1071	}{	not IsClan(pc,"Malkavian")	}{	G.Jack_Faction = G.Jack_Faction + 1	}{	}{	}{	}{	}{	}{	}{	**Jeho tajemství ať raději stojí za ta muka na mně uvalená.**	}

mingxiao
{	706	}{	Hmmm. Yes, I know of one. His name is Zygaena.	}{	Hmmm. Yes, I know of one. His name is Zygaena.	}{	#	}{	}{	G.Ming_Ziggy = 1; G.Ming_Zygaena = 1	}{	}{	}{	}{	}{	}{	}{	}
{	707	}{	Does he work for you?	}{	Does he work for you?	}{	471	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	706	}{	Hmmm. Ano, vím o jednom. Jeho jméno je Zygaena.	}{	Hmmm. Ano, vím o jednom. Jeho jméno je Zygaena.	}{	#	}{	}{	G.Ming_Ziggy = 1; G.Ming_Zygaena = 1	}{	}{	}{	}{	}{	}{	}{	}
{	707	}{	Pracuje pro vás?	}{	Pracuje pro vás?	}{	471	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
Much talk, little sense. -> Spousta řečí, smyslu pomálu.

Something to look forward to, eh? -> Máme se na co těšit, že?     <-- BTW, NPC maji take malkavianske hlasky? 

I'm here for your eyes, and your ears, and your face, and your blood. -> Jsem tu pro tvé oči a uši a tvou tvář a krev.

I'm here for the old box.  -> Jsem tu kvůli té staré krabici.

What is your name, face?  -> Řekni své jméno, škaredo.

Where is the box?  ->  Kde je stará krabice?

No, you will wither and die.  ->  Nikoliv, časem schřadneš a zemřeš.

Its secret best be serious for the trouble it heaps upon me.    ->   Za ta muka, která mi působí, nechť jeho tajemství stojí za to.

diky

**Comment by miracleflame** [comment]
> Something to look forward to, eh? -> Máme se na co těšit, že? <-- BTW, NPC maji take malkavianske hlasky?

Asi. Nemám overené, ale v UP súboroch to tak je.
