### ISSUE TITLE
Nepřesné názvy save souborů a map

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#331]
ve hře je hub přeloženo jako ulice, při ukládání třeba v kanalizaci to píše lokaci př. La(ulice)

https://snag.gy/8mPnWK.jpg lokace kanalizace
https://snag.gy/JyrMmF.jpg lokace kanalizace

to samé název mapy(ulice)
https://snag.gy/gcQbxZ.jpg lokace kanalizace
https://snag.gy/aZb78K.jpg lokace kanalizace

hub=rozbočovač

**Comment by miracleflame** [comment]
@soulcharmer chceš to upraviť na niečo iné? Napríklad "město"?

**Comment by soulcharmer** [comment]
hub ma tunu vyznamu, ale nejpresnejsi pokud jde o mapy bude asi "centrum"

diky

**Comment by miracleflame** [comment]
OK, len mi to príde skôr tak, že pod centrom sa obvykle myslí downtown.. aspoň v dialógoch sa to tak označuje, Ak chceš centrum, môžeš tiket zatvoriť.

**Comment by soulcharmer** [comment]
Aha uz vim, "ulice" jsem tam dal proto, ze  "centrum" uz bylo zabrane :)

Dalo by se tam dat "hlavni ulice" nebo "hl. ulice", aniz by se nekde neco rozbilo nebo nedavalo smysl?

Diky

**Comment by miracleflame** [comment]
Nerozbije to nič, ale ani to moc nerieši názvy sejvov v kanalizácii. :)

**Comment by soulcharmer** [comment]
ajo, to jsem v reportu prehlidl :-X

tak teda "hlavni uzel" nebo "hl. uzel"
