### ISSUE TITLE
Leopoldova společnost.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#333]
všiml jsem si že lovci upírů v Leopoldově společnosti mají jmenovky jako mafián a gangster, to je tím že to berou ze stejných LIPŮ? Nebo je to bug?

**Comment by miracleflame** [comment]
Presne tak.. to budem musieť odreportovať Wespovi, aby im zmenil soundgrupy, ak to ešte nespravil.

**Comment by miracleflame** [comment]
Myslím, že to bolo ošetrené v UP 9.7 beta 4
