### ISSUE TITLE
Náboje dračí dech

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#335]
https://snag.gy/s5oyrz.jpg

Sipy do kuse

**Comment by miracleflame** [comment]
@soulcharmer trochu som ten preklad rozvinul, môže byť?

		"ammoprintname"		"Dragon's Breath phosphoric cartridges"		// changed by wesp
		"ammodescription"	"Handmade phosphoric shotgun cartridges."	// changed by wesp

		"ammoprintname"		"Fosforem plněné patrony do Dračího dechu"
		"ammodescription"	"Krabička ručne vyrobené munice s fosforem do speciálně upravené brokovnice."

**Comment by soulcharmer** [comment]
"Fosforové patrony do Dračího dechu"
"Krabička ručně vyrobené munice s fosforem do upravené brokovnice."

diky
