### ISSUE TITLE
Zaseknutí postavy po použití plamenometu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#336]
Hotel Hallowbrook, zaseknutí postav po použití plamenometu, jedná se o tři identické postavy který se umějí teleportovat, když na ně použiji lehce plamenomet, tak aby se nerozpadly tak se seknou.

https://snag.gy/6fc9hY.jpg
https://snag.gy/0KWCYe.jpg

https://snag.gy/8kAD4I.jpg
https://snag.gy/2gHw1W.jpg

https://snag.gy/hPsI8L.jpg
https://snag.gy/sdanzZ.jpg

V aj jsem to nezkoušel předpokládám že to není češtinou.

**Comment by miracleflame** [comment]
[Odreportované Wespovi.](https://forums.planetvampire.com/bloodlines-tech-support/teleporting-adversaries-get-stuck-when-on-fire/)

**Comment by miracleflame** [comment]
Yey!
Wesp: This is a known random bug that I hope I just fixed in the upcoming beta :)!
