### ISSUE TITLE
Venus Dare

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#337]
https://snag.gy/g6B9Tl.jpg

Tady jsem nezaznamenal žádný zvuk.

**Comment by miracleflame** [comment]
To bude nejaká random chyba, kedy iný zvuk overridol hlasitosť predchádzajúceho zvuku. Hláška je unisex a dobre si pamätám, že som ju mnohokrát počul v hre.

Dá sa ti to zreprodukovať? Ak nie, môžeš tiket zatvoriť. Ak áno, skús porovnať s EN.

**Comment by maarten93** [comment]
Už se mi to znova nepovedlo
