### ISSUE TITLE
Becket na ulici v LA

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#339]
Odzkoušeno v čj i aj 

https://snag.gy/gQ1xiG.jpg
https://snag.gy/9JIvSL.jpg

Šel jsem neviditelný po ulici, když mě odchytil Becket, jenže se zasekne a já zůstanu přimrazen na místě, zrušení neviditelnosti nepomůže.

Pokud jsem od začátku viditelný tak to jde.

**Comment by miracleflame** [comment]
[Odreportované Wespovi.](https://forums.planetvampire.com/bloodlines-tech-support/beckett-sequence-stuck-when-obfuscate-is-active/)

**Comment by miracleflame** [comment]
Wesp:
Found and fixed! This is a common problem, so if there are other cutscenes that do not yet remove active disciplines, please make me aware of them...
