### ISSUE TITLE
Konec za sebe.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#345]
https://snag.gy/CoUIcb.jpg  nejdřív mluví o klíči, což je ještě v pořádku

https://snag.gy/yDZwEW.jpg a pak začne používat repliky, které používá po mém návratu z muzea.

https://snag.gy/DaGvYB.jpg

**Comment by maarten93** [comment]
https://snag.gy/2VwpeL.jpg

https://snag.gy/GpQoWs.jpg   dokonce se i znova aktivoval úkol v žurnálu.

**Comment by maarten93** [comment]
https://snag.gy/QYFhiM.jpg

Navíc princ začal říkat tuhle frázi, kterou myslím říká když mě posílí za sabbatama?

A zůstal jsem v  místnosti s ním a nemůžu se odtamtud dostat

**Comment by maarten93** [comment]
v Aj to jde.

**Comment by miracleflame** [comment]
Wow... Nemám absolútne žiadne zmysluplné vysvetlenie ani ospravedlnenie, prečo v rámci diffovania došlo k takejto vadnej úprave. Až ma to desí. Neviem či to mám považovať za šťastie, že si to tak rýchlo objavil alebo došlo k viacerým takýmto omylom, ale zbežne som prešiel očami diffy a nič podobné som už neobjavil.

**Comment by miracleflame** [comment]
Už to viem vysvetliť... podľa poznámok som chcel robiť tieto úpravy na riadkoch 1112... ale omylom som to spravil na riadkoch 1012... Jediný ďalší charakter, ktorému som robil úpravy nad line 1100 je Jack a tam som skontroloval všetko bez takéhoto omylu.

**Comment by maarten93** [comment]
Pořád není všude opraveno, zkoušel jsem jednu variantu konce která vede k otevření sarkofágu hráčskou postavou, ta šla, ale druhý pokus o jiný konec dopadl takhle:


https://snag.gy/UlIprt.jpg

https://snag.gy/XcMbTt.jpg

https://snag.gy/pQZgxD.jpg

https://snag.gy/ij6YGO.jpg

https://snag.gy/Tb01sK.jpg  tady už rozhovor pokračuje špatně

https://snag.gy/lMD35O.jpg

https://snag.gy/I4kmhM.jpg

Dnes jsem stárnul a nainstaloval, nejnovější verzi, češtiny,   tak snad není chyba u mě.

Myslím že tam těch variant rozhovoru je více, ale dnes už to nestihnu vyzkoušet.

**Comment by miracleflame** [comment]
Niečo sa ti tam rozbilo už v druhom kroku. Mal si mať niekoľko možností odpovedí na 1021.
{	1021	}{	[Laughs]Zase jsi za me udelal všechnu práci. Mám se co ucit... Myslel jsem, že je po všem... Ale ne, zde priplouváš s vetrem Gehenny v zádech a v rukou trímeš mou spásu. Klíc k mé budoucnosti.	}{	[Laughs]Zase jsi za me udelala všechnu práci. Mám se co ucit... Myslel jsem, že je po všem... Ale ne, zde priplouváš s vetrem Gehenny v zádech a v rukou trímeš mou spásu. Klíc k mé budoucnosti.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	1022	}{	Z ceho se tak radujete?	}{	Z ceho se tak radujete?	}{	1031	}{	}{	}{	}{	}{	}{	}{	}{	}{	Jste štasten? Už tu padla poznámka o mém klící?	}
{	1023	}{	No tak si ho pojdte vzít, když ho tak chcete.	}{	No tak si ho pojdte vzít, když ho tak chcete.	}{	1031	}{	}{	}{	}{	}{	}{	}{	}{	}{	Zkuste mi ho vzít... Prosím!	}
{	1024	}{	Zavri už ten rypák, ty nudnej žabožroutskej zmrde. Je po prdeli.	}{	Zavri už ten rypák, ty nudnej žabožroutskej zmrde. Je po prdeli.	}{	1031	}{	}{	}{	}{	}{	}{	}{	}{	}{	Prý jsou bricha princu plná zlata. Zjistíme to.	}

V súboroch som chybu nenašiel zatiaľ.

**Comment by maarten93** [comment]
Odinstaloval jsem celou hru a teď ji znovu stahuji z gogu, pak to znova vyzkouším.

**Comment by maarten93** [comment]
@miracleflame  Po přeinstalování, znovu stáhnutí a nainstalování češtiny problém pořád přetrvává, jediné co mám z předchozí instalace je save.

**Comment by maarten93** [comment]
Tak třeba touhle kombinací rozhovoru se mi podaří vyhnout se té chybě s sarkofágem, ale když použiji ten předchozí, tak to dělá pořád.

https://snag.gy/3pFb5f.jpg
https://snag.gy/yInsUg.jpg
https://snag.gy/Vn2TFZ.jpg
https://snag.gy/wpRUtA.jpg
https://snag.gy/rYASHx.jpg

**Comment by miracleflame** [comment]
Ešte predtým než to budem investigovať... tieto zmeny ešte neprešli konverziou do fontfriendly... určite v hre používaš zmeny urobené v základe?

**Comment by maarten93** [comment]
Teď naposled jsem zkompiloval instalačku přes compile.cmd a nainstaloval to přes ní.

**Comment by miracleflame** [comment]
To bude tým. Inštalačka sa kompiluje prevažne z fonfriendly súborov a tie ešte neboli updatované konverzným dumpom základných súborov. Pokúsim sa dnes porobiť čo najviac úprav a zbehnem dump. Tento tiket považujem za vyriešený.
