### ISSUE TITLE
lacroix

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#349]
https://snag.gy/F6reYg.jpg
Měl>Měla

Snad to půjde a nebude s tím problém jako u toho kurýra.

**Comment by miracleflame** [comment]
Obávam sa, že nie, ale za pokus to stojí... po dumpe.

**Comment by maarten93** [comment]
Tak to nepomohlo https://snag.gy/sBg3JR.jpg , ještě se to může zkusit napsat nějak neutrálně, ale vůbec mě nenapadá jak, tady to asi do do dialogového okna dát nepůjde, jelikož je to cutscéna.

**Comment by miracleflame** [comment]
Mne napadá unisex len niečo v zmysle "Jak pošetile promrhaná šance mě dorazit". @soulcharmer ?

**Comment by soulcharmer** [comment]
"Takto zahodit příležitost mě dorazit!"

diky
