### ISSUE TITLE
Radio titulky nesedí k audiu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#352]
https://snag.gy/RMYLSF.jpg

Sice anglicky moc neumím, ale připadá mi že rádio celou dobu zobrazuje jiné titulky než o čem v něm mluví, hraji od začátku.

**Comment by maarten93** [comment]
Zatím se mi na to už nepodařilo znovu narazit.

**Comment by maarten93** [comment]
Myslím že se to stalo hned po tom co jsem se poprvé ocitnul v bytě, pak až nainstaluji znova hru tak to zkusím.

**Comment by maarten93** [comment]
Už se mi to znovu nepodařilo z replikovat, teď jde rádio normálně, ale předtím když tam byli titulky té reklamy, tak v rádiu byl zvuk jak Deb dělá s někým rozhovor.

**Comment by miracleflame** [comment]
To je chyba enginu, ktorú som už Wespovi v minulosti reportoval. Totiž keď spustíš rádio, začne sa prehrávať zvukový súbor a spustia sa titulky. Keď rádio vypneš, v skutočnosti zvukový súbor hrá ďalej, len je muted. Ale titulky sa reálne pauznú. Čiže keď potom rádio znovu spustiš, zvuk bude oproti titulkom posunutý. Každopádne to čeština nespôsobuje, ani nevie opraviť.
