### ISSUE TITLE
Prozradil(a) jsi mdlou krev

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#353]
https://snag.gy/QRktZs.jpg
https://snag.gy/HuDNZ7.jpg

Tenhle zápis do žurnálu mi nedává moc smysl, nemělo by tam být Podrazil(a)

samovražednou>sebevražednou

Prodal jsem mu obyčejný dřevěný kolík, řekl jsem mu že je svatý a poslal ho zabít ninese.

To prozradila asi platí jen v případě že mu namluvím že prezident spojených států je upír a pošlu ho jej zabít, to pak ubere jeden bod maškarády

**Comment by miracleflame** [comment]
Ak to správne chápem, tak bod maškarády ti strhne len vtedy, keď ho pošleš za prezidentom. A ak ho pošleš za Ninesom alebo za princom, tak bod maškarády ti nestrhne, ale v zápise je vo všetkých prípadoch prezradenie mdlej krvi, áno?

Tam chybu nevidím, lebo mdlá krev sa ukrýva pred čistokrvnými vampírmi a to prezradenie sa vzťahuje voči tým vampírom a nie voči maškaráde.
