### ISSUE TITLE
Doktor v nemocnici

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#355]
https://snag.gy/pPVvYE.jpg

Kolik je těch hodin?
nemělo by tam být Kolik je hodin?

**Comment by miracleflame** [comment]
Pravda, v origin8áli je Ah, what time is it?
Ale @soulcharmer asi z nejakého dôvodu dal těch... Či? Nejaké zmeny?

**Comment by soulcharmer** [comment]
To je hovorove totez... bez opravy

dik
