### ISSUE TITLE
Vandal

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#356]
https://snag.gy/TKISRH.jpg tady jsem nezaznamenal žádný zvuk, ani animaci.

**Comment by miracleflame** [comment]
A ešte aj "nepustilA".
Keďže hovorí o nejakom Billovi, zmenil som aj konzultovanú Nikcu na Billa. Bill nie je Phil a je to lepšie než nicka.. hlavne keď hneď na to ho priamo spomína Vandal.
