### ISSUE TITLE
Nicka

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#357]
https://snag.gy/njPKUZ.jpg

Podle mě se tam víc hodí MATKO

**Comment by miracleflame** [comment]
@soulcharmer to nie je na mojm rozhodnutí... Inak Nicku som už upravil na Billa na základe #356

**Comment by maarten93** [comment]
Pokud jsi dobře pamatuji z minula, tak pokud Phila před, tímto nezabiješ tak jako nicka přijde Phil a následně Vandal mluví o Philovi, Pokud je Už Phil mrtvý, tak místo něho přijde jako nicka Bill a Vandal pak mluví o Billovi.

**Comment by miracleflame** [comment]
Výborne!

@soulcharmer Svatá matičko boží? Alebo svatá matko boží? Originál je Sweet mother of god.

**Comment by soulcharmer** [comment]
jo, "matko" muze taky byt, mozna se to hodi o kapanek vic.

diky
