### ISSUE TITLE
Drogový Trip 

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#358]
https://snag.gy/EItJeR.jpg
utropil(a) 

nemá tam být utrousil(a)? Utropil slovo utropil snad ani neexistuje.

**Comment by Honzixx** [comment]
Utropit je spíš takové lidové starší slovo. Tropit má význam něco jako provádět nebo vyvádět.
např. provádět neplechu --> tropit neplechu
Za mě je tam správně, ale utrousit tam taky sedí a je dnes známější. Ať rozhodne @soulcharmer :-)

**Comment by soulcharmer** [comment]
To vypada na nejake nezkrontrolovane preklady od @miracleflame   :-)  Nemame toho v popisech questu vic? Jen na tom screenu vidim nekolik veci k oprave:

Drogovy Trip
"Přinesl(a) jsi Tripovi krabičku s léky a utrousil(a) na něj pár kožených fórků."

Snilek:
"Zneužil(a) jsi týpka s mdlou krví a poslal(a) ho na sebevražednou misi. Jsi teď spokojen(a)?"


diky za report

**Comment by miracleflame** [comment]
Našiel som to ešte v mailoch pomaly spred roku, keď sme ešte neboli na gite a posielal som ti veci mailom. Dokonca boli tieto moje prvé príspevky bez diakritiky. Vyrobím z toho nejaké nové tikety na revíziu.
