### ISSUE TITLE
Nelze zkompilovat instalator

### ISSUE THREAD

**Issue by Krescz** [soulcharmer/gog_bloodlines_cz#359]
![error](https://cloud.githubusercontent.com/assets/26261159/23678488/a82883c2-0384-11e7-95f9-a085f9c1ab60.PNG)

Ahoj, asi něco dělám špatně. Při kompletaci instalatoru mi hlásí tento error.

**Comment by Krescz** [comment]
PS...postupoval jsem podle návodu. Neví tedy někdo co s tím?

**Comment by maarten93** [comment]
Zkus se podívat sem    #226

**Comment by Krescz** [comment]
maarten93 děkuji za odpověď, postupoval jsem krok po kroku, ale stále mi to vypisuje error: MUI2.nsh missing :(

**Comment by maarten93** [comment]
Tak to nevím co dál, včera jsem to instaloval a šlo mi to.

Ještě se zkus kouknout jestli tam máš tyhle dva soubory, protože ti to tam píše že je to nenašlo.

https://snag.gy/FtdHh0.jpg

**Comment by Krescz** [comment]
Nemám je tam. Nechápu jak je to možné. Mám si je dodatečně stáhnout?

**Comment by maarten93** [comment]
máš NSIS 3.01 ?  MUI2.nsh  by se mělo nainstalovat s tím programem samo a není potřeba je dále stahovat 
Program se stáhne od tady: http://nsis.sourceforge.net/Download

+ Po instalaci http://nsis.sourceforge.net/FontName_plug-in stáhnout FontName-0.7.zip nainstalovat a přesunout z NSIS\Plugins\FontName.dll do "NSIS\Plugins\x86-ansi , nic jiného není potřeba, už je to tak měsíc co jsem instaloval tenhle program, ale žádná nová verze nevyšla, takže by to mělo být stejné.

https://snag.gy/fHQB6y.jpg  když spustíš NSIS máš to stejné?

**Comment by Krescz** [comment]
Ano, postupoval jsem dle návodu. Zkusím to reinstalovat, třeba jsem při instalaci odškrtnul něco co jsem neměl.

**Comment by Krescz** [comment]
Přeinstaloval jsem NSIS a instalace proběhla hladce. Hra je nyní v češtině :) Děkuji za pomoc
