### ISSUE TITLE
Nepreložený dodatok v Therese.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#36]
{	401	}{	For all her unwholesome diversions and irritating disruptions, I should be less tolerant of her. She is my sister, however, and I suppose I'm obligated to forgive her her trespasses. I did sire her, after all. Please. . .be quick about it.	}{	For all her unwholesome diversions and irritating disruptions, I should be less tolerant of her. She is my sister, however, and I suppose I'm obligated to forgive her her trespasses. I did sire her, after all. Please. . .be quick about it.	}{	#	}{	npc.SetDisposition("Neutral",1)	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
bylo tam toho vic..
