### ISSUE TITLE
Hadí nora - banner model

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#360]
Před nápisama klubu "Hadí nora" ještě zůstala původní textura "Aps hole" je to takovej obrys.
Půjde to odstranit?
https://snag.gy/iVXseT.jpg
https://snag.gy/fgARXu.jpg
https://snag.gy/vAaUhr.jpg

**Comment by miracleflame** [comment]
Viem, v skutočnosti sa jedná o model. Bol na to aj tiket #56 
Konkrétne tento model bol v češtine vadný a pod určitými uhlami úplne mizol. Pôsobilo to viac buggy než v súčasnej podobe. S modelmi VTMB neviem pracovať, aj keď som si nedávno všimol, že sa objavil [veľmi rozsiahly guide](https://forums.planetvampire.com/bloodlines-modding/vtmb-models-everything-about-model-texture-changing/)
Možno sa k tomu ešte stihnem dostať a naučím sa to, preto tiket nechám otvorený.

**Comment by soulcharmer** [comment]
Nestacilo by proste ten model odstranit uplne a nechat tam jen placaty napis? To mi prijde nejjednodussi...

**Comment by miracleflame** [comment]
Ono ten model je "odstránený", ibaže hra si ho načíta originál z vpk a tomu sa dá zabrániť jedine tak, že sa overridne nejakým iným modelom. Bez modelu to každopádne nejde, lebo sa tak odstráni celý ten banner, na ktorom textúra visí. Časom na to mrknem.

**Comment by soulcharmer** [comment]
aha, v tom pripade bych nahradil ten neon v modelu nejakym bogus modelem, treba jen nejakou malou kulickou v  levem hornim rohu, aby se tam neco bylo, ale neprekazelo to... Teda pokud by to takto nejak slo...

**Comment by miracleflame** [comment]
[Credits za upravený model pre DLLulu](https://forums.planetvampire.com/bloodlines-modding/how-to-successfully-export-model-from-blender-to-mdl/)
A ja som trochu fixol samotnú textúru, ktorá išla mierne mimo a pridal jej pseudo 3D efekt skrz aplha channel, lebo stratou modelu sa stratil aj tretí rozmer.
