### ISSUE TITLE
Princ - ženský tvar

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#362]
Můj nezadržitelný křižáku --> Moje nezadržitelná křižačko
https://snag.gy/BktE0I.jpg
Žes byl --> Žes byla
https://snag.gy/d8Sya1.jpg

**Comment by miracleflame** [comment]
No ja neviem, či sa to hodí.. bola vôbec niekedy v histórii ľudstva nejaká križiačka?
@soulcharmer ?

**Comment by maarten93** [comment]
https://en.wikipedia.org/wiki/Women_in_the_Crusades

**Comment by maarten93** [comment]
nebo tam dát štítonoška. 
http://nedd.tiscali.cz/az-polovinu-vikinskych-najezdniku-tvorily-zeny-242527

**Comment by soulcharmer** [comment]
"Krizacka" zni opravdu divne i na prince. Zmenil bych krizaka na bojovnika/bojovnici - v tomto kontextu neni nic, co by vyzadovalo prechylovani krizaka:

"Má nezadržitelná bojovnice..."

Pokud jde o druhy screen, princ prece jen hovori spisovne, takze bych upravil na 

"že jsi byl" 
"že jsi byla"

diky
