### ISSUE TITLE
Žena v klubu

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#363]
Ztrať se ubožáku --> ubožačko
https://snag.gy/yWvfdt.jpg

**Comment by miracleflame** [comment]
Toto už je ale ozaj divné, lebo hra má v základe na toto ženskú repliku. MP3 a VCD súbory v preklade vlastne ani nemali byť, neviem, prečo sú.. hra ich má. Tak ja ich skúsim vyhodiť z češtiny a otestuj, prosím, či bez týchto súborov pôjde ženská replika... možno sa nám na tomto podarí rozlúsknuť, ako sa to dá rozchodiť...

**Comment by Honzixx** [comment]
Tak po smazání souborů line301_col_f.mp3 a line301_col_f.vcd je tam ženská replika.
https://snag.gy/5nqC07.jpg
