### ISSUE TITLE
Gary Golden - bug

### ISSUE THREAD

**Issue by Krescz** [soulcharmer/gog_bloodlines_cz#365]
Chtěl bych vás upozornit na bug, který pravděpodobně způsobuje tato čeština. Jedná se nikdy nekončící dialog s nosferatu Garym, když ho poprvé potkáte v jeskyni. Pomohlo mi až dát hru do původního stavu přes Gog Galaxy. Myslím, že by jste o tom měli vědět.

**Comment by miracleflame** [comment]
Dík. Mohol by si, prosím ťa, upresniť v čom presne spočíva nekončiaci dialóg? Ideálne screenshot...? Pre prípad obnovenia jazyka stačí mať odzálohovaný Unofficial patch ako sa píše v readme tohto projektu.

**Comment by Krescz** [comment]
Pochybuji, že screenshot bude o něčem vypovídat, ale pokusím se to vysvětlit. Představte si, že vedete normální dialog s NPC, které vám zadá úkol a pak se s vámi rozloučí, jenže místo toho, aby jste pokračovali, začne dialog nanovo a vám nezbývá nic jiného něž odklikávat odpovědi zase od začátku a tak pořád dokola. Taková smyčka, "loop".

**Comment by Honzixx** [comment]
Proto jsou potřeba screeny těch dialogů, jak jdou repliky po sobě (třeba to opakování), aby se dala chyba jednoduše vystopovat ;-) Ke každému reportu dávej screen třeba přes https://snag.gy/
