### ISSUE TITLE
Thung

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#366]
https://snag.gy/pJioaL.jpg

jse>jsem

Jen takový návrh, nebylo by místo mláďátko lepší mládě?

**Comment by miracleflame** [comment]
@soulcharmer otázka ohľadom mláďatka...
Nice work, cupcake. I felt that explosion a mile away. It's all over the news too. Man there's gonna be some pissed off Sabbat just howlin' for blood tonight, hehehe.
Pěkná prácička, mláďátko. Cítil jsem tu explozi až sem. Taky je to ve všech zprávách. Páni, někde teď určitě nějací Sabbati vyjou po krvi.

**Comment by maarten93** [comment]
Tady je třeba mládě https://snag.gy/ig49IU.jpg
Jinak co jsem koukal tak  mláďátko se ve hře vyskytuje hodně často. Třeba i na nahrávací obrazovce.

**Comment by soulcharmer** [comment]
Jo, ve hre mame mlade i mladatko. Zalezi, co kdo rika... Nines nikde ve svem dlg nema "cupcake".

Tung pouziva "cupcake" jednak jako zdrobnelinu a taky jako trochu blahosklonne osloveni - proto i zdrobnelina v prekladu.

Takze myslim, ze netreba nic dalsiho spravovat.

Dik za ten preklep
