### ISSUE TITLE
Zaseknutí při páčení zámku během morfizmu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#367]
https://snag.gy/QbGVfr.jpg

Když se pokouším o vypáčení zámku, během morfizmu, dojde k zaseknutí, ale ukončení této schopnosti obnoví páčení takže to není až takový problém.

**Comment by miracleflame** [comment]
Dík. [Odreportoval ](https://forums.planetvampire.com/bloodlines-tech-support/morphism-discipline-freezes-picklocking-when-active/)som Wespovi.
