### ISSUE TITLE
strings.txt revízia

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#372]
UIBarterActionStrs
        {
            "Name0"        "None"
            "Name1"        "Take"
            "Name2"        "Give"
            "Name3"        "Buy"
            "Name4"        "Sell"
            "Name5"        "Can't Afford"
            "Name6"        "Can't Sell"
            "Name7"        "Use"        // changed by wesp
            "Name8"        "Can't Use"        // changed by wesp
            "Name9"        "Read"
            "Name10"        "Can't Read"
            "Name11"    "Use"
            "Name12"    "Can't Use"
* 			"Name0"		"Nic"
			"Name1"		"Vzít"
			"Name2"		"Dát"
			"Name3"		"Koupit"
			"Name4"		"Prodat"
			"Name5"		"Moc drahé"
			"Name6"		"Neprodejné"											// Can't Sell
			"Name7"		"Použít"                // Equip
			"Name8"		"Nepoužitelné" 						        // Can't equip
			"Name9"		"Přečíst"
			"Name10"	"Mimo úroveň"
			"Name11"	"Použít"                // Use
			"Name12"	"Nepoužitelné"                                            // Can't use

                    UIBarterStrs
        {
            "Name0"    "No Item"
            "Name1"    "No Item"
            "Name2"    "Drop"
            "Name3"    "Can't Drop"
            "Name4"    "Ammo Full!"
            "Name5"    "Inventory Full!"
            "Name6"    "Exit"
            "Name7"    "MAX"
* 			"Name0"	"Žádný předmet"												// None
			"Name1"	"Žádný předmet"												// None
			"Name2"	"Zahodit"
			"Name3"	"Nemůžeš zahodit "												// Can't drop	
			"Name4"	"Není místo!"							// Ammo full
			"Name5"	"Není místo!"							// Inv full
			"Name6"	"Konec"

            
                    UIOccultStrs
        {
            "Name0"        "You have no clue what this thing is, but it looks eeeeeevil."
            "Name1"        "Maybe if you were a bit more goth you would have a clue what this thingie is."
            "Name2"        "If Ozzy were here, I'm sure he could tell you what this is."
            "Name3"        "It isn't a WWJD bracelet, so you have no idea what it could be."
            "Name4"        "You cannot identify this item, perhaps you should finish eating the soul doughnut?"
            "Name5"        "You haven't seen one of these before, but Bun Bun left it here, so it can't be good news."
            "Name6"        "Hmm, when you gaze upon this object, the skies darken and lightning flashes. Those aren't good clues to what this is though."
            "Name7"        "You can't identify this item, but it has a \"Made in Hell\" label on the bottom."
			"Name0"		"Nemáš zdání, co to je, ale vypadá to být zléééééé."
			"Name1"		"Možná kdybis byl(a) víc goth, tušil(a) by jsi, co to je za věcička."
			"Name2"		"Kdyby tady byl Ozzy, zaručeně by dokázal říct, co to je."
			"Name3"		"Není to náramek CBUJ (Co by udělal Ježíš), takže neznáš, co by to mohlo být."
			"Name4"		"Neumíš identifikovat tento předmět, možná budeš muset dojíst tu oplátku od kněze?"
			"Name5"		"Něco takového jsi jěště nevidel(a), ale zajíčky uprchly, takže nic dobrého z toho nekouká."
			"Name6"		"Hmm, když se na tuto věc zadíváš, obloha se zatáhne a uhodí blesk.  Tyto indice ti však nenapoví, co to je."
			"Name7"		"Neumíš identifikovat tento předmět, ale zespodu je štítek 'Vyrobeno v pekle'."
		

                    ItemReloadStrs
        {
            "Name0"        "Slow"    //"Short"
            "Name1"        "Medium"
            "Name2"        "Fast"
* 			"Name0"		"Pomalé"	//"Short"
			"Name1"		"Strední"
			"Name2"		"Rychlé"

**Comment by soulcharmer** [comment]
opravy: 

"Name3"	"Nemůžeš zahodit "												// Can't drop	
"Name3"	"Nelze zahodit"												// Can't drop	

Mam pocit, ze tyhle popisky pro okultni veci uz jsem prekladal, ale nemuzu to najit v tiketu ani v poste  :-X
Tak asi znova:

"Name0"		"Nemáš páru, co je to za věc, ale vypadá fakt ďábelsky."
"Name1"		"Možná kdybys byl(a) víc goth, odhadl(a) bys, co je to za udělátko."
"Name2"		"Kdyby tu byl Ozzy, určitě by ti řekl, co by to mohlo být."
"Name3"		"Náramek s heslem 'Co by udělal Ježíš?' to není, takže nemáš ponětí, co to je."
"Name4"		"Identifikovat tento předmět nezvládneš, ale co takhle dát si koblihu?"
"Name5"		"Něco takového jsi ještě neviděl(a), ale nechal to tady Bun Bun, takže z toho nic dobrého nekouká."
"Name6"		"Když na tuto věc zíráš, obloha se zatahuje a létají blesky. To ale neříká mnoho o funkci toho předmětu."
"Name7"		"Nedaří se ti tuto věc identifikovat, ale zespodu má nálepku 'Vyrobeno v pekle'."

a jeste

"Name1"		"Strední"
"Name1"		"Střední"



diky
