### ISSUE TITLE
McFly floats revize pre 9.7

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#374]
sounds\character\male\unique\mcfly

Aarrghh, ugh, oh man! Ghh, aarrrr, stupid door, aaggh, ah...
"...pitomý dveře!..."

Hey, let me out of here! What're you doin'? C'mon, this- c'mon, this isn't funny! Hey, arrgh! Anybody there? Hello?
Hej, pusťte mě odsud! Co to má znamenat? Hele, tohle není vtipný! Hej! Je tam někdo? Haló?

Ah, man, I gotta find the way out of this... stupid room. Arh... I got to get out of here... agh, huh...
Kruci, musím zjistiť jak utéct z téhle... pitomé izby... Musím vypadnout...

**Comment by soulcharmer** [comment]
Aarrghh, ugh, oh man! Ghh, aarrrr, stupid door, aaggh, ah...
"Zatracená práce! Pitomý dveře..."

Hey, let me out of here! What're you doin'? C'mon, this- c'mon, this isn't funny! Hey, arrgh! Anybody there? Hello?
"Hej, pusťte mě ven! Co to má znamenat? Hele-- hele, to není vtipný! Hej! Je tam někdo? Haló?"

Ah, man, I gotta find the way out of this... stupid room. Arh... I got to get out of here... agh, huh...
"Sakra, musím se s týhle cimry dostat. Musím ven..."


diky
