### ISSUE TITLE
Mercurio floats revize 9.7

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#375]
sound\character\male\unique\mercurio

Are you okay? What's wrong?
Jseš v pohode? Co se stalo?

You okay? What's wrong?
Jseš v pohode? Co se stalo?

What's going on?
Co se stalo?

Oh, what's going on?
Co se stalo?

Oh, what the hell is this?
Co má tohle k sakru znamenať?

Huh? Oh my god, I get out of here!
Bože můj, padám odsud!

Oh, I get out of here!
Padám odsud!

That's it, I'm gone!
Mám dost, mizím!

Hey, how'd I end up here?
Hele, co dělám tady?

How'd I end up here?
Co dělám tady?

Where I'd came, my?
Kam jsem se to dostal?°

Oh my go-...
Můj bo...

Whatta..?
Co to..?

We get a problem.
Máme problém.

What was that?
Co to bylo?

Who's there?
Kdo je tam?

**Comment by soulcharmer** [comment]
dole jsou vyznacene opravy:

Are you okay? What's wrong?
-Jseš v pohode? Co se stalo?
+Jseš v pohodě? Co se stalo?

You okay? What's wrong?
-Jseš v pohode? Co se stalo?
+Jsi v pohodě? Co se stalo?

What's going on?
Co se stalo?

Oh, what's going on?
-Co se stalo?
+Hej, co se stalo?

Oh, what the hell is this?
-Co má tohle k sakru znamenať?
+Hej, co to sakra je?

Huh? Oh my god, I get out of here!
Bože můj, padám odsud!

Oh, I get out of here!
Padám odsud!

That's it, I'm gone!
Mám dost, mizím!

Hey, how'd I end up here?
-Hele, co dělám tady?
+Hej, jak jsem se sem dostal?

How'd I end up here?
-Co dělám tady?
+Jak jsem se sem dostal?

Where I'd came, my?  <-- Tohle zni podezrele - mame k tomu jakykoliv kontext z UP?
Kam jsem se to dostal?°

Oh my go-...
Můj bo...

Whatta..?
Co to..?

We get a problem.
Máme problém.

What was that?
Co to bylo?

Who's there?
Kdo je tam?


diky

**Comment by miracleflame** [comment]
Where I'd came, my? je vyrobený lost_3.lip file z odposluchu (jeden z mála, ktorý som neodposlúchal ja). Okrem toho sú k dispozícii ešte lost 4 a 5, ktoré sa v hre neprehrávajú, ale mohli by nahradiť lost 3.
Weird. What I'm doing here?
What the heck is this?

Wav súbory som pushol do foldra Extra.

**Comment by soulcharmer** [comment]
Ten odposlech je IMHO blbe, ja tam slysim:

Where the heck am I?

coz odpovida i tem ostatnim, aniz bych vedel, kde se to ve hre objevi.

Preklad je:

"Kde to sakra jsem?"


diky
