### ISSUE TITLE
Veľký update na 9.7

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#376]
Aby ste mohli efektívne testovať ďalej, posúvam sem už update na 9.7 beta 4, ktorý sa čoskoro dostane na GOG release. Bola to strašná morda, hádam som nič neopomenul. Tento update je výrazne zameraný na rozšírenie titulkov, ktoré sa zobrazujú v ľavej hornej časti, tzv. floaty. Preto aj pri testovaní je potrebné zamerať sa predovšetkým na aktivovanie týchto titulkov rozličného typu... čiže používať na postavy rôzne cielené disciplíny a sledovať ich reakcie, púšťať sa s nimi do boja, ukrývať sa pred nimi, atď.. vyprovokovať čo najpestrejšiu paletu rôznych hlášok.

Je POTREBNÉ použiť všetky súbory z [UP 9.7 beta 4](http://www.patches-scrolls.de/patch/4647/7/) a na to potom hodiť aktuálnu češtinu. A samozrejme treba začať úplne novú hru. Postavy, ktoré by sa ešte hodilo pretestovať sú Ventrue, Brujah, Gangrel v tomto poradí priority, už by sa hodil aj male a takisto basic verziu sme tuším ešte netestovali.

Tento tiket je iba oznam, takže ho zatvorím hneď po vašom potvrdení, prípadne dohodnutí, kto za čo bude hrať.

**Comment by Honzixx** [comment]
Super, už se těším. Pokud nic nenamítáte, otestuju za mužskou postavu Ventrue na UP Basic. Začnu tak za týden ;-)

**Comment by maarten93** [comment]
Ok tak já zkusím klan Brujah, jen nevím jestli tento týden bude dost času.
