### ISSUE TITLE
Princ - intro

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#380]
Hraju za mužskou postavu. V intru princ mluví o mé stvořitelce, ale v mužském rodě. Některé věty v intru jsou správně. Zde na screenech jsou všechny věty, které jsou špatně:

obviněnému / obviněné, kterého / kterou, nenamáhal / nenamáhala
https://snag.gy/KI2v95.jpg
byl přistižen / byla přistižena
https://snag.gy/3WTVhP.jpg
obviněného / obviněnou, oddaného / oddanou, vyjímečného člena / vyjímečnou členku
https://snag.gy/hszyx0.jpg

**Comment by miracleflame** [comment]
Gramaticky dobre?

line1016_col_e.lip
"Nicméně obviněné, kterou tu před sebou máme, nebylo svolení odepřeno.  Vskutku, vůbec se nenamáhala o něj požádat.  Byla přistižena krátce po uchvácení tohoto dítěte. S těžkým srdcem musím vynést rozsudek, i když až do dneška jsem obviněnou považoval za oddanou a vyjímečnou členkyní naší organizace.  Jak ale někteří z vás ví, trest za tento přečin je smrt. Vězte, že nejsem o nic více soudcem nežli služebníkem práva, kterému podléháme všichni.  Nechť je toto přelíčení upomínkou naší komunitě, že se našeho kodexu musíme držet, jinak ohrožujeme všechny, kdo do ní patří."

line1019_col_e.lip
"Což nás přivádí k osudu tohoto nešťastně uchváceného dítěte.  Bez své stvořitelky je většina dětí odsouzena toulat se světem, aniž by věděly, kam patří, kde je jejich zodpovědnost, ale hlavně, jakými zákony se musejí řídit. Proto jsem se rozhodl--"

**Comment by Honzixx** [comment]
Opravil jsem dvě slova, jinak by to mělo být OK ;-)

"Nicméně obviněné, kterou tu před sebou máme, nebylo svolení odepřeno. Vskutku, vůbec se nenamáhala o něj požádat. Byla přistižena krátce po uchvácení tohoto dítěte. S těžkým srdcem musím vynést rozsudek, i když až do dneška jsem obviněnou považoval za oddanou a výjimečnou členku naší organizace. Jak ale někteří z vás ví, trest za tento přečin je smrt. Vězte, že nejsem o nic více soudcem nežli služebníkem práva, kterému podléháme všichni. Nechť je toto přelíčení upomínkou naší komunitě, že se našeho kodexu musíme držet, jinak ohrožujeme všechny, kdo do ní patří."
