### ISSUE TITLE
Policista - floaty

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#381]
Jsou všechny floaty už po dumpech? V SM v garážích chybí znaky u floatů policisty, aby toho nebylo víc, nedá se to pak moc kontrolovat ;-)
https://snag.gy/VeFjJw.jpg
https://snag.gy/S16XGo.jpg
https://snag.gy/NgR3Ed.jpg

**Comment by miracleflame** [comment]
Chyba bola v kódovaní zdrojových súborov, preto si s tým dumpy neporadili... Tento commit obsahuje aj konverzné dumpy po oprave... @maarten93 odporúčam si skompilovať novú inštalačku s týmito opravami.
