### ISSUE TITLE
Floaty - dvojitá šipka

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#382]
Zatím se mi to objevilo jen zde u policistů. Na začátku některých řádků je dvojitá šipka, je tam z nějakého záměru nebo tam nepatří? Mám jeden screen, ale je toho víc.
https://snag.gy/gTJ1pr.jpg

**Comment by miracleflame** [comment]
Áno, to je zámer a novinka v 9.7
Má symbolizovať začiatok priamej reči, lebo doteraz sa každá veta lámala do nového riadku z tým istým interprétom "Policajt", aj keď rozprávala stále tá istá osoba. A keď začala rozprávať iná, interprét ostáva rovnaký "Policajt" a ťažko sa dalo rozlíšiť, kto je kto. Tieto šípky pomáhajú rozlíšiť kedy rozpráva iná osoba. Všetky float konverzácie v hre sú takto riešené.

**Comment by Honzixx** [comment]
díky :-)
