### ISSUE TITLE
Hlas krve

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#383]
Nejsem si jistý, jestli to u Ventrue má být takto a změnu v UP jsem nikde nečetl, ale s Hlasem krve dostavám ke statistikám +4 body. U předchozích postav jsem dosttával jen +2. 
Screeny před použitím, po použití a floaty.
https://snag.gy/qUWrMw.jpg
https://snag.gy/gNap7y.jpg
https://snag.gy/jVugJU.jpg
https://snag.gy/dc8puM.jpg

**Comment by miracleflame** [comment]
V Basic je to +4 ako bolo vo vanilla hre. Plus to mení na +2.

**Comment by Honzixx** [comment]
Spousta změn Basic vs Plus, díky :-)
