### ISSUE TITLE
Princ intro

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#384]
Hraji za ženskou postavu, ale v intru mluví princ o mém stvořiteli jako o stvořitelce.

https://snag.gy/ds53NB.jpg
https://snag.gy/OEaVmf.jpg
https://snag.gy/zNdK6b.jpg

**Comment by miracleflame** [comment]
Desí ma, že ženského súboru sme sa nedotkli, takže to vyzrerá, akoby to hra ťahala z mužského.
Skúsil som opraviť ženský vrátane fontfriendly konverzie, takže by to malo po otestovaní ukázať výsledok.

**Comment by Honzixx** [comment]
Miro, mám to znova otestovat i za muže, když jsi to upravoval pro #380 ?

**Comment by miracleflame** [comment]
Tak je to začiatok intra, takže otestovať to za obe pohlavia by nemalo robiť problém.

**Comment by miracleflame** [comment]
Otestoval som to a nefunguje to. O to zvláštnejšie na tom je, že hra má v základe pre túto repliku pripravené všetky súbory aj v male aj female podobe, ale používa sa len male.

@soulcharmer je nejakým spôsobom možné spraviť z toho unisex? Keby sa popravovaná žena označovala za upíra či člena v mužskom rode, čítalo by sa to lepšie...

"Nicméně obviněnému, kterého tu před sebou máme, nebylo svolení odepřeno. Vskutku, vůbec se nenamáhal o něj požádat. Byl přistižen krátce po uchvácení tohoto dítěte. S těžkým srdcem musím vynést rozsudek, i když až do dneška jsem obviněného považoval za oddaného a vyjímečného člena naší organizace. Jak ale někteří z vás ví, trest za tento přečin je smrt. Vězte, že nejsem o nic více soudcem nežli služebníkem práva, kterému podléháme všichni. Nechť je toto přelíčení upomínkou naší komunitě, že se našeho kodexu musíme držet, jinak ohrožujeme všechny, kdo do ní patří."

**Comment by soulcharmer** [comment]
Tak to vypada jako bug pro wespa, matne si vybavuju, ze jsem na toto taky narazil.

Prevest to pujde, ale asi se nevyhneme urcite prkennosti... dulezitejsi jsou ty koncovky v minulem case nez oznaceni nasince:

"Nicméně obviněnému našinci, který tu před námi je, nebylo svolení odepřeno. Vskutku, vůbec totiž nepřišla žádná žádost. Toto konání bylo odhaleno krátce po uchvácení tohoto dítěte. S těžkým srdcem musím vynést rozsudek, i když až do dneška jsem obviněného považoval za oddaného a výjimečného člena naší organizace. Jak ale někteří z vás ví, trest za tento přečin je smrt. Vězte, že nejsem o nic více soudcem nežli služebníkem práva, kterému podléháme všichni. Nechť je toto přelíčení upomínkou naší komunitě, že se našeho kodexu musíme držet, jinak ohrožujeme všechny, kdo do ní patří."

**Comment by Honzixx** [comment]
@soulcharmer mě to přijde celkem dobré. Já bych tam jen přidal "ani" do věty:

Vskutku, vůbec totiž nepřišla ani žádná žádost.
nebo třeba takto
Ve skutečnosti totiž nepřišla vůbec žádná žádost.
Ve skutečnosti totiž nepřišla ani žádná žádost.

**Comment by soulcharmer** [comment]
Diky, po druhem precteni navrhuju tu vetu upravit na:

"Vskutku, nepřišla totiž ani žádná žádost."
