### ISSUE TITLE
Titulky bez zvuku

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#386]
https://snag.gy/PjTOew.jpg

Tady jsem neslyšel žádný dabing a myslím že v 9.6 tyhle titulky ani nebyli.

**Comment by maarten93** [comment]
https://snag.gy/VP9uY5.jpg

Další titulky kde jsem nezaznamenal zvuk.

**Comment by miracleflame** [comment]
Jak by som to... On tam ten zvuk je, aj vždy bol, len sme to nikdy nepočuli, lebo kamera je príliš ďaleko od zdroja zvuku. Teraz sa s titulkami objavuje veľa hlášok, ktoré padali, ale nebolo ich počuť. Nie je to bug.

**Comment by maarten93** [comment]
Předpokládám že úprava by asi byla hodně složitá, není to až tak rušivý problém, sice se to ve hře občas vyskytne, ale řekl bych že si toho málokdo všimne.

**Comment by miracleflame** [comment]
Urobil som na to [vlákno na fóre](https://forums.planetvampire.com/bloodlines-tech-support/unheard-captions-in-9-7/).

Preklad sa keď tak prispôsobí úpravám v UP, ak sa to bude riešiť.

**Comment by miracleflame** [comment]
Nakoniec sa ukázalo, že to je reálny bug, lebo zvuky pre tieto konkrétne hlášky ani neexistujú! Odstraňujem to z prekladu.

Brilantné testerské schopnosti toto. Ešteže ťa máme, Dík.

**Comment by maarten93** [comment]
@miracleflame Jen dotaz, ty už jsi to všechno z překladu odstranil? Já jen že jsem na to v tutoriálu znovu narazil.

**Comment by miracleflame** [comment]
Áno súbory sú odstránené z prekladu, ale to neznamená, že sa odstránili aj z tvojej hry a inštalácia novej češtiny to neodstráni. Po update na 9.7 bolo odstránených viacero súborov. Odporúčam kompletne odstrániť hru a všetko nainštalovať na novo.
