### ISSUE TITLE
Tulák

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#387]
https://snag.gy/9QLicq.jpg

Tyhle titulky mi přijdou dost zbytečný, sice nevím co říká ale není to pořád to samé, ale vše je napsané jako BRBLY, ale možná doopravdy to co říká nemá žádný význam ?

**Comment by miracleflame** [comment]
Viem, že som sa to pokúšal prekladať a potom som zistil, že starý preklad to rieši ako brbly, tak som to tak ponechal... Ono sú to vážne nezmysly

Hmm mmm mmm cram met time crab nipple meh. 

Hmm crab nipple hmm. 

Oh meh time crab nipple. 

Crab nipple this and crab nipple that. 

Crab nipple this'n has got crab nipple, whole lotta crab nipple. 

Je pravda, že teraz sa to dá vnímať ako citoslovcia, ktoré spravidla netitulkujeme.
Nechám to na rozhodnutí autora @soulcharmer

**Comment by soulcharmer** [comment]
jj, klidne to zahodte :)

diky
