### ISSUE TITLE
Časomíra není vydět

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#389]
https://snag.gy/g287kN.jpg

Nemyslím si že by to souviselo s češtinou, takže asi na wespa.

**Comment by miracleflame** [comment]
Niečo také sa mi tiež stalo pri dávnejšom testovaní, ale reštartovaní sa mi to už tuším nepodarilo zopakovať... Bral som to ako random bug.

**Comment by maarten93** [comment]
Nevím proč se to děje, ale občas se mi stane že časomíra zmizí.

**Comment by Honzixx** [comment]
Já jsem zatím pozoroval zmizení časomíry pouze při přechodu do jiné mapy se zapnutou disciplínou, tak to beru jako chybu hry 😉

**Comment by miracleflame** [comment]
[odreportované](https://forums.planetvampire.com/bloodlines-tech-support/discipline-duration-pool-not-showing/)

**Comment by miracleflame** [comment]
Wesp to potvrdil ako známy bug, s ktorým sa nič nedá robiť.
