### ISSUE TITLE
počítače znaky

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#391]
Je to už mnohem lepší, ale pořád občas narazím v PC na znaky.
https://snag.gy/nhW0vx.jpg

**Comment by miracleflame** [comment]
Ha ha! Ten login dole myslíš, že? To je meno tvojej postavy (žádné). Opravíš si to tak, že začneš novú hru s postavou, ktorej meno bude bez diakritiky.

**Comment by maarten93** [comment]
@miracleflame  Aha to jsem přehlídl, ale předtím když jsem začínal novou hru, tak mi to nedovolilo dokončit postavu dokud jsem jí nepojmenoval.

**Comment by miracleflame** [comment]
No to bude asi tým, že by default tam bolo Unnamed a postupne som preložil aj ten Name: Unnamed do češtiny by default, čím sa asi zrušila tá požiadavka...

Teraz neviem, či by nebolo lepšie vrátiť to na Unnamed, aby tam tá požiadavka bola...?

**Comment by miracleflame** [comment]
Cool, podarilo sa mi upraviť kód tak, aby pri tvorbe postavy hra vyžadovala zmeniť meno "žádné".
A zase vďaka bystrému testerovi.
