### ISSUE TITLE
Titulky Male + prezence

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#392]
https://snag.gy/UiemBG.jpg

Male pojmenování.

Mají npc nějak reagovat na schopnost prezence?
Když to na ně použiji tak se trochu klatí, ale nic neříkají, nebo mluví normálně jako případ na obrázku nahoře.

**Comment by miracleflame** [comment]
Opravil som to na Zbohatlík. Dík.

Vplyv prezence je vysvetlený tu http://vtmb.wikia.com/wiki/Presence čiže skôr na boj.
Pri NPC sa dá niekedy použiť v dialógoch obdobne ako Dominance či Dementace.
