### ISSUE TITLE
Bezdomovci reakce

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#393]
Předtím jsem to moc nezkoumal tak nevím jak to bylo předtím, ale bezdomovci na mě buď vůbec nijak nereagují nebo říkají jen brbly, brbly brbly.......

Ale neměli by říkat tohle to ? #92

**Comment by miracleflame** [comment]
Brbly som zmenil na citoslovce, aby sa nezobrazovali, ale až po dumpe to bude inštalovateľné...
Tie titulky z druhého tiketu sa týkajú bezdomovcov z Downtown LA pod diaľničným prejazdom pri Poslednej runde... Alebo možno ešte niektoré iné bezdomovecké NPC majú tieto špeciálne floaty. Tzn. toto nie je bug.
