### ISSUE TITLE
Pes 

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#394]
https://snag.gy/KSvhYU.jpg

I když je mrtví zraňuje mě když se k němu přiblížím a je slyšet i zvuk útoku.

**Comment by miracleflame** [comment]
[odreportované](https://forums.planetvampire.com/bloodlines-tech-support/dead-dog-causing-harm-and-barking/)

**Comment by miracleflame** [comment]
Wesp to potvrdil ako známy bug, s ktorým sa nič nedá robiť.
