### ISSUE TITLE
Update  9.7 beta4 -> 9.7 final

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#395]
Aplikovať na české repo

https://github.com/miracleflame/VTMB-Unofficial-Patch-by-Wesp/commit/14c623ec89fc2b418536a6264911178b4e87a84d

https://github.com/miracleflame/VTMB-Unofficial-Patch-by-Wesp/commit/7212e2beb489edd4dde3d2100b08adfbe86fcf0e

https://github.com/miracleflame/VTMB-Unofficial-Patch-by-Wesp/commit/9b1f370c7f89e11f44794aa15024841411add7ff

**Comment by miracleflame** [comment]
@soulcharmer poprosím o revíziu/preklad:

**Trip.dlg + lip**
Nice pants, dude... ah. <-- mužská replika
{	291	}{	Hezký kalhoty, vole...	}{	Hezký kalhoty, vole...	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**citizen_goth floats**
What's the haps, bro?
Jak se vede?

**sound\character\conversations\elizabeth_dane\copconversation1.lip**
(pridal som zvukovú stopu pre referenciu do foldru "extra")
"»Like a goddamn Cuisinart with all this blood..." "»Lieutenant?" "»Like an animal... Gamboa! Check the manifest to see if they had any, I dunno, animals - tigers, lions or something coulda done this and fell overboard." "»Roger that Lieutenant Golfos." "»Lieutenant?" "»Still, would've had to be one possessed little kitty cat to make this mess... No apparent tracks in the blood." "»Lieutenant?" "»What is it, private?" "»Uh - no bodies below deck either yet, they..." "»Christ - well tell them to keep looking! All this blood there's bound to be a body or two somewhere."
"»Jako zatracený Cuisinart se vší touhle krví...“ „»Poručíku?“ „»Jako zvíře ... Gamboa! Zkontrolujte jestli nevezli nějaké, já nevím, zvířata - tygře, lvy nebo něco, co by to udělalo a pak spadlo přes palubu„ „»Rozumím, poručíku Golfosi.“ „»Poručíku...„ „»Přesto by to musela být šeredně posedlá kočička, aby nadělala takový nepořádek... Žádné zjevné stopy v krvi„ „»Poručíku?“ „»Co se děje, vojíne?„ „»V podpalubí taky nejsou žádná těla..." „»Pro Krista - no řekněte jim, ať hledají dál! Tolik krve, přece tady někde musí být alespoň jedno tělo.“

**Comment by miracleflame** [comment]
@Honzixx @maarten93 Preklad dosiahol statusu 9.7 final a je po konverznom dumpe. To znamená, že si, prosím, skompilujte novú inštalačku a testujte po nainštalovaní aktualizácie. Na GOGu stále nie je táto verzia 9.7, takže je potrebné si pred aplikáciou češtiny doinštalovať UP 9.7 final zo stránky patches-scrolls.de
Díky!

**Comment by Honzixx** [comment]
Zkompilováno. Teď sem se k tomu moc nedostal, ale brzy se na to vrhnu plnou silou ;-)

**Comment by miracleflame** [comment]
@soulcharmer chcel by som už zavrieť tento tiket. Vyjadríš sa mi, prosím k revízii?

**Comment by soulcharmer** [comment]
Trip.dlg + lip
Nice pants, dude... ah. <-- mužská replika
Hezký kalhoty, kámo...

citizen_goth floats
What's the haps, bro?
Co je novýho, brácho?


sound\character\conversations\elizabeth_dane\copconversation1.lip
(pridal som zvukovú stopu pre referenciu do foldru "extra")
"»Like a goddamn Cuisinart with all this blood..." "»Lieutenant?" "»Like an animal... Gamboa! Check the manifest to see if they had any, I dunno, animals - tigers, lions or something coulda done this and fell overboard." "»Roger that Lieutenant Golfos." "»Lieutenant?" "»Still, would've had to be one possessed little kitty cat to make this mess... No apparent tracks in the blood." "»Lieutenant?" "»What is it, private?" "»Uh - no bodies below deck either yet, they..." "»Christ - well tell them to keep looking! All this blood there's bound to be a body or two somewhere."
"»Krve jako by si tu někdo hrál s otevřeným mixérem...“ „»Poručíku?“ „»Jako nějaký zvíře ... Gamboo! Koukni do záznamů, jestli nevezli nějakou, co já vím, zvěř - tygry, lvy nebo něco, co by zvládlo udělat tohle a pak spadnout přes palubu.„ „»Rozumím, poručíku Golfosi.“ „»Poručíku...„ „»Stejně to musela pěkně šílená zrůda na takovouhle paseku... Žádné viditelné stopy v krvi„ „»Poručíku?“ „»Co je, vojíne?„ „»V podpalubí se také zatím nenalezla žádná těla..." „»Proboha - tak hledejte dál! Tolik krve, přece tady musí někde být pár těl.“

je to vse?

**Comment by miracleflame** [comment]
Vše. Dík. Pridal som "být" do "Stejně to musela pěkně šílená zrůda..."
