### ISSUE TITLE
Počeštenie stránky prekladu

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#396]
https://prekladyher.eu/preklady/vampire-the-masquerade-bloodlines.315/

Aktualizace češtiny do vampiristické immersive-sim RPG tentokrát i s diakritikou

Čeština na túto unikátnu hru z roku 2004 od vývojárov Troika Games už existuje niekoľko rokov. Ale vzhľadom k tomu, že technický stav hry po vydaní si vyžadoval mnohé dodatočné opravy a patche a vznikol projekt Unofficial Patch, ktorý je stále vo vývoji, hra ním mení svoju podobu vrátane textov. Pôvodná čeština z roku 2007 bola robená na verziu UP 3.5 a na dnešnú verziu UP je neaplikovateľná. Okrem toho bola bez diakritiky.

S pôvodným autorom češtiny spolupracujeme na vývoji češtiny s diakritikou pre aktuálnu verziu hry.

FAQ:
Hýbe sa to niekam? Žiadne percentá tu nenabiehajú...
Pracujeme cez Github, nie tu. Odkaz na stránku vývoja tu je (adresa na další informace), stačí mať otvorené oči.

Kedy bude preklad hotový a k dispozícii?
Snáď určite v roku 2017, ale bližšie sa nedá špecifikovať.

Unofficial patch vychádza v dvoch prevedeniach, BASIC a PLUS. Na ktoré z nich je čeština?
Čeština je robená na obidve verzie a inštalátor ponúkne vybrať si.

Je potrebné mať osobitne vopred nainštalovaný Unoffical Patch pred aplikovaním češtiny?
V skratke táto čeština musí byť aplikovaná na verziu hry, ktorá už obsahuje UP Basic. Ovšem UP Basic je už súčasťou nového vydania hry na GOGu. Takže nainštalovaním hry od GOGu automaticky máte aj UP Basic.
UP PLUS netreba do takejto inštalácie doinštalovávať, pretože je kompletne obsiahnutý v češtine. Avšak(!) stále platí, že musí byť aplikovaný na verziu hry, ktorá už obsahuje Basic.

Počítačové terminály majú texty bez diakritiky. Je to zámer? Plánujete dorobiť diakritiku?
Fonty použité v počítačových termináloch sa nepodarilo identifikovať a upraviť. Avšak štandardne sa aj v reálnej praxi zvykne v počítačových termináloch písať bez diakritiky, takže pri tomto ostaneme a do budúcna diakritiku v termináloch neplánujeme.

Je možné zapojiť sa do beta testovania?
Určite. Kontaktujte ma na miracle.flame@gmail.com alebo soulcharmer@gmail.com

**Comment by soulcharmer** [comment]
Tak uz tam mam konecne ucet... Upravy pro 9.8 jsou ready a hned po jejich zapracovani bych vydal Betu.

Muj dalsi krok je prelozit tento text.

Diik a sorry za zpozdeni.

**Comment by soulcharmer** [comment]
Zatim zacatek:

"
Aktualizovaný překlad pro češtinu vydanou původně na http://www.bloodlines.cz/ , tentokrát pro verzi hry z GOG.com, i s diakritikou a s vylepšeními neoficiálního patche (viz níže).
"

"
Čeština pro tuto unikátní hru z roku 2004 od Troika Games už existuje mnoho let. Vývoj a vydání hry bylo bohužel provázeno mnoha technickými nedostatky, kterými se původní autoři nemohli věnovat. Proto vznikl projekt, který nezávisle a dodatečně opravuje a vylepšuje hru, a to včetně textů a questů. Více na http://www.moddb.com/mods/vtmb-unofficial-patch

Původní čeština byla vytvořena pro verzi neoficiálního patche 3.5. V rámci aktualizace překladu vycházíme z verze hry dostupné na GOG.com a verze neoficiálního patche 9.8. Čeština už je nyní k dispozici i s diakritikou na https://github.com/soulcharmer/gog_bloodlines_cz a testovací instalátor se brzy objeví i zde.
"

**Comment by miracleflame** [comment]
Aj som sa chcel ozvať, jak se vede s testovaním... ale nakoniec som to nechcel tlačiť, lebo GOG stále ponúka iba 9.7 na stiahnutie. Aj som im tam otvoril tiket asi pred mesiacom a priebežne ich bombardujem s tým, že UP 9.8 je dávno k dispozícii. Zatiaľ mi odpisujú len bláboly, že sú si vedomí atď. Každopádne vydávať češtinu 9.8, kým nie je na GOGu 9.8 by mohlo narobiť viac komplikácií než osohu.

**Comment by soulcharmer** [comment]
Co se děje s překladem? Není vidět postup...
Pracujeme na Githubu ( https://github.com/soulcharmer/gog_bloodlines_cz ), ne na tomto webu. Do testování se může zapojit kdokoliv.

Kdy bude hotový překlad k dispozici?
Testovací verze už je k dispozici na Githubu, sestavený instalátor se na tento web nevejde. Pokusíme se jej dodat v průběhu listopadu 2017.

Neoficiální patch (UP) existuje ve dvou verzích, BASIC a PLUS. Kterou bude podporovat čeština?
Čeština je kompatibilní s oběma verzemi, které budou volitelné v instalátoru.

Je potřeba mít předem nainstalovaný neoficiální patch před instalací češtiny?
Češtinu je nutno instalovat na verzi hry, která obsahuje UP BASIC. Tato verze patche už je součástí vydání hry na GOG.com. UP PLUS není třeba doinstalovávat, protože už je součástí češtiny. Přesto platí, že UP PLUS lze aplikovat jen na hru, která už v sobě má UP BASIC.

Počítačové terminály ve hře jsou přeloženy bez diakritiky. Je to záměr?
Částečně to záměr je, protože práce v ternimálu, představující zjednodušené uživatelské rozhraní, obvykle nezahrnuje používání diakritiky. Současně je technicky náročnější najít a upravit odpovídající fonty, proto aktuálně diakritiku do terminálu neplánujeme.

Je možné se zapojit do testování?
Rozhodně, testovací verze češtiny už je k dispozici na Githubu ( https://github.com/soulcharmer/gog_bloodlines_cz ), kde také můžete posílat zpětnou vazbu ( https://github.com/soulcharmer/gog_bloodlines_cz/issues ). V případě potřeby se obraťte na autory češtiny: miracle.flame@gmail.com nebo soulcharmer@gmail.com

**Comment by miracleflame** [comment]
Ešte keď tak sprav výber screenshotov do prezentácie z tých čo tam už sú + tie, čo máme v tikete  #341

**Comment by miracleflame** [comment]
@soulcharmer 
Ešte prosím ťa dopíš po česky k bodu
Je potřeba mít předem nainstalovaný neoficiální patch před instalací češtiny?
Přesto platí, že UP PLUS lze aplikovat jen na hru, která už v sobě má UP BASIC, čiže ak máte hru z iného zdroja (originál CD alebo Steam), je nutno předem nainstalovat příslušnou verzi Unofficial patch ručne z http://patches-scrolls.de/patch/4647/7/74148

**Comment by soulcharmer** [comment]
OK,

"
Je potřeba mít předem nainstalovaný neoficiální patch před instalací češtiny?
Češtinu je nutno instalovat na verzi hry, která obsahuje UP BASIC. Tato verze patche už je součástí vydání hry na GOG.com. Pro tuto verzi není UP PLUS třeba doinstalovávat, protože už je součástí češtiny.

Pokud ale máte jinou verzi hry, např. originální CD nebo ze Steamu, je potřeba nainstalovat UP ručně z http://patches-scrolls.de/patch/4647/7/74148
"

Taky kdyztak jeste pridej "(UP)" k prvni zmince o neof. patchi jako klic k dalsim otazkam.


diik

**Comment by soulcharmer** [comment]
Hotovo

https://prekladyher.eu/preklady/vampire-the-masquerade-bloodlines.315/
