### ISSUE TITLE
test batch 2

### ISSUE THREAD

**Issue by soulcharmer** [soulcharmer/gog_bloodlines_cz#398]
jack_tutorial.dlg: nějlehčí -> nejlehčí

jmena ulozenych pozic:
Quick Save -> Rychlá pozice
Auto Save -> Automat.pozice

názvy dnu a mesicu u ulozenych pozic se zatim neprekladaji

v tutorialu ma posledni vampir u sveho titulku "Upír"

v terminalech [q]uit -> [k]onec
a prikaz "quit" -> "konec"

**Comment by miracleflame** [comment]
> jack_tutorial.dlg: nějlehčí -> nejlehčí
opravené v e3dbf54

> jmena ulozenych pozic:
> Quick Save -> Rychlá pozice
> Auto Save -> Automat.pozice
> 
> názvy dnu a mesicu u ulozenych pozic se zatim neprekladaji
preložené v ccbf3d ako
NedPonUteStřČtvPátSob
JanFebMarAprMájJúnJúlAugSepOktNovDec

> v tutorialu ma posledni vampir u sveho titulku "Upír"
nechápem, objasni

> v terminalech [q]uit -> [k]onec
> a prikaz "quit" -> "konec"
opravené

**Comment by soulcharmer** [comment]
ajo, v tomto formatu by to melo byt:

NePoÚtStČtPáSo
LedÚnoBřeDubKvěČerČrvSrpZářŘíjLisPro

> nechápem, objasni

cestina vsude pouziva "Vampír" místo "Upír" (je to ten kontextovy titulek u vampira, ktereho ma hrac odlakat plechovkou od rybicek :)

**Comment by miracleflame** [comment]
Tajne som dúfal, že tie mesiace ponecháš, aby tomu rozumeli aj Slováci.
Všetko opravené.
