### ISSUE TITLE
instalator prepisuje nastaveni hry

### ISSUE THREAD

**Issue by soulcharmer** [soulcharmer/gog_bloodlines_cz#399]
chtelo by to kontrolu, zda bylo nastaveni hry zmeneno po instalaci hry (nejspis porovnanim casu zmeny souboru nastaveni a jinych souboru) a v takovem pripade tyto soubory neinstalovat.

Kdyby to neslo, mela by byt aspon hlaska v instalatoru a rada, ktere soubory zazalohovat

**Comment by miracleflame** [comment]
Dobré, že si na toto uvrhol svetlo, lebo sú tam nejaké detaily, ktoré treba dotiahnuť.
Avšak súbory nastavenia sú v češtine zahrnuté úmyselne z dvoch dôvodov.

1. lebo preklad názvov kláves rozbíja aj funkcionalitu samotného nastavenia.  Preto som do češtiny zahrnul aj defaultné nastavenie preložené do češtiny, nech aspoň funguje hneď bez potreby manuálneho bindovania odznovu. Dalo by sa použiť tlačítko "Nastavit výchozí", ktoré opraví bindovanie, ale to je také meh riešenie.
2. samotný súbor nastavenia config.cfg, ktorý tu je podstatný, v sebe nesie default meno postavy "Unnamed". To preddefinované meno sa dá nastaviť jedine v tomto súbore a ja som ho preložil na Žádné. Takisto som upravil zdrojový kód, aby nedovolil spustiť hru, kým sa postava nepremenuje. Z pohľadu kódu to je nedovoľ spustiť hru, ak sa postava volá Žádné. Ak tento súbor s nastaveniami vypustíme z češtiny, hra si ho natiahne z originál súborov hry pod vampire\cfg, kde bude meno "Unnamed" a navyše kód dovolí spustiť hru, pretože meno nebude "Žádné".

Takže jedine tak poznámka v inštalátori, že čeština prepíše nastavenia hry, ale ich odzálohovanie by malo význam jedine vtedy, ak už tie boli české.

**Comment by soulcharmer** [comment]
Prvni instalace je na prepis asi v pohode, jen bych tam do instalatoru pridal jeden krok, ktery uzivatele alespon informuje.

Mne se to stalo pri opakovane instalaci, kdy uz by bylo mozne detekovat, ze config.cfg je v cestine a v tom pripade neprepisovat.

To by slo?

**Comment by miracleflame** [comment]
Nakoniec je riešenie úplne jednoduché, o všetko sa postará súbor default.cfg, ktorý nastavenia neprepíše, jedine že by vôbec neexistovali. A ten kto už raz pustil hru v angličtine si holt musí prebindovať klávesy alebo použiť tlačítko Výchozí nastavení. Toto sa mi zdá elegantnejšie než dávať do češtiny nastavenia na pevno.
