### ISSUE TITLE
Preklep v replike 621 Bertram.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#40]
{	621	}{	Ale Sabbati svou nestvůrnou náturu glorifikují. Odmítají ji skrývat a pěkně po svém ji dávají na odiv. Taky jsou vygumovaní a lehkomyslní, jejich průměrná délka života je stejná jako u vampírské jepice.	}{	Ale Sabbati svou nestvůrnou náturu glorifikují. Odmítají ji skrývat a pěkně po svém ji dávají na odiv. Taky jsou vygumovaní a lehkomyslní, jejich průměrná délka života je stejná jako u vampírské jepice.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by miracleflame** [comment]
opravené
{	621	}{	Ale Sabbati svou nestvůrnou náturu glorifikují. Odmítají ji skrývat a pěkně po svém ji dávají na obdiv. Taky jsou vygumovaní a lehkomyslní, jejich průměrná délka života je stejná jako u vampírské jepice.	}{	Ale Sabbati svou nestvůrnou náturu glorifikují. Odmítají ji skrývat a pěkně po svém ji dávají na obdiv. Taky jsou vygumovaní a lehkomyslní, jejich průměrná délka života je stejná jako u vampírské jepice.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
Prosim revertni to :)

http://prirucka.ujc.cas.cz/?slovo=odiv

Ja ked sa pokusam o slovencinu, tiez to nedopada volaako ;)

**Comment by miracleflame** [comment]
Promiň, to som si vážne za celý život nevšimol, že existuje takýto tvar slova. :)
