### ISSUE TITLE
Update 9.7 -> 9.8

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#400]
@soulcharmer prosím prelož/zreviduj.

**dlg\downtown la\patty.dlg**
{	36	}{	Ah yes, he said he'd burn for you. He gave me this.	}{	Ah yes, he said he'd burn for you. He gave me this.	}{	91	}{	(G.Skelter_Quest == 3 or (G.Vandal_Quest == 1 and G.Patch_Plus == 1)) and pc.HasItem("item_w_tzimisce2_claw") 	}{	pc.RemoveItem("item_w_tzimisce2_claw") 	}{	}{	}{	}{	}{	}{	}{	He was all fire and flames for you. Then he gave me this gift.	}
{	56	}{	Ah Kent, he said he'd burn for you. He gave me this.	}{	Ah Kent, he said he'd burn for you. He gave me this.	}{	91	}{	(G.Skelter_Quest == 3 or (G.Vandal_Quest == 1 and G.Patch_Plus == 1)) and pc.HasItem("item_w_tzimisce2_claw") 	}{	pc.RemoveItem("item_w_tzimisce2_claw") 	}{	}{	}{	}{	}{	}{	}{	The show cat was all fire and flames for you. Then he gave me this gift.	}
{	85	}{	Indeed, Kent said he'd burn for you. He gave me this.	}{	Indeed, Kent said he'd burn for you. He gave me this.	}{	91	}{	(G.Skelter_Quest == 3 or (G.Vandal_Quest == 1 and G.Patch_Plus == 1)) and pc.HasItem("item_w_tzimisce2_claw") 	}{	pc.RemoveItem("item_w_tzimisce2_claw") 	}{	}{	}{	}{	}{	}{	}{	Indeed the show cat was all fire and flames for you. Then he gave me this gift.	}

**dlg\downtown la\milligan.dlg**
{	65	}{	Give me your driver's license. I'm letting you go.	}{	Give me your driver's license. I'm letting you go.	}{	101	}{	Intimidate 6	}{	G.Mill_Intimidate = 1	}{	}{	}{	}{	}{	}{	}{	}
Dej mi svůj řidičák a nechám tě jít.	}{	Dej mi svůj řidičák a nechám tě jít.

{	86	}{	You saw nothing tonight. Nothing happened. You will forget everything.	}{	You saw nothing tonight. Nothing happened. You will forget everything.	}{	91	}{	Dominate 3	}{	G.Mill_Dominated = 1	}{	}{	}{	}{	}{	}{	}{	}
Nic si tady neviděl. Nestalo se tu nic. Všechno to zapomeneš.

**Plus_CZ/vdata/hackterminals/haven_pc.txt + basic haven_pc**
		"subject"	"Looking for dates?"
		"sender"	"gary@schrecknet.vtm"
		"body"		"Are you lonely, boss? Then maybe finding one of these weird fleshy Tzimisce balls for me will stop you from wallowing in self pity. I'll give you a poster in return of a girl hanging out for you."

**dlg/santa monica/tourette.dlg + sound/character/dlg/santa monica/tourette/line931_col_e.lip**
{	931	}{	[Jeanette]Therese has officially sided with the Camarilla. Could be a prince, one day.	}{	[Jeanette]Therese has officially sided with the Camarilla. Could be a prince, one day.	}{	#	}{	pc.SetCamera("tJeanette") or npc.SetDisposition("joy",1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	932	}{	How are you two getting along?	}{	How are you two getting along?	}{	811	}{	G.Story_State >= 10 and G.Tourette_1 == 0	}{	G.Tourette_1 = 1	}{	}{	}{	}{	}{	}{	}{	Did you find room for two in your pale skin?	}
{	933	}{	Congratulations. If you ever need a favor, find me. Goodbye.	}{	Congratulations. If you ever need a favor, find me. Goodbye.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Call on me anytime, daughters of Janus.	}
{	934	}{	Finishing the other's sentence - it's really creepy. Goodbye.	}{	Finishing the other's sentence - it's really creepy. Goodbye.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Your madness is divine. Farewell.	}	

**vdata/items/item_g_jumbles_flyer.txt**
"printname"	"Fleshy Ball"	// added by wesp
+	"description"	"A weird and disgusting fleshy ball."	
	"printname"	"Masová koule"	// added by wesp
	"description"	"Podivná nechutná masová koule."	// added by wesp

**vdata/system/quests_hollywood.txt**
			"Description"	"Gary will swap a poster of Imalia for a fleshy Tzimisce ball. Just put the ball in the mailbox and check your haven and emails later."
			"Description"	"Gary nabízí plakát Imalie vyměnou za masovou kouli klanu Tzimisce. Nech kouli ve schránce svého úkrytu a později si zkontroluj email."

**Comment by soulcharmer** [comment]
**patty**
{ 36 }{ Jo vidíš, říkal, že by pro tebe i shořel. Dal mi tohle. }{ Jo vidíš, říkal, že by pro tebe i shořel. Dal mi tohle. }{ 91 }{ (G.Skelter_Quest == 3 or (G.Vandal_Quest == 1 and G.Patch_Plus == 1)) and pc.HasItem("item_w_tzimisce2_claw") }{ pc.RemoveItem("item_w_tzimisce2_claw") }{ }{ }{ }{ }{ }{ }{ Byl pro tebe zcela zapálen. A pak mi předal tento dar. }
{ 56 }{ Jo vidíš, Kent, říkal, že by pro tebe i shořel. Dal mi tohle. }{ Jo vidíš, Kent, říkal, že by pro tebe i shořel. Dal mi tohle. }{ 91 }{ (G.Skelter_Quest == 3 or (G.Vandal_Quest == 1 and G.Patch_Plus == 1)) and pc.HasItem("item_w_tzimisce2_claw") }{ pc.RemoveItem("item_w_tzimisce2_claw") }{ }{ }{ }{ }{ }{ }{ Ten sekáč byl pro tebe zcela zapálen. A pak mi předal tento dar. }
{ 85 }{ To jo, Kent říkal, že by pro tebe i shořel. Dal mi tohle. }{ To jo, Kent říkal, že by pro tebe i shořel. Dal mi tohle. }{ 91 }{ (G.Skelter_Quest == 3 or (G.Vandal_Quest == 1 and G.Patch_Plus == 1)) and pc.HasItem("item_w_tzimisce2_claw") }{ pc.RemoveItem("item_w_tzimisce2_claw") }{ }{ }{ }{ }{ }{ }{ Ten sekáč byl pro tebe vskutku zcela zapálen. A pak mi předal tento dar. }

**dlg\downtown la\milligan.dlg**
{ 65 }{ Give me your driver's license. I'm letting you go. }{ Give me your driver's license. I'm letting you go. }{ 101 }{ Intimidate 6 }{ G.Mill_Intimidate = 1 }{ }{ }{ }{ }{ }{ }{ }

**Naval řidičák. Pak můžeš jít.**

{ 86 }{ You saw nothing tonight. Nothing happened. You will forget everything. }{ You saw nothing tonight. Nothing happened. You will forget everything. }{ 91 }{ Dominate 3 }{ G.Mill_Dominated = 1 }{ }{ }{ }{ }{ }{ }{ }

**Nic jsi tady neviděl. Nic se nestalo. Všechno to zapomeneš.**

**Plus_CZ/vdata/hackterminals/haven_pc.txt + basic haven_pc**
"subject" "Hledas rande?"
"sender" "gary@schrecknet.vtm"
"body" "Je ti smutno, sefe? Tak to se zkus podivat po jedne te divne tzimiscke hroude masa a treba te ta sebelitost prejde. Dam ti za ni plakat holky, ktera zazene zal."

dlg/santa monica/tourette.dlg + sound/character/dlg/santa monica/tourette/line931_col_e.lip
{ 931 }{ [Jeanette]Tereza se nadobro přidala ke Kamarille. Mohla by to jednou dotáhnout na prince. }{ [Jeanette]Tereza se nadobro přidala ke Kamarille. Mohla by to jednou dotáhnout na prince. }{ # }{ pc.SetCamera("tJeanette") or npc.SetDisposition("joy",1) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 932 }{ Tak jak spolu vy dvě vycházíte? }{ Tak jak spolu vy dvě vycházíte? }{ 811 }{ G.Story_State >= 10 and G.Tourette_1 == 0 }{ G.Tourette_1 = 1 }{ }{ }{ }{ }{ }{ }{ Našly jste pod tou bledou kůží pokoj pro dva? }
{ 933 }{ Gratuluji. Když budeš někdy potřebovat pomoc, dej mi vědět. Sbohem. }{ Gratuluji. Když budeš někdy potřebovat pomoc, dej mi vědět. Sbohem. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Zavolejte mi kdykoliv, Janusovy dcery. }
{ 934 }{ To je úlet dokončovat větu té druhé. Mějte se. }{ To je úlet dokončovat větu té druhé. Mějte se. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Vaše šílenství je božské. Sbohem. }


**vdata/items/item_g_jumbles_flyer.txt**
"printname" "Hrouda masa" // added by wesp
"description" "Podivná, nechutná hrouda masa."


**vdata/system/quests_hollywood.txt**
"Description" "Gary nabízí plakát Imalie výměnou za tzimisckou hroudu masa. Nech hroudu ve schránce svého úkrytu a po nějaké době zkontroluj email."
