### ISSUE TITLE
compile.cmd error

### ISSUE THREAD

**Issue by aladarknis** [soulcharmer/gog_bloodlines_cz#401]
![vtmbcz_error](https://user-images.githubusercontent.com/24768968/32333113-595cb5cc-bfe7-11e7-9472-e279aa1786b2.png)

**Comment by soulcharmer** [comment]
To vypada na chybejici NSIS.

v Instalator/readme.txt mame:

"
Beta verze instalátoru, naskriptované v NSIS:

Požadavky:
- instalátor se zkompiluje spuštěním compile.cmd
- musíte mít nainstalován NSIS ( http://nsis.sourceforge.net/Download ) a jeho přídavný plug-in ( http://nsis.sourceforge.net/FontName_plug-in )
- POZOR FontName plug-in se nainstaluje chybně, je potřeba presunout "NSIS\Plugins\FontName.dll" do "NSIS\Plugins\x86-ansi\"
"

Kazdopadne nyni uz neni treba kompilovat instalator rucne - je vydan ke stazeni:

https://prekladyher.eu/preklady/vampire-the-masquerade-bloodlines.315/

Prosim zkus

**Comment by aladarknis** [comment]
NSIS som nainštaloval podľa návodu v readme.txt, ale to nevadí keďže hotový inštalátor funguje bezchybne. Díky moc.

**Comment by soulcharmer** [comment]
@miracleflame  myslis, ze to muzeme zavrit?

**Comment by miracleflame** [comment]
No jasné, kompilátor je pre naše učely a určite funguje,
