### ISSUE TITLE
chybky v instalatoru

### ISSUE THREAD

**Issue by soulcharmer** [soulcharmer/gog_bloodlines_cz#402]
viz https://prekladyher.eu/tema/vampire-the-masquerade-bloodlines.1179/page-4

Pri možnosti PLUS tam sú ešte 4 podsekcie, ako no new audio, no new particles a pod. Počítam, že ak tieto nové efekty chcem, tak tie políčka zaškrtávať nemám. Divné ale je, že ak ich zaškrtnem, tak sa zväčší velkosť inštalácie, čo ale nedáva zmysel, lebo zaškrtnutím dávam najavo, že nechcem aby sa isté veci inštalovali.
 

Keď som nainštaloval češtinu s plus možnosťou, tak mi v hre ukazuje, že mám verziu patchu 9.8 plus. Nebude sa to nejak biť s tým, že tá čeština má byť pre patch 9.7?

**Comment by miracleflame** [comment]
Prvý odstavec sa češtiny nijako netýka, to sú UP záležitosti.

Druhý:
ukázalo sa, že z nejakého dôvodu dva súbory z PlusCZ ušli FFdumpu, neviem vysvetliť ako.

zmeny sú marginálne:

- práve číslo verzie v gameui_english.txt

- +++ b/UP_Plus_CZ_fontfriendly/vdata/system/strings.txt
@@ -599,12 +599,12 @@ StringData
                        "Name25" "[p]redchozi"
                        "Name26" "[s]mazat"
                        "Name27" "[n]abidka"
-                       "Name28" "[q]uit"
+                       "Name28" "[k]onec"^M
                        "Name29" "Zpravy pro: "
                        "Name30" "e-mail"
                        "Name31" "Mate %d e-mailovych zprav, %d neprectenych"
-                       "Name32" "Pro skonceni prace zadejte 'quit' nebo stisknete 'ESC'"
-                       "Name33" "quit"
+                       "Name32" "Pro skonceni prace zadejte 'konec' nebo stisknete 'ESC'"^M
+                       "Name33" "konec"^M
                        "Name34" "?"        // help
                        "Name35" "vypis"
                        "Name36" "e-mail"

Neviem či to stojí za hotfix upload, podľa mňa ani nie, počkal by som na update na GOGu a riešil potom až 9.8

Samozrejme toto na repe opravím.
