### ISSUE TITLE
compile.cmd

### ISSUE THREAD

**Issue by kouccarter** [soulcharmer/gog_bloodlines_cz#404]
![compile-asi-bug1](https://user-images.githubusercontent.com/33968831/33224702-a1eb114e-d16c-11e7-8dab-bb2cfc681aa6.png)
+
![compile-asi-bug2](https://user-images.githubusercontent.com/33968831/33224709-a99ab7be-d16c-11e7-802c-cea92f909902.png)
Nedal sa mi vytvoriť inštalačný exe súbor pre hru, aj keď je cesta v compile.cmd zadaná správne. Príde mi to zvláštne :) , ale aspoň viem už (po asi dvoch hodinách skúšania) kam to NSIS mám vážne nainštalovať...

**Comment by miracleflame** [comment]
Vždy mi príde trochu úsmevné, keď koncový užívateľ predpokladá, že máme chybu v skriptoch, ktoré v priebehu vývoja používame tisíc razy. Nie, nemáme, funguje nám to a pre naše potreby to stačí.

Čeština pre koncového užívateľa je normálne k dispozícii na stiahnutie a nainštalovanie zo stránky prekladu na https://prekladyher.eu/preklady/vampire-the-masquerade-bloodlines.315/
a nevyžadujeme od nikoho, aby niečo kompiloval bez potrebných znalostí.

**Comment by kouccarter** [comment]
mne zas príde smutné že "stažení není k dispozici" práve z toho linku čo
ste mi uviedli a nemám žiadnu záruku že vážne sa to bude stiahnuť aj po
zaregistrovaní. Takže sa tam radšej neregistrujem a potrápil som sa s
Vašimi skriptami.

Takže normálne k dispozícii nie je (prikladám screeny).

2017-11-27 9:21 GMT+01:00 miracleflame <notifications@github.com>:

**Comment by miracleflame** [comment]
Celkový počet stažení:    111
Keď toto niekto nepovažuje za záruku a stále predpokladá, že to nefunguje, potom by sa nemal púštať do hľadania chýb inde, lebo určite ich nájde aj tam, kde nie sú - viď tento prípad.

Priložené screeny neevidujem.

**Comment by kouccarter** [comment]
takže stiahnuť bez registrácie ("normálne" ako napr. z "https://cestiny.idnes.cz/" alebo "
abcgames.sk" ) nie je normálne. Aspoň viem čo pre Vás znamená "normálne"
pán normálny.

2017-11-27 9:38 GMT+01:00 miracleflame <notifications@github.com>:
