### ISSUE TITLE
Cestina_VTMBup97.exe

### ISSUE THREAD

**Issue by kouccarter** [soulcharmer/gog_bloodlines_cz#405]
Hru mám vo verzii 9.8 a aj cestinu vo verzii 9.8 a aj tak mi v texte píše že sa jedná o 9.7 cestinu. Idem to nainstalovat a som zvedavy ako to bude kompatibilné.
![preco-9 7](https://user-images.githubusercontent.com/33968831/33228058-e179c15c-d1b2-11e7-89a0-6f618e492e36.png)

**Comment by miracleflame** [comment]
Prečítaj si diskusiu k prekladu na https://prekladyher.eu/preklady/vampire-the-masquerade-bloodlines.315/ a tam nájdeš k tomuto veľa dôležitých informácií.
