### ISSUE TITLE
UP_Plus/vdata/items/item_g_oh_diary.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#406]
Tak je to tady. :) Až by si si náhodou našiel tento víkend čas, budeme potrebovať preložiť tento textík. Bude toho časom viac, len som chcel rýchlo nájsť niečo na preklad, nech to kvôli mne nestojí.. keby náhodou. Dík.

"printname"	"Diary"
	"description"	"This is the charred remains of what looks like a diary:
			05/30/1958 - Just arrived here, at the Ocean House. We have a week-long holiday here in Santa Monica, and Ed has booked us a room for the hotel's grand opening. It's a wonderful place, almost magical. The children have been swimming all afternoon.
			05/31/1958 - The first two days have been almost perfect, except that Ed can't seem to stop asking about the locket I received from my mother. He seems to think it was sent to me by some other admirer. Ed can be sweet, but sometimes his jealousy can get the better of him. Hopefully he'll feel better tomorrow.
			06/01/1958 - Sun is out today, not a cloud in the sky. Ed seems a little on edge, keeps guessing as to who my \"new boyfriend\" is. Silly Ed.
			06/03/1958 - There was a picnic for the hotel guests this morning... quite a grand affair. Ed is in a dark mood. I don't know what I can do to reassure him that he is my one and only love. The only time he seemed to brighten up was when he was speaking to the groundskeeper. Boys and their tools....
			06/04/1958 - We only have two days left, and thank God we're finally going home. Ed won't speak to me or the children, and I've found him more than once in the bathroom holding the locket and staring at it. I'm afraid he's suffered some sort of breakdown. I've told him we can go home, but he just shakes his head. He won't look at me. I just want to go home.
			06/05/1958 - Ed left early this morning, and I haven't seem him since. If I haven't seen him in another hour, I'm going to call the hotel manager. Against my better wishes, Ed Jr. went to look for him downstairs in the basement. I'm going to send Tiffany down to fetch him, if... wait... someone is knocking at the door....
			Oh my God, Ed covered in blood... coming to kill me... locked myself in the bathroom... he's gone crazy... he keeps shouting we'll be together forever and he'll never let me go... someone please hel... (The writing trails off the end of the page.)"

**Comment by soulcharmer** [comment]
Hm, tohle ze je novy text?

Mozna mam deja vu nebo si to jen pletu se Shiningem, ktery jsem taky prekladal :-)



"printname" "Deník"
"description" "Toto jsou ohořelé zbytky starého deníku:
30.5. 1958 - Právě jsme dorazili do hotelu Ocean House. Máme tu v Santa Monice zaplacený týdenní pobyt a Ed zarezervoval apartmán u příležitosti slavnostního otevření hotelu. Je to nádherné místo, skoro magické. Děti se koupaly celé odpoledne.
31.5. 1958 - První dva dny byly téměř dokonalé až na to, že Ed se stále vyptává na medailón, který mám od matky. Kdo ví proč si myslí, že mi ho poslal nějaký nápadník. Ed je zlatíčko, ale někdy to s tou žárlivostí přehání. Snad ho to do zítřka přejde.
1.6. 1958 - Slunce svítí, nikde ani mráček. Ed vypadá podrážděně a snaží se uhodnout, kdo je ten můj "nový přítel". Hlupáček.
3.6. 1958 - Dnes ráno byl pro hosty hotelu společný piknik... velká událost. Ed má špatnou náladu. Nevím, jak ho mám přesvědčit, že on je má jediná láska. Jediné, co ho rozptýlilo, bylo, když se dal do řeči se správcem. Kluci a jejich hračky...
4.6. 1958 - Už zbývají jen dva dny a díky bohu, že jedeme domů. Ed už nemluví ani se mnou ani s dětmi a několikrát jsem ho přistihla, jak v koupelně zírá na ten medailón. Bojím se, že mu nějak přeskočilo. Řekla jsem mu, že můžeme jet domů, ale on jen kroutí hlavou. Ani se na mě nepodíval. Chci jet domů.
5.6. 1958 - Ed ráno odešel a od té doby jsem ho neviděla. Jestli se do hodiny nevrátí, volám řediteli hotelu. Proti mému přání ho šel Ed junior hledat dolů do sklepa. Pošlu pro něj Tiffany, jestli... někdo buší na dveře...
Proboha, Ed je od krve... chce mě zabít... zamkla jsem se v koupelně... zešílel... řve, že budeme navždy spolu a že mě nikdy neopustí... pomozte mi někd... (Tady rukopis končí.)"

**Comment by miracleflame** [comment]
Aj mi napadlo, že to, čo je tuná v Plus môže byť už dávno preložené v našom basic... a našiel som to... pozri a rozhodni, čo bude finálna verzia:

"printname"	"Deník"
	"description"	"Toto jsou ohořelé zbytky bývalého deníku:

			30. 5. 1958 - Právě jsme dorazili do hotelu Ocean House.  Přijeli jsme na týden do Santa Moniky a Ed zamluvil pokoj hned po slavnostním otevření hotelu.  Je to tady úžasné, téměř magické.  Děti byly celé odpoledne v bazénu.

			31. 5. 1958 - První dva dny byly skoro perfektní, až na to, že Ed se neustále vyptává na ten přívěsek, co mám od matky. Asi si myslí, že mi ho poslal nějaký ctitel.  Ed je sladký, ale někdy ho ta jeho žárlivost doslova ovládá. Snad se do zítřka umoudří.
			
			1. 6. 1958 - Dnes je slunečno, nebe je bez mráčku.  Ed je pořád nějak napjatý a snaží se hádat, kdo je ten můj tajný přítel. Hlupáček.
			
			3. 6. 1958 - Dnes byl pro hotelové hosty pořádán společný piknik... byla to velká akce.  Ed má doslova temnou náladu. Už nevím, co mám udělat, abych ho přesvědčila, že jen on je má jediná láska.  Jen když se bavil se správcem hotelu, vypadal, že je v pořádku. Holt kluci a jejich hračky...
			
			4. 6. 1958 - Už nám zbývají jen dva dny a díky bohu, že pojedeme domů. Ed nemluví ani se mnou ani s dětmi. Několikrát jsem ho přistihla v koupelně, jak na ten přívěsek civí. Bojím se, že snad prodělal nějaký duševní kolaps. Říkala jsem mu, že můžeme odjet dřív, ale on jen kroutí hlavou.  Ani se na mě nepodívá. Chci už odjet pryč.
			
			5. 6. 1958 - Ed brzo ráno někam odešel a od té doby se neukázal.  Jestli se do hodiny nevrátí, zavolám řediteli hotelu.  I když jsem nechtěla, Ed junior ho šel hledat dolů do suterénu.  Asi pro něj pošlu Tiffany... někdo klepe.

			Bože můj, Ed celý od krve mě přišel zabít jsem zamčená v koupelně musel zešílet pořád řve že budeme pořád spolu že mě nikomu nedá pomozte něk (na tomto místě text končí)."

**Comment by soulcharmer** [comment]
Ha, ja to tusil :-) Tak to jen pro priste vzdy zkontroluj predem, korektura je rychlejsi nez novy preklad.

Kazdopadne novy preklad je v mnoha ohledech lepsi, tak tady jsem udelal finalni merge:



"printname" "Deník"
"description" "Toto jsou ohořelé zbytky starého deníku:
30.5. 1958 - Právě jsme dorazili do hotelu Ocean House. Máme tu v Santa Monice zaplacený týdenní pobyt a Ed zarezervoval apartmán u příležitosti slavnostního otevření hotelu. Je to nádherné místo, skoro magické. Děti byly celé odpoledne v bazénu.
31.5. 1958 - První dva dny byly téměř dokonalé až na to, že Ed se stále vyptává na medailón, který mám od matky. Kdo ví proč si myslí, že mi ho poslal nějaký nápadník. Ed je zlatíčko, ale někdy to s tou žárlivostí přehání. Snad ho to do zítřka přejde.
1.6. 1958 - Slunce svítí, nikde ani mráček. Ed vypadá podrážděně a snaží se uhodnout, kdo je ten můj "nový přítel". Hlupáček.
3.6. 1958 - Dnes ráno byl pro hosty hotelu společný piknik... velká událost. Ed má špatnou náladu. Nevím, jak ho mám přesvědčit, že on je má jediná láska. Jediné, co ho rozptýlilo, bylo, když se dal do řeči se správcem. Holt kluci a jejich hračky...
4.6. 1958 - Už zbývají jen dva dny a díky bohu, že jedeme domů. Ed už nemluví ani se mnou ani s dětmi a několikrát jsem ho přistihla, jak v koupelně zírá na ten medailón. Bojím se, že mu nějak přeskočilo. Řekla jsem mu, že můžeme jet domů, ale on jen kroutí hlavou. Ani se na mě nepodíval. Chci už odjet pryč.
5.6. 1958 - Ed ráno odešel a od té doby jsem ho neviděla. Jestli se do hodiny nevrátí, volám řediteli hotelu. I když jsem nechtěla, Ed junior ho šel hledat dolů do suterénu. Pošlu pro něj Tiffany, jestli... někdo buší na dveře...
Proboha, Ed je od krve chce mě zabít jsem zamčená v koupelně, zešílel! řve, že budeme navždy spolu a že mě nikomu nedá pomozte mi někd (tady rukopis končí.)"


Diky

**Comment by miracleflame** [comment]
Musím sa ospravedlniť, mal som naponáhlo a chcel som sem už aspoň niečo dať. Už by sa to nemalo stať, pretože Plus súbory sú všetky aktualizované, takže ostávajú samotné Basic súbory.
