### ISSUE TITLE
Unofficial_Patch/dlg/chinatown/yukie.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#407]
{	421	}{	Namu...	}{	Namu...	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{	G.Yukie_Follow = 2	}{	}{	}{	}{	}{	}{	}{	}
{	422	}{	Co? Jo, dál už půjdu sám. Díky za pomoc.	}{	Co? Jo, dál už půjdu sama. Díky za pomoc.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Nerozuměno. Budu pokračovat bez tebe.	}
**{	423	}{	Wait! Ming is certainly hiding deep below the big temple. Can you open some magical hunter portal there to get me down?	}{	Wait! Ming is certainly hiding deep below the big temple. Can you open some magical hunter portal there to get me down?	}{	471	}{	Persuasion 10	}{	}{	}{	}{	}{	}{	}{	}{	Not yet. Can you open a hunter mumbo jumbo door at the big house to her lair below?	}**

{	471	}{	Ya Ta!	}{	Ya Ta!	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
**{	472	}{	Great, I'm curious what you can do.	}{	Great, I'm curious what you can do.	}{	0	}{	}{	G.Yukie_Shortcut = 1	}{	}{	}{	}{	}{	}{	}{	I wonder about your magic.	}**

**Comment by soulcharmer** [comment]
{ 423 }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys otevřít nějaký magický portál, který by mě tam dostal? }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys otevřít nějaký magický portál, který by mě tam dostal? }{ 471 }{ Persuasion 10 }{ }{ }{ }{ }{ }{ }{ }{ Ještě ne. Můžeš zprovoznit čáry máry dveře vedoucí do jejího doupěte pod velkým domem? }

{ 472 }{ Bezva, jsem zvědav, co dokážeš. }{ Bezva, jsem zvědavá, co dokážeš. }{ 0 }{ }{ G.Yukie_Shortcut = 1 }{ }{ }{ }{ }{ }{ }{ Tvá magie mě nemálo zajímá. }

**Comment by miracleflame** [comment]
dík
