### ISSUE TITLE
Unofficial_Patch/dlg/downtown la/chunk2.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#408]
**{	369	}{	Flee, mortal!	}{	Flee, mortal!	}{	0	}{	Presence 1 & G.Patch_Plus == 1	}{	G.Dialog_Presence = 1; dialogParticles(); G.Chunk_Run = 1	}{	}{	}{	}{	}{	}{	}{	}**

{	401	}{	Pokud neodejdete, tak... tak nemám na vybranou.	}{	Pokud neodejdete, tak... tak nemám na vybranou.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
**{	402	}{	Yes, you choose to die.	}{	Yes, you choose to die.	}{	0	}{	}{	G.Chunk_Attack = 1	}{	}{	}{	}{	}{	}{	}{ To die to die, this is the question.	}
{	403	}{	What if I just went to visit the roof and not LaCroix?	}{	What if I just went to visit the roof and not LaCroix?	}{	421	}{	Persuasion 10 & G.Patch_Plus == 1	}{	G.Chunk_Skip = 1	}{	}{	}{	}{	}{	}{	}{ But if my mind longed for a view from the roof instead?	}**

{	421	}{	No tak... asi to bude v pořádku. Jeďte nahoru. Páni, doufám, že mi za to nezabaví mou svítilnu.	}{	No tak... asi to bude v pořádku. Jeďte nahoru. Páni, doufám, že mi za to nezabaví mou svítilnu.	}{	#	}{	}{	G.Chunk_Open = 6	}{	}{	}{	}{	}{	}{	}{	}
**{	422	}{	Thanks!	}{	Thanks!	}{	0	}{	G.Chunk_Skip == 0	}{	}{	}{	}{	}{	}{	}{	}{	Thanks, thanks, thanks.	}
{	423	}{	Thanks!	}{	Thanks!	}{	0	}{	G.Chunk_Skip == 1	}{	G.Chunk_Skip = 2	}{	}{	}{	}{	}{	}{	}{	Thanks, thanks, thanks.	}**

**Comment by soulcharmer** [comment]
{ 369 }{ Utíkej, smrtelníku! }{ Utíkej, smrtelníku! }{ 0 }{ Presence 1 & G.Patch_Plus == 1 }{ G.Dialog_Presence = 1; dialogParticles(); G.Chunk_Run = 1 }{ }{ }{ }{ }{ }{ }{ }

{ 402 }{ Jo, vybíráš si smrt. }{ Jo, vybíráš si smrt. }{ 0 }{ }{ G.Chunk_Attack = 1 }{ }{ }{ }{ }{ }{ }{ Zemřít nebo zemřít, to není otázka. }
{ 403 }{ A co kdybych vyjel až na střechu a ne za LaCroixem? }{ A co kdybych vyjela až na střechu a ne za LaCroixem? }{ 421 }{ Persuasion 10 & G.Patch_Plus == 1 }{ G.Chunk_Skip = 1 }{ }{ }{ }{ }{ }{ }{ Ale co když se chci místo toho raději pokochat pohledem ze střechy? }

{ 422 }{ Díky! }{ Díky! }{ 0 }{ G.Chunk_Skip == 0 }{ }{ }{ }{ }{ }{ }{ }{ Dík, dík, dík. }
{ 423 }{ Díky! }{ Díky! }{ 0 }{ G.Chunk_Skip == 1 }{ G.Chunk_Skip = 2 }{ }{ }{ }{ }{ }{ }{ Dík, dík, dík. }

**Comment by miracleflame** [comment]
zámerne si nepreložil
this is the question.
ako
toť otázka
ale opačne ako zápor?

**Comment by soulcharmer** [comment]
jo, je to jeden z tech malkavianskych kecu, ktery je dobre nebrat doslova.

Shakepearovske 'zit nebo nezit'  se tu meni na 'nezit (tvou rukou) nebo nezit (prirozene)', protoze Chunk chce zautocit, coz pro malkaviana pochopitelne neni otazka :-)

Takze nakonec bych to upravil na tu shakepearovskou variantu:

**{ 402 }{ Jo, vybíráš si smrt. }{ Jo, vybíráš si smrt. }{ 0 }{ }{ G.Chunk_Attack = 1 }{ }{ }{ }{ }{ }{ }{ Nežít nebo nežít, to není otázka. }**

**Comment by miracleflame** [comment]
Detto sa klaniam prekladateľským schopnostiam, ktoré viditeľne nie sú iba o znalosti jazykov.
