### ISSUE TITLE
Unofficial_Patch/dlg/main characters/jack_tutorial.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#409]
{	883	}{	I'll see you there after I got a good day's sleep.	}{	I'll see you there after I got a good day's sleep.	}{	0	}{	G.Patch_Plus == 1	}{	G.Tut_Jack = 15	}{	}{	}{	}{	}{	}{	}{	We will be there after we close our eyes during the daylight.	}

{	933	}{	That's funny. I'll sleep the day off and laugh later. See ya.	}{	That's funny. I'll sleep the day off and laugh later. See ya.	}{	0	}{	G.Patch_Plus == 1	}{	LeaveTutorialShort(); pc.Bloodloss(1)	}{	}{	}{	}{	}{	}{	}{	Your humor is hokey. I am no longer here because I need to close my eyes when the sun shines.	}

ref:{	1032	}{	Moc vtipný. Měj se.	}{	Moc vtipný. Měj se.	}{	0	}{		}{	LeaveTutorialShort()	}{	}{	}{	}{	}{	}{	}{	Tvůj humor je k pláči. Já už tu nejsem.	}

{	1033	}{	That's funny. I'll sleep the day off and laugh later. See ya.	}{	That's funny. I'll sleep the day off and laugh later. See ya.	}{	0	}{	G.Patch_Plus == 1	}{	LeaveTutorialShort(); pc.Bloodloss(1)	}{	}{	}{	}{	}{	}{	}{	Your humor is hokey. I am no longer here because I will close my eyes when the sun shines.	}

**Comment by miracleflame** [comment]
{ 883 }{ Uvidíme se tam, až se přes den pořádně prospím. }{ Uvidíme se tam, až se přes den pořádně prospím.  }{ 0 }{ G.Patch_Plus == 1 }{ G.Tut_Jack = 15 }{ }{ }{ }{ }{ }{ }{ My přijdem až poté, co naše oči zůstanou zavřené před slunečním svitem. }

{ 933 }{ Moc vtipný. Budu se smát až prospím den. Měj se.  }{ Moc vtipný. Budu se smát až prospím den. Měj se.  }{ 0 }{ G.Patch_Plus == 1 }{ LeaveTutorialShort(); pc.Bloodloss(1) }{ }{ }{ }{ }{ }{ }{ Tvůj humor je k pláči. Já už tu nejsem, protože mé oči musí zůstat zavřené před slunečním svitem. }

{ 1033 }{ Moc vtipný. Budu se smát až prospím den. Měj se.  }{ Moc vtipný. Budu se smát až prospím den. Měj se.  }{ 0 }{ G.Patch_Plus == 1 }{ LeaveTutorialShort(); pc.Bloodloss(1) }{ }{ }{ }{ }{ }{ }{ Tvůj humor je k pláči. Já už tu nejsem, protože mé oči musí zůstat zavřené před slunečním svitem. }

**Comment by soulcharmer** [comment]
{ 883 }{ Potkáme se tam, až se pořádně vyspím. }{ Potkáme se tam, až se pořádně vyspím. }{ 0 }{ G.Patch_Plus == 1 }{ G.Tut_Jack = 15 }{ }{ }{ }{ }{ }{ }{ Budeme tam, až zavřeme oči přes den. }

{ 933 }{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ 0 }{ G.Patch_Plus == 1 }{ LeaveTutorialShort(); pc.Bloodloss(1) }{ }{ }{ }{ }{ }{ }{ Tvůj humor je podezřelý. Už zde nejsem, musím jít zavřít oči před sluncem. }

{ 1033 }{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ 0 }{ G.Patch_Plus == 1 }{ LeaveTutorialShort(); pc.Bloodloss(1) }{ }{ }{ }{ }{ }{ }{ Tvůj humor je podezřelý. Už zde nejsem, musím jít zavřít oči před sluncem. }
