### ISSUE TITLE
 Unofficial_Patch/dlg/santa monica/bertram.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#410]
{	157	}{	Pick me up at my haven after I sleep the day through and then we'll go.	}{	Pick me up at my haven after I sleep the day through and then we'll go.	}{	0	}{	not IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1	}{	G.Bertram_Ready = 2	}{	}{	}{	}{	}{	}{	}{	Light the way for me when I wake tomorrow evening, Your Dudeness.	}
{	158	}{	Pick me up at my haven after I sleep the day through and then we'll go.	}{	Pick me up at my haven after I sleep the day through and then we'll go.	}{	0	}{	IsClan(pc,"Nosferatu") and G.Bertram_Map == 1 and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1	}{	G.Bertram_Ready = 2	}{	}{	}{	}{	}{	}{	}{	}

{	466	}{	I'll have some questions for you when I get back. Pick me up at my haven after I sleep the day through and then we'll go.	}{	I'll have some questions for you when I get back. Pick me up at my haven after I sleep the day through and then we'll go.	}{	0	}{	G.Bertram_Map == 1 and IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1	}{	G.Bertram_Ready = 2	}{	}{	}{	}{	}{	}{	}{	}
{	467	}{	I'll have some questions for you when I get back. Pick me up at my haven after I sleep the day through and then we'll go.	}{	I'll have some questions for you when I get back. Pick me up at my haven after I sleep the day through and then we'll go.	}{	0	}{	not IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1	}{	G.Bertram_Ready = 2	}{	}{	}{	}{	}{	}{	}{	Light the way for me when I wake tomorrow evening, Your Dudeness.	}

**Comment by soulcharmer** [comment]
{ 157 }{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ not IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ Posviťte mi na cestu, až se probudím zítra večer, Vaše Kámošstvo. }
{ 158 }{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ IsClan(pc,"Nosferatu") and G.Bertram_Map == 1 and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ }

{ 466 }{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ G.Bertram_Map == 1 and IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ }
{ 467 }{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ not IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ Posviťte mi na cestu, až se probudím zítra večer, Vaše Kámošstvo. }
