### ISSUE TITLE
 Unofficial_Patch/dlg/santa monica/killer.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#411]
{	156	}{	Good. You should talk to Nines Rodriguez in the Last Round downtown.	}{	Good. You should talk to Nines Rodriguez in the Last Round downtown.	}{	0	}{	Humanity 5	& G.Patch_Plus == 1	}{	G.Killer_Nines = 1; G.Killer_Freed = 1; pc.SetQuest("Serial",9)	}{	}{	}{	}{	}{	}{	}{	Wonderful. Now go and talk to the ninth one downtown in the Last Round.	}

**Comment by soulcharmer** [comment]
{ 156 }{ Fajn. Měl bys dát řeč s Ninesem Rodriguezem v Poslední rundě v centru. }{ Fajn. Měl bys dát řeč s Ninesem Rodriguezem v Poslední rundě v centru. }{ 0 }{ Humanity 5 & G.Patch_Plus == 1 }{ G.Killer_Nines = 1; G.Killer_Freed = 1; pc.SetQuest("Serial",9) }{ }{ }{ }{ }{ }{ }{ Báječné. Nyní běž a promluv s devátým v Poslední rundě v centru. }

**Comment by miracleflame** [comment]
dík
