### ISSUE TITLE
Unofficial_Patch/dlg/santa monica/lily.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#412]
{	271	}{	Už jsem ti říkala, že žádné peníze nemám. A nemám ani nic jiného, co bych ti mohla dát. Proč mi to děláš?	}{	Už jsem ti říkala, že žádné peníze nemám. A nemám ani nic jiného, co bych ti mohla dát. Proč mi to děláš?	}{	#	}{	npc.SetDisposition("Sad", 2)	}{	G.Lily_Extort = 2	}{	}{	}{	}{	}{	}{	}{	}
**{	274	}{	Because money rules the world. Better cash your junk in then...	}{	Because money rules the world. Better cash your junk in then...	}{	0	}{	G.Patch_Plus == 1 and pc.HasItem("item_g_lilly_purse") and pc.HasItem("item_g_lilly_photo") and pc.HasItem("item_g_lilly_diary") and pc.HasItem("item_g_bailbond_receipt")	}{	pc.RemoveItem("item_g_lilly_purse"); pc.RemoveItem("item_g_lilly_photo"); pc.RemoveItem("item_g_lilly_diary"); pc.RemoveItem("item_g_bailbond_receipt")	}{	}{	}{	}{	}{	}{	}{	Because the green rules everything. Sell your trinkets to get some...	}**

**Comment by soulcharmer** [comment]
Tohle je trochu od boku, ale snad je to dobre

{ 274 }{ Protože prachy vládnou světu. Můžeš aspoň zpeněžit svý věci... }{ Protože prachy vládnou světu. Můžeš aspoň zpeněžit svý věci... }{ 0 }{ G.Patch_Plus == 1 and pc.HasItem("item_g_lilly_purse") and pc.HasItem("item_g_lilly_photo") and pc.HasItem("item_g_lilly_diary") and pc.HasItem("item_g_bailbond_receipt") }{ pc.RemoveItem("item_g_lilly_purse"); pc.RemoveItem("item_g_lilly_photo"); pc.RemoveItem("item_g_lilly_diary"); pc.RemoveItem("item_g_bailbond_receipt") }{ }{ }{ }{ }{ }{ }{ Protože zelená světem vládne. Prodej své tretky a také budeš mít... }

**Comment by miracleflame** [comment]
Better cash your junk in then...

toto by som na základe priloženého kontextu preložil skôr v takomto zmysle:
Takže raději naval prachy...

**Comment by soulcharmer** [comment]
prave kvuli kontextu jsem to tak prelozil.

"cash in" znamena 'prodat', coz je videt i v malkavianske replice.

zbytek radku rika, ze pokud mas Lilynu fotku, denik, kabelku a stvrzenku od kauce, tak je v ramci tento repliky predas  (pc.RemoveItem).

Takze neznam presny kontext dialogu, ale z toho, co mam, to vypada, ze takto je to spravne.

Kdyztak to zadej k otestovani.

Dik

**Comment by miracleflame** [comment]
Máš naprostou pravdu, až teraz som si to uvedomil, keď si na to upozornil. Musím uznať, že máš vážne nadštandardné prekladateľské schopnosti. 

Aplikujem všetky preklady naraz, až budeš hotový so zvyškom. Myslím, že jadro práce na celom update by bolo tým pádom hotovo. Následne dám rýchly test novo skompilovanej inštalačky na čistej poslednej verzii z GOGu a potom sa to môže dať testovať do verejnosti, lebo z 99%by to malo všetko fachať jak na predošlej verzii.
