### ISSUE TITLE
Unofficial_Patch/dlg/santa monica/thug.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#413]
{	2	}{	Do toho tě nic není, věř mi.	}{	Do toho tě nic není, věř mi.	}{	11	}{	Persuasion 4	}{		}{	}{	}{	}{	}{	}{	}{	Tvůj mozek to nepotřebuje vědět.	}
{	3	}{	Chceš mě snad zastavit?	}{	Chceš mě snad zastavit?	}{	31	}{	Intimidate 4	}{		}{	}{	}{	}{	}{	}{	}{	Teď mě nezastavuj, dobře se bavím!	}
{	4	}{	Neopovažuj se mi vyhrožovat, smrtelníku!	}{	Neopovažuj se mi vyhrožovat, smrtelníku!	}{	31	}{	Presence 1 & G.Patch_Plus == 1	}{	G.Dialog_Presence = 1; dialogParticles()	}{	}{	}{	}{	}{	}{	}{		}

{	2	}{	It's not important to you and your conspicious friends. Or shall I call the cops before something happens?	}{	It's not important to you and your conspicious friends. Or shall I call the cops before something happens?	}{	11	}{	Persuasion 4	}{	}{	}{	}{	}{	}{	}{	}{	Your brain does not need to know, or should I ask the doughnut-eaters to come?	}
{	3	}{	You guys look like you are out for trouble. You better not start any with me!	}{	You guys look like you are out for trouble. You better not start any with me!	}{	31	}{	Intimidate 4	}{	}{	}{	}{	}{	}{	}{	}{	Don't stop me now, I'm having such a good time!	}
{	4	}{	Don't you dare talk to me like that, mortal!	}{	Don't you dare talk to me like that, mortal!	}{	31	}{	Presence 1 & G.Patch_Plus == 1	}{	G.Dialog_Presence = 1; dialogParticles()	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
{ 2 }{ Do toho tobě ani tvým kámošům nic není. Nebo mám zavolat fízly, než se něco stane? }{ Do toho tobě ani tvým kámošům nic není. Nebo mám zavolat fízly, než se něco stane? }{ 11 }{ Persuasion 4 }{ }{ }{ }{ }{ }{ }{ }{ Tvůj mozek to nepotřebuje vědět. Nebo mám požádat koblihožrouty o příjezd? }
{ 3 }{ Vypadá to, že vaše banda si o něco koleduje. Vyserte se na to! }{ Vypadá to, že vaše banda si o něco koleduje. Vyserte se na to! }{ 31 }{ Intimidate 4 }{ }{ }{ }{ }{ }{ }{ }{ Teď mě nezastavuj, náramně se bavím! }
{ 4 }{ Neopovažuj se mi vyhrožovat, smrtelníku! }{ Neopovažuj se mi vyhrožovat, smrtelníku! }{ 31 }{ Presence 1 & G.Patch_Plus == 1 }{ G.Dialog_Presence = 1; dialogParticles() }{ }{ }{ }{ }{ }{ }{ }

**Comment by miracleflame** [comment]
dík
