### ISSUE TITLE
 Unofficial_Patch/vdata/system/histories000.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#414]
"Name"				"Homosexual"
			"Description"			"You always found your own gender much more attractive than the other sex, although many people still have issues dealing with this. Maybe vampiric society is different..."
			"ShortDescription"		"Start as a homosexual."

"Description" "Po uchvácení se bestie v tvém nitru přirozeně sladila s tvým tělem a tato afinita je patrná na první pohled. Snadněji se učíš Zvířeckosti, avšak ostatní, zvláště smrtelníci, tě budou vnímat s odporem."
			Výhody: Zvyšování Zvířeckosti stojí méně bodů

**Comment by miracleflame** [comment]
"Name"				"Homosexuál"
		"Description"			"Vždy tě stejné pohlaví přitahovalo mnohem více než to opačné i přesto, že se s tím mnozí těžce vyrovnávají. Možná, že to bude ve společnosti upíru jiné..."
		"ShortDescription"		"Začínáš s homosexuální orientací."

To druhé, prosím, iba skontroluj:

predtým
"Description" "Po uchvácení se bestie v tvém nitru přirozeně sladila s tvým tělem a tato afinita je patrná na první pohled. Začínáš s jedním bodem navíc ve Zvířeckosti, avšak ostatní, zvláště smrtelníci, tě budou vnímat s odporem."
Výhody: +1 do Zvířeckosti

potom
"Description" "Po uchvácení se bestie v tvém nitru přirozeně sladila s tvým tělem a tato afinita je patrná na první pohled. Snadněji se učíš Zvířeckosti, avšak ostatní, zvláště smrtelníci, tě budou vnímat s odporem."
Výhody: Zvyšování Zvířeckosti stojí méně bodů

**Comment by soulcharmer** [comment]
"Homosexual"
		"Description"			"You always found your own gender much more attractive than the other sex, although many people still have issues dealing with this. Maybe vampiric society is different..."
		"ShortDescription"		"Start as a homosexual."

"Homosexuál"
"Lidé tvého pohlaví tě vždy přitahovali více než ti ostatní, i když mnozí s tím stále mají problém. Možná to bude ve společnosti vampírů jiné..."
"Začínáš s homosexuální orientací."



potom
"Description" "Po uchvácení se bestie v tvém nitru přirozeně sladila s tvým tělem a tato afinita je patrná na první pohled. Snadněji se učíš Zvířeckosti, avšak ostatní, zvláště smrtelníci, tě budou vnímat s odporem."
Výhody: Zvyšování Zvířeckosti stojí méně bodů

^ v poradku
