### ISSUE TITLE
Unofficial_Patch/vdata/signs/tutorial_popup.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#415]
"Text"		"                       Warning!
It seems as if an important Python script has not been compiled correctly on your system!
You are probably playing inside a Linux Wine environment without the loader-linux script.
Please exit the game and find it in the main game directory. Modify it to fit your setup!"

**Comment by soulcharmer** [comment]
"Text"		"Varování!

Zdá se, že jeden důležitý pythonovský skript se na vašem systému nezkompiloval správně!
Zřejmě hrajete v prostředí Linux Wine bez skriptu 'loader-linux'.
Ukončete prosím hru a najděte tento skript v hlavním adresáři hry. Pak skript upravte, aby fungoval správně!"
