### ISSUE TITLE
Unofficial_Patch/vdata/signs/jump_note.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#416]
"Text"		"Just  jump  and  you  will  land  near  our  shore.  For  when  you  want  to sneak  inside  without  good  old  Gary  noticing  you  ;)!  -m1tn1ck
P.S.:  I  hope  you  didn't  get  hurt  too  much  by  the  bug-stopper  I  set  up."

**Comment by miracleflame** [comment]
Jen skoč a přistaneš poblíž našeho břehu. To pro případ, že se chceš dostat dovnitř bez Garyho povšimnutí  ;)! -m1tn1ck"

P.S.: Doufám, že ti má nastřežená pastička příliš neublížila."

**Comment by soulcharmer** [comment]
drobna oprava :

Jen skoč a přistaneš poblíž našeho břehu. To pro případ, že se budeš chtít dostat dovnitř, aniž by tě starouš Gary zmerčil  ;)! -m1tn1ck

P.S.: Doufám, že ti má nastražená pastička moc neublížila.
