### ISSUE TITLE
 Unofficial_Patch/vdata/hackterminals/scott_laptop.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#417]
"runtext" "Když jsem dělal na jednom dějepisném projektu ve veřejné knihovně, všiml jsem si, jak někdo z Lasombry jde do oddělení s uměním. Šel jsem za ním neviditelný, ale místnost byla prázdná! Počkal jsem, dokud nevyšel ven a sledoval jsem ho až do kanalizace vstupem, který sám používám. On pak nedaleko vylezl do ulic a navštívil několik klubů."
			**"runtext"	"Beckett asked me to research into an ancient sarcophagus in the LA public library. During one of my nightly sessions I noticed another vampire sneaking around who looked like a Lasombra to me. Luckily I recently learned Obfuscate and so could avoid being spotted. Curious about what he was doing here in LA and whether it's about our coffin I'll shadow him the next few days."**

			"runtext"	"Dnes šel ten z Lasombry do starého domu v centru s červeným symbolem. Po chvíli jsem šel za ním, ale byl tam jen jeden černoch, co se mě ptal, jestli jsem osvícen. Odešel jsem a po nějaké době se opět objevil ten princův agent. Brzy poté ten černoch v panice vyběhnul a schoval se v kanálech, kde jsem ho ztratil."
			**"runtext"	"First the Lasombra went into this old house downtown showing a red symbol. I followed him in after a while, but only found a black guy who asked if I'd been enlightened. I left and some time later the new agent of the prince entered that building. Soon after the black guy ran out in panic and climbed down into the sewers where I lost him."**

			"runtext"	"Sledoval jsem toho z Lasombry taxíkem do Santa Moniky. Tam jsem viděl, jak jde na staré vrakoviště, asi se pobavit s kaitifem, co tam bydlí. Než jsem se na něco zmohl, dorazil ten nový princův agent a ten z Lasombry se z ničeho nic teleportoval rovnou za mě! Doufám, že mě nezpozoroval. Znovu si vzal taxík zpátky do centra, někam do svého doupěte v knihovně."
			**"runtext"	"In Santa Monica I watched how the Lasombra entered the old junkyard, probably to talk with the Caitiff living there. Before I could do something about it, the new agent of the prince arrived and suddenly the Lasombra teleported behind me! I hope I wasn't spotted. Then he took a cab back to the LA library."**

			"runtext"	"Z toho, co jsem viděl, vyvozuju, že ten z Lasombry se snaží rekrutovat vampíry a ghúly, aby doplnil stavy tupých Sabbatů na odstřel. Řekl bych, že toho kaitifa nepřesvědčil, u toho černocha těžko říct. Ten nový princ se mi nelíbí, ale doslechl jsem se, že Beckett z mého klanu je ve městě. Je to učenec, všechno mu řeknu!"
			**"runtext"	"I suspect that the Lasombra tries to recruit vampires or ghouls to compliment the usual Sabbat cannon fodder. I'm pretty sure he failed turning the Caitiff, I don't know about the black guy. This doesn't affect the sarcophagus thing, but I still got a bad feeling with him always returning to the library. As I'm not a fighter myself I will contact and ask Beckett about it."**

**Comment by soulcharmer** [comment]
"Beckett chtěl, ať nastuduju jakýsi starověký sarkofág ve veřejné knihovně. Když jsem tam jednou v noci četl, všiml jsem si jiného vampíra, co vypadal, že je z Lasombry. Naštěstí jsem se nedávno naučil Mizení, to se bude hodit. Zajímá mě, co pohledává v LA a jestli se to týká té naší rakve, takže ho budu pár dní sledovat."

"Dnes šel ten z Lasombry do starého domu v centru s červeným symbolem. Po chvíli jsem šel za ním, ale byl tam jen jeden černoch, co se mě ptal, jestli jsem byl osvícen. Odešel jsem a po nějaké době se opět objevil ten princův agent. Brzy poté ten černoch v panice vyběhnul a schoval se v kanálech, kde jsem ho ztratil."

"V Santa Monice jsem sledoval, jak ten Lasombra jde na staré vrakoviště, asi se pobavit s kaitifem, co tam bydlí. Než jsem se na něco zmohl, dorazil ten nový princův agent a ten Lasombra se z ničeho nic teleportoval rovnou za mě! Doufám, že mě nezpozoroval. Pak si vzal taxík zpátky do veřejné knihovny."

"Mám podezření, že ten Lasombra se snaží rekrutovat vampíry nebo ghúly, aby doplnil stavy tupých Sabbatů na odstřel. Řekl bych, že toho kaitifa nepřesvědčil, u toho černocha těžko říct. Nemá to nic společného s tím sarkofágem, ale nechce se mi líbít, že se pokaždé vrací do té knihovny. Nejsem žádný bijec, takže rovnou všechno řeknu Beckettovi."
