### ISSUE TITLE
Unofficial_Patch/vdata/hackterminals/haven_pc.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#418]
"body"	"Zdravím tě mládě, můj přítel, Gangrel jménem Scott, má podezření, že tady v L.A. verbuje Lasombra našince pro Sabbaty. Prý ho viděl zmizet ve veřejné knihovně LA! Já mám teď jiné povinnosti, tak se s ním sejdi, prosím tě, v santamonickém obchodě s kuřivem a zjisti podrobnosti. Přece nechceme, aby se něco přihodilo našim vzácným moudrostem, ne? 
Beckett"
		**"body"	"Hello young one, a fellow Gangrel named Scott, who was doing some research for me in the LA public library on our infamous coffin, noticed a Lasombra there! As I'm preoccupied right now, please meet him in my stead at the Smoke Shop in Santa Monica to learn about the details. After all, Sabbat always means trouble and we wouldn't want anything bad happening to all the precious knowledge, now would we? 
Beckett"**

		"body"	"Opět zdravím... můj přítel mi zdělil, že se ti v knihovně podařilo přerušit jeden Sabbatský přijímací rituál, při kterém téměř zahynul. Postará se o to, aby se něco takového už nemohlo opakovat. Snad není zapotřebí zdůrazňovat, že by nebylo moudré někomu o této nepříjemnosti vykládat.
		**"body"	"Hello again... my friend told me that you interrupted the Sabbat test proceedings at the library which almost got him killed. He will remove the access to that ritual chamber so it won't happen again. Needless to stress that it might not be very astute to tell anyone about this short affair.**

**Comment by miracleflame** [comment]
Som skúsil:

"Zdravím tě mládě. Můj přítel, Gangrel jménem Scott, prováděl v místní veřejné knihovně studii ohledem naší slavné rakve, když tam zahlédl někoho z Lasombry. Já mám teď jiné povinnosti, tak se s ním sejdi, prosím tě, v santamonickém obchodě s kuřivem a zjisti podrobnosti. Přece jenom Sabbati jdou ruka v ruce s trablema a my nechceme, aby se něco přihodilo našim vzácným moudrostem, ne?"

"Opět zdravím... můj přítel mi zdělil, že se ti v knihovně podařilo přerušit zkoušku Sabbatského přijímacího rituálu, při kterém téměř zahynul. Postará se o to, aby se něco takového už nemohlo opakovat a zamezí přístup do oné kaple. Snad není zapotřebí zdůrazňovat, že by nebylo moudré někomu o této nepříjemnosti vykládat."

**Comment by soulcharmer** [comment]
"body"	"Zdravím tě, mládě. Můj kolega Gangrel jménem Scott, který pro mě dělal ve veřejné knihovně výzkum ohledně toho nechvalně známého sarkofágu, si tam všimnul někoho z Lasombry! Jelikož jsem momentálně zaneprázdněn, sejdi se s ním prosím místo mě v santamonickém obchodě s kuřivem a zjisti podrobnosti. Přitomnost Sabbatu je ostatně vždy problém a nechceme přece, aby se naše vzácné znalosti dostaly do nesprávných rukou, není-liž pravda?"

"body"	"Opět zdravím... můj kolega mi sdělil, že se ti v knihovně podařilo přerušit sabbatský přijímací rituál, při kterém téměř zahynul. Nyní znepřístupní tu rituální místnost, aby se něco takového už nemohlo opakovat. Snad není zapotřebí zdůrazňovat, že by nebylo moudré se někomu o této nepříjemnosti zpovídat."
