### ISSUE TITLE
Unofficial_Patch/vdata/hackterminals/asianvamp_laptop.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#419]
"runtext"	"Zdá se, že jsem k sobě upoutal pozornost jednoho nováčka, princova agenta. Není mi známo, kdo to je, ale má mnohem více schopností než většina Kainitů, na které jsem dosud narazil. Pro jistotu se připravím pro případ, že se naše cesty zkříží."
//			"runtext"	"Agent, o kterém již byla řeč objevil mrtvolu Virgila Crumba. Střet se zdá být nevyhnutelný. Pokud nevyváznu živ, nechť má poslední zpráva jasně uvádí, že Santa Monika je zralá k podmanění. Pokud přijdeme ve větším počtu, narazíme pouze na slabý odpor."

			**"runtext"	"I have drawn the attention of a newcomer, an agent of the prince, who has discovered the corpse of Virgil Crumb. I know very little about this individual, but they seem much more resourceful than most Cainites I have observed. I will prepare myself in the event that our paths cross because an altercation seems imminent. If I do not survive, let my last report state that Santa Monica is ripe for the taking. We'll find little resistance if we come in force."**

**Comment by soulcharmer** [comment]
Upoutal jsem pozornost jednoho nováčka, princova agenta, který objevil mrtvolu Virgila Crumba.  Není mi známo, kdo to je, ale je mnohem schopnější než většina Kainitů, na které jsem dosud narazil. Připravím se pro případ, že se naše cesty zkříží, protože střet se zdá být nevyhnutelný. Pokud to nepřežiju, nechť je má poslední zpráva jasná: Santa Monika je zralá k podmanění. Pokud přijdeme ve větším počtu, narazíme pouze na slabý odpor."
