### ISSUE TITLE
"Přeskočit intro" sa nezmestí v rozlíšení 1440p

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#42]
[ukážka](https://snag.gy/ctQAPa.jpg)

Riešením by bolo použiť preklad s menším počtom znakov ako napr. "Žádné Intro" alebo "Vynech Intro" - tento počet znakov som testoval a pasuje tam.

Rozhodni

**Comment by soulcharmer** [comment]
neslo by "Přeskoč intro"  :)?

**Comment by miracleflame** [comment]
"Přeskoč intro" sa tiež nezmestí.

**Comment by soulcharmer** [comment]
v tom pripade "Vynech intro" . Diky

**Comment by miracleflame** [comment]
implementované
