### ISSUE TITLE
item_g_oh_diary mindfuck

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#421]
UP_Plus\vdata\items\item_g_oh_diary.txt
Funguje bezproblémovo

UP_Plus_CZ\vdata\items\item_g_oh_diary.txt
Nefunguje. Predmet ani neukazuje ikonu v GUI, keď je frobbed. Zobrazí sa hláška Nová věc v inventáři: **Deník**
V inventári nič nepribudne.

UP_Plus_CZ_fontfriendly\vdata\items\item_g_oh_diary.txt
Nefunguje. Predmet ani neukazuje ikonu v GUI, keď je frobbed. Zobrazí sa hláška Nová věc v inventáři: **Den**
V inventári nič nepribudne.

Jediné, v čom sa súbory líšia je samotný preklad sekcií "printname" a "description", všetky úvodzovky sedia správne aj na začiatku aj na konci.

FF zobrazuje Den a nie Deník preto, lebo UP_Plus_CZ\vdata\items\item_g_oh_diary.txt je nejakým zázrakom v ANSI a nie UTF-8. Ale bez ohľadu na to, či je súbor ANSI a či UTF-8 stále je rozbitá samotná ikona a predmet v inverntári ako taký. Nechápem.

**Comment by miracleflame** [comment]
Tak som na to kápol. V preložených textoch vdata sa nesmú len tak používať úvodzovky ako v tomto prípade
`_snaží se uhodnout, kdo je ten můj "nový přítel"._`
na použitie úvodzoviek v texte je potrebné zadávať to v podobe
`_snaží se uhodnout, kdo je ten můj \"nový přítel\"._`

Ktovie koľko takých chýb máme v iných vdata súboroch... skúsim to prečesať...

**Comment by soulcharmer** [comment]
Zkusil bych nejaky hex editor a srovnat v nem soubory byte po bytu.

Edit: Oops, editoval jsem starou verzi tiketu :) Mozna hex editor pomuze jinde, escapovani znaku a podivne kodovani obvykle delaji problemy.
