### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#422]
Ahoj Marteen, Honzo

to je doba, čo? Možno ste si všimli, že preklad češtiny sa chce posunúť na verziu 10.0.
Je tam zopár konkrétnych vecí, ktoré treba otestovať, nie komplet celú hru. Len pár konkrétnych detailov, ktoré by som popísal do tiketu aj s príkazmi do konzoly, ako sa k danej veci rýchlo dostať.

Bohužial ja nemám moc čas a ani chuť priamo v hre niečo testovať. Je to paradoxné, ale cítim k tomu nejakú averziu. Radšej budem uvažovať a písať mimo hry, upravovať kód.

Našli by ste si vy k tomu chuť a čas? V minulosti ste na testoch hodne mákli a pomohli, verím že lepšie než by som to dal ja. Môj úplne hrubý odhad je, že by do toho bolo treba investovať možno tak 6 hodín času v hre všehovšudy. Je to smiešne, ale mne to príde tak moc, že nemám ani odvahu sa do toho pustiť.

Keby aj nie, ostávam s pozdravom

Mirek

**Comment by maarten93** [comment]
Ahoj, rád pomůžu s testováním, pošly mi co vše budeš potřebovat a já se na to kouknu, nevím kolik budu mít v týdnu času, ale o víkendu hlavně v neděli budu mít víc času.

**Comment by miracleflame** [comment]
Maarten,
oceňujem takú ochotu, je to velice fajn pocit, hneď tomu sám začínam venovať viac pozornosti. Díky moc.

Už si nepamätám, akým spôsobom si vy synchronizujete repo na kompliovanie najnovšej inštalačky, ale je potrebné prepnúť si to na branch UP10.0 a spúšťať Instalator\compile.cmd odtiaľ. Keby náhodou, aktuálnu inštalačku som uploadol tu
[https://drive.google.com/file/d/1xHv20VsEFbK5FxPUs7JzYBJ1cizGbFg6/view?usp=drive_web]

Úlohy budú formou tiketov.

**Comment by miracleflame** [comment]
A s touto poznámkou zatvorím aj toto.

...takže v GitHube dáš vľavo hore to plusko, iba šípku vedľa rozklikneš a vybereš CLONE, soulcharmer\gog_bloodlines_cz
vyberieš si kam to chceš stiahnuť, to je na tebe...
počkáš až to doťahá...
hore prepneš master na UP10.0
klikneš na tlačítko View branch
a potom tlačítko Sync
a to by malo byť celé, aktuálnu vec máš tam, kde si ju dal stiahnuť..
inštalačku si kompiluješ cez Instalator\compile.cmd

zakaždým, keď urobím dump opráv, treba si to znovu Syncnúť a skompilovať novú inštalačku, alebo len vybrať potrebné súbory z fontfriendly foldra.
