### ISSUE TITLE
Bezdomovec žádá o almužnu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#424]
Při testování, historie za Toreadora ženu jsem narazil na tohle, je to když se poprvé vyleze z bytu do Santa Monica, ta mě bezdomovec žádá o almužnu a nedostanu vůbec na výběr jestli mu jí dám nebo ne, rovnou mi to strhne peníze a objeví se tohle.  

https://snag.gy/SFtrMR.jpg

**Comment by Honzixx** [comment]
Děje se mi to taky. U všech klanů, nezávisle na pohlaví. Taky jsem si všimnul, že i za ženu mě bezdomovec oslovuje jako muže. Za malkaviánku nemluví vůbec.

**Comment by miracleflame** [comment]
Ty vole, keď vidím, čo sa tu nakopilo, mám dojem, že plnohodnotný test celej hry by tomu nezaškodil :{

**Comment by miracleflame** [comment]
Bolo to tam dosť rozhasené, ani nechápem, kedy k tomu došlo. Fixol som to v branchi UP10.0
Skúste si to syncnúť a otestovať opravu.

**Comment by Honzixx** [comment]
Už je to ok, testoval jsem dva muže a dvě ženy. Možno zavřít ;-)
