### ISSUE TITLE
DLG Romero

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#426]
Táto úloha sa pomerne ťažko zadáva a ešte ťažšie testuje so 100% istotou.

Ide o nové úpravy v dialógoch a skriptoch v nich. 

Najprehľadnejšie to môžete vidieť tu:
https://github.com/soulcharmer/gog_bloodlines_cz/commit/0d8923daacb4dc59dafe232baa3eda701f047703#diff-44d3167242b358972aaa09eded943fa1

...ako mená postáv tak aj konkrétne dialógy, čo sa upravili.

Treba sa pochopiteľne presunúť k danej postave a možnože aj prepnúť stav nejakého skriptu, aby bola daná replika v ponuke. Dám príklad Romero

Romero

Je na mape (map hw_cemetery_1)
noclip pomôže k pohybu vzdušnou čiarou
niekedy treba zmeniť stav príbehu na nejakú pokročilejšiu hodnotu 0-99, v prípade Romera netreba.
inak do konzoly stačí napísať
G.Story_State=## (požadovaná hodnota a na veľkosti písmen presne záleží)

Tu je zoznam quest hodnôt v pohybe príbehom:
-6   Started New Game.
-5   Character Creation.
-4   During opening cinematic, added by wesp.
-3   During tutorial.
-2   Tutorial done, transition to haven.
-1   Entered haven.
0   Entered Santa Monica.
1   Convinced Trip to sell you guns.
2   Showing Elysium tip for the first time (temporary).
3   Showing combat tip for the first time (temporary).
5   Spoke with Beckett at warehouse.
10   Entered downtown.
15   Elizabeth Dane completed.
20   Spoke with Bach at Grout's mansion.
25   Spoke with Prince after Grout's mansion.
30   Spoke with Beckett at museum.
35   Spoke with Prince after museum.
40   Spoke with the Tzimisce, added by wesp.
45   Spoke with Gary.
50   Mandarin started experiments.
55   Rescued Barabus.
60   Spoke with Chang brothers, added by wesp.
65   Spoke with Prince after Giovanni mansion.
70   Spoke with Johansen.
75   Spoke with Prince after Leopold Society.
80   Spoke with Ming-Xiao after Hallowbrook.
85   Spoke with Prince about Ming-Xiao.
90   Spoke with Jack after Griffith park.
95   Spoke with endgame cabbie.
100   Cabbie takes you to Chinatown (Kuei-Jin ending).
105   Cabbie takes you to Chinatown (Sabbat ending), added by wesp.
110   Cabbie takes you to Prince (Prince ending).
115   Cabbie takes you to Anarchs (Anarch ending).
120   Cabbie takes you to Chantry (Camarilla ending).
125   Cabbie takes you to Chinatown (Solo ending).

Prepínačov existuje viac druhov a prepínajú sa obvykle v rámci dialógov alebo nejakých prepínačov na mape. Ale z hlavy ich neviem.

Takže Romero

Replika 132 má podmienku IsClan(pc,"Malkavian" and G.Player_Homo == 0 to znamená, že hráč musí byť Malkavian (a žena bola podmienená už v replike predtým) a zároveň má históriu Homosexuál. Keď sa táto replika použije, nastaví sa prepínač G.Romero_Crush = 0 čo znamená, že ho prejde chuť.
Replika 135 má podmienku len homosexualitu a ide o zahováranie.

Barabus - podmienka bola predtým iba na Počítače (Computer -5), teraz je to zmenené na celkovú hodnotu Hacking, ktorá sa počíta aj z Počítačov aj z Chytrosti, či jak je to preložené (pc.CalcFeat("Hacking") < 6). Myslím, že netreba testovať.

Ďalšie dialógy dám ako osobitné tikety, nech toho nie je veľa natlačeného v jednom a nech sa to lepšie fajkuje.

**Comment by maarten93** [comment]
Zkoušel jsem pomocí map hw_cemetery_1 se dostat rovnou k Romerovy , ale když to udělám tak se mi změní pohlaví na postavě a zmizí historie homosexuál.

**Comment by maarten93** [comment]
Tak jsem to vyřešil pomocí vgender_int (0-1) se změní pohlaví 
vhistories - zobrazí seznam kodů historií
vhistory nn - nastaví historii místo nn kód historie.

**Comment by maarten93** [comment]
bohužel už nemám čas to testovat.

**Comment by miracleflame** [comment]
No to snáď neni pravda! To bude každá jedna nová vec pošahaná? Dobre, toto som otestoval, bolo to rozbité a fixol som to.

@maarten93 díky za dobré tipy. Rozpíšem tu, ako sa táto vec dá pomocou konzoly otestovať behom 3 minút, ale prísť na to trvá o niečo dlhšie ))) ale verím, že je to len vec cviku a tie ďalšie už pôjdu autopilotom:

map hw_cemetery_1
giftxp 99
vclan 4 (vclans vypíše všetky možnosti)
vgender_int 0
vhistory nemeníme, lebo podmienka je v skutočnosti, že NESMIE byť homosexuál (moja chyba)
ešte si treba dať bod do Vzhledu a stačí nakráčať k Romerovi
dialógové možnosti 2 1 2 1
