### ISSUE TITLE
DLG Yukie

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#427]
{	423 }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys otevřít nějaký magický portál, který by mě tam dostal? }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys otevřít nějaký magický portál, který by mě tam dostal? }{ 471 }{ Persuasion 10 }{ }{ }{ }{ }{ }{ }{ }{ Ještě ne. Můžeš zprovoznit čáry máry dveře vedoucí do jejího doupěte pod velkým domem? }

{	472 }{ Bezva, jsem zvědav, co dokážeš. }{ Bezva, jsem zvědavá, co dokážeš. }{ 0 }{ }{ G.Yukie_Shortcut = 1 }{ }{ }{ }{ }{ }{ }{ Tvá magie mě nemálo zajímá. }

Skúšal som s tým vychcať takto

map ch_ramen_1
noclip
giftxp 99
G.Yukie_Follow=1
G.Story_State=100
a dať si Přesvědčování 10

Dialóg prebehol, ibaže sa nič zvláštne nestalo... myslím, že je potrebné, aby Yukie bola niekde v chráme ku koncu hry. Pamätá si to niekto, kde presne by mala byť a za akých okolností?

ešte by mala mať niekde aj novú floating hlášku
"Ya Ta! (Dobře)"

**Comment by maarten93** [comment]
Už je to dlouho co jsem to hrál, ale pokud si pamatuji tak portál k Ming otevírá hráč umístěním soch na příslušné podstavce a Yukii si tam vůbec nepamatuji. Je možné že je to přidáno nově. Čas na testování budu mít snad zítra, teď mám v práci dlouhý týden noční a ještě ve čtvrtek jdu na přes čas, ve středu mám volno, ale musím si zařídit několik věcí, tak snad potom se k tomu dostanu.

**Comment by maarten93** [comment]
tady je ještě video https://www.youtube.com/watch?v=nfVW6Gk339Y od času 21:00 se otevírá portál

**Comment by Honzixx** [comment]
Youkie tam byla, myslím přes nějaký vedlejší quest a pak byla možnost si ji vzít před chrámem na pomoc, když se šlo na Ming. Já budu moct testovat asi až po víkendu, ale myslím, že mám doma savy, kdy jsem tam Yukie měl, tak to klidně vezmu já. Tato situace k testu bude před otevřením toho portálu hluboko v chrámu.

**Comment by maarten93** [comment]
https://forums.planetvampire.com/bloodlines-tech-support/yukie's-shortcut-during-'ming-must-die!'-isn't-working/msg137386/#msg137386

tak je to přidáno asi až v pachti 9.9 a má to asi sloužit jako zkratka k ming po té co jsou pozabíjeni stráže venku před chrámem.

**Comment by miracleflame** [comment]
Je dosť možné, že táto fíčura je záležitosťou novej mapy, takže pri použití sejvu je potrebné mať na pamäti, že mapa, na ktorej sa to deje, nesmie byť v sejve ešte načítaná.

Inak by som dal tomu nízku prioritu, lebo šanca, že by to nefungovalo s našim dlg je mizivá, dialóg ako taký mi prebehol.. (ale nechcem  to zavrhnúť úplne, lebo čo sa týka tohto updatu, vážne všetko rad radom je domrdané, čo som testoval).

**Comment by Honzixx** [comment]
Tak to funguje, dostal jsem se k tomu a Yukie vytvoří portál ještě před vstupem do chrámu (zkratka). 
Jediná hláška Ya Ta! je na konci tohoto dialogu a ne floating (obr. 2) a ani v souboru Yukie.dlg jsem nenašel zmínku o floating hlášce Ya Ta! (pokud to není v jiném souboru).
https://snag.gy/IpRPi1.jpg
https://snag.gy/oaeIE1.jpg
https://snag.gy/PRBt7n.jpg

**Comment by miracleflame** [comment]
Výborné. Díky.
