### ISSUE TITLE
downtown la/chunk2.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#428]
{	369	}{ Utíkej, smrtelníku! }{ Utíkej, smrtelníku! }{ 0 }{ Presence 1 & G.Patch_Plus == 1 }{ G.Dialog_Presence = 1; dialogParticles(); G.Chunk_Run = 1 }{ }{ }{ }{ }{ }{ }{ }

{	389	}{	Teď máš šanci si zahrát na hrdinu. Zkus mě zastavit.	}{	Teď máš šanci si zahrát na hrdinu. Zkus mě zastavit.	}{	401	}{	}{	}{	}{	}{	}{	}{	}{	}{	Dělej zeď, pokud musíš, ale varuji tě, že jsem demoliční koule.	}

{	402	}{ Jo, vybíráš si smrt. }{ Jo, vybíráš si smrt. }{ 0 }{ }{ G.Chunk_Attack = 1 }{ }{ }{ }{ }{ }{ }{ Nežít nebo nežít, to není otázka. }
{	403	}{ A co kdybych vyjel až na střechu a ne za LaCroixem? }{ A co kdybych vyjela až na střechu a ne za LaCroixem? }{ 421 }{ Persuasion 10 & G.Patch_Plus == 1 }{ G.Chunk_Skip = 1 }{ }{ }{ }{ }{ }{ }{ Ale co když se chci místo toho raději pokochat pohledem ze střechy? }

{	422 }{ Díky! }{ Díky! }{ 0 }{ G.Chunk_Skip == 0 }{ }{ }{ }{ }{ }{ }{ }{ Dík, dík, dík. }
{	423 }{ Díky! }{ Díky! }{ 0 }{ G.Chunk_Skip == 1 }{ G.Chunk_Skip = 2 }{ }{ }{ }{ }{ }{ }{ Dík, dík, dík. }

Vedeli ste, že Chunk má aj také fajnové repliky ako napríklad
Mám takovou radost, že se ti nic nestalo, rohlíčku. Já byl... zdravotně indisponován a když jsem se dověděl o tom útoku, bál jsem se, že... Ovšem teď už je tvůj bezpečák zase zpátky, aby tě chránil, takže se ničeho neboj.
	A DOST! TEĎ POSLOUCHEJ! JSEŠ PRO MĚ NAPROSTO ODPUDIVEJ!	
Ale pusinko...
KDYBYSME BYLI POSLEDNÍ DVA LIDI NA PLANETĚ, RADŠI BYCH TĚ ZABILA!
JSI STEJNĚ TLUSTEJ JAKO ŠEREDNEJ A LÍNEJ!
I CVIČENÝ PES BY ZVLÁDNUL TVOU PRÁCI STOKRÁT LÍP!
Ale... Ale, ale...
VÁŽNĚ SI MYSLÍŠ, ŽE NĚKDO JAKO JÁ BY CHTĚL TEBE?
TY JEDEN DEBILNÍ, PLEŠATÝ, VYŽRANÝ POZÉRE!
ŘÍKÁ SE TOMU OVOCE, TLUSTOPRDE, ZJISTI SI TO!

A to všetko záleží od štartovacích podmienok dialógu... možno by nebolo odveci snažiť sa s ľuďmi čo najviac vykecať a vidieť všetky možné repliky, ktoré v rámci bežného testu ušli. Oddelím rozličné štarty dialógu hviezdičkou

G.Story_State=10
*
G.Story_State=10
G.Chunk_Befriend=0
*
G.Story_State=10
G.Chunk_Befriend=2
*
G.Story_State=10
G.Chunk_Feed=1
*
G.Chunk_Open=1
*
G.Story_State=15
*
G.Story_State=15
G.Chunk_Seduce=1
*
G.Story_State=20
*
G.Story_State=30
*
G.Story_State=35
*
G.Story_State=35
G.Chunk_Sorry=1
*
G.Story_State=80
*
G.Story_State=80
G.Chunk_Seduce=1
*
G.Story_State=100
*
G.Story_State=100
G.Chunk_Seduce=1
*
G.Story_State=110
*
G.Chunk_Spooked=1
*
G.Chunk_Reset=1

je v map la_ventruetower_1

**Comment by maarten93** [comment]
Nevím asi něco dělám špatně, ale ty rozhovory výš se mi nepodařilo vyvolat, a navíc od   G.Story_State=80 a výš nemůžu Chunka nikde najít, ale při hledání Chunka jsem narazil na tohle https://snag.gy/a3u0zd.jpg.

Jestli to chápu dobře na na vyvolání repliky 369 je potřeba mít v prezenci alespoň jeden bod?
Zkoušel jsem tam dát 5 bodů ale vůbec to nepomohlo.

**Comment by maarten93** [comment]
Jinak ostatní repliky na které jsem narazil byli v pohodě.

**Comment by maarten93** [comment]
jestli to dobře chápu spouštěč repliky 369, by měl být hra ve fázi G.Story_State=105   ?
 
Podle tady toho:
{	665	}{	(Starting Condition)	}{	}{	361	}{	G.Story_State == 105	}{	}{	}{	}{	}{	}{	}{	}{	}  

Ale z zkoušel jsem různé fáze hry od 70, ale pokaždé je Hala vystřílená a Chunk je mrtvý.

**Comment by miracleflame** [comment]
Hmmm... skúšal si proste načítať mapu la_ventruetower_1 a ako tam pred tebou sedí pozapínať potrebné hodnoty a hovoriť potom? Ono netuším kde by reálne mal byť v rámci vyšších štádií deja, je možné, že tam hrajú rolu rozličné iné prepínače v rámci vývoja deja podľa rozhodnutí hráča a vtedy by tá mapa vyzerala ináč, resp. Chunk by tam bol...

**Comment by maarten93** [comment]
Ne pokaždé jsem se tam portoval z jiné mapy.

**Comment by maarten93** [comment]
Dík, za tip už to jde, musím být na té mapě, když měním fázi hry.
https://snag.gy/IHGWO8.jpg
https://snag.gy/czjOF9.jpg

**Comment by maarten93** [comment]
389 https://snag.gy/FhKG7P.jpg
401 https://snag.gy/zgkCGP.jpg
402 https://snag.gy/vWUyFT.jpg

**Comment by maarten93** [comment]
Na tyhle repliky jsem nenarazil:
{	403	}{ A co kdybych vyjel až na střechu a ne za LaCroixem? }{ A co kdybych vyjela až na střechu a ne za LaCroixem? }{ 421 }{ Persuasion 10 & G.Patch_Plus == 1 }{ G.Chunk_Skip = 1 }{ }{ }{ }{ }{ }{ }{ Ale co když se chci místo toho raději pokochat pohledem ze střechy? }

{	422 }{ Díky! }{ Díky! }{ 0 }{ G.Chunk_Skip == 0 }{ }{ }{ }{ }{ }{ }{ }{ Dík, dík, dík. }
{	423 }{ Díky! }{ Díky! }{ 0 }{ G.Chunk_Skip == 1 }{ G.Chunk_Skip = 2 }{ }{ }{ }{ }{ }{ }{ Dík, dík, dík. }

Na tohle jsem narazil poprvé:
https://snag.gy/m49lDh.jpg

**Comment by maarten93** [comment]
Co znamená podmínka G.Patch_Plus == 1 ?
Musí být nainstalovaný plus patch?

**Comment by miracleflame** [comment]
To sa dá normálne prepínať v konzole ako G.Story_State, čiže G.Patch_Plus=1

na 403 treba Přesvědčování 10, tým sa zapne G.Chunk_Skip=1 a z toho by mala prameniť replika 423.
422 by mala vychádzať z čohokoľvek nižšie

{	412	}{	To, co pro něj mám, se mu bude líbit.	}{	To, co pro něj mám, se mu bude líbit.	}{	421	}{	}{	}{	}{	}{	}{	}{	}{	}{	Bude hltat má slova jako vy hltáte cukrové těsto.	}
{	413	}{	Pusť mě dovnitř.	}{	Pusť mě dovnitř.	}{	421	}{	Dominate 1	}{	}{	}{	}{	}{	}{	}{	}{	}
{	414	}{	Bráno, otevři se dokořán.	}{	Bráno, otevři se dokořán.	}{	421	}{	Dementation 1	}{	}{	}{	}{	}{	}{	}{	}{	Bráno, otevři se dokořán.	}
{	415	}{	Pusť mě dovnitř.	}{	Pusť mě dovnitř.	}{	421	}{	Thaumaturgy 1 & G.Patch_Plus == 1	}{	dialogParticles()	}{	}{	}{	}{	}{	}{	}{	}
{	416	}{	On mě potřebuje.	}{	On mě potřebuje.	}{	421	}{	Presence 1 & G.Patch_Plus == 1	}{	G.Dialog_Presence = 1; dialogParticles()	}{	}{	}{	}{	}{	}{	}{	}

**Comment by maarten93** [comment]
403 https://snag.gy/BPaz2O.jpg   https://snag.gy/fzEACg.jpg
423 https://snag.gy/Ui6Ndc.jpg
422 https://snag.gy/rtZuFP.jpg  https://snag.gy/d3BM8m.jpg

**Comment by maarten93** [comment]
Vše funguje

**Comment by miracleflame** [comment]
Díky

**Comment by miracleflame** [comment]
mimochodom t8 issue s Princom
I do not have a valid reply
to je rovnako aj s anglickou verziou, odreportoval som to Wespovi... aj keď je možné, že technicky sa k danej replike ani nedá nijako dostať bez cheatovania. uvidíme, čo povie Wesp.
