### ISSUE TITLE
Bill Plechovka replika 101 nenapovedá, čo sa deje a perčo sú odpovede také aké sú

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#43]
{	101	}{	[Bill dies]... 	}{	[Bill dies]... 	}{	#	}{	npc.SetDisposition("Sad", 1)	}{	G.Bill_Dead = 1	}{	}{	}{	}{	}{	}{	}{	}

Obsah medzi zátvorkami [] sa v hre nezobrazuje.

**Comment by miracleflame** [comment]
zvolil som tak[to opravu
{	101	}{	[Bill dies]... <Bill umírá>	}{	[Bill dies]... <Bill umírá>	}{	#	}{	npc.SetDisposition("Sad", 1)	}{	G.Bill_Dead = 1	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
kontext je IMHO zcela zrejmy s predchozi repliky (radek 91) i z moznosti, ktere nasleduji. Veci v [ ] jsou ve zdrojacich na mnoha mistech a jsou pro lokalizatory a programatory obsluznych skriptu. Kdybychom chteli byt takto polopaticti, museli bychom toho poopravovat docela dost a to za to nestoji.

revert :)

**Comment by miracleflame** [comment]
No jak myslíš... ja som sa na to zameral práve z toho dôvodu, že som to hral a teda vôbec mi to neprišlo zrejmé z jeho poslenej repliky
 { 91 }{ [cough, cough, cough, cough]Vylezl z kanálu. Zrovna z toho, co je tady za rohem. [cough, cough, cough, cough]Už se tam nechci nikdy vrátit. [cough, cough, cough, cough]Nenechte tu zrůdu, aby vylezla a zas mě tam odnesla...[cough, cough, cough, cough] }{ [cough, cough, cough, cou
gh]Vylezl z kanálu. Zrovna z toho, co je tady za rohem. [cough, cough, cough, cough]Už se tam nechci nikdy vrátit. [cough, cough, cough, cough]Nenechte tu zrůdu, aby vylezla a zas mě tam odnesla...[cough, cough, cough, cough]	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

Pričom počas finálnej
{ 101 }{ [Bill dies]... }{ [Bill dies]... }{ # }{ npc.SetDisposition("Sad", 1) }{ G.Bill_Dead = 1 }{ }{ }{ }{ }{ }{ }{ }
stále stojí na mieste, a vyzerá celkom živo až kým hráč neukončí dialóg. Potom sa náhle zloží na zem.
