### ISSUE TITLE
downtown la/prince2.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#430]
map la_ventruetower_
G.Story_State=110
G.Prince_Reaction=4
a potom osobitne
G.Prince_Reaction=5

replika 1031

**Comment by maarten93** [comment]
Tohle mi fungovalo ale musel jsem dát G.Story_State=120
https://snag.gy/M5RwrZ.jpg

**Comment by miracleflame** [comment]
super, zatváram.
