### ISSUE TITLE
main characters/jack_tutorial.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#431]
G.Patch_Plus=1

...
Myslím, že na tebe venku čekají. Měl bys stíhat svůj taxík. 
Jasně.
Jestli se ještě někdy vrátíš, zastav se v Poslední rundě. To je bar tady v centru. Proberem tu politiku.[chuckle] Z toho se potrháš smíchy.[laugh] Zlom vaz.
**{	883	}{ Potkáme se tam, až se pořádně vyspím. }{ Potkáme se tam, až se pořádně vyspím. }{ 0 }{ G.Patch_Plus == 1 }{ G.Tut_Jack = 15 }{ }{ }{ }{ }{ }{ }{ Budeme tam, až zavřeme oči přes den. }**

...
Času není nazbyt... tak mi odříkej jenom základy.
....
Suprový. A teď se běž nahlásit jako správný pěšák. Jestli to přežiješ, zastav se v centru v Poslední rundě a pokecáme, jak je to tady celý v hajzlu. Do té doby, [chuckles]zlom vaz! Nebo spíš, rád jsem tě poznal, kluku!
**{	933	}{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ 0 }{ G.Patch_Plus == 1 }{ LeaveTutorialShort(); pc.Bloodloss(1) }{ }{ }{ }{ }{ }{ }{ Tvůj humor je podezřelý. Už zde nejsem, musím jít zavřít oči před sluncem. }**

...
Nepotřebuju ničí pomoc. Padám odsud.
Ta dnešní mládež. No bude to tvůj pohřeb, kluku.
Říkám, nech me na pokoji!
Jestli to přežiješ, zastav se v centru v Posle....
**{	1033	}{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ Moc vtipný. Nejdřív se na to vyspím a pak se zasměju. Měj se. }{ 0 }{ G.Patch_Plus == 1 }{ LeaveTutorialShort(); pc.Bloodloss(1) }{ }{ }{ }{ }{ }{ }{ Tvůj humor je podezřelý. Už zde nejsem, musím jít zavřít oči před sluncem. }**

**Comment by Honzixx** [comment]
Vše OK, u 933 a 1033 funguje -1 dávky krve.

**Comment by miracleflame** [comment]
super dík
