### ISSUE TITLE
main characters/mingxiao2.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#432]
G.Story_State=19
G.Patch_Plus=0/G.Patch_Plus=1
map la_malkavian_1

{	351	}{	[As Ming Xiao]Ty... co tady děláš?	}{	[As Ming Xiao]Ty... co tady děláš?	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	352	}{	Čau, Ninesi! Kde se tu bereš?	}{	Čau, Ninesi! Kde se tu bereš?	}{	361	}{ G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	Ten s číslovaným jménem!	}
{	353	}{	Chtěl bych se tě zeptat na stejnou věc...	}{	Chtěla bych se tě zeptat na stejnou věc...	}{	361	}{ G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	Potuluji se v mystickém bludišti své mysli...	}
{	354	}{	Jen jdu zrovna kolem...	}{	Jen jdu zrovna kolem...	}{	361	}{ G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	Jen si vyšlapuji kolem dokola...	}
{	355	}{	Čau, Ninesi! Kde se tu bereš?	}{	Čau, Ninesi! Kde se tu bereš?	}{	151	}{ G.Patch_Plus == 1	}{	}{	}{	}{	}{	}{	}{	}{	Ten s číslovaným jménem!	}
{	356	}{	Chtěl bych se tě zeptat na stejnou věc...	}{	Chtěla bych se tě zeptat na stejnou věc...	}{	151	}{ G.Patch_Plus == 1	}{	}{	}{	}{	}{	}{	}{	}{	Potuluji se v mystickém bludišti své mysli...	}
{	357	}{	Jen jdu zrovna kolem...	}{	Jen jdu zrovna kolem...	}{	151	}{ G.Patch_Plus == 1	}{	}{	}{	}{	}{	}{	}{	}{	Jen si vyšlapuji kolem dokola...	}

{	151	}{	[As Nines]Ven. Hned.	}{	[As Nines]Ven. Hned.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	152	}{	Ty taky vyšetřuješ Groutovo zmizení?	}{	Ty taky vyšetřuješ Groutovo zmizení?	}{	371	}{	}{	}{	}{	}{	}{	}{	}{	}{	I ty hledáš chybějícího Malkaviana?	}
{	153	}{	Není ti nic?	}{	Není ti nic?	}{	371	}{	not IsClan(pc,"Malkavian")	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by Honzixx** [comment]
Tady je vše OK. Zkusil jsem G.Patch_Plus=0 i 1.
