### ISSUE TITLE
santa monica/bertram.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#433]
...
Takže můžeš mě tam dostat?
Jo, to můžu. Řekni, až budeš připraven a vyrazíme. Ale jakmile tam budeš, bude to na tobě. Musíš se dostat dovnitř a nastražit výbušninu do prostřední kanceláře, aby to strhlo celou budovu.
**{	157	}{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ not IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ Posviťte mi na cestu, až se probudím zítra večer, Vaše Kámošstvo. }
{	158	}{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ IsClan(pc,"Nosferatu") and G.Bertram_Map == 1 and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ }**

G.Bertram_Go == 1
Můžeme vyrazit?
**{	466	}{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ G.Bertram_Map == 1 and IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ }
{	467	}{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ Až se vrátím, budu mít na tebe pár otázek. Vyzvedni mě v mém úkrytu, až se zítra prospím, a pak půjdeme. }{ 0 }{ not IsClan(pc,"Nosferatu") and pc.HasItem("item_g_astrolite") and G.Patch_Plus == 1 }{ G.Bertram_Ready = 2 }{ }{ }{ }{ }{ }{ }{ Posviťte mi na cestu, až se probudím zítra večer, Vaše Kámošstvo. }**

**Comment by Honzixx** [comment]
Vše je OK.
