### ISSUE TITLE
santa monica/killer.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#434]
to je myslím ten boss na vrakovisku SM 

map sm_hub_1
G.Patch_Plus=1
G.Story_State=10 (preistotu)
Lidskost 5
Přesvědčování 7

....
Myslíš si, že by tvá rodina ocenila to, co teď předvádíš?	}{	Myslíš si, že by tvá rodina ocenila to, co teď předvádíš?

Ne... Bože, ne! Ne! Musí to skončit. Takhle nemůžu existovat. Máš pravdu. Bože, máš pravdu! Už to nikdy neudělám, přísahám. Odpusť mi.

	**156 }{ Fajn. Měl bys dát řeč s Ninesem Rodriguezem v Poslední rundě v centru. }{ Fajn. Měl bys dát řeč s Ninesem Rodriguezem v Poslední rundě v centru. }{ 0 }{ Humanity 5 & G.Patch_Plus == 1 }{ G.Killer_Nines = 1; G.Killer_Freed = 1; pc.SetQuest("Serial",9) }{ }{ }{ }{ }{ }{ }{ Báječné. Nyní běž a promluv s devátým v Poslední rundě v centru. }**

**Comment by maarten93** [comment]
https://snag.gy/4nzNlY.jpg
Objevilo se mi tohle.

**Comment by miracleflame** [comment]
To je replika, ktorá sa normálne prehráva cez záznamník v bytoch a počas priameho dialógu by sa k nej nemalo ako dostať. Je to v dialógu nepreložené, lebo skutočný text sa zobrazuje ako floating, ten preložený je. 

Ak ti takto začal dialóg aj s prepínačmi, ktoré som vypísal, asi treba ešte toto
G.Killer_Lucky=1
G.Killer_Freed=0

Ale najlepšie by asi bolo, keby sa dialóg otestoval nie v Dineri, ale na vrakovisku po súboji, ako to je zamýšlané.... alebo vlastne načo... stačí dialóg v Dineri.

**Comment by Honzixx** [comment]
Otestoval jsem to přímo na vrakovišti a je to OK.

**Comment by miracleflame** [comment]
Paráda. Dík.
