### ISSUE TITLE
santa monica/lily.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#435]
G.Patch_Plus=1
G.Lily_Release=1
G.E_Quest=3
G.Lily_Extort=1
give item_g_lilly_purse
give item_g_lilly_photo
give item_g_lilly_diary
give item_g_bailbond_receipt
map sm_pier_1

Čau.
Pamatuješ, co jsi provedla? Dej sem nějaké peníze a já Éčkovi nic neřeknu.	}{	Pamatuješ, co jsi provedla? Dej sem nějaké peníze a já Éčkovi nic neřeknu.
Už jsem ti říkala, že žádné peníze nemám. A nemám ani nic jiného, co bych ti mohla dát. Proč mi to děláš?
{	274	}{ Protože prachy vládnou světu. Můžeš aspoň zpeněžit svý věci... }{ Protože prachy vládnou světu. Můžeš aspoň zpeněžit svý věci... }{ 0 }{ G.Patch_Plus == 1 and pc.HasItem("item_g_lilly_purse") and pc.HasItem("item_g_lilly_photo") and pc.HasItem("item_g_lilly_diary") and pc.HasItem("item_g_bailbond_receipt") }{ pc.RemoveItem("item_g_lilly_purse"); pc.RemoveItem("item_g_lilly_photo"); pc.RemoveItem("item_g_lilly_diary"); pc.RemoveItem("item_g_bailbond_receipt") }{ }{ }{ }{ }{ }{ }{ Protože zelená světem vládne. Prodej své tretky a také budeš mít... }

**Comment by miracleflame** [comment]
Funguje, ale len ťažko sa chápe, o čo tam kráča. Dialóg sa bez ničoho ukončí a veci z inventáru zmiznú bez notifikácie.

Dovolil som si takú menšiu úpravu textu, @soulcharmer može byť?

{	274	}{ Protože prachy vládnou světu. Tady máš svý věci, můžeš zpeněžit aspoň ty... }{ Protože prachy vládnou světu. Tady máš svý věci, můžeš zpeněžit aspoň ty... }{ 0 }{ G.Patch_Plus == 1 and pc.HasItem("item_g_lilly_purse") and pc.HasItem("item_g_lilly_photo") and pc.HasItem("item_g_lilly_diary") and pc.HasItem("item_g_bailbond_receipt") }{ pc.RemoveItem("item_g_lilly_purse"); pc.RemoveItem("item_g_lilly_photo"); pc.RemoveItem("item_g_lilly_diary"); pc.RemoveItem("item_g_bailbond_receipt") }{ }{ }{ }{ }{ }{ }{ Protože zelená světem vládne. Tady máš, prodej své tretky a také budeš mít... }

**Comment by soulcharmer** [comment]
Jo, to zni dobre.

Davalo by smysl zadat bug report proti UP, pokud jde o ty chybejici hlasky na konci teto repliky?

Diik

**Comment by miracleflame** [comment]
Myslím, že je to tak by design. Totiž, toto si tam Wesp vymyslel ako novú možnosť upratať si bordel v inventári. Hláška od Lily nechýba, lebo žiadna nebola nahovorená, takže to ide do Auto-End... a notifikácie na Item Lost tuším neexistujú, iba Item Gained.

Zatvorím to, ak súhlasíš.

EDIT:
Tak som to trochu preskúmal a náhodou tam je možnosť elegantne to napojiť na
{	281	}{	Děkuji.	}{	Děkuji.	}{	#	}{	npc.SetDisposition("Joy", 2)	}{	pc.HumanityAdd(1)	}{	}{	}{	}{	}{	}{	}{	}
{	282	}{	Ať vám láska vydrží. Sbohem.	}{	Ať vám láska vydrží. Sbohem.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Ať žije láska v nemrtvých. Sbohem.	}

Oslovil som s tým aj Wespa.

**Comment by soulcharmer** [comment]
Jasne, to vypada dobre, diky

**Comment by miracleflame** [comment]
@soulcharmer 
Wesp to ešte na popud Malkava vylepšil na
"Dead presidents rule. Take your trinkets and turn them green..."
takže....?
"Protože mrtví prezidenti vládnou. Vem si své tretky a udělej z nich zelené..."

**Comment by soulcharmer** [comment]
"Mrtví prezidenti vládnou. Vezmi sobě své tretky a proměň je na zelenou..."
