### ISSUE TITLE
Princ

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#439]
https://snag.gy/a3u0zd.jpg
Na tohle jsem narazil náhodou.

**Comment by miracleflame** [comment]
Dík, že si to dal ako osobitný bug...
Ako som napísal v Chunkovi - to je rovnako aj s anglickou verziou, odreportoval som to Wespovi... aj keď je možné, že technicky sa k danej replike ani nedá nijako dostať bez cheatovania. uvidíme, čo povie Wesp.

**Comment by miracleflame** [comment]
Wesp:
This works correctly out of the Kuij-Yin ending cutscene and then it is fine!

"Toto sa použije korektne počas Kuij-Yin záverečnej scény!"
