### ISSUE TITLE
nines.dlg chýba ženská replika 241 ku "zelenáči"

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#44]
{	241	}{	Nic takovýho... A opakuju, zelenáči, dávej si pozor, kde něco takovýho říkáš - koleduješ si o nakládačku. Už od svýho uchvácení bojuju za to, aby L.A. bylo svobodný. A po té době jsem jeden z mála, co nezradili ani nepřeběhli na jinou stranu. Prostě nejstarší veterán na bojišti.	}{	Nic takovýho... A opakuju, zelenáči, dávej si pozor, kde něco takovýho říkáš - koleduješ si o nakládačku. Už od svýho uchvácení bojuju za to, aby L.A. bylo svobodný. A po té době jsem jeden z mála, co nezradili ani nepřeběhli na jinou stranu. Prostě nejstarší veterán na bojišti.	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{	G.Nines_Leader = 1	}{	}{	}{	}{	}{	}{	}{	Nepoužívej moje jméno a prince ve stejné věte, Malku. Už od svýho uchvácení bojuju za to, aby L.A. bylo svobodný. A po té době jsem jeden z mála, co nezradili ani nepřeběhli na jinou stranu. Prostě nejstarší veterán na bojišti.	}

**Comment by miracleflame** [comment]
opravené na "mládě" pre ženskú repliku podľa vzoru
{	331	}{	Tak dvě minuty, zelenáči, víc času nazbyt nemám.	}{	Tak dvě minuty, mládě, víc času nazbyt nemám.	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
ok
