### ISSUE TITLE
Foto Lily

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#440]
Všimnul jsem si, že není přeložena zadní strana (datum a Santa Monica) u fotografie Lily
https://snag.gy/wTLQHt.jpg

**Comment by miracleflame** [comment]
![screenshot2789](https://user-images.githubusercontent.com/19254203/46255351-449ecc00-c49c-11e8-9810-1b71012532bb.jpg)

**Comment by miracleflame** [comment]
Dík, preložené.
