### ISSUE TITLE
UP10 test and release

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#441]
Ján testuje celú hru pokiaľ viem a keď skončí, myslím, že sme pripravení na release.

**Comment by maarten93** [comment]
Budeš implementovat i UP 10.1? Je tam opraveno celkem dost chyb, mimo jiné i historie co jsi hlásil Wespovi.

**Comment by miracleflame** [comment]
Je tam toho fakt hodne. Až príliš moc. A na GOGu to ešte dlho nebude tipujem...
Náš preklad vychádza z inštalácie GOGu, neobsahuje kopec súborov, ktoré by si ostatní museli doinštalovať cez samostatný UP patch. To zas niekedy nabudúce o rok, keď na GOGu vyjde 10.3 :D

**Comment by maarten93** [comment]
Jinak jsem to dohrál.

**Comment by miracleflame** [comment]
@Honzixx ako si na tom?

**Comment by Honzixx** [comment]
Už mi nezbývá moc do konce, dnes nejpozději zítra to doklepu ;-)

**Comment by Honzixx** [comment]
Tak mám dohráno. Otestuju pak jen fixy, až budou.

**Comment by miracleflame** [comment]
Funfacts o Wespovi (to je autor UP, ktorý vyvíja už pomaly dve dekády):

počet ovládaných programovacích jazykov - 0

textový editor používaný na patchovanie - Wordpad

internetové pripojenie - 1 Mbit

pracovný štýl - každý deň si spakuje poslednú verziu svojho pracovného adresára UP (2,6 GB cca 18000 úborov) a na prenosnom médiu (predpokladá sa, že ak by to diskety kapacitne uniesli, použil by diskety) si ju prinesie do práce, na konci práce spakuje nanovo, ak boli úpravy a prenesie na médiu domov.

Návrh na prácu s GitHubom odmietal od apríla roku 2017 až napokon včera dokázal urobiť svoj prvý commit. Vyžadovalo si to veľmi veľa presviedčania, demonštrovania, vysvetľovania, aké to je jednoduché a rozbehnuteľné behom 10 minút aj so zaučením. Stále sa vzpieral s argumentom, že on nie je programátor a že doterajší štýl je úplne efektívny (to vidno na tých bugoch, z ktorých polovicu vyrobil sám). Mám s nim veľmi grotesknú výmenu tuctov mailov na túto tému, v ktorých tento reverzný inžinier a patcher pôsobí ako nechápavé dieťa, ktorému treba elementárne záležitosti okolo aplikácie GitHub Desktop krôčik po krôčiku trikrát zopakovať a názorne ukázať a detailne vysvetliť aj s názornými príkladmi. Jedno sa pánovi musí nechať. Nenechá sa rozčúliť ani zdeptať.

**Comment by Honzixx** [comment]
To je mazec 😀

**Comment by miracleflame** [comment]
...a stále nechápe, čo je na tom lepšie, je to pre neho iba príťaž navyše, lebo aj tak mieni všetko robiť AJ po starom. 🤦‍♂️

**Comment by maarten93** [comment]
''Asi je ze staré školy'' 😁 Asi má tak zaběhlý a naučený jeho systém, že mu něco jiného a i jednoduššího přijde složitější. On asi UP nedělá sám ne? Někde jsem o něm četl že je povoláním chemik.

**Comment by maarten93** [comment]
Tedy je rozhovor s ním: https://offtherecordblog.org/2017/08/18/interview-with-wesp5/

Jestli jsem si to správně přeložil, tak celou hru dohrál pouze jednou za Toeradora a ostatní klany se mu nelíbí.

**Comment by miracleflame** [comment]
Správne by som to preložil tak, že nie je žiadny klan, čo by sa mu nepáčil. Inak to robí sám s podporou komunity na fóre a ako som sa dočítal, tak projekt prebral po niekom inom, ale netuším kedy to bolo. Myslím, že hódne dávno.

EDIT:
Otázka úplne mimo misu... Máte radi System Shock 2?

**Comment by maarten93** [comment]
https://drive.google.com/open?id=1siTZQBWwreIz0a7oYdVuE0LgJVHCNiOY

**Comment by maarten93** [comment]
System Shock 2 jsem nikdy nehrál, ani první díl, ale myslím že jsem o něm četl, to je ta hra kde se vzbouří umělá inteligence? Četl jsem nějaký článek že snad někdo chystá nějaký remake.

**Comment by Honzixx** [comment]
Taky jsem neměl tu čest ani s jedním System Shockem.

**Comment by miracleflame** [comment]
Pýtal som sa preto, lebo chcem popracovať aj na češtine k SS2, ktorá existuje, len by potrebovala korektúru a tá horšia časť je dorobenie diakritiky, lebo všetky texty sú bez diakritiky. Možno nejaký auto-correct spell check by to vedel uľahčiť, alebo mi napadol už aj google prevod reči na text, že by sa to len prečítalo atď.

K tomu ale treba mať vzťah k tej hre, len preto som sa pýtal. Inak to považujem rovnako ako VTMB za jednu z najlepšie napísaných a prevedených hier, veľmi výživné a ako už býva zvykom u najkultovejších hier, dokonalá audio stránka... 

Z tejto scény mi vždy ide mráz po chrbte rovnako, ako keď som to zažil prvý raz v noci so sluchátkami a hodne nahlas. A to som neočakával taký zvrat. Ale pozor, je to veľmi heavy spoiler. (a fakt silno odporúčam mušlové slúchadlá)
https://www.youtube.com/watch?v=djSDFybzTuQ

**Comment by maarten93** [comment]
Koupím jí na Gogu a zkusím jí, hry podobného typu mě hodně baví, klidně pokud budeš chtít tak ti pomůžu s testováním.

**Comment by maarten93** [comment]
Koukám že na to také vycházejí patche.

**Comment by miracleflame** [comment]
A nie len patche ale aj iné mody a tie veľmi odporúčam. Ale ešte by som s tým počkal, kým bude pridaná diakritika, resp. opravená gramatika, lebo niektoré opravy prekladu robil Slovák. A ešte by som rád preložil aj niektoré s tých modov, čo prídávajú nový text na HUD, keď príde mail alebo quest notifikácie. Potom by som celý ultimátny balíček modov poslal ako portable okamžite použiteľnú vec - iba veci, čo nemenia pôvodnú mechaniku a obsah hry, čiste kozmetické veci a vychytávky.

Toto by som už diskutoval skôr cez mail, ale nemám na teba adresu. Prípadne založím nový GitHub projekt. Keď tak mi napíš na adresu, čo mám v credits tejto hry.

**Comment by maarten93** [comment]
Poslal jsem ti e-mail.

**Comment by miracleflame** [comment]
@soulcharmer 
Pripravené na release po skompilovaní inštalačky. Je to na tebe.

Ešte raz díky za neoceniteľnú pomoc s opravami @maarten93 @Honzixx

**Comment by soulcharmer** [comment]
Tak snad konecne hotovo:

https://prekladyher.eu/preklady/vampire-the-masquerade-bloodlines.315/

Kouknete na to, jestli nekde neco nechybi.

Doky!

**Comment by miracleflame** [comment]
Až na taký detail, že sa tam v popisoch aj FAQ spomína verzia 9.7 namiesto 10.0 je to krásne.

**Comment by soulcharmer** [comment]
Fixed. 
Zavirame :)?
