### ISSUE TITLE
Bill vs. Phil

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#442]
Po osvobození Lily zabije doktora jménem Bill. https://snag.gy/eFmwnL.jpg
Pokud toho doktora zabiju ještě před touto scénou, nebo ho nechám naživu, pořád se jmenuje Bill.
Po scéně rozhovor s Vandalem:
Pokud jsem doktora zabil před scénou, mluví se o Billovi. https://snag.gy/X54f6L.jpg
Pokud doktora nezabiju před scénou, mluví se o Philovi. https://snag.gy/v3fdtA.jpg
Pokud si pamatuju dobře, tak ve scéně s Lily by se měl doktor jmenovat jinak, podle toho jestli ten původní byl zabit nebo ne, takže něco je tu rozbité.
Testuju za Nosferatu muž, UP 10 Plus.

**Comment by maarten93** [comment]
Není původní doktor Phil? A náhradní Bill? Předtím se Bill jmenoval Nicka řešilo se to tady: https://github.com/soulcharmer/gog_bloodlines_cz/issues/357

**Comment by miracleflame** [comment]
Nedarí sa mi zistiť, prečo by to nemalo fungovať podľa zámeru, súbory sedia s anglickými... Prosím majte k dispozícii aj anglickú verziu a všetko na čo natrafíte otestujte použitím sejvu aj v anglickej verzii, nech vieme hneď určiť, či to je chyba UP alebo prekladu. Tuto mi to zatiaľ pripadá ako chyba v UP.

**Comment by maarten93** [comment]
Problém bude v tom že replika předtím než je Lily zabit Phill/Bill je společná pro oba v angličtině jsou oba pojmenováni Scrubs says:, Až potom Vandal Mluví o Phillovi/Billovi podle toho jestli Phill žije. 

https://snag.gy/Vibat0.jpg

Předtím bylo Scrubs přeloženo jako Nicka, viz: https://github.com/soulcharmer/gog_bloodlines_cz/issues/357#issuecomment-285017396
K tomuto se mi vybavil seriál Scrubs, který byl přeložen jako doktůrci.

**Comment by miracleflame** [comment]
Toto je obrázok na 100% z anglického UP10? To bby potom znamenalo, že sound\character\male\blue_blood\Bill/Phil je úplne odignorované a berie sa to iba zo sound\character\male\blue_blood\
Ak by sa potvrdilo, že to tak je, v tom prípade by sa podľa mňa hodil preklad Doktůrek, ako navrhuješ.

**Comment by maarten93** [comment]
V Gogu jsem dal Verify/Repair a pak jsem nainstaloval UP10+ ve verzi final, takže by to tak mělo být.

**Comment by miracleflame** [comment]
Bude Doktůrek )

**Comment by Honzixx** [comment]
Odzkoušeno, je to doktůrek ;-) https://snag.gy/WoOGem.jpg
