### ISSUE TITLE
Léčení krví

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#443]
Kosmetická drobnost, není přeloženo Duration.

https://snag.gy/L6w9zv.jpg

**Comment by miracleflame** [comment]
Tak to vyzerá, že tieto súbory predsa bude treba preložiť. Prosím otestujte s týmto ešte raz disciplíny a okultné predmety.

[traiteffect.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2463875/traiteffect.txt)
[traiteffects000.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2463876/traiteffects000.txt)

**Comment by maarten93** [comment]
Otestuji, ale pokud jsem něco nepřehlídnul tak u všech ostatních schopností a artefaktů na které jsem narazil bylo zatím vše přeloženo.

**Comment by Honzixx** [comment]
Zkusil jsem všechny artefakty dříve zmíněné plus i ty, které mám momentálně ve hře a vše vypadá ok.
Schopnosti zatím taky ok.

**Comment by maarten93** [comment]
Tak beru zpět, zkusil jsem krvavou hvězdu a stejný problém.
https://snag.gy/F1gvkc.jpg
jinak zatím mám u sebe krvavou hvězdu, Tarulfang a bodlák Weekapaug

**Comment by Honzixx** [comment]
Zvláštní, já mám krvavou hvězdu přeloženou s těmito soubory od Miry
https://snag.gy/oVD1iO.jpg

**Comment by maarten93** [comment]
To na hoře je ještě bez souborů co jsem dával, sem jsem zkoušel, jestli je to nepřeložené i u krvavé hvězdy, předtím jsem si toho nevšiml když jsem jí dostal. 
S těmito  soubory to co jsou tady to už je přeloženo a krvavá hvězda i léčení krví funguje jak má. 
https://snag.gy/jSgsVH.jpg
 Nerozhodí to znovu historie?

**Comment by miracleflame** [comment]
Díky za váš neoceniteľný entuziazmus všetko to testovať odznovu, je mi cťou opäť pracovať s vami v tíme! Ospravedlňujem sa za slabší výpadok v posledných dňoch, choroba v celej rodine ma dosť brzdila a ešte stále trochu brzdí...

Áno aj históriové disciplíny s účinkami trvania a poškození, prosím, otestujte, malo by to byť OK... dúfam...

**Comment by maarten93** [comment]
Teď na rychlo otestován Gangrel Hmyzavec, který úplně ze začátku nešel a vše funguje jak má, disciplíny trvají o 25% déle postih funguje taky.

**Comment by maarten93** [comment]
Nosferatu nuzák funguje dostávám víc krve z bezdomovců i prostitutek.

**Comment by miracleflame** [comment]
Okej teraz sem dám súbory, ktoré majú preloženú iba Duration, ale Damage nie (Damage sa používa pri efekte Nuzáka). Treba otestovať, či sa zas niekde nezobrazuje získaný efekt so slovom Damage.

[traiteffect.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2464186/traiteffect.txt)
[traiteffects000.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2464187/traiteffects000.txt)

**Comment by maarten93** [comment]
Nuzák pořád funguje, ale třeba tady: https://snag.gy/UxYsl3.jpg se objevuje popisek Damage

**Comment by miracleflame** [comment]
Tak.. som sa silno pohrúžil do toho a preložil som použitím špeciálnych znakov pre š úplne všetko v týchto súboroch, lebo som pri testovaní zistil, že aj Lidskost-Cost efekt sa tam zobrazuje... 

Prosím pretestovať  týmito súbormi, hlavne či efekty reálne fungujú.

[traiteffect.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2464356/traiteffect.txt)
[traiteffects000.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2464357/traiteffects000.txt)

**Comment by maarten93** [comment]
Omlouvám se za odmlčení musel jsem jít něco zařídit, teď zas přeinstalovávám celou hru, nejnovější kompilace češtiny mi při instalaci píše invalid file handle 32, přeinstaluji celou hru a znovu zkusím nainstalovat češtinu snad to pomůže, pak otestuji zbývající věci.

**Comment by maarten93** [comment]
Přeinstalace nepomohla, instalátor pořád hlásí https://snag.gy/VfTPmw.jpg nevím jestli to něčemu vadí. hláška se zobrazí ještě několikrát, ale dá se odklikat a instalace se potom dokončí, jen nevím jestli to pak nebude dělat bordel ve hře.

**Comment by maarten93** [comment]
Gangrel paní šelem funguje, jak o 25% delší trvání zvířeckosti, tak 35% vyšší poškození a o 25% kratší morfizmus.

**Comment by maarten93** [comment]
Léčení krví s těma posledníma soubory je opět Duration 
Nosferatu Nuzák funguje
Daimonori Damage  https://snag.gy/LEah8Z.jpg

**Comment by miracleflame** [comment]
Chybová hláška Invalid File handle pri inštalácii sa prihodila už aj mne a neraz. Je to nejaká náhodná chyba, ktorá sa neopakuje po opätovnej inštalácií z toho istého inštalátora. Ak by náhodou áno, možno reštart PC pomôže. Tipujem, že to skôr súvisí s momentálnym stavom vecí v systéme než so samotnou inštalačkou, lebo je fakt ťažké chybu zreprodukovať.

Ak si po preinštalovaní češtiny znovu nenahral traiteffects súbory odtiaľto, tak ani preložené nebude nič, tie súbory som ešte nezahrnul do prekladu, kým sa poriadne neotestujú samostatne. Každopádne by nemalo byť s týmito poslednými súbormi ani možné, aby tam bolo niečo v angličtine....?

**Comment by maarten93** [comment]
Jo zkusil jsem znovu stáhnout ty poslední soubory co jsi sem dal, teď už je to v češtině pak to podrobněji otestuji, asi jsem je zaměnil v pc sem jich měl několik,  zatím jsem na rychlo zkoušel pár předmětů z inventáře, a u Daimonori je špatný efekt https://snag.gy/iuCcZj.jpg

**Comment by maarten93** [comment]
Daimonori, navíc vůbec nefunguje, nedává bonus do poškození u divotvorství.

**Comment by maarten93** [comment]
Krvavá hvězda funguje a udává i správný efekt.

**Comment by maarten93** [comment]
Fetiš z mumie funguje a popisek efektu je správně

**Comment by maarten93** [comment]
Léčení krví nefunguje, neobjevil se efekt a neurychluje léčení.

**Comment by maarten93** [comment]
Hlas krve funguje a udává správný efekt

**Comment by maarten93** [comment]
Předzvěst funguje a udává správný efekt

**Comment by maarten93** [comment]
Talisman Fae funguje i s popiskem efektu

**Comment by maarten93** [comment]
Bodlák funguje

**Comment by maarten93** [comment]
Tarulfang funguje

**Comment by maarten93** [comment]
Saulocept funguje

**Comment by maarten93** [comment]
Elizino srdce funguje

**Comment by maarten93** [comment]
Alamutův klíč funguje, ale popis efektu je v agličtině https://snag.gy/5oJEzc.jpg

**Comment by maarten93** [comment]
Galdjum funguje

**Comment by maarten93** [comment]
Starožitný medailon funguje

**Comment by maarten93** [comment]
Spletený talisman funguje

**Comment by maarten93** [comment]
Zharalketh funguje

**Comment by maarten93** [comment]
Perla funguje

**Comment by maarten93** [comment]
Nosferatu nuzák nefunguje

**Comment by maarten93** [comment]
Gangrel hmyzavec funguje

**Comment by maarten93** [comment]
Tremere tajuplný génius funguje

**Comment by miracleflame** [comment]
Tak to zhrniem:
Daimonori, navíc vůbec nefunguje, nedává bonus do poškození u divotvorství.
Nosferatu nuzák nefunguje
Alamutův klíč funguje, ale popis efektu je v agličtině
Léčení krví nefunguje, neobjevil se efekt a neurychluje léčení.

Mohol by si tieto otestovať s týmto, prosím?
[traiteffects000.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2470431/traiteffects000.txt)

**Comment by maarten93** [comment]
Daimonori už jde
Léčení krví pořád ne, neobjeví se popisek efektu.
Alamutův klíč je pořád efekt anglicky
Nosferatu nuzák už funguje.

**Comment by maarten93** [comment]
Když tak jestli myslíš že bude potřena otestovat více historií, tak se na to vrhnu.

**Comment by miracleflame** [comment]
Keď som updatoval repo na UP10 ani vo sne by mi nenapadlo, že niekoľkonásobne viac času strávim opravovaním všeličoho, čo už bolo... Holt, ukázalo sa, že aj opravy a preklady už aplikované (#340) sa nedostali vždy do oboch verzií basic/plus. Prečesal som to a zotrel som všetky rozdiely - Soak Pool už by malo byť preložené.

A Léčení nešlo preto, lebo som sem dal basic súbory. S týmito už by to malo byť ozaj všetko v cajku.

[traiteffect.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2472432/traiteffect.txt)
[traiteffects000.txt](https://github.com/soulcharmer/gog_bloodlines_cz/files/2472433/traiteffects000.txt)

Pretlačil som už všetko cez dumpy do novej inštalačky.

**Mimochodom odporúčam vám veľmi veľmi nainštalovať si poslednú verziu GitHub Desktop. Je približne tisícnásobne lepšia, prehľadnejšia, použiteľnejšia a užitočnejšia než tá s ktorou sme robili pred rokom. Príde mi dokonca ešte lepšia než samotná stránka GitHubu, len Issues tam nie sú. Na všetko ostatné je úplne dokonalá!**

**Comment by Honzixx** [comment]
Tyhle 2  poslední soubory jsou už teda v kompilaci? Nahodil jsem si novej GitHub a vypadá dobře :-)

**Comment by miracleflame** [comment]
Áno súčasné repo už obsahuje aj tieto dva posledné súbory, aj basic verziu aj plus verziu, lebo predpokladám, že už je to naozaj kompletne fixed. Ale nechávam priestor na dobrovoľný test.

Ten GitHub Desktop sa dá prepnúť do Dark theme, veľmi odporúčam... Ľavou zadnou sa tam robí všetko čo treba, Undo changes, Undo commit, Revert Commit, Pull/Push, všetko ide bleskovou rýchlosťou konečne a akákoľvek zmena v súboroch je okamžite vidieť prehľadne v diffoch ešte predtým než sa čokoľvek niekam pošle... úžasné. Vy nič z toho robiť nemusíte (ale môžete skúsiť, ak by ste objavili jednoduchý preklep, môžete skúsiť opraviť v repe), tak to asi neoceníte, ale napríklad pushnuté commity tam môžete veľmi prehľadne vidieť zdiffované, to aj vám umožní odhaliť nejakú chybku v implementácii zmeny, keby náhodou...

**Comment by maarten93** [comment]
Léčení krví už funguje a Klíč už je česky.

**Comment by maarten93** [comment]
zdá se že teď už je vše v pohodě(netestoval jsem vše jen věcí). O Github Deskop jsem vůbec netušil že existuje. Vypadá super hlavně historie je tam hodně přehledná.

**Comment by miracleflame** [comment]
A týmto by som uzavrel tento rekordne dlhý tiket. :)
Díky moc za váš čas a ochotu s týmito problémami, pomohlo to vychytať aj rôzne iné nesúvisiace chybky.
