### ISSUE TITLE
Titulky bez zvuku č2.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#444]
Už se to kdysi řešilo tady: https://github.com/soulcharmer/gog_bloodlines_cz/issues/386

Tohle je z dneška:
https://snag.gy/7DUCrk.jpg

**Comment by miracleflame** [comment]
v anglickej verzii sa to správa rovnako?

**Comment by maarten93** [comment]
Vyzkoušeno v angličtině titulky tam nejsou.
ještě jsem narazil znovu na tohle taky beze zvuku. https://snag.gy/VP9uY5.jpg

**Comment by miracleflame** [comment]
Zas sa ukázalo, že mojou vinou niečo nie je fixnuté tak, ako som si myslel. V dumpoch nám ostalo kopec súborov, ktoré boli z češtiny vymazané. Premazal som to a teraz urobím zopár tiketov na pretestovanie záležitostí, ktoré nám dlhodobo smrdeli vo výslednom preklade a teraz odrazu zmizli z prekladu.

Díky za tú neodbytnosť! ;)

Takže toto by už malo byť fixnuté.

**Comment by miracleflame** [comment]
Ready to test.. odporúčam premazať si svoje UP.

**Comment by maarten93** [comment]
Už je to ok
