### ISSUE TITLE
Hlídač v tutoriálu

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#445]
Tohle asi nesouvisí s češtinou? Ale pamatuji si z dřívějška že pokud pošlu hlídače v Tutoriálu na před tak ho zabije sabat a já přijdu o bod lidskosti, teď jsem udělal to samé a nic se nestalo.

https://snag.gy/IFZC4P.jpg
https://snag.gy/mykgKo.jpg

**Comment by Honzixx** [comment]
Taky si pamatuju, ze to tak bylo. Ja mam svoji lidskost rad, tak ho proto nechavam nazivu 😀

**Comment by maarten93** [comment]
Já to chci zkusit dohrát za sabat, tenhle konec jsem ještě nikdy neměl a myslím že je na to potřeba nižší lidskost.

**Comment by maarten93** [comment]
Zkoušeno v English a nefunguje.

**Comment by maarten93** [comment]
Tady podle toho to měli v UP10 opravit
+Restored killing innocents Humanity loss and tutorial guard death.
https://forums.planetvampire.com/bloodlines-tech-support/unofficial-patch-10-0-released!/

**Comment by miracleflame** [comment]
Toto je bug, ktorý Wesp fixne v rámci mapy, čiže mimo dlg preklad.
ref. https://forums.planetvampire.com/bloodlines-tech-support/unofficial-patch-10-1-released!/msg140809/#msg140809
