### ISSUE TITLE
Žaneta

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#447]
Tady podle mě úplně nesedí vyznění překladu: https://snag.gy/sVO1e8.jpg   (Sklapni konečně. Prostě ti to nedám a basta.)  V angličtině by tam mělo být tohle: I'm sorry to hear that Jeanette, but I really need to give it to Therese.(něco jako: To je mi opravdu líto Žaneto, ale potřebuji to předat Tereze)  https://snag.gy/2zJAYG.jpg
https://steamcommunity.com/sharedfiles/filedetails/?id=215066276
A ani ta reakce se podle mě k té odpovědi v češtině úpně nehodí: https://snag.gy/HIU5Ek.jpg

**Comment by miracleflame** [comment]
Všetko je v poriadku. Repliky sú k dispozícii dohromady 4, ale táto jedna ti tam chýba, lebo máš Lidskost menej ako 5. Aj náväzná reakcia je ako má byť podľa EN verzie.

Pravdepodobne aj viac dialógových možností budeš mať inde inak kvôli tej Lidskosti, ale to je práveže dobre, lebo niektoré sa zobrazia iba v prípade, že máš menej ako 5 a to sa na test hodí.
