### ISSUE TITLE
Trip 

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#448]
Nevím jestli je to chyba, ale když jsem šel prodat věci k Tripovy tak rozhovor začal jako bych u něj ještě nebyl, ale předtím jsem u něj byl už několikrát.

https://snag.gy/3cdPX1.jpg

**Comment by maarten93** [comment]
Testoval jsem v Aj, a je to tam taky, asi to není chyba, uzavřel bych to.

**Comment by miracleflame** [comment]
Práveže nevidím žiadnu štartovaciu pozíciu na tejto replike 191. Malo by to nasledovať po hráčovej replike. Ako to tam máš presne od začiatku?

**Comment by maarten93** [comment]
Ne to jsem blbě napsal, myslel jsem tím že stejný rozhovor jsem sním vedl když jsem přišel poprvé, rozhovor je veden takto, přijdu k němu a on mi řekne něco v tom smyslu že je rád že jsem přišel znovu, pak se ho zeptám na sériového vraha, dále na jeho jméno a jestli neprodává drogy a pak že mu nějaké seženu naproti na poliklinice a pak myslím to skočí na to jestli jsem v santamonice nový(na to samé se mě už ptal když jsem přišel poprvé)

**Comment by miracleflame** [comment]
Nj Wesp to tam s tým Tripom podľa možností domachlil a precyklil kvôli tomu obnovenému questu s drogami. Ale tak to má byť.
