### ISSUE TITLE
Chunkův bratr

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#449]
https://snag.gy/uKSgrU.jpg
Místo Chunka je v átriu jeho bratr(Chunk je mrtvý), u jeho popisku se objevuje jméno Chunk, u předchozích bylo Chunkův bratr a navíc není přeloženo.
https://snag.gy/ClbzhR.jpg

**Comment by miracleflame** [comment]
Tuná je skôr problém v tom, že máme v češtine súbor v angličtine! :D 
Dobrý testing! 

Má to byť Chunk... tento istý float pre Chunkovho brata tam máme preložený.

**Comment by miracleflame** [comment]
Pripravené na test.

**Comment by maarten93** [comment]
už je česky, ale píše se tam Chunk místo Chunkův bratr https://snag.gy/a0HujA.jpg

**Comment by miracleflame** [comment]
Takže vo všetkom inom ide o Chunkovho brata, len táto jedna hláška sa z neznámeho dôvodu berie z foldra pre Chunka? Chápem to správne? A aká akcia presne to vyvolá?

**Comment by maarten93** [comment]
Jo všude jinde je Chunkův bratr, když chci přepnout monitor s kamerami.

**Comment by miracleflame** [comment]
> In this case yes, in "chunk3/line621_col_e.vcd" the NPC line must be changed to "character/dlg/downtown la/chunk3/line621_col_e.wav".

Netýka sa súborov češtiny, bude opravené v novej verzii UP.
