### ISSUE TITLE
Floating hlášky nepodporujú sexovanie, príklady Nines a Dirty_cop

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#45]
V prípade prekladu, ktorý sa opiera o konkrétne pohlavie, je nutné vymyslieť unisex hlášku.

**Comment by soulcharmer** [comment]
"mlade" i "ty tam" je dostatecne unisex - je tady ke kontrole jeste neco?

**Comment by miracleflame** [comment]
Toto tu je len ako reminder... nič na riešenie...
Pokojne to zatvor, ak myslíš.

**Comment by miracleflame** [comment]
Považuejm za uzavreté. V prípade potreby by sa znovu otvorilo.

**Comment by miracleflame** [comment]
Práve som zistil, že tie floaty, ktoré majú prepojenie s dlg dokážu byť sexované, len to musí byť podchytené v dlh a lip musí byť *_f.lip

Prejdem podľa commitov prípady, kde sme to mohli aplikovať.

**Comment by miracleflame** [comment]
Ukázalo sa, že nakoniec nefunguje ani táto metóda. Jedine u replík, ktoré boli obojpohlavné už v origináli. Zatiaľ sa nepodarilo zistiť, v čom spočíva pointa. Držíme sa unisex tvarov, prípadne sa dá Auto-End line prerobiť na ... čím ostane text v dialógu, kde vieme robiť obojpohlavné repliky.
