### ISSUE TITLE
Patty

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#450]
https://snag.gy/eB0dDi.jpg
Nepřeloženo.

**Comment by miracleflame** [comment]
Preložené. Prosím otestovať za obe pohlavia (pomocou konzoly)

**Comment by maarten93** [comment]
Zde je nějaký problém, vůbec není v uličce kam jsem jí poslal jako předtím, ale stojí před klubem a vůbec nereaguje https://snag.gy/I8wpFv.jpg

**Comment by maarten93** [comment]
Problém bude nejspíš u mě, z nějakého důvodu mi zamrzly všechna NPC na ulici předtím se objevila hláška ai disabled a teď všechny savy co jsem zkoušel mají zamrzlá NPC, jediné co funguje je úplně nová hra.

**Comment by maarten93** [comment]
Tak se mi konečně podařilo rozhýbat npc, vyzkoušeno za obě pohlaví text je v češtině, ale je pokaždé stejný.

**Comment by miracleflame** [comment]
Tie zamrznuté postavy sme tu už v minulosti mali, že? To je problém použitia sejvov s inými Unofficial_Patch\maps\graphs\*.* ktoré sa pri premazaní a preinštalovaní prerobili... Je dobré zálohovať si ich spolu so sejvami pri preinštalácii...

Text má byť rovnaký pre obe pohlavia, vďaka.
