### ISSUE TITLE
Hon na Muddyho

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#452]
https://snag.gy/QNOypD.jpg
Skyline->Skyeline

**Comment by miracleflame** [comment]
To vážne sa v celej hre píše Skyeline a nie Skyline?

**Comment by maarten93** [comment]
Přímo na baráku na ceduli je napsáno Skyeline.

**Comment by miracleflame** [comment]
Ani som si toho doteraz nebol vedomý, že nejde o Skyline. Opravené všetky možné výskyty - e1d7a4d390ff88e1e01ed6124765df9c9cd34c5c
