### ISSUE TITLE
Muzeum po dokončení mise

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#454]
Po dokončení mise v muzeu mi stále zůstává Muzeum na mapě města.
https://snag.gy/a851yR.jpg
Mohu se tam přenést, ale už se nedostanu pryč, protože není na konci Beckett.
ttps://snag.gy/BbYpHN.jpg

**Comment by maarten93** [comment]
Znovu navštívení muzea, by mělo být umožněno v patchi UP10  
+Opened museum and Giovanni Mansion after quests for Pisha's items.
https://forums.planetvampire.com/bloodlines-tech-support/unofficial-patch-10-0-released!/

**Comment by miracleflame** [comment]
V tom prípade by sa malo dať aj normálne odísť asi tou istou cestou ako si prišiel... Skús to preveriť a ak by bol problém nahlásim Wespovi.

**Comment by Honzixx** [comment]
Tak za to se omlouvám, nevěděl jsem a nenapadlo mě zkusit odejít jinak. Kanálem a taxi se normálně odejít z muzea dá. Možno zavřít ;-)
