### ISSUE TITLE
Posel s kazetou

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#455]
Při hledání kazety pro Izaka, po rozhovoru s poslem, který pak uteče za roh. Nepřeložené "male" a pár drobností ve floating. https://snag.gy/960yra.jpg

**Comment by miracleflame** [comment]
Pripravené na test.

**Comment by Honzixx** [comment]
Je to přeložené OK  ;-) https://snag.gy/XZCSIV.jpg
