### ISSUE TITLE
Grout audiozáznam

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#457]
https://snag.gy/4CRobS.jpg
NEBE NA SEBOU. ->NEBE NAD SEBOU.

**Comment by maarten93** [comment]
https://snag.gy/CWX0b8.jpg
SVOU VÁBÍCÍ PÍSE VOLILI.->SVOU VÁBÍCÍ PÍSEŇ VOLILI.

**Comment by miracleflame** [comment]
Pripravené na test. Pri tom druhom som iba zmenil slovosled, aby špeciálny znak ň nevyšiel zrovna na zalomenie.

**Comment by maarten93** [comment]
Už je to ok
