### ISSUE TITLE
test floating hlášok v boji s Jezebel Locke

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#459]
Prosím otestujte, čo sa presne zobrazuje pri boji keď napríklad utečiete, ukryjete sa, hľadá vás a pod. Malo by stačiť aspoň niečo z toho.

Toto je test kvôli premazaniu dumpov, ktoré obsahovali súbory dávno vyjmuté z prekladu.

**Comment by Honzixx** [comment]
Tak tady pár hlášek má, ale narazil jsem na jednu nepřeloženou female..... https://snag.gy/nK5RlJ.jpg
Jinak tady screeny přeložených hlášek, co jsem z ní vytáhl:
https://snag.gy/1OzP3l.jpg
https://snag.gy/1F46wt.jpg
https://snag.gy/Jy3wtu.jpg

**Comment by Honzixx** [comment]
Jo a testuju to před chvílí nově zkompilovanou češtinou  na novou, čistou instalaci hry ;-)

**Comment by miracleflame** [comment]
Díky, malo by to byť pokryté.
