### ISSUE TITLE
test floating hlášok v boji so Stanom Gimblom

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#460]
Prosím otestujte, čo sa presne zobrazuje pri boji keď napríklad utečiete, ukryjete sa, hľadá vás a pod. Malo by stačiť aspoň niečo z toho.

Toto je test kvôli premazaniu dumpov, ktoré obsahovali súbory dávno vyjmuté z prekladu.

**Comment by Honzixx** [comment]
Z Gimbliho jsem vytáhnul tři hlášky a vše přeložené.
https://snag.gy/vc38o4.jpg
https://snag.gy/kg35M8.jpg
