### ISSUE TITLE
Artefakty nevypisující účinek

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#461]
U Bodláku Weekapaug https://snag.gy/pMRL6r.jpg
a u Elizina srdce https://snag.gy/hbwgkY.jpg
se nezobrazuje zisk či ztráta efektu. Ale toto nefunguje ani v EN verzi, tak je chyba v UP, nebo to ani nejde technicky udělat stejně, jako v případě navrácení osobních věcí Lily #435

**Comment by maarten93** [comment]
Elizino srdce zatím nemám, u bodláku se mi také zisk a ztráta nevypisuje, ale funguje jak má opravdu dává +1 do obrany.

**Comment by Honzixx** [comment]
Taky mi fungují OK, jen to nevypisuje ty efekty.

**Comment by miracleflame** [comment]
Podľa Wespovho vyjadrenia sa tento typ buffu nezobrazuje cez HUD float.
ref. https://forums.planetvampire.com/bloodlines-tech-support/unofficial-patch-10-1-released!/msg140809/#msg140809
