### ISSUE TITLE
Dračí dech

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#463]
http://vtmb.wikia.com/wiki/Dragon%27s_Breath
Podařilo se někomu od Mercuria získat tuto zbraň? Mluví o ní když po něm chci sehnat brokovnici, říká že sežene brokovnici a také tuto zbraň, ale brokovnice už mu přišla a toto zbraň chybí.

**Comment by Honzixx** [comment]
Tyjo tak to si nejsem jistej. Myslím si, že v minulosti jsem si ji od něj koupil, ale byla snad až ke konci hry. Buďto před, nebo až po Sabbat hotelu.

**Comment by miracleflame** [comment]
[> You can get it before the Hallowbrook Hotel mission. That way you get to use it for that and realize just how much it sucks and go back to using something better. Still p. cool, tho'.](https://gamefaqs.gamespot.com/boards/914819-vampire-the-masquerade-bloodlines/53629292)

give item_w_crossbow_flaming
