### ISSUE TITLE
Zabijácké šachy

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#470]
Úkol se dá plnit neustále znovu rozhovorem s Ji Wen Ja, pak už za něj nesou zkušenosti, ale přidává lidskost.
https://snag.gy/TiCl5v.jpg odpovědí č.2 která je po splnění úkolu pořád přístupná si můžu znovu aktivovat úkol.

**Comment by miracleflame** [comment]
Jedná sa o repliku Vy jste Ji Wen Ja?

**Comment by maarten93** [comment]
Jo, Jste Ji Wen Ja?

**Comment by miracleflame** [comment]
Malo by to byť fixed.

**Comment by maarten93** [comment]
Už je to ok.
