### ISSUE TITLE
Zygaena

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#471]
https://snag.gy/qyM7ib.jpg
Po použití schopnosti krádež krve, Zygaena zamrzne a přestane se hýbat i útočit.

Nahlásíš to Wespovi?

**Comment by miracleflame** [comment]
Dá sa to reprodukovať zakaždým?

**Comment by maarten93** [comment]
Zkoušel jsem to 2x.

**Comment by miracleflame** [comment]
Treba otestovať, či fix pomohol, dík.

**Comment by maarten93** [comment]
Částečně pomohlo, po použití schopnosti krádež krve se sice vzpamatuje a rozhýbe, ale docela dlouho to trvá.

**Comment by maarten93** [comment]
Už funguje jak má, promiň předtím jsem tam měl hozenou starou verzi.
