### ISSUE TITLE
Barabus

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#473]
https://snag.gy/xe4rXV.jpg

**Comment by miracleflame** [comment]
Inak toto som vám chcel povedať už dávno... Tie obrázky nemusíte uploadovať na SnagIt. Malo by stačiť drag&dropnúť priamo do miesta, kde píšete tiket. ;)

**Comment by maarten93** [comment]
![vampire 2018-10-12 22-56-44-33](https://user-images.githubusercontent.com/25608384/46894189-e8f91900-ce73-11e8-85fe-73f9234095c2.jpg)

**Comment by maarten93** [comment]
Ok jde to, ale musel jsem převést formát na .jpg

**Comment by miracleflame** [comment]
Jak je komu čo pohodlnejšie... malo by to brať aj png.

**Comment by miracleflame** [comment]
Tak toto bola hodne blbá chyba (moja). Pripravené na test.

**Comment by maarten93** [comment]
už ok
