### ISSUE TITLE
Občas se zobrazují texty rozhovorů a občas ne.

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#474]
![vampire 2018-10-14 17-10-19-64](https://user-images.githubusercontent.com/25608384/46918627-650a7280-cfd4-11e8-8de4-2722bed28a73.jpg)
![vampire 2018-10-14 17-10-27-18](https://user-images.githubusercontent.com/25608384/46918628-650a7280-cfd4-11e8-9edc-400698aa74c1.jpg)

Předtím mi to nedělalo, ale u postav zde je jako příklad Yukie se občas nezobrazuje text toho co říká, stalo se mi to teď třeba i u Zygaena a Šlapek, ale i dalších. Předtím to nedělalo. testováno 2x

**Comment by miracleflame** [comment]
Nevidím absolútne žiadny dôvod, prečo by sa niečo také malo diať kvôli prekladu, všetko je tam proste OK, neviem čo by som tam mal opraviť. Náhodou sa ti nechtiac nepodarilo stačiť medzerník počas toho? Vtedy myslím miznú titulky k dialógom a ostávajú iba možnosti odpovede.

**Comment by maarten93** [comment]
Zkoušeno znova a dával jsem si pozor na mezerník a nemačkal ho(nemačkal jsem nic kromě čísel replik) a pořád to dělá, někdy se zobrazí text a někdy ne, ještě můžu zkusit úplný reistal hry jestli není problém u mě, ale jediné co jsem dělal je že jsem zkompiloval nejnovější češtinu a nainstaloval ji.

**Comment by miracleflame** [comment]
EN to nerobí?

**Comment by maarten93** [comment]
Dal jsem v gogu Verify/Repair celá hra je nyní v Aj a už to funguje jak má, ještě až se mi stáhne Čeština tak jí  nainstaluji a zkusím znovu co to udělá.
![vampire 2018-10-14 17-37-25-90](https://user-images.githubusercontent.com/25608384/46918908-6c337f80-cfd8-11e8-8447-cb68f1374d5a.jpg)
![vampire 2018-10-14 17-37-09-38](https://user-images.githubusercontent.com/25608384/46918909-6c337f80-cfd8-11e8-8ce0-201f74e04806.jpg)
![vampire 2018-10-14 17-37-12-61](https://user-images.githubusercontent.com/25608384/46918911-6c337f80-cfd8-11e8-8d9f-dcfdcfc28b95.jpg)

**Comment by maarten93** [comment]
Teď při instalaci češtiny opět vyskočila hláška invalid file handle 32, což už se mi chvíli nestalo.

**Comment by maarten93** [comment]
Ok, tak nevím co se stalo když jsem instaloval předchozí češtinu tak jsem dal taky Verify/Repair ostatně to dávám vždy když instaluji nově češtinu, nainstaloval jsem jí bez problémů a měl jsem tento problém, teď jsem udělal to samé a jediný rozdíl je že při instalaci vyskočila hláška invalid file handle 32 a už to jde.

**Comment by miracleflame** [comment]
"invalid file handle 32" by som úplne ignoroval, najskôr sa to týka inštalácie fontov do systému, ktoré sa už nemenia, takže o nič neprichádzaš. Ale ako som spomínal, preinštalácia presne tej istej češtiny by už mala zbehnúť bez erroru.
