### ISSUE TITLE
VV

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#475]
![image](https://user-images.githubusercontent.com/25608384/46920110-7d38bc80-cfe9-11e8-93b5-2e1a2bfdb24c.png)

VV je moc dole.

**Comment by miracleflame** [comment]
Nie som si istý, či to takto bude stačiť. Ak nie, budeme to musieť vymyslieť ináč so zalamovaním.

**Comment by miracleflame** [comment]
Tak som to nakoniec vymyslel ináč, malo by to byť aj krajšie, len to treba otestovať.

**Comment by maarten93** [comment]
Tady je vše ok
