### ISSUE TITLE
Nadia Milliner

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#476]
![vampire 2018-10-14 18-56-31-14](https://user-images.githubusercontent.com/25608384/46920129-dc96cc80-cfe9-11e8-9471-74c2e5ff2aa4.jpg)

Ale to tady děsný...->Ale je to tady děsný...

**Comment by miracleflame** [comment]
Fixed.
Inak verím, že vám to napdalo, ale keby nie... na otestovanie fixu je pre vás najjednoduchšie vždy v GitHub softwari 
na karte History 
pre daný commit kliknúť pravým na FF súbor, v tomto prípade cestina_fontfriendly\dlg\giovanni\nadia.dlg a vybrať Show in Explorer
potom už len copy & paste do vašej hry 
....namiesto preinštalovávania celej češtiny.

**Comment by maarten93** [comment]
Už ok.
