### ISSUE TITLE
VV č.2

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#478]
![image](https://user-images.githubusercontent.com/25608384/46921446-a4988500-cffb-11e8-9f92-14bb752e0a43.png)
Moc dlouhý e-mail

**Comment by miracleflame** [comment]
Opravené.. treba otestovať.

**Comment by maarten93** [comment]
Zde chybí Podpis VV.

**Comment by maarten93** [comment]
![image](https://user-images.githubusercontent.com/25608384/47031769-ea2a8e80-d170-11e8-9799-d2e7d7d16810.png)

**Comment by miracleflame** [comment]
Asi by vypadalo blbo, keby tam ten podpis bol ešte narvaný niekde... Necháme jak je... 

Jedine, že by sa ten text okolo básne kapku zjednodušil a skrátil o jeden riadok.. @soulcharmer ?

**Comment by soulcharmer** [comment]
Navrhuju dat proste jeji podpis na posledni radek, neco jako:

"... brali jako basnirku vazne?   -VV"

**Comment by miracleflame** [comment]
Dobrý nápad. Uděláno.
