### ISSUE TITLE
[post 10.0] Andrei za sabbat

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#479]
Konec za Sabbat, tohle je hodně divné a asi to úplně nesouvisí s češtinou, hraji konec za sabbat když mě princ pošle do hotelu zabít sabbaty a Andreie, tak díky několika splněným podmínkám se k nim můžu přidat, existují dvě varianty které jsou k dispozici:

1)Andrei na mě čeká hned na začátku dole ve vstupní hale, nemusím s nikým bojovat, jen sejdu dolů a promluvím sním že se k němu chci přidat, v této variantě je vše ok, až na pár replik beze zvuku a animace , viz obrázky níže:
![vampire 2018-10-14 22-03-00-53](https://user-images.githubusercontent.com/25608384/46921896-8766b500-d001-11e8-98dc-354aefa3452a.jpg)

Tento druhý obrázek nedává úplně smysl s nikým jsem tady nebojoval
![vampire 2018-10-14 22-02-35-20](https://user-images.githubusercontent.com/25608384/46921897-8766b500-d001-11e8-9770-7ac29d678b4f.jpg)
![vampire 2018-10-14 22-02-48-49](https://user-images.githubusercontent.com/25608384/46921898-8766b500-d001-11e8-992d-4912aead7244.jpg)

2)Ignoruji nebo si nevšimnu Andreie dole v hale a projdu horním patrem nakonec ke dveřím, za kterými už se klasicky prosekám sabbatama a na konci je Andrei jako boss, jenže říká úplně to samé jako když jdu za ním rovnou na začátku v hale, tentokrát je celý rozhovor beze zvuku(tady už pak dává smysl věta o prosekaní se jeho služebníky) , řeknu mu že se k němu přidám a zabiji pro něho prince a Ming, s čímž souhlasí a pak mě klasicky napadne.

![vampire 2018-10-14 22-25-19-06](https://user-images.githubusercontent.com/25608384/46922044-6bfca980-d003-11e8-9987-b67159e3b63e.jpg)
![vampire 2018-10-14 22-25-25-73](https://user-images.githubusercontent.com/25608384/46922045-6bfca980-d003-11e8-87d4-2a04d42c3c29.jpg)
![vampire 2018-10-14 22-25-28-42](https://user-images.githubusercontent.com/25608384/46922046-6c954000-d003-11e8-8d33-5a5f613e01f1.jpg)
![vampire 2018-10-14 22-25-33-11](https://user-images.githubusercontent.com/25608384/46922047-6c954000-d003-11e8-9ff4-800647c0b8a0.jpg)
![vampire 2018-10-14 22-25-36-31](https://user-images.githubusercontent.com/25608384/46922048-6c954000-d003-11e8-9180-a1d29d94594a.jpg)
![vampire 2018-10-14 22-25-39-51](https://user-images.githubusercontent.com/25608384/46922049-6c954000-d003-11e8-9857-0eec95a97e9f.jpg)
![vampire 2018-10-14 22-25-11-07](https://user-images.githubusercontent.com/25608384/46922050-6c954000-d003-11e8-9d24-6575d2ed7089.jpg)
![vampire 2018-10-14 22-25-17-01](https://user-images.githubusercontent.com/25608384/46922051-6d2dd680-d003-11e8-8c65-2218d807b37d.jpg)

Snad jsem to vysvětlil dost srozumitelně.

**Comment by maarten93** [comment]
Zkoušeno v Aj až na ty fráze v první variantě, kde není v češtině zvuk je vše stejné.
Ještě jsem zkoušel co se stane když mu řeknu že splním princův rozkaz a zabiji ho, tak se teleportuje pryč a vyvolá nestvůru která vůbec na nic nereaguje a ani neútočí.

**Comment by miracleflame** [comment]
skús pozrieť do týchto súborov a vymazať všetky o ktorých vieš, že sa vyskytujú v týchto záverečných dialógoch
sound\character\dlg\hollywood\andrei\line185-251_col_e.lip

...uvidíme, či to potom prestane robiť problémy so zvukom a animáciami (treba si ešte predtým pridať aj súbory posledného commitu).

EN bugy som odreportoval Wespovi.

**Comment by maarten93** [comment]
Ve vstupní hale už jde zvuk, ale žádná animace, pokud ho ve vstupní hale ignoruji a prosekám se přes sabbat na konci říká to samé co ve vstupní hale, ale už je vše beze zvuku, přitom normálně co si pamatuji tak by měl říkat něco úplně jiného.

Poslal Wesp už nějakou odpověď?

**Comment by miracleflame** [comment]
Mohol by si mi, prosím ťa, poslať save, nech s s tým vyhrám? Dík.

**Comment by maarten93** [comment]
https://drive.google.com/open?id=12gG_WKacyQ-iaFe8MaxgXXMzhV_vWfIr - atrium
https://drive.google.com/open?id=1YIqWW-48mIJOFf3FkPy2Ix9bAduZ9urB - vestibul

Snad jsou to správné savy, první atrium by měl být Andrei hned na začátku hotelu, druhý vestibul je po prosekáni se sabbaty v hotelu.

**Comment by miracleflame** [comment]
Ešte preistotu save pred načítaním mapy atria. Mám obavy, že by som mohol mať inode problém so zamrznutými postavami.

**Comment by maarten93** [comment]
https://drive.google.com/open?id=1siTZQBWwreIz0a7oYdVuE0LgJVHCNiOY

**Comment by miracleflame** [comment]
U mňa so súčasnou češtinou bez mazania čohokoľvek v prvej variante pod schodami všetko prebehlo úplne v poriadku aj animácie aj zvuk. 

Ak som s presekal cez hotel, na konci hovoril to isté, ale nebol ani zvuk ani animácie. To bude asi nejaká chyba UP. Preberiem to s Wespom.

**Comment by maarten93** [comment]
Já jsem předtím promazal sound\character\dlg\hollywood\andrei\line185-251_col_e.lip, teď jsem to zkoušel znovu a až na první repliku buď pozdravena, vůbec nehýbe pusou když mluví.

**Comment by miracleflame** [comment]
Toto nechávam otvorené do ďalšieho releasu, keďže v UP10.0 oprava nehrozí.

**Comment by miracleflame** [comment]
Otestované v češtine 10.2beta a bug už neexistuje.
