### ISSUE TITLE
Hlasatel

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#480]
![vampire 2018-10-16 19-57-59-26](https://user-images.githubusercontent.com/25608384/47036990-0b45ac00-d17e-11e8-9844-e9ac32dddbfd.jpg)

Zalomení+umožňovat->umožňoval+zmírnit->zmírnil

**Comment by miracleflame** [comment]
Tu navrhujem vypustiť problematické ň kvôli zamalovaniu nasledovne

...který by umožnil vyšší limity pro škodliviny, a zmírnil rizika spojena s produkcí energie.

OK, @soulcharmer ?

**Comment by soulcharmer** [comment]
jj, diky

**Comment by miracleflame** [comment]
Opravené. Test by nemal byť potrebný.
