### ISSUE TITLE
Rádio

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#481]
Nejsou titulky, jestli jsem dobře pochopil, tak v jedné části mluví nějaká holka o Ashi Riversovi + nějaké další reportáže.

**Comment by maarten93** [comment]
Dále nějaký chlápek co nemůže spát protože se bojí upírů.

**Comment by maarten93** [comment]
Pak na další lince volá Frankenstein.

**Comment by miracleflame** [comment]
Toto som nedávno sám testoval a všetky rádiá boli funkčné...
malo by stačiť skákať medzi Q.Story_State 10 20 30 (niekedy tuším aj dvakrát toľko) a znovu nahrť mapu havenu map sm_pawnshop_1 alebo tak nejak

a je potrebné mať zapnutý Plus patch, lebo to je exkluzívne pre Plus.

Overíš to ešte prosím? ja tú hru v práci nemám.

**Comment by maarten93** [comment]
Otestuji, plus patch mám, až na tohle jsem měl všechna rádia s titulky, je to mapa úkrytu nad zastavárnou, v jedné z posledních fází hry, hned po Griffith Park, kam mě odveze Jack těsně před východem slunce, potom se už tam nedá vrátit.

**Comment by miracleflame** [comment]
Všetky rádia hrajú to isté podľa aktuálneho G.Story_State
vedel by si v konzole zistiť akú máš hodnotu G.Story_State? možno stačí napísať iba 
G.Story_State
alebo
get G.Story_State

**Comment by maarten93** [comment]
G.Story_State je 90, teď když jsem znovu nahrál save tak tam titulky jsou, ale jsou to úplně jiné rozhovory než předtím.

**Comment by maarten93** [comment]
Tak jsem zkusil párkrát nahrát ten save a nakonec se mi podařilo narazit na ty rozhovory které byli předtím bez titulků, tentokrát už byli s titulky, nevím proč se předtím nezobrazovali.

**Comment by miracleflame** [comment]
Neni možné, že celé vysielanie už išlo dokola? Titulky sa zobrazujú iba počas prvého kola.

**Comment by maarten93** [comment]
To si nemyslím, "probudil jsem se v úkrytu" zapnul jsem Tv, chýlili jsem jí poslouchal, pak jsem jí vypnul a zapnul jsem rádio a žádné titulky.
