### ISSUE TITLE
Chunkův bratr

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#482]
![vampire 2018-10-16 20-38-30-42](https://user-images.githubusercontent.com/25608384/47039177-98d7ca80-d183-11e8-980d-7cd6798a7363.jpg)

Na nic nereaguje ať ukončím rozhovor jakkoliv, pokud použiji schopnost dominance a řekl mu aby utíkal nic nedělá, pokud se sním nedomluvím tak by mě měl napadnout, což taky neudělá, pokud ho překecám aby mě pustil nahoru taky nic neudělá a navíc k tomu všemu sním můžu mluvit pořád dokola.

**Comment by miracleflame** [comment]
To vyzerá, že akcie G.Chunk_Run = 1 ani  G.Chunk_Attack = 1 nič nerobia... Ak to tak je aj v EN, tak to bude chyba UP.

**Comment by maarten93** [comment]
V Aj se chová stejně

**Comment by miracleflame** [comment]
Prosím otestovať tento fix
[ventrue.zip](https://github.com/miracleflame/VTMB-Unofficial-Patch-by-Wesp/files/2491890/ventrue.zip)

Commit:
https://github.com/miracleflame/VTMB-Unofficial-Patch-by-Wesp/commit/8654ff7ebdb4d6cd8d105f145185102e989cf683

**Comment by maarten93** [comment]
Tohle moc nepomohlo, rozdíl je v tom že ať už udělám cokoliv tak mě vždy napadne.

**Comment by miracleflame** [comment]
Wesp si pýta z konzoly hodnoty G.Chunk_Run a G.Chunk_Attack 
moc to nešpecifikoval, ale tipujem že myslí po použití nejakej repliky.

**Comment by maarten93** [comment]
G.Chunk_Run je 1 a G.Chunk_Attack je 0 po použití dominance která by ho měla donutit utéct.

**Comment by maarten93** [comment]
Pokud nepoužiji žádnou schopnost nebo přesvědčovací metodu tak G.Chunk_Run je 0 a G.Chunk_Attack je 1

**Comment by miracleflame** [comment]
Ok, toto je každopádne záležitosť UP a nie prekladu, takže to zatvorím. Dík.
