### ISSUE TITLE
Ovládnutý strážník

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#483]
![vampire 2018-10-16 22-36-40-74](https://user-images.githubusercontent.com/25608384/47045883-34713700-d194-11e8-9dfa-38c1d46db5c1.jpg)
Nepřeloženo

**Comment by miracleflame** [comment]
Dobrý úlovok. To stojí za test.

**Comment by maarten93** [comment]
Už ok.
