### ISSUE TITLE
Andrei konec za sabbat

### ISSUE THREAD

**Issue by maarten93** [soulcharmer/gog_bloodlines_cz#484]
![vampire 2018-10-16 22-56-43-81](https://user-images.githubusercontent.com/25608384/47047230-4b655880-d197-11e8-8790-89b7b6be87d2.jpg)
![vampire 2018-10-16 22-56-58-88](https://user-images.githubusercontent.com/25608384/47047238-50c2a300-d197-11e8-868e-f2c0d10b605e.jpg)
nepřeloženo.

**Comment by miracleflame** [comment]
To sú tie isté hlášky ako v rádiu, takže som použil ten istý preklad. Ibaže tu to nie je adresované Deb, takže som to dal do množného čísla. Bude to vyzerať dobre?

Inak dúfam, že dabing neznie ako cez telefón.

**Comment by maarten93** [comment]
Už je to ok.

Dabing je v pohodě a zní i jako Andrei.
