### ISSUE TITLE
Mandarin - řvál --> řval

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#485]
Jen opravit á za a ;-) https://snag.gy/kq204I.jpg

**Comment by Honzixx** [comment]
Rovnou se tu zeptám. Nebylo by od věci sjednotit všechny zmínky o Mandarinovi (v logu questů apod.), když se jeho floatingy změnily na číňana?

**Comment by miracleflame** [comment]
Good point. Netušil som, že mandarin sa spomína aj inde, poriešim to.
A toto by som updaril skôr na "aspoň řvi" nech to má unisex formy.

**Comment by miracleflame** [comment]
Pozri commit, ako v ňom vyzerá diff. To sú všetky zvyšné výskyty Mandarina, malo by sa to zobrazovať opravené, neviem, či sa ti to chce testovať v hre...

**Comment by Honzixx** [comment]
Testnu to, mam na to nachystany save.

**Comment by Honzixx** [comment]
Je to OK, všude je číňan a "aspoň řvi" je tam taky ;-)
