### ISSUE TITLE
Policajt v budově Fu - Floaty

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#486]
Některé floaty jsou jako Muž místo Policajta.
https://snag.gy/7Nk8Pa.jpg

**Comment by miracleflame** [comment]
Bohužial s týmto nič nenarobíme, lebo rovnaké floaty mechanika hry používa celoplošne aj pre iných mužov, ktorým by sa tam zas zobrazoval Policajt. Je to tak aj v AJ, myslím.
