### ISSUE TITLE
PC Kotel hříchu

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#488]
Tady si nejsem úplně jist, jestli je nabídka "soukromý" myšlena jako přídavné jméno, pak by podle mě bylo lepší dát spíše "soukromé".
Pokud je to myšleno jako podstatné jméno, má to být "soukromí".
https://snag.gy/GHTrSa.jpg

**Comment by miracleflame** [comment]
Originál je "PRIVATE" a malo by to byť soukromé, opravím.
