### ISSUE TITLE
Koncové titulky

### ISSUE THREAD

**Issue by Honzixx** [soulcharmer/gog_bloodlines_cz#489]
V koncových titulkách u testerů je aktualizovanej češtiny, spravně to má být aktualizované češtiny ;-)
![image](https://user-images.githubusercontent.com/25451297/47089322-e0606400-d220-11e8-824b-f8856eaf82ff.png)

**Comment by miracleflame** [comment]
Sa ospravedlňujem.

To stojí za test! )

**Comment by Honzixx** [comment]
Už je to OK :-D
