### ISSUE TITLE
Nepreložená textúra materials\plaster\malkwllf.ttz

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#49]
[Náhľad](https://snag.gy/YvdDXQ.jpg)

Chcelo by to preklad... možno by som to zvládol implementovať.. pokúsim sa, ak mi dáš český text.

**Comment by soulcharmer** [comment]
Nights, nights gone by, nights here without the taste of the master's blood.
His terrible gaze, the sight of the pale moon in the sky.
I am lost, trapped here by the master.
Once his most loyal servant but now the victim of his growing mistrust, the fractured surface of his paranoia, hearing the screams beyond these walls.
Something has happened, something  unnamable.
The beginnings of a harrowing madness that I surely will not...

**Comment by soulcharmer** [comment]
no, neco vymyslim. Nevis, ze ktere mapy ta zed je?

**Comment by miracleflame** [comment]
nights nights, gone by, nights here without taste of life
master's blood, his terrible gaze the sight of the pale moon in
the sky. I am lost, trapped here by the master, once his most
loyal servant but now the victim of his growing mistrust, the fractured
surface of his paranoia, hearing the screams beyond these walls, something has happened,
something unnamable,
the beginings of a harrowing madness that I surely will not...

**Comment by miracleflame** [comment]
ah, ty si zareagoval rýchlejšie než by som čakal )
je to z mapy la_malkavian_3b, nepovinná, ľahko missnuteľná, ale jedna z najzaujímavejších lokácií v hre...
[screen](https://snag.gy/xOqNIh.jpg)

**Comment by soulcharmer** [comment]
Kolik nocí již zde dlím bez krve svého pána...
Jeho upřený pohled jako vybledlý měsíc na obloze.
Jsem ztracen, uvězněn svým pánem.
Kdysi jeho oddaný sluha a nyní oběť jeho rostoucí nedůvěry a paranoi, slyšící hlasy na druhé straně zdí.
Něco se stalo, něco za oponou.
Počátek hrůzného šílenství, kterému zajisté . . .

**Comment by soulcharmer** [comment]
@miracleflame - ten font je bezva. Mozna bych ten text dal v texture trochu vys, aby to slo precist i bez lusteni - ostatne ten ghul mohl odpadnout i ze stoje :)

jinak je to tvoje.

**Comment by miracleflame** [comment]
[preložená textúra](https://snag.gy/YhlLn3.jpg)
[in game](https://snag.gy/FxLZKH.jpg)
