### ISSUE TITLE
Preklad dlg updates chinatown downtown 198b40b5

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#491]
[commit](https://github.com/soulcharmer/gog_bloodlines_cz/commit/198b40b54f746549bba24d93da9fa832394db657)

cestina\dlg\chinatown\barabus.dlg
{	1	}{	[In a prison, desperate to get out]PUSŤ MĚ VEN!	}{	[In a prison, desperate to get out]PUSŤ MĚ VEN!	}{	#	}{	npc.SetDisposition("Anger", 3)	}{	}{	}{	}{	}{	}{	}{	}{	}
**{	2	}{	Wait...	}{	Wait...	}{	11	}{	}{	}{	}{	}{	}{	}{	}{	}{	Wait and see...	}**

cestina\dlg\chinatown\wongho.dlg
{	62	}{	Rozumím. Víte, kam ji Tongové odnesli?	}{	Rozumím. Víte, kam ji Tongové odnesli?	}{	71	}{	}{	}{	}{	}{	}{	}{	}{	}{	Kam odnesli váš poklad, **do you know**?	}

cestina\dlg\chinatown\yukie.dlg
{	423 }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys otevřít nějaký magický portál **in front of it,** který by mě tam dostal? }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys otevřít nějaký magický portál **in front of it**, který by mě tam dostal? }{ 471 }{ Persuasion 10 }{ }{ }{ }{ }{ }{ }{ }{ Ještě ne. Můžeš zprovoznit čáry máry dveře vedoucí do jejího doupěte pod velkým domem? }

cestina\dlg\downtown la\bum.dlg
{	101	}{	Dobrá, dobrá, už jdu. Už na to nechci nikdy vzpomenout.	}{	Dobrá, dobrá, už jdu. Už na to nechci nikdy vzpomenout.	}{	#	}{	}{	pc.AwardExperience("Killer02"); FindPlayer().ChangeMasqueradeLevel( -1 )	}{	}{	}{	}{	}{	}{	}{	}
**{	102	}{	You better do.	}{	You better do.	}{	0	}{	}{	G.Bum_Leave = 1	}{	}{	}{	}{	}{	}{	}{	Do or die.	}**

cestina\dlg\downtown la\chunk2.dlg
**{	380	}{	What if I just went to visit the roof and not LaCroix?	}{	What if I just went to visit the roof and not LaCroix?	}{	421	}{	Persuasion 10 & G.Patch_Plus == 1	}{	G.Chunk_Skip = 1	}{	}{	}{	}{	}{	}{	}{ But if my mind longed for a view from the roof instead?	}**

cestina\dlg\downtown la\chunk3.dlg
**{	380	}{	I killed your brother and I will now kill you.	}{	I killed your brother and I will now kill you.	}{	391	}{	Humanity -5 & G.Chunk_Dead == 1 }{	}{	}{	}{	}{	}{	}{	}{	I will now do to you what I did to the other doughnut.	}**
{	389	}{	I killed your brother and I will now kill you.	}{	I killed your brother and I will now kill you.	}{	391	}{	Humanity -5 & G.Chunk_Dead == 1 }{	}{	}{	}{	}{	}{	}{	}{	I will now do to you what I did to the other doughnut.	}

cestina\dlg\downtown la\larry.dlg
{	221	}{	Hele, má kámoška ve Zpovědnici - menuje se Venuše Dare - shání někoho, kdo by uměl... Ale ať ti to vyklopí sama. Můžu jí brnknout a dát doporučení, jestli máš zájem.	}{	Stejně jsi na můj vkus trochu moc bledá. Hele, má kámoška ve Zpovědnici - menuje se Venuše Dare - shání někoho, kdo by uměl... Ale ať ti to vyklopí sama. Můžu jí brnknout a dát doporučení, jestli máš zájem.	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{	G.Larry_Venus = 1; pc.SetQuest("Confession",1)	}{	}{	}{	}{	}{	}{	}{	}
**{	224	}{	Uh, no need to do that. I heard that she is dead.	}{	Uh, no need to do that. I heard that she is dead.	}{	0	}{	IsDead("Venus")	}{	}{	}{	}{	}{	}{	}{	}{	I won't be doing any work for people being really dead.	}**

cestina\dlg\downtown la\milligan.dlg
{	52	}{	**Your crew** na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-).	}{	**Your crew** na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-).	}{	71	}{	Humanity 6 & G.Pisha_Desire == 1	}{	FindPlayer().HumanityAdd( -1 )	}{	}{	}{	}{	}{	}{	}{	Tví přátelé jsou v břiše nemocnice, muško. Luxusní žertík na tvůj účet.	}
{	53	}{	**Your crew** na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-).	}{	**Your crew** na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-).	}{	71	}{	Humanity -6 & G.Pisha_Desire == 1	}{	}{	}{	}{	}{	}{	}{	}{	Tví přátelé jsou v břiše nemocnice, muško. Luxusní žertík na tvůj účet.	}
{	65	}{	Naval řidičák. **If you tell anyone about this, you will share their fate.**	}{	Naval řidičák. **If you tell anyone about this, you will share their fate.**	}{	101	}{	Intimidate 6	}{	G.Mill_Intimidate = 1	}{	}{	}{	}{	}{	}{	}{	}

cestina\dlg\downtown la\pisha.dlg
{	156	}{	Postaral jsem se o něj po svém. Neřekne ani slovo. Strach mu to nedovolí. **If you don't believe me, you can find him here.**	}{	Postarala jsem se o něj po svém. Neřekne ani slovo. Strach mu to nedovolí. **If you don't believe me, you can find him here.**	}{	171	}{	G.Mill_Intimidate == 1 and G.Patch_Plus == 1 and pc.HasItem("item_w_claws_ghoul")	}{	pc.RemoveItem("item_w_claws_ghoul") }{	}{	}{	}{	}{	}{	}{	}

cestina\dlg\downtown la\prince1.dlg
{	101	}{	Vážně? V tom případě se postarám, aby byl náležitě potrestán. Nicméně i tak se ti podařilo uspět. To zaslouží pochvalu.	}{	Vážně? V tom případě se postarám, aby byl náležitě potrestán. Nicméně i tak se ti podařilo uspět. To zaslouží pochvalu.	}{	#	}{	}{	G.Prince_Mercurio = 1; G.Mercurio_Dead = 1	}{	}{	}{	}{	}{	}{	}{	}
**{	102	}{	Thanks.	}{	Thanks.	}{	111	}{	G.Mercurio_Dead == 0	}{	G.Mercurio_Dead = 1	}{	}{	}{	}{	}{	}{	}{	I had some fun.	}
{	103	}{	Thanks, and don't care about Mercurio. I killed him already.	}{	Thanks, and don't care about Mercurio. I killed him already.	}{	111	}{	G.Mercurio_Dead == 1 and (not pc.HasItem("item_g_mercurio_journal") or G.Patch_Plus == 0)	}{	}{	}{	}{	}{	}{	}{	}{	I had fun killing Mercury myself.	}
{	104	}{	Thanks, and don't care about Mercurio. I killed him already, here is his journal.	}{	Thanks, and don't care about Mercurio. I killed him already, here is his journal.	}{	111	}{	G.Mercurio_Dead == 1 and pc.HasItem("item_g_mercurio_journal") and G.Patch_Plus == 1	}{	pc.RemoveItem("item_g_mercurio_journal")	}{	}{	}{	}{	}{	}{	}{	I had fun killing Mercury myself. And I brought the stories he wrote.	}**

cestina\dlg\downtown la\skelter.dlg
**{	513	}{	Okay, but I also found this. Seems Grout killed that Toreador sugar daddy of Patty.	}{	Okay, but I also found this. Seems Grout killed that Toreador sugar daddy of Patty.	}{	261	}{	G.Patty_Known == 1 and pc.HasItem("item_w_tzimisce2_claw") 	}{	pc.RemoveItem("item_w_tzimisce2_claw"); G.Grout_Kent = 1	}{	}{	}{	}{	}{	}{	}{	Okydoky. And here get the picture of Patty's star that burned up there.	}**

**Comment by soulcharmer** [comment]
cestina\dlg\downtown la\pisha.dlg
{ 156 }{ Postaral jsem se o něj po svém. Neřekne ani slovo. Strach mu to nedovolí. Jestli mi nevěříš, najdeš ho tady.	}{ Postarala jsem se o něj po svém. Neřekne ani slovo. Strach mu to nedovolí. Jestli mi nevěříš, najdeš ho tady.	}{ 171 }{ G.Mill_Intimidate == 1 and G.Patch_Plus == 1 and pc.HasItem("item_w_claws_ghoul") }{ pc.RemoveItem("item_w_claws_ghoul") }{ }{ }{ }{ }{ }{ }{ }

cestina\dlg\downtown la\prince1.dlg
{ 101 }{ Vážně? V tom případě se postarám, aby byl náležitě potrestán. Nicméně i tak se ti podařilo uspět. To zaslouží pochvalu. }{ Vážně? V tom případě se postarám, aby byl náležitě potrestán. Nicméně i tak se ti podařilo uspět. To zaslouží pochvalu. }{ # }{ }{ G.Prince_Mercurio = 1; G.Mercurio_Dead = 1 }{ }{ }{ }{ }{ }{ }{ }
{ 102 }{ Díky. }{ Díky. }{ 111 }{ G.Mercurio_Dead == 0 }{ G.Mercurio_Dead = 1 }{ }{ }{ }{ }{ }{ }{ Byla to legrace. }
{ 103 }{ Díky. A Mercurio je mi ukradený. Sám jsem ho sejmul. }{ Díky. A Mercurio je mi ukradený. Sama jsem ho sejmula. }{ 111 }{ G.Mercurio_Dead == 1 and (not pc.HasItem("item_g_mercurio_journal") or G.Patch_Plus == 0) }{ }{ }{ }{ }{ }{ }{ }{ Byla radost umřít Mercuria. }
{ 104 }{ Díky. A Mercurio je mi ukradený. Sám jsem ho sejmul. Zde je jeho deník. }{ Díky. A Mercurio je mi ukradený. Sama jsem ho sejmula. Zde je jeho deník. }{ 111 }{ G.Mercurio_Dead == 1 and pc.HasItem("item_g_mercurio_journal") and G.Patch_Plus == 1 }{ pc.RemoveItem("item_g_mercurio_journal") }{ }{ }{ }{ }{ }{ }{ Byla radost umřít Mercuria. Také nesu příběhy, co napsal. }

cestina\dlg\downtown la\skelter.dlg
{ 513 }{ Okej, ale taky jsem našel tohle. Vypadá to, že Grout sejmul toho Toreadorskýho páprdu od Patty. }{ Okej, ale taky jsem našla tohle. Vypadá to, že Grout sejmul toho Toreadorskýho páprdu od Patty. }{ 261 }{ G.Patty_Known == 1 and pc.HasItem("item_w_tzimisce2_claw") }{ pc.RemoveItem("item_w_tzimisce2_claw"); G.Grout_Kent = 1 }{ }{ }{ }{ }{ }{ }{ Okidoki. A tady je obrázek pána od Patty, který nahoře shořel. }

**Comment by miracleflame** [comment]
Takže tu chýba ešte preklad prvých 8 postáv.

**Comment by soulcharmer** [comment]
cestina\dlg\chinatown\barabus.dlg
{ 1 }{ [In a prison, desperate to get out]PUSŤ MĚ VEN! }{ [In a prison, desperate to get out]PUSŤ MĚ VEN! }{ # }{ npc.SetDisposition("Anger", 3) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 2 }{ Počkej... }{ Počkej... }{ 11 }{ }{ }{ }{ }{ }{ }{ }{ }{ Vyčkej a uvidíš... }

cestina\dlg\chinatown\wongho.dlg
{ 62 }{ Rozumím. Víte, kam ji Tongové odnesli? }{ Rozumím. Víte, kam ji Tongové odnesli? }{ 71 }{ }{ }{ }{ }{ }{ }{ }{ }{ Kam odnesli váš poklad, víte to? }

cestina\dlg\chinatown\yukie.dlg
{ 423 }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys před ním otevřít nějaký magický portál, který by mě tam dostal? }{ Počkej! Ming se určitě schovává hluboko pod chrámem. Nemohla bys před ním otevřít nějaký magický portál, který by mě tam dostal? }{ 471 }{ Persuasion 10 }{ }{ }{ }{ }{ }{ }{ }{ Ještě ne. Můžeš zprovoznit čáry máry dveře vedoucí do jejího doupěte pod velkým domem? }

cestina\dlg\downtown la\bum.dlg
{ 101 }{ Dobrá, dobrá, už jdu. Nechci na to už nikdy vzpomenout. }{ Dobrá, dobrá, už jdu. Nechci na to už nikdy vzpomenout. }{ # }{ }{ pc.AwardExperience("Killer02"); FindPlayer().ChangeMasqueradeLevel( -1 ) }{ }{ }{ }{ }{ }{ }{ }
{ 102 }{ To bych radil. }{ To bych radila. }{ 0 }{ }{ G.Bum_Leave = 1 }{ }{ }{ }{ }{ }{ }{ Jinak umřeš. }

cestina\dlg\downtown la\chunk2.dlg
{ 380 }{ Co kdybych nejel za LaCroixem, ale chtěl se jen podívat na střechu? }{ Co kdybych nejela za LaCroixem, ale chtěla se jen  podívat na střechu? }{ 421 }{ Persuasion 10 & G.Patch_Plus == 1 }{ G.Chunk_Skip = 1 }{ }{ }{ }{ }{ }{ }{ Ale co když se chci pouze pokochat výhledem ze střechy? }

cestina\dlg\downtown la\chunk3.dlg
{ 380 }{ Sejmul jsem tvýho bráchu a teď sejmu i tebe. }{ Sejmula jsem tvýho bráchu a teď sejmu i tebe. }{ 391 }{ Humanity -5 & G.Chunk_Dead == 1 }{ }{ }{ }{ }{ }{ }{ }{ Nyní udělám to, co se přihodilo druhé koblize. }
{ 389 }{ Sejmul jsem tvýho bráchu a teď sejmu i tebe. }{ Sejmula jsem tvýho bráchu a teď sejmu i tebe. }{ 391 }{ Humanity -5 & G.Chunk_Dead == 1 }{ }{ }{ }{ }{ }{ }{ }{ Nyní udělám to, co se přihodilo druhé koblize. }

cestina\dlg\downtown la\larry.dlg
{ 221 }{ Hele, má kámoška ve Zpovědnici - jmenuje se Venuše Dare - shání někoho, kdo by uměl... Ale ať ti to vyklopí sama. Můžu jí brnknout a dát doporučení, jestli máš zájem. }{ Stejně jsi na můj vkus trochu moc bledá. Hele, má kámoška ve Zpovědnici - jmenuje se Venuše Dare - shání někoho, kdo by uměl... Ale ať ti to vyklopí sama. Můžu jí brnknout a dát doporučení, jestli máš zájem. }{ # }{ npc.SetDisposition("Neutral", 1) }{ G.Larry_Venus = 1; pc.SetQuest("Confession",1) }{ }{ }{ }{ }{ }{ }{ }
{ 224 }{ To nebude potřeba. Slyšel jsem, že už nežije. }{ To nebude potřeba. Slyšela jsem, že už nežije. }{ 0 }{ IsDead("Venus") }{ }{ }{ }{ }{ }{ }{ }{ Nemohu pracovat pro někoho, kdo je v pravdě mrtev. }

cestina\dlg\downtown la\milligan.dlg
{ 52 }{ Tví kumpáni na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-). }{ Tví kumpáni na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-). }{ 71 }{ Humanity 6 & G.Pisha_Desire == 1 }{ FindPlayer().HumanityAdd( -1 ) }{ }{ }{ }{ }{ }{ }{ Tví přátelé jsou v břiše nemocnice, muško. Luxusní žertík na tvůj účet. }
{ 53 }{ Tví kumpáni na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-). }{ Tví kumpáni na tebe čekají v suterénu té nemocnice. Celé to byl vtip... Baf :-). }{ 71 }{ Humanity -6 & G.Pisha_Desire == 1 }{ }{ }{ }{ }{ }{ }{ }{ Tví přátelé jsou v břiše nemocnice, muško. Luxusní žertík na tvůj účet. }
{ 65 }{ Naval řidičák. A jestli o tom někomu řekneš, dopadneš stejně.	}{ Naval řidičák. A jestli o tom někomu řekneš, dopadneš stejně.	}{ 101 }{ Intimidate 6 }{ G.Mill_Intimidate = 1 }{ }{ }{ }{ }{ }{ }{ }

**Comment by miracleflame** [comment]
preložené 95a39d5d
