### ISSUE TITLE
Preklad dlg updates generic giovanni hollywood main characters d8709cd2

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#492]
d8709cd2

cestina\dlg\Hollywood\andrei.dlg
{	178	}{	Zdá se, že jsem přemohl všechny tvoje stvůry **in the sewers**. Prošel jsem a můžu se už přidat k Sabbatu?	}{	Zdá se, že jsem přemohla všechny tvoje stvůry **in the sewers**. Prošla jsem a můžu se už přidat k Sabbatu?	}{	185	}{		}{		}{	}{	}{	}{	}{	}{	}{	Mohu se nyní přidat ke Kainovým mečům, když tvá krvavá zvířátka už nežijí?	}

cestina\dlg\Hollywood\gargoyle.dlg
{	142	}{	Tak možná spojenec je lepší slovo. Potřebuje tvoje schopnosti v boji s Kamarillou...	}{	Tak možná spojenec je lepší slovo. Potřebuje tvoje schopnosti v boji s Kamarillou...	}{	61	}{	G.Gargoyle_Persuade == 1	}{	}{	}{	}{	}{	}{	}{	}{	Ne! Baron potřebuje pravou ruku ke své levé **to fight the Camarilla**! Nikoliv prostoduchého otroka...	}

cestina\dlg\Hollywood\vv.dlg
{	987	}{	Zmiz odsud!	}{	Zmiz odsud!	}{	#	}{	npc.SetDisposition("Anger", 3)	}{		}{	}{	}{	}{	}{	}{	}{		}
**{	988	}{	I'll go.	}{	I'll go.	}{	0	}{	G.Misti_Dead == 0 or (G.Misti_Dead == 1 and G.Velvet_Quest == 0)	}{	}{	}{	}{	}{	}{	}{	}{	I'm gone already.	}
{	989	}{	I'll go.	}{	I'll go.	}{	0	}{	G.Misti_Dead == 1 and G.Velvet_Quest > 0 and G.Velvet_Quest < 3	}{	pc.SetQuest("Strip",4)	}{	}{	}{	}{	}{	}{	}{	I'm gone already.	}
{	990	}{	I'll go.	}{	I'll go.	}{	0	}{	G.Misti_Dead == 1 and G.Velvet_Quest >= 3	}{	pc.SetQuest("Writer",11)	}{	}{	}{	}{	}{	}{	}{	I'm gone already.	}
{	991	}{	Thanks!	}{	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}**

cestina\dlg\generic\prostitute.dlg
{	19	}{	Hledám, ale ne pro sebe. Pro známého.	}{	Hledám, ale ne pro sebe. Pro známého.	}{	91	}{	G.Romero_Whore == 1 and G.In_Hollywood == 1	}{	}{	}{	}{	}{	}{	}{	}{	Můj diář je plný, ale přimlouvám se za někoho jiného, **a friend.**	}

cestina\dlg\giovanni\mira.dlg
{	240	}{	Myslím, že se do toho nechci namočit. Omluvte mě.	}{	Myslím, že se do toho nechci namočit. Omluvte mě.	}{	0	}{	G.Mira_Gossip == 1	}{	}{	}{	}{	}{	}{	}{	}{	**I'm not curious enough for this, sorry.**	}

cestina\dlg\main characters\heather.dlg
**{	704	}{	I fed on him but let him live. Get him out as long as the trance is lasting.	}{	I fed on him but let him live. Get him out as long as the trance is lasting.	}{	711	}{	not IsDead("McFly") and G.Mcfly_Dump == 0 and G.Mcfly_Feed == 1	}{	G.Heather_Lure = 2	}{	}{	}{	}{	}{	}{	}{	I took a sip, now throw the fish out.	}**

cestina\dlg\main characters\regent.dlg
{	616	}{	Jen jsem udělal, co jsem považoval za správné. **And this book can go back into your library.**	}{	Jen jsem udělala, co jsem považovala za správné. **And this book can go back into your library.**	}{	711	}{	G.Patch_Plus == 1 and G.Isaac_Gargoyle == 4 and pc.HasItem("item_g_gargoyle_book")	}{	pc.SetQuest("Gargoyle",5); pc.GiveItem("item_p_occult_dexterity"); pc.RemoveItem("item_g_gargoyle_book")	}{	}{	}{	}{	}{	}{	}{	Tento skutek zasluhoval diskrétnost. And I have returned the book on time.	}
{	617	}{	Jen jsem udělal, co jsem považoval za správné. **And this book can go back into your library.**	}{	Jen jsem udělala, co jsem považovala za správné. **And this book can go back into your library.**	}{	711	}{	G.Patch_Plus == 1 and G.Isaac_Gargoyle < 4 and pc.HasItem("item_g_gargoyle_book")	}{	pc.SetQuest("Gargoyle",9); pc.GiveItem("item_p_occult_dexterity"); pc.RemoveItem("item_g_gargoyle_book")	}{	}{	}{	}{	}{	}{	}{	Tento skutek zasluhoval diskrétnost. **And I have returned the book on time.**	}

**Comment by soulcharmer** [comment]
cestina\dlg\Hollywood\andrei.dlg
{ 178 }{ Zdá se, že jsem přemohl všechny tvoje stvůry v kanálech. Prošel jsem a můžu se už přidat k Sabbatu? }{ Zdá se, že jsem přemohla všechny tvoje stvůry v kanálech. Prošla jsem a můžu se už přidat k Sabbatu? }{ 185 }{ }{ }{ }{ }{ }{ }{ }{ }{ Mohu se nyní přidat ke Kainovým mečům, když tvá krvavá zvířátka už nežijí? }

cestina\dlg\Hollywood\gargoyle.dlg
{ 142 }{ Tak možná spojenec je lepší slovo. Potřebuje tvoje schopnosti v boji s Kamarillou... }{ Tak možná spojenec je lepší slovo. Potřebuje tvoje schopnosti v boji s Kamarillou... }{ 61 }{ G.Gargoyle_Persuade == 1 }{ }{ }{ }{ }{ }{ }{ }{ Ne! Baron potřebuje pravou ruku ke své levé, aby porazil Kamarillu! Nikoliv prostoduchého otroka... }

cestina\dlg\Hollywood\vv.dlg
{ 987 }{ Zmiz odsud! }{ Zmiz odsud! }{ # }{ npc.SetDisposition("Anger", 3) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 988 }{ Už jdu. }{ Už jdu. }{ 0 }{ G.Misti_Dead == 0 or (G.Misti_Dead == 1 and G.Velvet_Quest == 0) }{ }{ }{ }{ }{ }{ }{ }{ Už zde nejsem. }
{ 989 }{ Už jdu. }{ Už jdu. }{ 0 }{ G.Misti_Dead == 1 and G.Velvet_Quest > 0 and G.Velvet_Quest < 3 }{ pc.SetQuest("Strip",4) }{ }{ }{ }{ }{ }{ }{ Už zde nejsem. }
{ 990 }{ Už jdu. }{ Už jdu. }{ 0 }{ G.Misti_Dead == 1 and G.Velvet_Quest >= 3 }{ pc.SetQuest("Writer",11) }{ }{ }{ }{ }{ }{ }{ Už zde nejsem. }
{ 991 }{ Díky! }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }

cestina\dlg\generic\prostitute.dlg
{ 19 }{ Hledám, ale ne pro sebe. Pro známého. }{ Hledám, ale ne pro sebe. Pro známého. }{ 91 }{ G.Romero_Whore == 1 and G.In_Hollywood == 1 }{ }{ }{ }{ }{ }{ }{ }{ Můj diář je plný, ale přimlouvám se za někoho jiného, přítele.	}

cestina\dlg\giovanni\mira.dlg
{ 240 }{ Myslím, že se do toho nechci namočit. Omluvte mě. }{ Myslím, že se do toho nechci namočit. Omluvte mě. }{ 0 }{ G.Mira_Gossip == 1 }{ }{ }{ }{ }{ }{ }{ }{ Má zvědavost nesahá dost daleko, promiňte.	}

cestina\dlg\main characters\heather.dlg
{ 704 }{ Napil jsem se z něj, ale žije. Odveď ho, dokud je v tranzu. }{ Napila jsem se z něj, ale žije. Odveď ho, dokud je v tranzu. }{ 711 }{ not IsDead("McFly") and G.Mcfly_Dump == 0 and G.Mcfly_Feed == 1 }{ G.Heather_Lure = 2 }{ }{ }{ }{ }{ }{ }{ Byl to jen malý doušek. Nyní je možné rybku pustit. }

cestina\dlg\main characters\regent.dlg
{ 616 }{ Jen jsem udělal, co jsem považoval za správné. A tuto knihu si můžete vrátit do knihovny.	}{ Jen jsem udělala, co jsem považovala za správné. A tuto knihu si můžete vrátit do knihovny.	}{ 711 }{ G.Patch_Plus == 1 and G.Isaac_Gargoyle == 4 and pc.HasItem("item_g_gargoyle_book") }{ pc.SetQuest("Gargoyle",5); pc.GiveItem("item_p_occult_dexterity"); pc.RemoveItem("item_g_gargoyle_book") }{ }{ }{ }{ }{ }{ }{ Tento skutek zasluhoval diskrétnost. A přináším knihu nazpět včas. }
{ 617 }{ Jen jsem udělal, co jsem považoval za správné. A tuto knihu si můžete vrátit do knihovny.	}{ Jen jsem udělala, co jsem považovala za správné. A tuto knihu si můžete vrátit do knihovny.	}{ 711 }{ G.Patch_Plus == 1 and G.Isaac_Gargoyle < 4 and pc.HasItem("item_g_gargoyle_book") }{ pc.SetQuest("Gargoyle",9); pc.GiveItem("item_p_occult_dexterity"); pc.RemoveItem("item_g_gargoyle_book") }{ }{ }{ }{ }{ }{ }{ Tento skutek zasluhoval diskrétnost. A přináším knihu nazpět včas.	}

**Comment by miracleflame** [comment]
Preložené 58eaf7c8
