### ISSUE TITLE
Preklad dlg updates santa monica 3bd1796b

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#493]
3bd1796b

cestina\dlg\santa monica\arthur.dlg
**{	2	}{	Hello there! How you've been?	}{	Hello there! How you've been?	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	3	}{	Hi.	}{	Hi.	}{	11	}{	}{	}{	}{	}{	}{	}{	}{	}{	Greetings!	}
{	6	}{	Lovely night, huh?	}{	Lovely night, huh?	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}**

cestina\dlg\santa monica\bertram.dlg
**{	554	}{	Maybe I can make it up for you later.	}{	Maybe I can make it up for you later.	}{	0	}{	G.Knox_Killed == 1	}{	G.Knox_Killed = 2	}{	}{	}{	}{	}{	}{	}{	}
{	715	}{	Then you will probably be sorry to hear that I killed him.	}{	Then you will probably be sorry to hear that I killed him.	}{	551	}{	IsDead("Knox")	}{	G.Knox_Killed = 1	}{	}{	}{	}{	}{	}{	}{	Sorry, but I fed him to the big death.	}**

cestina\dlg\santa monica\killer.dlg
{	156 }{ Fajn. Měl bys dát řeč s **some people** v Poslední rundě v centru then. }{ Fajn. Měl bys dát řeč s **some people** v Poslední rundě v centru then. }{ 0 }{ Humanity 5 & G.Patch_Plus == 1 }{ G.Killer_Nines = 1; G.Killer_Freed = 1; pc.SetQuest("Serial",9) }{ }{ }{ }{ }{ }{ }{ Báječné. Nyní běž a promluv s devátým v Poslední rundě v centru. }

cestina\dlg\santa monica\malcolm.dlg
**{	93	}{	Hide it behind the plant pots in the corridor of the appartment building across the street, doctor.	}{	Hide it behind the plant pots in the corridor of the appartment building across the street, doctor.	}{	0	}{	G.Patch_Plus == 1	}{	}{	}{	}{	}{	}{	}{	}{	Drop my green behind the living green in the big sleeping house across the road. Farewell.	}**

cestina\dlg\santa monica\stan_gimble.dlg
**{	3	}{	Oh, I'm using his phone, but he doesn't seem to be here at the moment. Can I help you?	}{	Oh, I'm using his phone, but he doesn't seem to be here at the moment. Can I help you?	}{	11	}{	G.Patch_Plus == 1	}{	}{	}{	}{	}{	}{	}{	}{	No, only with his phone. Can you solve the mystery of missing McGee?	}
{	212	}{	Haló?	}{	Haló?	}{	1	}{ G.Patch_Plus == 0	}{	}{	}{	}{	}{	}{	}{	}{	Ano?	}
{	213	}{	Hi, is this Gimble's Prosthetics?	}{	Hi, is this Gimble's Prosthetics?	}{	1	}{	G.Patch_Plus == 1	}{	}{	}{	}{	}{	}{	}{	}{	Do I speak with the guy who cuts people up?	}**

cestina\dlg\santa monica\therese.dlg
{	293	}{	To je fuk. S naší dohodou to nemá co dělat... **At least I brought you this diary.**	}{	To je fuk. S naší dohodou to nemá co dělat... **At least I brought you this diary.**	}{	301	}{ pc.HasItem("item_g_oh_diary") and G.Patch_Plus == 1	}{ pc.RemoveItem("item_g_oh_diary")	}{	}{	}{	}{	}{	}{	}{	Snášej břímě své sestry a dodrž naši úmluvu... **Also I got you some old words from there.**	}

cestina\dlg\santa monica\thug.dlg
{	21	}{	Get outta here, man!	}{	Get outta here, man!	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	41	}{	Hey, you better get outta here.	}{	Hey, you better get outta here.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
cestina\dlg\santa monica\arthur.dlg
{ 2 }{ Zdravím! Jak se vede? }{ Zdravím! Jak se vede? }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 3 }{ Brýden. }{ Brýden. }{ 11 }{ }{ }{ }{ }{ }{ }{ }{ }{ Zdravíčko! }
{ 6 }{ Krásná noc, že? }{ Krásná noc, že? }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }

nejsem si jist, zda se ^ realne pouziva...

cestina\dlg\santa monica\bertram.dlg
{ 554 }{ Možná bych ti to mohl někdy vynahradit. }{ Možná bych ti to mohla někdy vynahradit. }{ 0 }{ G.Knox_Killed == 1 }{ G.Knox_Killed = 2 }{ }{ }{ }{ }{ }{ }{ }
{ 715 }{ Tak to tě asi nepotěší, že jsem ho sejmul. }{ Tak to tě asi nepotěší, že jsem ho sejmula. }{ 551 }{ IsDead("Knox") }{ G.Knox_Killed = 1 }{ }{ }{ }{ }{ }{ }{ Je mi líto, ale mé já jím nakrmilo velkou smrt. }

cestina\dlg\santa monica\killer.dlg
{ 156 }{ Fajn. V tom případě bys měl dát řeč s lidmi v Poslední rundě v centru. }{ Fajn. V tom případě bys měl dát řeč s lidmi v Poslední rundě v centru. }{ 0 }{ Humanity 5 & G.Patch_Plus == 1 }{ G.Killer_Nines = 1; G.Killer_Freed = 1; pc.SetQuest("Serial",9) }{ }{ }{ }{ }{ }{ }{ Báječné. Nyní běž a promluv s devátým v Poslední rundě v centru. }

cestina\dlg\santa monica\malcolm.dlg
{ 93 }{ Dejte to za květináče v chodbě činžáku naproti přes ulici, doktore. }{ Dejte to za květináče v chodbě činžáku naproti přes ulici, doktore. }{ 0 }{ G.Patch_Plus == 1 }{ }{ }{ }{ }{ }{ }{ }{ Odložte mé zelené lupínky za zelené lupínky v květináčích ve velké noclehárně na druhé straně silnice. Sbohem. }

v originale je preklep : appartment -> apartment

cestina\dlg\santa monica\stan_gimble.dlg
{ 3 }{ Mám jeho telefon, ale zdá se, že tu momentálně není. Mohu vám pomoci? }{ Mám jeho telefon, ale zdá se, že tu momentálně není. Mohu vám pomoci? }{ 11 }{ G.Patch_Plus == 1 }{ }{ }{ }{ }{ }{ }{ }{ Ne, pouze s jeho telefonem. Umíte vyřešit záhadu zmizelého McGee? }
{ 212 }{ Haló? }{ Haló? }{ 1 }{ G.Patch_Plus == 0 }{ }{ }{ }{ }{ }{ }{ }{ Ano? }
{ 213 }{ Zdravím, to jsou Gimblovy protézy? }{ Zdravím, to jsou Gimblovy protézy? }{ 1 }{ G.Patch_Plus == 1 }{ }{ }{ }{ }{ }{ }{ }{ Hovořím s mužem, co řeže údy? }

cestina\dlg\santa monica\therese.dlg
{ 293 }{ To je fuk. S naší dohodou to nemá co dělat... Aspoň ti nesu tady ten deník.	}{ To je fuk. S naší dohodou to nemá co dělat... Aspoň ti nesu tady ten deník.	}{ 301 }{ pc.HasItem("item_g_oh_diary") and G.Patch_Plus == 1 }{ pc.RemoveItem("item_g_oh_diary") }{ }{ }{ }{ }{ }{ }{ Snášej břímě své sestry a dodrž naši úmluvu... Mé já také odtamtud přináší nalezená stará slova.	}

cestina\dlg\santa monica\thug.dlg
{ 21 }{ Padej odsud, čéče! }{ Padej odsud, čéče! }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 41 }{ Hej, radši se odsud ztrať. }{ Hej, radši se odsud ztrať. }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
