### ISSUE TITLE
Preklad new doll6.dlg 20558567

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#494]
20558567

{	1	}{	Hey! How ya doin'?	}{	Hey! How ya doin'?	}{	#	}{	npc.SetDisposition("Neutral", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	2	}{	I guess smoking isn't enough for you, handsome.	}{	I guess smoking isn't enough for you, handsome.	}{	11	}{	Seduction 5 & not IsMale(pc)	}{	}{	}{	}{	}{	}{	}{	}{	You need more than to puff, my beauty.	}
{	3	}{	Would you like to suck on something else than a cigar?	}{	Would you like to suck on something else than a cigar?	}{	11	}{	Seduction 5 & IsMale(pc)	}{	}{	}{	}{	}{	}{	}{	}{	Do you want to polish my pipe?	}
{	4	}{	Can I interest you in something else besides smoking?	}{	Can I interest you in something else besides smoking?	}{	21	}{	Seduction -5	}{	}{	}{	}{	}{	}{	}{	}{	Are you looking for more than blowing smoke?	}
{	5	}{	Sorry, I don't want to disturb you.	}{	Sorry, I don't want to disturb you.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	I don't want to intrude in your boredom.	}
{	11	}{	You got it.	}{	You got it.	}{	#	}{	npc.SetDisposition("Flirt", 1)	}{	G.Doll6_Seduce = 1	}{	}{	}{	}{	}{	}{	}{	}
{	12	}{	I hope you don't taste too strong of tobacco. Come here!	}{	I hope you don't taste too strong of tobacco. Come here!	}{	0	}{	}{	G.Seductive_Feed = 1; pc.SeductiveFeed(npc)	}{	}{	}{	}{	}{	}{	}{	I'll suck on you as if you were a cigar!	}
{	21	}{	That's a negative.	}{	That's a negative.	}{	#	}{	npc.SetDisposition("Apathy", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	22	}{	(Auto-End)	}{	(Auto-End)	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	31	}{	Can't help you with that, I'm afraid.	}{	Can't help you with that, I'm afraid.	}{	#	}{	npc.SetDisposition("Disgust", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	32	}{	I didn't even... oh, I see, the usual reaction.	}{	I didn't even... oh, I see, the usual reaction.	}{	21	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	41	}{	Well ain't that somethin'!	}{	Well ain't that somethin'!	}{	#	}{	npc.SetDisposition("Flirt", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	42	}{	I am back.	}{	I am back.	}{	11	}{	}{	}{	}{	}{	}{	}{	}{	}{	Here we are again.	}
{	44	}{	(Starting Condition)	}{	}{	31	}{	IsClan(pc,"Nosferatu")	}{	}{	}{	}{	}{	}{	}{	}{	}
{	45	}{	(Starting Condition)	}{	}{	41	}{	G.Doll6_Seduce == 1	}{	}{	}{	}{	}{	}{	}{	}{	}
{	46	}{	(Starting Condition)	}{	}{	1	}{	npc.times_talked == 1	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
{ 1 }{ Čau! Jak se vede? }{ Čau! Jak se vede? }{ # }{ npc.SetDisposition("Neutral", 1) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 2 }{ Tipuju, že pokuřování ti tak úplně nestačí, fešáku. }{ Tipuju, že pokuřování ti tak úplně nestačí, fešáku. }{ 11 }{ Seduction 5 & not IsMale(pc) }{ }{ }{ }{ }{ }{ }{ }{ Potřebuješ více než šlukovat, krasavče. }
{ 3 }{ Nechceš pokouřit něco kromě toho cigára? }{ Nechceš pokouřit něco kromě toho cigára? }{ 11 }{ Seduction 5 & IsMale(pc) }{ }{ }{ }{ }{ }{ }{ }{ Nechceš vyleštit moji fajfku? }
{ 4 }{ Nezajímalo by tě něco kromě kouření? }{ Nezajímalo by tě něco kromě kouření? }{ 21 }{ Seduction -5 }{ }{ }{ }{ }{ }{ }{ }{ Máte chuť na něco jiného než foukání kouře? }
{ 5 }{ Pardon, nechtěl jsem obtěžovat. }{ Pardon, nechtěla jsem obtěžovat. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Už se mi nechce narušovat vaši nudu. }
{ 11 }{ Rozhodně. }{ Rozhodně. }{ # }{ npc.SetDisposition("Flirt", 1) }{ G.Doll6_Seduce = 1 }{ }{ }{ }{ }{ }{ }{ }
{ 12 }{ Doufám, že příchuť tabáku nebude moc silná. Pojď sem! }{ Doufám, že příchuť tabáku nebude moc silná. Pojď sem! }{ 0 }{ }{ G.Seductive_Feed = 1; pc.SeductiveFeed(npc) }{ }{ }{ }{ }{ }{ }{ Vysaju tě jako doutník! }
{ 21 }{ Z toho nic nebude. }{ Z toho nic nebude. }{ # }{ npc.SetDisposition("Apathy", 1) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 22 }{ (Auto-End) }{ (Auto-End) }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 31 }{ S tím bohužel nepomůžu. }{ S tím bohužel nepomůžu. }{ # }{ npc.SetDisposition("Disgust", 1) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 32 }{ Vždyť jsem ještě nic... aha, obvyklá reakce. }{ Vždyť jsem ještě nic... aha, obvyklá reakce. }{ 21 }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 41 }{ No to se podívejme! }{ No to se podívejme! }{ # }{ npc.SetDisposition("Flirt", 1) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 42 }{ To jsem zase já. }{ To jsem zase já. }{ 11 }{ }{ }{ }{ }{ }{ }{ }{ }{ Opět se potkáváme. }
{ 44 }{ (Starting Condition) }{ }{ 31 }{ IsClan(pc,"Nosferatu") }{ }{ }{ }{ }{ }{ }{ }{ }
{ 45 }{ (Starting Condition) }{ }{ 41 }{ G.Doll6_Seduce == 1 }{ }{ }{ }{ }{ }{ }{ }{ }
{ 46 }{ (Starting Condition) }{ }{ 1 }{ npc.times_talked == 1 }{ }{ }{ }{ }{ }{ }{ }{ }

**Comment by miracleflame** [comment]
49dddb16
