### ISSUE TITLE
Preklad lip files updates 

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#495]
8752fc99

cestina\sound\character\dlg\hollywood\slater\line1_col_e.lip
"S'up- oh, uh, and welcome to Red Spot, home of the Monstro-Chug, 72 ounces of your favorite beverage for 89cents, blah... blah. You need some help or something?" 

cestina\sound\character\female\float_10.lip
Why didn't I do that before?

cestina\sound\character\female\float_11.lip
Parking validation.

cestina\sound\character\female\float_12.lip
Umm... ohhh, crap.

cestina\sound\character\female\float_13.lip
Ohhh, I should... No.

cestina\sound\character\female\float_9.lip
That's get idea...

cestina\sound\character\female\upset\float_1.lip
cestina\sound\character\female\upset\float_7.lip
cestina\sound\character\female\upset\float_8.lip
You're not allowed to be here!

cestina\sound\character\female\upset\float_10.lip
cestina\sound\character\female\upset\float_3.lip
You better leave!

cestina\sound\character\female\upset\float_11.lip
cestina\sound\character\female\upset\float_4.lip
Hey, what're you doing?

cestina\sound\character\female\upset\float_12.lip
cestina\sound\character\female\upset\float_5.lip
cestina\sound\character\female\upset\float_6.lip
You don't belong here.

cestina\sound\character\female\upset\float_2.lip
cestina\sound\character\female\upset\float_9.lip
I think you should go.

cestina\sound\character\male\italian_accent\upset\float_2.lip
Hey, do- you're not supposed to be here.

cestina\sound\character\male\italian_accent\upset\float_3.lip
(Italian mumble)... You- you need to be- you need to leave... You're not supposed to be here. 

cestina\sound\character\male\italian_accent\upset\float_4.lip
(Italian mumble)... You- you not supposed to be here... Who- who are you?

cestina\sound\character\male\officer\officer_2\float_10.lip
Stop or I'll...

cestina\sound\character\male\officer\officer_2\float_11.lip
Hey, stop!

cestina\sound\character\male\officer\officer_2\float_12.lip
Ahh... Stop, please.

cestina\sound\character\male\officer\officer_2\float_9.lip
I can have you arrested.

cestina\sound\character\male\officer\panicrun_loop.lip
Uh-huh, no! Officer in need of assistance!

cestina\sound\character\male\upset\float_1.lip
cestina\sound\character\male\upset\float_6.lip
You better move on.

cestina\sound\character\male\upset\float_10.lip
cestina\sound\character\male\upset\float_4.lip
What the..?

cestina\sound\character\male\upset\float_11.lip
You better make yourself scarce!

cestina\sound\character\male\upset\float_12.lip
What the..? You- you're not supposed to be here.

cestina\sound\character\male\upset\float_13.lip
I-it's time for you to get out of here!

cestina\sound\character\male\upset\float_14.lip
What- what're you doing here?

cestina\sound\character\male\upset\float_2.lip
cestina\sound\character\male\upset\float_8.lip
Stop it and get out of here.

cestina\sound\character\male\upset\float_3.lip
cestina\sound\character\male\upset\float_9.lip
What are you doing here?

cestina\sound\character\male\upset\float_5.lip
Huh? You're not supposed to be here!

cestina\sound\character\male\upset\float_7.lip
You better get out of here!

**Comment by soulcharmer** [comment]
cestina\sound\character\dlg\hollywood\slater\line1_col_e.lip
"Jak je? Aha, vítejte v Sámošce, kde máme Monstro-Chug, 2 litry oblíbenýho pití za 89 centů. Bla, bla, bla. Potřebujete s něčím pomoct?"

cestina\sound\character\female\float_10.lip
Proč jsem to neudělala už dřív?

cestina\sound\character\female\float_11.lip
Ověření parkovného.

cestina\sound\character\female\float_12.lip
Ehm... a sakra.

cestina\sound\character\female\float_13.lip
Aha. Musím... ne.

cestina\sound\character\female\float_9.lip
To je nápad...

cestina\sound\character\female\upset\float_1.lip
cestina\sound\character\female\upset\float_7.lip
cestina\sound\character\female\upset\float_8.lip
Tady nemáte co dělat!

cestina\sound\character\female\upset\float_10.lip
cestina\sound\character\female\upset\float_3.lip
Raději odejděte!

cestina\sound\character\female\upset\float_11.lip
cestina\sound\character\female\upset\float_4.lip
Hej, co to děláte?

cestina\sound\character\female\upset\float_12.lip
cestina\sound\character\female\upset\float_5.lip
cestina\sound\character\female\upset\float_6.lip
Sem nemáte přístup.

cestina\sound\character\female\upset\float_2.lip
cestina\sound\character\female\upset\float_9.lip
Bude lepší, když půjdete.

cestina\sound\character\male\italian_accent\upset\float_2.lip
Hej, co... tady nemáte co dělat.

cestina\sound\character\male\italian_accent\upset\float_3.lip
(mumlání v italštině)... Vy- musíte... odcházet... Tady nemáte co být.

cestina\sound\character\male\italian_accent\upset\float_4.lip
(mumlání v italštině) Vy- tady nemáte co být... Kdo jste?

cestina\sound\character\male\officer\officer_2\float_10.lip
Stůjte nebo...

cestina\sound\character\male\officer\officer_2\float_11.lip
Hej, stůjte!

cestina\sound\character\male\officer\officer_2\float_12.lip
Aha... Stůjte, prosím.

cestina\sound\character\male\officer\officer_2\float_9.lip
Můžu vás zatknout.

cestina\sound\character\male\officer\panicrun_loop.lip
A jéje, ne! Strážník potřebuje posily!

cestina\sound\character\male\upset\float_1.lip
cestina\sound\character\male\upset\float_6.lip
Radši se ztraťte.

cestina\sound\character\male\upset\float_10.lip
cestina\sound\character\male\upset\float_4.lip
Co to...?

cestina\sound\character\male\upset\float_11.lip
Radši odsud zmizte!

cestina\sound\character\male\upset\float_12.lip
Co to...? Tady- tady nemáte co dělat.

cestina\sound\character\male\upset\float_13.lip
Je na čase odsud vypadnout!

cestina\sound\character\male\upset\float_14.lip
Co- co tady chcete?

cestina\sound\character\male\upset\float_2.lip
cestina\sound\character\male\upset\float_8.lip
Nechte toho a vypadněte.

cestina\sound\character\male\upset\float_3.lip
cestina\sound\character\male\upset\float_9.lip
Co tady děláte?

cestina\sound\character\male\upset\float_5.lip
Co? Tady nemáte co dělat!

cestina\sound\character\male\upset\float_7.lip
Vypadněte odsud!

**Comment by miracleflame** [comment]
49dddb16
