### ISSUE TITLE
Preklad hackterminals

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#496]
288181c1

cestina\vdata\hackterminals\empire_lobby_computer.txt
			"name"		"Brooklyn"
			"description"	"Closed"
			"runtext"	"The Brooklyn Suite (5th floor) is CLOSED due to crime investigation."

			"name"		"Buffalo Suite"
			"description"	"Closed"
			"runtext"	"The Buffalo Suite (6th floor) is CLOSED due to crime investigation."

cestina\vdata\hackterminals\haven_pc.txt
		"subject"	"Knihovna"
		"sender"	"beckett@legend.vtm"
		"body"	"Zdravím tě, mládě. **LaCroix praised you as very capable, so maybe you can assist me with something.** Můj kolega Gangrel jménem Scott, který pro mě dělal ve veřejné knihovně výzkum ohledně toho nechvalně známého sarkofágu, si tam všimnul někoho z Lasombry! Jelikož jsem momentálně zaneprázdněn, sejdi se s ním prosím místo mě v santamonickém obchodě s kuřivem a zjisti podrobnosti. Přitomnost Sabbatu je ostatně vždy problém a nechceme přece, aby se naše vzácné znalosti dostaly do nesprávných rukou, není-liž pravda?
		"subject"	"Výtečně"
		"sender"	"beckett@legend.vtm"
		"body"	"Opět zdravím... Scott mi sdělil, že se ti v knihovně podařilo přerušit sabbatský přijímací rituál, při kterém téměř zahynul. **We are both very grateful for this, and he will make sure the access to the ritual chamber will be cut off in time**. Snad není zapotřebí zdůrazňovat, že by nebylo moudré se někomu o této nepříjemnosti zpovídat, **not even Sebastian.**
		"subject"	"Raketomet na prodej"
		"sender"	"gary@schrecknet.vtm"
		"body"		"Šéfe, mám tu další plakát, na který tu jen padá prach, jestli máš zájem. Vypadá to, že jedna Anarchka před uchvácením udělala nějaký 'umělecký' fotky. Bude celý tvůj **for the low, low price of one data CD**. Mělo by být v Metalhead Industries. Máš info od Mitnicka, že jo? Dej to do schránky, jako minule."
		"subject"	"Hledáš rande?"
		"sender"	"gary@schrecknet.vtm"
		"body"		"Je ti smutno, šéfe? Barabus se mi zmínil, že zahlédl ve Fu Syndikátu pomačkaný Ohavný kalich, údajně z Čínské čtvrti. Dám ti za něj plakát **of Claira Killenbach and her favorite drink.**"

cestina\vdata\hackterminals\jeanette_laptop.txt
		"line0"		"   Azyl"
		"line1"		"Hello Sweetheart"

cestina\vdata\hackterminals\kilpatricks_computer.txt
			"name"		"Muddy"			// this is what the player must type in to trigger this function. (16 characters)
			"description"	"Info o Muddym"		// this is a description of this function  (128 characters)
			"runtext"	"Radši nechci vědět, proč se mu říká Muddy...
**... and I'll never know, because now he's dead!"**

cestina\vdata\hackterminals\krime_computer.txt
			"name"		"Durbin, M"
			"description"	"Michael 'Muddy' Durbin"
			"runtext"	"Michael 'Muddy' Durbin
Jistina zapsána 5.3.04 -- Napadení.  Dříve odsouzen za automobilovou loupež a jiný případ loupeže.  Případ #777121.  Výše kauce: 10,000$.  Předmět kauce: Zástava - 01 Corvega, barva: šedá.  
Poznámky: Známý recidivista. Nebudu se divit, když zkusí zdrhnout."
Aktualizace 10/25/04 -- Po smrti. **Murdered by the serial killer.**"	// changed by wesp
			"name"		"Nilson, B"
			"description"	"Brian Nilson"
			"runtext"	"Brian Nilson
Jistina zapsána 1.12.01 -- Ublížení na zdraví.  Případ #245990.  Výše kauce: 10,000$.  Předmět kauce: Hotovost.  
Poznámky: Místní rváč hodil chlápka, co si od něj chtěl údajně koupit drogy, z přístupových schodů na pláž."
Aktualizace 10/24/04 -- Po smrti.      **Killed in a local fight.**"	// changed by wesp

cestina\vdata\hackterminals\shrekhub2_terminal.txt
		"subject"	"Spotlight!"
		"sender"	"sksp@company.vtm"
		"body"		"Did you leave the broken spotlight up on the railing? Someone will trip over it and break their neck! Put in into the workshop as soon as possible, I will not stow that away for you.

cestina\vdata\hackterminals\sinbin.txt
			"name"		"Murder!!!"
			"runtext"	"Somebody killed Chastity! What sicko would do that? Luckily the others are okay, but both want to take a leave now. I got a friend of mine to do a silent cleanup. Nobody knows who that prude bitch with her fake name was anyway!"	// changed by wesp
			"name"		"Murder!!!"
			"runtext"	"There was a bloodbath downstairs at the peepshow with several dead. I don't know if I can cover that up without the damned cops closing me down, but I will try my best!"	// changed by wesp

**Comment by soulcharmer** [comment]
cestina\vdata\hackterminals\empire_lobby_computer.txt
"name" "Brooklyn"
"description" "Zavřeno"
"runtext" "Apartmán Brooklyn (paté podlaží) je UZAVŘEN kvůli kriminálnímu vyšetřování."

		"name"		"Apartmán Buffalo"
		"description"	"Zavřeno"
		"runtext"	"Apartmán Buffalo (šešté podlaží) je UZAVŘEN kvůli kriminálnímu vyšetřování."

cestina\vdata\hackterminals\haven_pc.txt
"subject" "Knihovna"
"sender" "[beckett@legend.vtm](mailto:beckett@legend.vtm)"
"body" "Zdravím tě, mládě. LaCroix tě chválil pro výjimečné schopnosti, proto doufám, že mi budeš moci asistovat. Můj kolega Gangrel jménem Scott, který pro mě dělal ve veřejné knihovně výzkum ohledně toho nechvalně známého sarkofágu, si tam všimnul někoho z Lasombry! Jelikož jsem momentálně zaneprázdněn, sejdi se s ním prosím místo mě v santamonickém obchodě s kuřivem a zjisti podrobnosti. Přitomnost Sabbatu je ostatně vždy problém a nechceme přece, aby se naše vzácné znalosti dostaly do nesprávných rukou, není-liž pravda?
"subject" "Výtečně"
"sender" "[beckett@legend.vtm](mailto:beckett@legend.vtm)"
"body" "Opět zdravím... Scott mi sdělil, že se ti v knihovně podařilo přerušit sabbatský přijímací rituál, při kterém téměř zahynul. Oba jsme za to velmi vděčni a on se postará, aby ta rituální místnost byla brzy odříznuta. Snad není zapotřebí zdůrazňovat, že by nebylo moudré se někomu o této nepříjemnosti zpovídat, ani Sebastianovi.
"subject" "Raketomet na prodej"
"sender" "[gary@schrecknet.vtm](mailto:gary@schrecknet.vtm)"
"body" "Šéfe, mám tu další plakát, na který tu jen padá prach, jestli máš zájem. Vypadá to, že jedna Anarchka před uchvácením udělala nějaký 'umělecký' fotky. Bude celý tvůj za pouhé jedno datové CD. Mělo by být v Metalhead Industries. Máš info od Mitnicka, že jo? Dej to do schránky, jako minule."
"subject" "Hledáš rande?"
"sender" "[gary@schrecknet.vtm](mailto:gary@schrecknet.vtm)"
"body" "Je ti smutno, šéfe? Barabus se mi zmínil, že zahlédl ve Fu Syndikátu pomačkaný Ohavný kalich, údajně z Čínské čtvrti. Dám ti za něj plakát s Claire Killenbach a jejím oblíbeným drinkem."

cestina\vdata\hackterminals\jeanette_laptop.txt
"line0" " Azyl"
"line1" "Ahoj zlato"

cestina\vdata\hackterminals\kilpatricks_computer.txt
"name" "Muddy" // this is what the player must type in to trigger this function. (16 characters)
"description" "Info o Muddym" // this is a description of this function (128 characters)
"runtext" "Radši nechci vědět, proč se mu říká Muddy...
... a ani to nezjistím, páč už je po něm!"

cestina\vdata\hackterminals\krime_computer.txt
"name" "Durbin, M"
"description" "Michael 'Muddy' Durbin"
"runtext" "Michael 'Muddy' Durbin
Jistina zapsána 5.3.04 -- Napadení. Dříve odsouzen za automobilovou loupež a jiný případ loupeže. Případ #777121. Výše kauce: 10,000$. Předmět kauce: Zástava - 01 Corvega, barva: šedá.
Poznámky: Známý recidivista. Nebudu se divit, když zkusí zdrhnout."
Aktualizace 10/25/04 -- Po smrti. Zavražděn sériovým vrahem." // changed by wesp
"name" "Nilson, B"
"description" "Brian Nilson"
"runtext" "Brian Nilson
Jistina zapsána 1.12.01 -- Ublížení na zdraví. Případ #245990. Výše kauce: 10,000$. Předmět kauce: Hotovost.
Poznámky: Místní rváč hodil chlápka, co si od něj chtěl údajně koupit drogy, z přístupových schodů na pláž."
Aktualizace 10/24/04 -- Po smrti. Zabit při místní rvačce." // changed by wesp

cestina\vdata\hackterminals\shrekhub2_terminal.txt
"subject" "Reflektor!"
"sender" "[sksp@company.vtm](mailto:sksp@company.vtm)"
"body" "Ten rozbitej reflektor nechanej na zabradlí je tvoje práce? Někdo se tam o něj přerazí! Dej ho okamžitě zpátky do dílny, nebudu to za tebe dělat sám.

cestina\vdata\hackterminals\sinbin.txt
"name" "Vrazda!!!"
"runtext" "Někdo zabil Chastity! Co to je za úchyla? Ostatní jsou v pořádku, ale obě chcou odejít. Mám kámoše, co se v tichosti zbaví těla. Stějně nikdo neví, kdo ta prudérní děvka z falešným jménem vlastně byla!" // changed by wesp
"name" "Vrazda!!!"
"runtext" "Dole v peepshow došlo k masakru a několik lidí zařvalo. Nevím, jestli se mi to podaří před fízlama ututlat, ale udělám, co půjde!" // changed by wesp

**Comment by miracleflame** [comment]
32e39414
