### ISSUE TITLE
Preklad zvysok vdata

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#497]
2fe51253
8be670be

cestina\vdata\signs\newspaper_elizabeth_dane.txt
		"Text"				"ZÁHADA NA VODĚ"
		"Text"				"DAVY JONES SHOCKER"

cestina\vdata\signs\newspaper_oh_1.txt
		"Text"				"POŽÁR V HOTELU!"
		"Text"				"OCEAN HOUSE FIRE!"

cestina\vdata\signs\tutorial_popup_computers2.txt
Pokud tvá úroveň Hackování bude stejná nebo vyšší než úroveň zabezpečení dané položky, tvůj pokus se zdaří.
**To stop using a computer type \"quit\" or use the ESC key.**"	// changed by wesp"

cestina\vdata\system\quests_hollywood.txt
			"ID"		"4" // Killed Misti
			"Description"	"You killed Misti, so VV will no longer speak with you."
			"ID"		"11" // Killed Misti
			"Description"	"You killed Misti, so VV will no longer speak with you."
			"ID"		"2" // Flynn 431
			"Description"	"Máš pro Imalii výtisk časopisu Guy, **now deliver it to her.**"
			"ID"		"7"
			"Description"	"Gary nabízí plakát **Claira Killenbach** vyměnou za Ohavný kalich z Fu Syndikátu. Nech kalich ve schránce svého úkrytu a později si zkontroluj email."

cestina\vdata\system\quests_santamonica.txt
			"ID"		"6"     // line 71 of Gimble's dialog
			"Description"	"Při prohledávání McGeeova bytu you found a connection to Stan Gimble, výrobce protéz. Slíbil, že řekne, co ví o McGeeovi, pokud se zastavíš v jeho dílně, který je na konci Hlavní ulice v suterénním prostoru."

cestina\vdata\system\stats.txt
UP_Plus_CZ\vdata\system\stats.txt
				"HelpTextL2"	"V podřepu se můžeš neviditelně pohybovat. Efekt skončí, pokud se někoho dotkneš nebo provedeš nějaký zásah do svého okolí **or perform stealth kills**. Aktivace stojí jednu dávku krve a trvá 20 sekund."
				"HelpTextL3"	"Pod rouškou Mizení můžeš zabíjet zezadu **while staying invisible**. Nesmíš se ale dotknout oběti zepředu, jinak efekt skončí. Navíc kontaktní útok, který prolomí Mizení úrovně 3, bude o 50% účinnější. Aktivace stojí jednu dávku krve a trvá 22 sekund."

**Comment by miracleflame** [comment]
Tieto dva vlastne nemajú zmenu. Tento text bol rovnaký v predošlých verziách. Keď som to sem dával som si to neuvedomil, myslel som, že ide o zmenu textu.

cestina\vdata\signs\newspaper_elizabeth_dane.txt
"Text" "ZÁHADA NA VODĚ"
"Text" "DAVY JONES SHOCKER"

cestina\vdata\signs\newspaper_oh_1.txt
"Text" "POŽÁR V HOTELU!"
"Text" "OCEAN HOUSE FIRE!"

**Comment by soulcharmer** [comment]
cestina\vdata\signs\tutorial_popup_computers2.txt
Pokud tvá úroveň Hackování bude stejná nebo vyšší než úroveň zabezpečení dané položky, tvůj pokus se zdaří.
Práci v terminálu ukončíš příkazem "quit" nebo klávesou ESC." // changed by wesp"

cestina\vdata\system\quests_hollywood.txt
"ID" "4" // Killed Misti
"Description" "Máš na svědomí smrt Misti, takže VV už se s tebou nebude bavit."
"ID" "11" // Killed Misti
"Description" "Máš na svědomí smrt Misti, takže VV už se s tebou nebude bavit."
"ID" "2" // Flynn 431
"Description" "Máš pro Imalii výtisk časopisu Guy, Doruč jí ho."
"ID" "7"
"Description" "Gary nabízí plakát Clairy Killenbach vyměnou za Ohavný kalich z Fu Syndikátu. Nech kalich ve schránce svého úkrytu a později si zkontroluj e-mail."

cestina\vdata\system\quests_santamonica.txt
"ID" "6" // line 71 of Gimble's dialog
"Description" "Při prohledávání McGeeova bytu se ukázala spojitost se Stanem Gimblem, výrobcem protéz. Slíbil, že řekne, co ví o McGeeovi, když se zastavíš v jeho dílně, která je na konci Hlavní ulice v suterénním prostoru."

cestina\vdata\system\stats.txt
UP_Plus_CZ\vdata\system\stats.txt
"HelpTextL2" "V podřepu se můžeš neviditelně pohybovat. Efekt skončí, pokud se někoho dotkneš, provedeš nějaký zásah do svého okolí, nebo někoho v tichosti zabiješ. Aktivace stojí jednu dávku krve a trvá 20 sekund."
"HelpTextL3" "Pod rouškou Mizení můžeš zabíjet zezadu beze ztráty neviditelnosti Nesmíš se ale dotknout oběti zepředu, jinak efekt skončí. Navíc kontaktní útok, který prolomí Mizení úrovně 3, bude o 50% účinnější. Aktivace stojí jednu dávku krve a trvá 22 sekund."

**Comment by miracleflame** [comment]
c650f0ca
