### ISSUE TITLE
Hollywood dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#5]
andrei.dlg

Ah. It seems that these final nights have brought us together once again. I see you have begun to embrace the beast within you. I smell the sweetest blood of my brethren upon your very hands. But enough with the pleasantries. Witness the power of my flesh, transformed into the vessel of your destruction. Farewell young cainite.
Á. Zdá se, že konec světa nás opět přivedl k sobě. Vidím, že už jsi začal objímat bestii v tvém nitru. Cítím sladkou krev mých bratů na tvých rukou. Ale dost už bylo hezkých řečiček. Buď svědkem moci mého masa, přetransformovaného v koráb tvého zničení. Sbohem mladý vampíre.
Á. Zdá se, že konec světa nás opět přivedl k sobě. Vidím, že už jsi začala objímat bestii v tvém nitru. Cítím sladkou krev mých bratů na tvých rukou. Ale dost už bylo hezkých řečiček. Buď svědkem moci mého masa, přetransformovaného v koráb tvého zničení. Sbohem mladá vampírko.

I know you, you were at the junkyard in Santa Monica. Time to die, Sabbat freak!
Tebe já znám, byl jsi na santamonickém vrakovišti. Žas zemřít, Sabbatká zrůdo!

My eyes have seen you before, Sword of Caine. And now they will see you die!
Mé oči tě už viděli, Kainův meči. A teď tě uvidí umírat!

Actually I'm interested in the Sabbat myself. But threatening me can only have one result!
Vlastně se sám zajímám o Sabbaty. Ale výhrůžky můžou mít jediný následek!
Vlastně se sama zajímám o Sabbaty. Ale výhrůžky můžou mít jediný následek!

I want to become Sword of Caine myself, maybe I will take your place!
I já se chci stát Kainovým mečem, možná nahradím tvé místo!

Good observation! Maybe I should join the Sabbat...
Dobrý postřeh! Možná bych měl vstoupit mezi Sabbati...
Dobrý postřeh! Možná bych měla vstoupit mezi Sabbati...

You look through me like I do. Should I join the Sword of Caine?
Díváš se na mně jako já. Přidám se ke Kainovmu meči?

You know I am quite fascinated by the bloody architecture. In reality it's even better than on the tape!
Víš co, jsem opravdu fascinován tou krvavou architekturou. Naživo je ještě lepší než na té pásce!
Víš co, jsem opravdu fascinována tou krvavou architekturou. Naživo je ješti lepší než na té pásce!

Not too much for those of us able to give the gift of metamorphosis, young one. I know you have a cold appreciation for the aesthetic of my creations, I see awe and longing in your eyes.
Je to nic pro nás schopných daru metamorfózy, mládě. Já vím, že máš chladné uznání pro estetičnost mých stvoření, vidím v tých očích úžas a touhu.

Yeah, you see the longing to kill you!
To jo, vidíš touhu zabít tě!

Aww, I am longing for you to be dead already... again!
Óó, já tak toužím, abys už byl mrtvý... zas!

Not really!	But what else can you offer?
Ani ne! Ale co jiného můžeš nabídnout?

What else can you give to us?
Co jiného nám můžeš dát?

I'm not interested in becoming your sculpture, but we might still work together, Sabbat.
Nemám zájem stát se tvou sochou, ale pořád můžeme spolupracovat, Sabbate.

I will stay as I am, but we can still play together, Sword of Caine.
Zůstanu, čím jsem, ale pořád si můžem spolu hrát, Kainův meči.

Amazing! Can I learn that if I join the Sabbat?
Parádní! Můžu se to naučit pokud se přidám k Sabbatům?

Will I get this gift when I become Sword of Caine?
Dostanu tento dar pokud se stanu Kainovým mečem?

Nobody will miss them. Looks like I would fit well into the Sabbat!
Nikomu nebudou chybět. Zdá se, že bych dobře zapadnul mezi Sabbaty!
Nikomu nebudou chybět. Zdá se, že bych dobře zapadla mezi Sabbaty!

They are gone with the wind. I am sharp like the Sword of Caine!
Odvanul je vítr. Já jsem jako ostří Kainovho meče!

The Sabbat, I'm interested in that. Do they do what you tell them?
Sabbati, o to se zajímám. Dělaj vše co jim řekneš?

I want to learn about the Sword of Caine. Are they following your lead?
Chci se učit o Kainovém meči. Následují tvé vedení?

It must have been a lot of work to create these "machines".
Muselo to dát spoustu práce stvořit tyhle "stroje".

Much work to build the "machines", yes?
Spousta práce postavit tyhle "stroje", ano?

You are right, they are small but powerful. I like them!
Máš pravdu, jsou malé, no mocné. Líbí se mi!

I like your little animals of terror!
Líbí se mi tvá malá zvířátka teroru!

I'm rather intrigued by it. Why did you create these creatures?
Docela mě to zajímá. Proč jsi stvořil tyhle stvůry?

Didn't you listen, I want to join you. Or is this some kind of test? If so, go ahead!
Neposlouchal jsi snad, že se chci k tobě přidat? Nebo to je nejaký druh zkoužky? Pokud ano, pokračuj!

Oh, you want to test my power before I can join. I will win!
Ó, chceš otestovat mou moc než se přidám. Já zvítezím!

That sounds bad! Maybe I can join the Sabbat to prevent this.
To zní špatně! Možná se můžu přidat k Sabbatům a zabránit tomu.

We want to become Sword of Caine to stop this fate!
Chceme se přidat ke Kainovmu meči a zastavit to!

No, because you knew that I was coming for you.
Ne, protože jsi vědel, že si pro tebe přijdu.

You surely remembered seeing me only some bloody killings ago.
Zajisté si pamatuješ naše shledání před jenom pár krvavými okamžiky.

Greetings.
Buď pozdraven.
Buď pozdravena.

It looks as if I was more powerful than all of your creatures in the end. So did I pass that test and can join the Sabbat now?
Zdá se, že jsem byl nakonec mocnější ne všechna tvá stvoření. Takže jsem prošel zkouškou a můžu se přidat k Sabbatům?

Did I win the duel to become Sword of Caine by killing all of your little pet machines?
Jsme vítezem duelu o Kainův meč tím, že jsme pobili všechna tvá malá zvířátka?

Yes.
Ano.

Great!
Výborně!

Happy, happy, happy!
Hurá, hurá, hurá!

What do you want?
Co chceš?

LaCroix send me to kill you.
LaCroix mě posílá, abych tě zabil.
LaCroix mě posílá, abych tě zabila.

I came here to kill you for the jester.
Přišli jsme sem zabít tě pro šaška.

What did you say?
Co jsi to řekl?
Co jsi to řekla?

Relax, I will just tell him I did the job.
Uklidni se, prostě mu řeknu, že je to hotovo.

I will lie to him like I always do to myself.
Budu mu lhát jako lžu vždy sobě.

You heard me, I will do exactly what he ordered.
Slyšel jsi, udelám přesne co si objednal.

Listen and learn, I will do what he wants.
Poslouchej a uč se, udělám, co chce.

Thank you.
Ďekuji.

Then I'll kill his Kuei-Jin bitch and hand him to you on a plate!
Pak zabiju jeho štětku Kuei-Jin a přinesu ti ho na podnosu!

Later I'll break his mirror mistress and make fun of him for you!
Pozdeji rozbiju jeho zrcadlovou čarodějku a udělám si z něj srandu pro tebe!

I cannot help you with that.
S tím ti nepomůžu.

No problem, I'll do it alone.
Žádný problém, udělám to sám.
Žádný problém, udělám to sama.

I will fight on my own.
Budu bojovat na vlastnou pěst.

The beginning of our future together? So you made the tape.
Začátek naší společné budoucnosti? Takže ty jsi natočil tu pásku.

I am pleased.
Jsem potěšen.

Why are you so taciturn today?
Proč jsi dnes tak stručný?

Do you have no more lines to say?
Nemáš víc vět, co bys mi řekl?

I don't know.
Nevím.

Then let's do it!
Tak to udělejme!

Let us start, NOW!
Začnime, HNED!

This might indeed be true. So you made the tape?
Tohle vskutku může být pravda. Takže jsi natočil tu pásku?

One more thing...
Ještě jedna věc...

Take this.
Vem si tohle.

I'll cut down our enemies with it.
Rozsekám tím naše nepřátele.

Oh, a magic sword to kill our enemies!
Ó, kouzelný meč prosti našim nepřátelům!

What!?!
Cože!?!

I changed my mind, after seeing what you did to this girl here!
Změnil jsem názor po tom, co jsi udělal této dívce tu!
Změnila jsem názor po tom, co jsi udělal této dívce tu!

My other self didn't like your behaviour towards the flower on the wall.
Mému druhému já se nelíbi co jsi proved tady té květince na zdi.

I no longer wish to speak with you.
Už si víc nepřeju s tebou mluvit.

Yeah, talking time is over. Time to die, freak!
Jo, čas na mluvení vypršel. Nastal čas zemřit, zrůdo!

No more talking. Dying time is here, false prophet!
Už žádné mluvení. Nastal čas zemřit, falešný proroku!

What the hell is going on in here? This place is a madhouse!
Co se to tady do pekla děje? Tohle místo je šílenství!

Frightening? Take a look at this grill, buddy.
Desivé? Podívej se na tenhle gril, kámo.

Ah! The Sword of Caine!
Á! Kainův meč!

ash.dlg

Change your mind?
Změna názoru?

Indeed.
Jistě.

I have.
Stalo se.

Don't go anywhere. I'll be back.
Nikam nechoď. Já se vrátím.

It will be well spent.
Dobře to investuju.

Gold for good!
Zlato pro dobro!

And... cut!
A... střih!

I know that place...
Znám to místo...

dhatter.dlg

You just want to give it to me nevertheless.
Prostě mi ho chcete dát tak či tak.

He will love to meet a being like me.
S osobou jako já se nadšeně setká.

Hey you! Hands in plain view, uh? Let's keep 'em above the waist there, pal.
Hej! Ruce tak, abych na ně viděl, jo? Drž je takhle nad pasem, chlape.
Hej! Ruce tak, abych na ně viděl, jo? Drž je takhle nad pasem, děvče.

Maybe I can use some of your stuff, show me what you got.
Možná by se mi hodilo něco z ponuky, ukaž. co máš.

Here are my eyes, show them your courtesy.
Tady jsou mé oči, ukaž jim svůj majetek.

Isaac.dlg

[This line is for something not connected to Hollywood][Irritated]A kangaroo court…
[This line is for something not connected to Hollywood][Irritated]Kengurový dvůr…

I'll get back to looking for that tape. Later, Isaac.
Jdu pokračovat v hledání té pásky. Nashle Izaaku.

My search continues... I am gone.
Mé hledání pokračuje... Jsem pryč.

And second... Nothing. Forget it. I have to go.
A podruhé... Nic. Zapomeňte na to. Musím jít.

And the secret... I won't tell... I won't tell....
A tajemství... neprozradím... neprozradím...

I've learned something about the Gargoyle.
Zjistil jsem něco o chrličovi.
Zjistila jsem něco o chrličovi.

I know something I won't tell... maybe.
Vím něco, co neřeknu... možná.

First of all, I've killed the Gargoyle.
Ze všeho nejdřív, zabil jsem chrliče.
Ze všeho nejdřív, zabila jsem chrliče.

First, the stone one lies in pieces.
Poprvé, kamenný leží v troskách.

First of all, I've convinced it to be loyal to you.
Ze všeho nejdřív, přesvědčil jsem chrliče, aby vám byl lojální.
Ze všeho nejdřív, přesvědčila jsem chrliče, aby vám byl lojální.

First, the baron attained the loyalty of the stone one.
Poprvé, baron získal lojalitu kamenného.

It's nothing. Forget it. I have to go.
To nic. Zapomeňte na to. Musím jít.

I won't tell... I won't tell....
Neřeknu.. neřeknu...

Oh, and I found a Tremere book about Gargoyles too. Have fun!
A také jsem našel Tremerskou knihu o chrličích. Příjemnou zábavu!
A také jsem našla Tremerskou knihu o chrličích. Příjemnou zábavu!

The blood wizards wrote this about the bloody thing too. Have a good read!
Krvavý čaroděj napsal tohle o těch krvavých věcech. Příjemné čtení!

Thanks, but I'll take a cab.
Díky, ale vemu si taxík.

I'll trust the guy in the yellow car.
Spolehnu se na chlápka v žlutém aute.

Thanks, but I've got my own way of getting there.
Díky, ale mám své spůsoby jak se tam dostanu.

Care to join me in a private room?
Stojíš o mou společnost v soukromé místnosti?

I will.
Zatočím.

Hell and back with me!
Do pekla a spátky se mnou!

misti.dlg

Hm, I'm not hungry right now, just dance for me!
Hm, teď akorát nemám hlad , jenom mi zatanči!

Shake it baby!
Roztoč je, bejby!

romero.dlg

Sounds boring. Anything else you may need?
To zní jako nuda. Něco jiného nepotřebuješ?

The same and the same and the same. Need something new?
To samé a to samé a to samé. Něco nového nepotřebuješ?

Any chance for me to do some zombie killing?
Je tady pro mě šance na nejaké kálení zobií?

Can I be the hammer?
Mohu být kladivem?

No need, really.
Není třeba, vážne.

We don't need this.
Tohle nepotřebujeme.

Have fun.
Užij si.

All these little pictures...
Všechny tydle obrázečky...

I will bring someone back for you.
Někoho ti přivedu.

I will catch some prey for you.
Ulovím ti nejakou oběť.

So you are hot again?
Takže jsi zas  nadrženej?

I see you are burning inside!
Vidím jak uvnitř hoříš!

slater.dlg

Thanks. I'll ask him. Goodbye.
Díky. Zeptám se ho. Sbohem.

Zeptám se Flynna, až budu pryč.

You must be at least as high as this counter to buy alcohol, porn, and/or cigarettes.
Musíte být alespoň tak vysoký, ako ukazatel, když chcete kupovat alkohol, porno anebo cigarety.

You don't like my stoop?
Nelíbí se vám, že se hrbím?

You gonna buy something? This ain't your momma's house, okay, we ain't giving it away for free, alright?
Koupíte si něco? Tady nejste u mamky na návštěvě, jasný, nedáváme tu nic zadarmo, dobře?

tommy.dlg

People like you should warn me about a bad restaurant like this.
Lidé jako vy by mě měli varovat před tak špatnou restaurací, jako je tahle.

I would rather join you for a drink right now.
Raději si s vami vypiju hned teď.

No need to leave to get some tasty liquid.
Není potřeba odcházat pro lahodný mok.

vv.dlg

And here's the screenplay.
A tady je scénář.

The Hatter's words, for you too.
Hatterova slova, také pro vás.

My pleasure, thanks.
Potěšení je na mé strane, dík.

I'll keep you in my heart and the picture in my pocket.
Uchovám si vás v srdci a obrázek v mé kapse.

**Comment by soulcharmer** [comment]
tyhle radky jsem nenasel"

Hey you! Hands in plain view, uh? Let's keep 'em above the waist there, pal.
Hej! Ruce tak, abych na ně viděl, jo? Drž je takhle nad pasem, chlape.
Hej! Ruce tak, abych na ně viděl, jo? Drž je takhle nad pasem, děvče.

Maybe I can use some of your stuff, show me what you got.
Možná by se mi hodilo něco z ponuky, ukaž. co máš.

Here are my eyes, show them your courtesy.
Tady jsou mé oči, ukaž jim svůj majetek.

**Comment by soulcharmer** [comment]
jinak hotovo
