### ISSUE TITLE
UP 11.1 Plus main menu logo

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#500]
Before:
![image](https://user-images.githubusercontent.com/19254203/163030544-063e229e-386f-4f35-9327-67f4c83d3cfe.png)

After:
![image](https://user-images.githubusercontent.com/19254203/163030305-c88d20aa-c60b-4159-8b27-d4e696d39bd2.png)

Táto textúra prepíše pôvodné české logo so sponzormi.
Ako s tým naložiť?

**Comment by soulcharmer** [comment]
prepsat, dokud byl sponzoring pri vyrabeni prekladu (a mnoho let po te), byla tam loga uvedena. Ted uz nekolik let udrzujeme cestinu sami a zadny sponzoring nemame ani nepotrebujeme.

Dik.

**Comment by miracleflame** [comment]
Ja si práve nemôžem dovoliť tvrdiť, že by som sponzoring nepotreboval, ale o tom asi inakade.
Je to v repe, takže to tam ponechávam.
