### ISSUE TITLE
preklad item_w_rem_m_700_bach.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#502]
"ammoprintname"			".308 High Velocity Round"	// changed by Wesp
		"ammodescription"		"A .308 Winchester Match King rifle round for precise sniping with Remington rifles."	// changed by Wesp

		_"ammoprintname"			"Dalekonosná munice"
		"ammodescription"		"Náboje ráže .308, nejčastěji určené k odstřelování."_

**Comment by soulcharmer** [comment]
_"ammoprintname"		"Dalekonosná munice"
	"ammodescription"		"Náboje .308 Winchester Match King pro přesné odstřelování z pušek Remington."_
