### ISSUE TITLE
preklad loadingtips.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#504]
To avoid trouble when arriving select the target location on the map with a mouse button that is not used to trigger an attack or choose fists as your weapon before you travel."	// changed by wesp

Feed often and maintain your Humanity to prevent frenzy."

**Comment by soulcharmer** [comment]
Pokud nechceš způsobit potíže při příjezdu do nové oblasti přes mapu, ujisti se, že tlačítko myši, které používáš pro výběr cíle, není namapováno na útok nebo před výběrem místa na mapě přepni svou zbraň na pěsti." // changed by wesp

Záchvatům běsu se můžeš vyhnout, pokud budeš pravidelně doplňovat svou zásobu krve a udržovat svou Lidskost."
