### ISSUE TITLE
stats.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#505]
The victim is shown his greatest waking Nightmares, eventually causing a heart attack.

The target and any others nearby all suffer a fatal episode.

EDIT:
Odstránil som disciplíny, ktoré sme v minulosti neprekladali a asi slúžia na multiplayer alebo čo.

**Comment by soulcharmer** [comment]
Vyvolá u oběti její nejhorší noční můry, které ve finále způsobí zástavu srdce.

Cíl a všichni ostatní v blízkém okolí utrpí smrtelný záchvat.
