### ISSUE TITLE
preklad strings.txt

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#506]
"Name5"		"In the game of life, your reading skills are ET for the 2600."
			"Name6"		"Vampire might not need glasses, but they DO need 'Hooked on Phonics.'"

**Comment by soulcharmer** [comment]
"Name5"		"Tvoje schopnosti číst jsou bohužel někde na úrovni batolete."
"Name6"		"Vampíři sice nemusí nosit brýle, ale měli by aspoň jednou zvládnout slabikář."
