### ISSUE TITLE
Celej žhavá jack.dlg {846}

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#51]
Nie som si celkom istý, či tento gramatický tvar použiteľný v českom slangu , preto som to nepushoval, takže to nechávam na Teba.

{	846	}{	[chuckle]Jseš celej žhavej se zavděčit, co? Mně je to celkem šumafuk, ale ostatní odsud by určitě ocenili, kdyby ses do toho moc nemixoval, jasný?	}{	[chuckle]Jseš celej žhavá se zavděčit, co? Mně je to celkem šumafuk, ale ostatní odsud by určitě ocenili, kdyby ses do toho moc nemixovala, jasný?	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

**Comment by soulcharmer** [comment]
Jo, to je preklep. A jeste bych nahradil to "nemixoval" na konci, takze cela spravena replika je:

{ 846 }{ [chuckle]Jseš celej žhavej se zavděčit, co? Mně je to celkem šumafuk, ale ostatní odsud by určitě ocenili, kdyby ses do toho moc nemontoval, jasný? }{ [chuckle]Jseš celá žhavá se zavděčit, co? Mně je to celkem šumafuk, ale ostatní odsud by určitě ocenili, kdyby ses do toho moc nemontovala, jasný? }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }

Je to tvoje, diky.
