### ISSUE TITLE
Preklad Combat knife

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#512]
49d78cdc

UPbasicCZ\vdata\items\item_w_avamp_blade.txt
	"printname"		"Combat Knife"	// changed by wesp
	"description"		"Some knives are used to carve up food. Some knives are used to carve up people. This is one of the latter."	// changed by wesp

**Comment by soulcharmer** [comment]
UPbasicCZ\vdata\items\item_w_avamp_blade.txt
"printname" "Bojový nůž" // changed by wesp
"description" "Některé nože jsou na krájení jídla. Jiné nože jsou na krájení lidí. Tento patří do té druhé skupiny." // changed by wesp
