### ISSUE TITLE
Preklad signs 4e6548da

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#513]
4e6548da

pier_note.txt
"Beckett,  the  meeting  here  seems  to  be  a  trap!  In  case  I  don't  make  it,  check  the  shop  on  the  move  in  Santa  Monica.  I  left  the  door  unlocked,  my  password  is  the  city  of  the  coffin.  -Scott"

smoke_note.txt
"Beckett,  couldn't  wait  any  longer.  The  guy  left  early.  He  intends  to  meet  someone  at  the  end  of  the  pier.  Hope  to  see  you  there.  -Scott"

tutorial_popup.txt
		"Text"		"                       Warning!
It seems as if an important Python script has not been compiled correctly on your system!
You are probably playing inside a Linux Wine environment without running from loader.exe.
Find it as VtM Bloodlines Game Mod Loader in the user programs section of the start menu!"

**Comment by soulcharmer** [comment]
pier_note.txt
"Beckette, tahleta schůzka vypadá na nějakou past! Kdybych to nedal, zajdi do obchodu, co se stěhuje ze Santa Moniky. Nechal jsem otevřený dveře a heslo je město sarkofágu. -Scott"

smoke_note.txt
"Beckette, už jsem nemohl dýl čekat. Ten týpek odešel brzo. Chce se s někým potkat na konci promenády. Doufám, že se tam uvidíme. -Scott"

tutorial_popup.txt
"Text" " Varování!
Zdá se, že se na tomto systému nepodařilo zkompilovat jeden důležitý skript v Pythonu!
Zřejmě hraješ v prostředí Linux Wine bez spustění loader.exe.
Najdeš ho pojmenovaný jako VtM Bloodlines Game Mod Loader mezi uživatelskými programy v úvodním menu."
