### ISSUE TITLE
Preklad vdata ee087376

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#515]
ee087376

UPbasicCZ\vdata\system\quests_chinatown.txt
			"ID"		"4" // 	kill ox
			"Description"	"**You have made Mr. Ox vanish**, takže jakékoliv dohody s ním jsou tímto anulovány."

			"ID"		"2" // 	place talisman
			"Description"	"Podařilo se ti umístit talisman neštěstí. **Now report back to Mr. Ox.**"

			"ID"		"3" // 	Shu 31, 41, Shu killed
			"Description"	"Vyřídil(a) sis to s Shuem, protože tě chytil, jak schováváš do skříňky talisman od pana Oxe. **You should return to him now."**

			"ID"		"6" // 	kill ox
			"Description"	"**You have made Mr. Ox vanish**, takže jakékoliv dohody s ním jsou tímto anulovány."

UPbasicCZ\vdata\system\quests_downtown.txt
			"ID"		"3" // Milligan 71,91, 111, 151 / killing Milligan, changed by wesp
			"Description"	"Problém s Milliganem jsi pro Pishu vyřesil(a). **Go back to the abandoned hospital and tell her.**"

			"ID"		"4"
			"Description"	"**You found Ash captured and tortured at the Society of Leopold. Why don't you help him this time?**"

			"Description"	"Dorazil(a) jsi do obchodu s kuřivem, ale Beckettův přítel tam nebyl. Avšak objevil(a) jsi odkaz, **suggesting that something is going down at the end of the Santa Monica Pier.**"

			"Description"	"**At the end of the Santa Monica pier you found signs of a bloody fight and a hastily scrawled paper telling you to investigate the \"shop on the move\" in Santa Monica. And a password is supposed to be the \"city of the coffin\**"

			"Description"	"**You searched the Santa Monica Coffee Shop and found Scott's laptop. His journal noted**, že můžeš vniknout do městské knihovny přes kanalizaci. Nejvyšší čas to udělat."

UPbasicCZ\vdata\system\quests_hollywood.txt
			"ID"		"5" // Ash 531
			"Description"	"You didn't help Ash in Hollywood and he got caught by the hunters."

UPbasicCZ\vdata\system\quests_santamonica.txt
			"ID"		"11" // Killer
			"Description"	"You went to the pier to look for the murder mentioned in the newspaper, but there was nothing visible anymore. Better keep your eyes open though."

			"ID"		"4"
			"Description"	"Ming-Xiao will deal with LaCroix and the sarcophagus."
			"Type"		"success"
		}
		CompletionState
		{
			"ID"		"5"
			"Description"	"The Sabbat will deal with LaCroix and the sarcophagus."
			"Type"		"success"
		}
		CompletionState
		{
			"ID"		"6"
			"Description"	"LaCroix and you will open the sarcophagus together."
			"Type"		"success"
		}
		CompletionState
		{
			"ID"		"7"
				"Description"	"You gave the key to LaCroix. Let him open his precious sarcophagus if he must, you will stay with the Anarchs."
			"Type"		"success"
		}
		CompletionState
		{
			"ID"		"8"
			"Description"	"The Regent will deal with LaCroix and the sarcophagus."
			"Type"		"success"
		}
		CompletionState
		{
			"ID"		"9"
			"Description"	"You gave the key to LaCroix. Let him open his precious sarcophagus if he must, you will find your own unlife."
			"Type"		"success"
		}
		CompletionState
		{
			"ID"		"10"
			"Description"	"You kept the key to open the sarcophagus yourself."
			"Type"		"success"
		}
		CompletionState
		{
			"ID"		"11"
			"Description"	"Congratulations, you found the easter egg ending."

**Comment by soulcharmer** [comment]
UPbasicCZ\vdata\system\quests_chinatown.txt
"ID" "4" // kill ox
"Description" "Díky tobě pan Ox zmizel, takže jakékoliv dohody s ním jsou tímto anulovány."

"ID"		"2" // 	place talisman
"Description"	"Podařilo se ti umístit talisman neštěstí. Jdi to vyřídit panu Oxovi."

"ID"		"3" // 	Shu 31, 41, Shu killed
"Description"	"Vyřídil(a) sis to s Shuem, protože tě chytil, jak schováváš do skříňky talisman od pana Oxe. Vrať se za ním."

"ID"		"6" // 	kill ox
"Description"	"Díky tobě pan Ox zmizel, takže jakékoliv dohody s ním jsou tímto anulovány."

UPbasicCZ\vdata\system\quests_downtown.txt
"ID" "3" // Milligan 71,91, 111, 151 / killing Milligan, changed by wesp
"Description" "Problém s Milliganem jsi pro Pishu vyřesil(a). Vrať se do opuštěné nemocnice a řekni jí to."

"ID"		"4"
"Description"	"Ash byl zajat a mučen Leopoldovou společností. Pomůžeš mu aspoň tentokrát?"

"Description"	"Dorazil(a) jsi do obchodu s kuřivem, ale Beckettův kontakt tam nebyl. Avšak objevil(a) jsi odkaz, že se něco stalo na konci santamonické promenády."

"Description"	"Na santamonické promenádě se ti podařilo najít známky po krvavém boji a narychlo napsanou poznámku o obchodě, \"který se stěhuje\" ze Santa Moniky. Heslo by mělo být \"město sarkofágu\"."

"Description"	"Prohledal(a) jsi santamonický obchod s kávou, kde byl Scottův počítač. V jeho poznámkách stálo, že můžeš vniknout do městské knihovny přes kanalizaci. Nejvyšší čas to udělat."

UPbasicCZ\vdata\system\quests_hollywood.txt
"ID" "5" // Ash 531
"Description" "Nepomohl(a) jsi Ashovi v Hollywoodu a lovci jej dopadli."

UPbasicCZ\vdata\system\quests_santamonica.txt
"ID" "11" // Killer
"Description" "Hledal(a) jsi na promenádě známky po vraždě z novin, ale už tam nebylo nic k vidění. Bude ale dobré mít se na pozoru."

"ID"		"4"
"Description"	"Ming-Xiao vyřeší situaci s LaCroixem a sarkofágem."
"Type"		"success"
	}
CompletionState
	{
"ID"		"5"
"Description"	"Sabbat vyřeší situaci s LaCroixem a sarkofágem."
"Type"		"success"
	}
CompletionState
	{
"ID"		"6"
"Description"	"LaCroix otevře sarkofág spolu s tebou."
"Type"		"success"
	}
CompletionState
	{
"ID"		"7"
"Description"	"Klíč jsi dal(a) LaCroixovi. Ať si ten svůj sarkofág otevře sám. Ty zůstáváš s Anarchy."
		"Type"		"success"
	}
CompletionState
	{
"ID"		"8"
"Description"	"Regent vyřeší situaci s LaCroixem a sarkofágem."
"Type"		"success"
	}
CompletionState
	{
"ID"		"9"
"Description"	"Klíč jsi dal(a) LaCroixovi. Ať si ten svůj sarkofág otevře sám. Ty jsi najdeš svůj vlastní osud."
		"Type"		"success"
	}
CompletionState
	{
"ID"		"10"
"Description"	"Nechal(a) sis klíč k otevření sarkofágu."
"Type"		"success"
	}
CompletionState
	{
"ID"		"11"
"Description"	"Gratulujeme, podařilo se ti najít tajný konec hry."
