### ISSUE TITLE
Preklad dlg chinatown d78de2a5

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#516]
d78de2a5

UPbasicCZ\dlg\chinatown\barabus.dlg
{	6	}{	Calm down, I'm not one of them.	}{	Calm down, I'm not one of them.	}{	11	}{	}{	}{	}{	}{	}{	}{	}{	}{	Behave, I am your kind of monster.	}
{	72	}{	My pleasure.	}{	My pleasure.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Thank to me too.	}

UPbasicCZ\dlg\chinatown\barry_r.dlg
{	2	}{	The guy with the ponytail and glasses at the table mi to odkýval.	}{	The guy with the ponytail and glasses at the table mi to odkýval.	}{

UPbasicCZ\dlg\chinatown\ji.dlg
{	432	}{	Whatever.	}{	Whatever.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	No ass kicking today.	}

UPbasicCZ\dlg\chinatown\lufang.dlg
{	329	}{	Teď když mi oba nabízíte stejnou slevu, jeden z vás musí jít.	}{	Teď když mi oba nabízíte stejnou slevu, jeden z vás musí jít.	}{	391	}{	G.Lu_Ji > 3 and G.Ji_Lu != 6	}{	}{	}{	}{	}{	}{	}{	}{	I'll net the same from your nest egg now, so one of you has to go.	}
{	392	}{	Whatever.	}{	Whatever.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	No ass kicking today.	}
{	482	}{	No problem.	}{	No problem.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	We don't worry.	}

UPbasicCZ\dlg\chinatown\wongho.dlg
{	142	}{	See ya.	}{	See ya.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	I'll be back.	}
{	162	}{	See ya.	}{	See ya.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	I'll be back.	}

UPbasicCZ\dlg\chinatown\yukie.dlg
{	304	}{	Je mi líto, ale veřím, že jsem ho zabil u Rudého draka. A tough guy with yellow eyes? }{	Je mi líto, ale veřím, že jsme ho zabila u Rudého draka. A tough guy with yellow eyes?	}
{	413	}{	Je mi líto, ale veřím, že jsem ho zabil u Rudého draka. A tough guy with yellow eyes?	}{	Je mi líto, ale veřím, že jsem ho zabila u Rudého draka. A tough guy with yellow eyes?	}

**Comment by soulcharmer** [comment]
UPbasicCZ\dlg\chinatown\barabus.dlg
{ 6 }{ Klídek, nejsem jeden z nich. }{ Klídek, nejsem jedna z nich. }{ 11 }{ }{ }{ }{ }{ }{ }{ }{ }{ Chovej se slušně, Já jsem v tvém týmu. }
{ 72 }{ Rádo se stalo. }{ Rádo se stalo. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Také si děkuji. }

UPbasicCZ\dlg\chinatown\barry_r.dlg
{ 2 }{ Chlápek u stolu v brýlích a s culíkem mi to odkýval. }{ Chlápek u stolu v brýlích a s culíkem mi to odkýval. }{

UPbasicCZ\dlg\chinatown\ji.dlg
{ 432 }{ Jak myslíš. }{ Jak myslíš. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Dnes tedy žádná bitka. }

UPbasicCZ\dlg\chinatown\lufang.dlg
{ 329 }{ Teď když mi oba nabízíte stejnou slevu, jeden z vás musí jít. }{ Teď když mi oba nabízíte stejnou slevu, jeden z vás musí jít. }
{ 392 }{ Jak myslíš. }{ Jak myslíš. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Dnes tedy žádná bitka. }
{ 482 }{ Není problém. }{ Není problém. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Nemáme problém. }

UPbasicCZ\dlg\chinatown\wongho.dlg
{ 142 }{ Nashle. }{ Nashle. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Zřejmě se vrátím. }
{ 162 }{ Nashle. }{ Nashle. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Zřejmě se vrátím. }

UPbasicCZ\dlg\chinatown\yukie.dlg
{ 304 }{ Je mi líto, ale myslím, že jsem ho zabil u Rudého draka. Ranař se žlutýma očima? }{ Je mi líto, ale myslím, že jsme ho zabila u Rudého draka. Ranař se žlutýma očima? }
{ 413 }{ Je mi líto, ale myslím, že jsem ho zabil u Rudého draka. Ranař se žlutýma očima? }{ Je mi líto, ale myslím, že jsem ho zabila u Rudého draka. Ranař se žlutýma očima? }

**Comment by miracleflame** [comment]
Ešte poprosím malkaviánsku repliku
{ 329 }{ Teď když mi oba nabízíte stejnou slevu, jeden z vás musí jít. }{ Teď když mi oba nabízíte stejnou slevu, jeden z vás musí jít. }{ 391 }{ G.Lu_Ji > 3 and G.Ji_Lu != 6 }{ }{ }{ }{ }{ }{ }{ }{ I'll net the same from your nest egg now, so one of you has to go. }

**Comment by soulcharmer** [comment]
aaa, pardon.

Vylepsil jsem cely radek:

{ 329 }{ Teď když mi oba nabízíte stejnou slevu, jeden z vás už není potřeba. }{ Teď když mi oba nabízíte stejnou slevu, jeden z už není potřeba. }{ 391 }{ G.Lu_Ji > 3 and G.Ji_Lu != 6 }{ }{ }{ }{ }{ }{ }{ }{ Nyní když oba poskytujete stejné procento, jeden z vás musí jít. }

**Comment by miracleflame** [comment]
Moja chyba, že som to tam nedal prvý raz, ale pri nahradzovaní mi to neuniklo.
