### ISSUE TITLE
Preklad dlg downtown la e07c8ca6

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#517]
e07c8ca6

UPbasicCZ\dlg\downtown la\boris.dlg
{	2	}{	I don't understand you.	}{	I don't understand you.	}{	11	}{	}{	}{	}{	}{	}{	}{	}{	}{	Yes, what the hell?	}
{	4	}{	Sometimes the voices explain.	}{	Sometimes the voices explain.	}{	211	}{	}{	}{	}{	}{	}{	}{	}{	}{	Sometimes the voices explain.	}
{	6	}{	What?	}{	What?	}{	1	}{	}{	}{	}{	}{	}{	}{	}{	}{	I'm coming.	}
{	8	}{	Huh?	}{	Huh?	}{	21	}{	}{	}{	}{	}{	}{	}{	}{	}{	It's me.	}
{	233	}{	Your doggie mustn't know.	}{	Your doggie mustn't know.	}
{	271	}{	Okay, okay. Idi togda (Go, then), Dima. Very well... happy? Now spit it out. Make this quick, eh.	}{	Okay, okay. Idi togda (Go, then), Dima. Very well... happy? Now spit it out. Make this quick, eh.	}{	#	}{	}{	G.Dema_Leave = 1	}{	}{	}{	}{	}{	}{	}{	}
{	272	}{	The goddess no longer offers tribute nor lets you defile her temple.	}{	The goddess no longer offers tribute nor lets you defile her temple.	}{	251	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	273	}{	Venus no longer shares her bounty, nor may you enter her atmosphere.	}{	Venus no longer shares her bounty, nor may you enter her atmosphere.	}{	251	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	274	}{	Words fail me... so I will rely on the poetry of violence.	}{	Words fail me... so I will rely on the poetry of violence.	}

UPbasicCZ\dlg\downtown la\damsel.dlg
{	730	}{	Uh, I'm going.	}{	Uh, I'm going.	}{	551	}{	}{	}{	}{	}{	}{	}{	}{	}{	I am already gone.	}

UPbasicCZ\dlg\downtown la\dema.dlg
{	8	}{	Cože?	}{	Cože?	}{	11	}{	}{	}{	}{	}{	}{	}{	}{	}{	We do what we must.	}
{	9	}{	Ne.	}{	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	10	}{	You better move.	}{	You better move.	}{	51	}{	}{	}{	}{	}{	}{	}{	}{	}{	Go away now.	}
{	30	}{	I'm the new lady friend of your boss.	}{	I'm the new lady friend of your boss.	}{	1	}{	not IsMale(pc)	}{	}{	}{	}{	}{	}{	}{	}{	I'm the new goddess of the man behind the door.	}

UPbasicCZ\dlg\downtown la\dirty_cop.dlg
{	121	}{	What the hell was that thing?!?	}{	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

UPbasicCZ\dlg\downtown la\empire_desk_clerk.dlg
{	62	}{	Sorry, I'll go.	}{	Sorry, I'll go.	}{	0	}{	}{	}

UPbasicCZ\dlg\downtown la\igor.dlg
{	42	}{	I will.	}{	I will.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	Only if we remember it.	}

UPbasicCZ\dlg\downtown la\jumbles.dlg
{	22	}{	Thanks.	}{	Thanks.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	He will see me and die.	}
{	32	}{	Thanks.	}{	Thanks.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	He will see me and die.	}

UPbasicCZ\dlg\downtown la\junkie_girl.dlg
{	73	}{	Co? Jo aha. Nejsem Kanker. To mám z takové bizardní nehody s mixérem...	}{	Co? Do I look like a brother to you? To mám z takové bizardní nehody s mixérem...	}

UPbasicCZ\dlg\downtown la\patty.dlg
{	96	}{	V santamonické krevní bance. He really needed a drink.	}{	V santamonické krevní bance. He really needed a drink.	}{	101	}{	Humanity 3 & (G.Vandal_Quest == 1 and G.Patch_Plus == 1)	}{	G.Vandal_Quest = 3; G.Patty_SM = 1; FindPlayer().HumanityAdd( -1 )	}{	}{	}{	}{	}{	}{	}{	He was thirsty, so he went to santamonické krevní bance.	}
{	97	}{	V santamonické krevní bance. He really needed a drink.	}{	V santamonické krevní bance. He really needed a drink.	}{	101	}{	Humanity -3 & (G.Vandal_Quest == 1 and G.Patch_Plus == 1)	}{	G.Vandal_Quest = 3; G.Patty_SM = 1	}{	}{	}{	}{	}{	}{	}{	He was thirsty, so he went to santamonické krevní bance.	}

UPbasicCZ\dlg\downtown la\prince2.dlg
{	555	}{	Nejen, že jsem Bacha zabil, ale mám i jeho deník. That should be valuable.	}{	Nejen, že jsem Bacha zabila, ale mám i jeho deník. That should be valuable.	}
{	1070	}{	Jednou jsem viděl the easter egg vlka, chci vidět the easter egg ending!	}{	Jednou jsem viděla the easter egg vlka, chci vidět the easter egg ending!	}

**Comment by soulcharmer** [comment]
UPbasicCZ\dlg\downtown la\boris.dlg
{ 2 }{ Tomu nerozumím. }{ Tomu nerozumím. }{ 11 }{ }{ }{ }{ }{ }{ }{ }{ }{ Ano. Cože co? }
{ 4 }{ Hlasy to někdy vysvětlí. }{ Hlasy to někdy vysvětlí. }{ 211 }{ }{ }{ }{ }{ }{ }{ }{ }{ Hlasy to někdy vysvětlí. }
{ 6 }{ Cože? }{ Cože? }{ 1 }{ }{ }{ }{ }{ }{ }{ }{ }{ Už jdu. }
{ 8 }{ Co? }{ Co? }{ 21 }{ }{ }{ }{ }{ }{ }{ }{ }{ To jsem já. }
{ 233 }{ Tvůj pesík se to nesmí dovědět. }{ Tvůj pesík se to nesmí dovědět. }
{ 271 }{ Dobře, dobře. Idi togda, Dimo. Tak co, spokojen? A teď, ven s tím. A rychle... }{ Dobře, dobře. Idi togda, Dimo. Tak co, spokojena? A teď, ven s tím. A rychle... }{ # }{ }{ G.Dema_Leave = 1 }{ }{ }{ }{ }{ }{ }{ }
{ 272 }{ Bohyně již nenabízí odměny a nenechá tě znesvětit její chrám. }{ Bohyně již nenabízí odměny a nenechá tě znesvětit její chrám. }{ 251 }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 273 }{ Venuše již nesdílí svou hojnost a nedovolí ti se k ní přiblížit. }{ Venuše již nesdílí svou hojnost a nedovolí ti se k ní přiblížit. }{ 251 }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 274 }{ Nenacházím slova... proto se spolehnu na poezii násilí. }{ Nenacházím slova... proto se spolehnu na poezii násilí. }

UPbasicCZ\dlg\downtown la\damsel.dlg
{ 730 }{ Tak já půjdu. }{ Tak já půjdu. }{ 551 }{ }{ }{ }{ }{ }{ }{ }{ }{ Již zde nejsem. }

UPbasicCZ\dlg\downtown la\dema.dlg
{ 8 }{ Cože? }{ Cože? }{ 11 }{ }{ }{ }{ }{ }{ }{ }{ }{ Děláme, co musíme. }
{ 9 }{ Ne. }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 10 }{ Radši mi uhni. }{ Radši mi uhni. }{ 51 }{ }{ }{ }{ }{ }{ }{ }{ }{ Nyní odejdi. }
{ 30 }{ Jsem nová přítelkyně tvýho šéfa. }{ Jsem nová přítelkyně tvýho šéfa. }{ 1 }{ not IsMale(pc) }{ }{ }{ }{ }{ }{ }{ }{ Jsem nová bohyně muže za dveřmi. }

UPbasicCZ\dlg\downtown la\dirty_cop.dlg
{ 121 }{ Co to sakra bylo?!? }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }

UPbasicCZ\dlg\downtown la\empire_desk_clerk.dlg
{ 62 }{ Pardon, už jdu. }{ Pardon, už jdu. }{ 0 }{ }{ }

UPbasicCZ\dlg\downtown la\igor.dlg
{ 42 }{ Dobře. }{ Dobře. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Jen pokud si to zapamatujeme. }

UPbasicCZ\dlg\downtown la\jumbles.dlg
{ 22 }{ Díky. }{ Díky. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Uvidí mě a zemře. }
{ 32 }{ Díky. }{ Díky. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Uvidí mě a zemře. }

UPbasicCZ\dlg\downtown la\junkie_girl.dlg
{ 73 }{ Co? Jo aha. Nejsem Kanker. To mám z takové bizardní nehody s mixérem... }{ Co? Vypadám snad jako brácha? To mám z takové bizardní nehody s mixérem... }

UPbasicCZ\dlg\downtown la\patty.dlg
{ 96 }{ V santamonické krevní bance. Fakt potřeboval napít. }{ V santamonické krevní bance. Fakt potřeboval napít. }{ 101 }{ Humanity 3 & (G.Vandal_Quest == 1 and G.Patch_Plus == 1) }{ G.Vandal_Quest = 3; G.Patty_SM = 1; FindPlayer().HumanityAdd( -1 ) }{ }{ }{ }{ }{ }{ }{ Měl velkou žízeň, proto jsme šli do santamonické krevní banky. }
{ 97 }{ V santamonické krevní bance. Fakt potřeboval napít. }{ V santamonické krevní bance. Fakt potřeboval napít. }{ 101 }{ Humanity -3 & (G.Vandal_Quest == 1 and G.Patch_Plus == 1) }{ G.Vandal_Quest = 3; G.Patty_SM = 1 }{ }{ }{ }{ }{ }{ }{ Měl velkou žízeň, proto jsme šli do santamonické krevní banky. }

UPbasicCZ\dlg\downtown la\prince2.dlg
{ 555 }{ Nejen, že jsem Bacha zabil, ale mám i jeho deník. To by mělo mít nějakou hodnotu. }{ Nejen, že jsem Bacha zabila, ale mám i jeho deník. To by mělo mít nějakou hodnotu. }
{ 1070 }{ Jednou jsem viděl tajného vlka, chci vidět i tajný konec! }{ Jednou jsem viděla tajného vlka, chci vidět i tajný konec! }
