### ISSUE TITLE
Preklad dlg Giovanni

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#518]
0bc58659

UPbasicCZ\dlg\giovanni\adam.dlg
{	51	}{	Určitě? Pokud byste změnil názor, dejte mi vědět. Věřte mi, vážně je to ve vašem zájmu zúčastnit se. Popřemýšlejte o tom.	}{	Určitě? Pokud byste změnila názor, dejte mi vědět. Věřte mi, vážně je to ve vašem zájmu zúčastnit se. Popřemýšlejte o tom.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	52	}{	I will.	}{	I will.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	I'll discuss it with myself.	}
{	225	}{	I'm ruined....	}{	I'm ruined....	}{	#	}{	npc.SetDisposition("Sad", 1)	}{	}{	}{	}{	}{	}{	}{	}{	}
{	226	}{	What do you say?	}{	What do you say?	}{	221	}{	}{	}{	}{	}{	}{	}{	}{	}{	I know.	}

UPbasicCZ\dlg\giovanni\christopher.dlg
{	102	}{	Thanks.	}{	Thanks.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	I'll find it.	}
{	272	}{	Oh, really?	}{	Oh, really?	}{	273	}{	}{	}{	}{	}{	}{	}{	}{	}{	This will not happen.	}
{	273	}{	Get out of here! You're lucky I don't hit you!	}

UPbasicCZ\dlg\giovanni\luca.dlg
{	12	}{	What?	}{	What?	}{	121	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	101	}{	Shut up, you. I didn't even wanna come.	}{	Shut up, you. I didn't even wanna come.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}
{	131	}{	Where's 'e invitation. Aw, screw it, let's go home.	}{	Where's 'e invitation. Aw, screw it, let's go home.	}{	#	}{	}{	}{	}{	}{	}{	}{	}{	}{	}

UPbasicCZ\dlg\giovanni\nadia.dlg
{	566	}{	Enjoy the party. Excuse me.	}{	Enjoy the party. Excuse me.	}{	0	}{	}{	}{	}{	}{	}{	}{	}{	}{	I fade back into the party.	}

UPbasicCZ\dlg\giovanni\victor.dlg
{	12	}{	Not again.	}{	Not again.	}{	0	}{	}{	gio1_victorMariaFlee()	}{	}{	}{	}{	}{	}{	}{	}
{	121	}{	[Scream in fear]Ahh! Help!!!	}{	[Scream in fear]Ahh! Help!!!	}

**Comment by soulcharmer** [comment]
UPbasicCZ\dlg\giovanni\adam.dlg
{ 51 }{ Určitě? Pokud byste změnil názor, dejte mi vědět. Věřte mi, vážně je to ve vašem zájmu se zúčastnit. Popřemýšlejte o tom. }{ Určitě? Pokud byste změnila názor, dejte mi vědět. Věřte mi, vážně je to ve vašem zájmu se zúčastnit. Popřemýšlejte o tom. }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 52 }{ Dobře. }{ Dobře. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Promluvím si se sebou. }
{ 225 }{ Jsem v koncích... }{ Jsem v koncích... }{ # }{ npc.SetDisposition("Sad", 1) }{ }{ }{ }{ }{ }{ }{ }{ }
{ 226 }{ Cože? }{ Cože? }{ 221 }{ }{ }{ }{ }{ }{ }{ }{ }{ My víme. }

UPbasicCZ\dlg\giovanni\christopher.dlg
{ 102 }{ Díky. }{ Díky. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Najdu to. }
{ 272 }{ Vážně? }{ Vážně? }{ 273 }{ }{ }{ }{ }{ }{ }{ }{ }{ To se nestane. }
{ 273 }{ Zmizte odsud! Máte štěstí, že vás neztluču! }

UPbasicCZ\dlg\giovanni\luca.dlg
{ 12 }{ Cože? }{ Cože? }{ 121 }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 101 }{ Buďte zticha. Ani jsem nechtěl přijít. }{ Buďte zticha. Ani jsem nechtěl přijít. }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 131 }{ Kde mám tu pozvánku... To je fuk, jde se domů. }{ Kde mám tu pozvánku... To je fuk, jde se domů. }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }

UPbasicCZ\dlg\giovanni\nadia.dlg
{ 566 }{ Dobře se bavte. Omluvte mě. }{ Dobře se bavte. Omluvte mě. }{ 0 }{ }{ }{ }{ }{ }{ }{ }{ }{ Zapluji zpět do večírku. }

UPbasicCZ\dlg\giovanni\victor.dlg
{ 12 }{ To snad ne. }{ To snad ne. }{ 0 }{ }{ gio1_victorMariaFlee() }{ }{ }{ }{ }{ }{ }{ }
{ 121 }{ [Scream in fear]Ááá! Pomoc!! }{ [Scream in fear]Ááá! Pomoc!! }
