### ISSUE TITLE
Anglické Auto-end dlg repliky

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#52]
Niektoré repliky, čo ukončujú dialóg a následne sa zobrazia ako floating text sa na štvrť sekundy objavia v dialógovom okne v angličtine. Je to skôr kozmetický nedostatok, ktorý je minimálne rušivý, preto sa pýtam, či to budeme opravovať.

[ukážka](https://snag.gy/CSeaLW.jpg)

**Comment by soulcharmer** [comment]
Cili .lip je prelozen, ale Auto-end v .dlg neni? 

To by znamenalo, ze to je vicemene rucni prace, takze bych se v prvni rade podival, kolik by toho bylo celkove pro celou hru.

Na druhou stranu, kdyz najdeme chybu v .lip, chtelo by to opravit i odpovidajici .dlg, coz je trochu otrava.

Ovsem na treti stranu to je jen probliknuti, takze kdyz si .lip a .dlg line budou vicemene odpovidat, nemelo by to delat problemy.

Pokud to tedy je zvladnutelne manualne prenest, udelal bych to jednou a pak na to v podstate zapomnel.

Nechavam na tobe.

**Comment by miracleflame** [comment]
Počas testovania som toho postrehol absolútne minimum.
Z toho dôvodu budem ručne opravovať konkrétne výskyty, pokiaľ si niečo také ešte všimnem.. presne ako hociktorý iný bug... takže žiadne hromadné prečesávanie veškerého materiálu.

Tiket zatváram ako opravený chunk.
