### ISSUE TITLE
K niektorým postavám v hre chýbajú titulky

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#54]
Hlavne policajtom, ale aj bežným útočníkom, či generic citizenom.. Alovi, túlákovi v podchode pri Last Round, policajtovi na móle a iné...

V spolupráci s Wespom som vytvoril titulky pre postavy, ktoré som zatiaľ objavil.

Preklad do CZ bude nasledovať.

**Comment by soulcharmer** [comment]
Cool!  Dej vedet, az budes chtit preklady.

**Comment by miracleflame** [comment]
Preložené a pripravené na revíziu v #83 - #101 
Po revízii bude potrebné zbehnúť skript translate_ff_lip.rb a skonvertovať na cp1250

**Comment by miracleflame** [comment]
Samozrejmá vec, tiket sa môže zatvoriť.
