### ISSUE TITLE
Tommy.dlg replika 131 zvuk nesedí s textom

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#55]
Zrejme neopraviteľný bug vanilla verzie, kde repozitár súborov vyzerá takto

line131_col_e.lip
"What do you want? Can't you see I'm working?"

line131_col_e.mp3
"Me? Tommy Flayton? THE food authority of Los Angeles? Food critic for the biggest paper on the West Coast? Radio personality for the KTLK... [sort of disgusted]Chow-er Hour? Maybe if I reviewed more Pancake Huts, you'd know me." 

mp3, ktorá by zodpovedala textu v line131_col_e.lip sa mi nepodarila nikde nájsť... ešte sa na to spýtam Wespa. Zatiaľ upravím text, tak aby sedel so zvukom.

**Comment by miracleflame** [comment]
Po mojom návrhu Wesp prijal takéto riešenie

{   131   }{   Oh, hey, waiter! I asked for a Cabernet Sauvignon, not a Merlot! Next thing you know he'll bring sparkling grape juice, ugh.    }{   Oh, hey, waiter! I asked for a Cabernet Sauvignon, not a Merlot! Next thing you know he'll bring sparkling grape juice, ugh.    }{   #   }{   npc.SetDisposition("Anger", 1)   }{   }{   }{   }{   }{   }{   }{   }{   }
{   132   }{   }{   }{   }{   }{   }{   }{   }{   }{   }{   }{   }{   }
{   133   }{   }{   }{   }{   }{   }{   }{   }{   }{   }{   }{   }{   }
{   134   }{   I'm not the waiter, but your are just the man I wanted to talk to.   }{   I'm not the waiter, but your are just the man I wanted to talk to.   }{   81   }{   G.Tommy_Know == 1   }{   }{   }{   }{   }{   }{   }{   }{   You. Me. Talk.   }
{   135   }{   Who are you?   }{   Who are you?   }{   31   }{   G.Tommy_Know == 0   }{   }{   }{   }{   }{   }{   }{   }{   You are not known to me. Should you be?   }

**Comment by miracleflame** [comment]
Zreviduj, prosím.

**Comment by soulcharmer** [comment]
fixed:

{ 134 }{ Nepatřím k obsluze, ale právě s vámi jsem chtěl mluvit. }{ Nepatřím k obsluze, ale právě s vámi jsem chtěla mluvit. }{ 81 }{ G.Tommy_Know == 1 }{ }{ }{ }{ }{ }{ }{ }{ Vy. Já. Promluvíme. }
{ 135 }{ Kdo jste? }{ Kdo jste? }{ 31 }{ G.Tommy_Know == 0 }{ }{ }{ }{ }{ }{ }{ }{ Nejste mi znám. Měl byste být? }
