### ISSUE TITLE
Revize Update na 9.6

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#57]
**UP_Plus_CZ\vdata\system\loadingtips.txt**

"Text"      "Clan Lasombra:
            Firm believers in the worthy ruling and the unworthy serving, the Clan Lasombra have maintained their ancient traditions even as they direct the Sabbat to their own purposes. Due to their penchant for darkness and control of shadows, the Lasombra cast no reflections. Their careless atrocities lend credence to the idea that it's easier to live with your actions when you don't have to face yourself in the mirror."

"Text"      "Klan Lasombra:
            Zarytě věří v nadřazenost panovníků a podřazenost sluhů. Klan si udržuje starověké tradice popři řízení Sabbatu ke svým vlastním účelům. Vzhledem k jejich sklonům k temnotě a ovládaní stínů, členové Lasombry nevrhají svůj odraz. V Jejich bezohledné krutosti se ubezpečují myšlenkou, že je snažší žít se svými skutky, když nemusíte stát sobě tváří v tvář v zrcadle."

**dlg/Hollywood/andrei.dlg** 
{   2   }{  I know what you are doing in LA. Time to die, Sabbat freak! }{  I know what you are doing in LA. Time to die, Sabbat freak! }{  0   }{  G.Player_Sabbat == 0    }{  }{  }{  }{  }{  }{  }{  }{  My mind knows your purpose, Sword of Caine. And soon it will know your death!   }

{   2   }{  Já vím, co tady v LA dělaš. A teď chcípni, sabbatská zrůdo! }{  Já vím, co tady v LA dělaš. A teď chcípni, sabbatská zrůdo! }{  0   }{  G.Player_Sabbat == 0    }{      }{  }{  }{  }{  }{  }{  }{  Má mysl zná tvé záměry, Kainův nohslede. A brzy bude znát tvou smrt! }

**dlg/downtown la/boris.dlg** 
{   1   }{  Chert voz'mi (What the hell)?   }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   2   }{  Zaydi (Come)!   }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   3   }{  Ya dumayu ti znaesh shto ya govoru (I think you know what I say)?   }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   4   }{  Shto eto takoe (What is this)?  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }

{   1   }{  Čert  to vem!  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   2   }{  Pojď!  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   3   }{  Zajímalo by mě jestli rozumíš tomu, co říkám!    }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   4   }{  Co je tohle?    }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }

**dlg/downtown la/dema.dlg** 
{   1   }{  [EE-deek k-CHOR-too, SVOLE-ahtch!] Idi k chertu, svoloch' (Go to hell, bitch)!  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   2   }{  [YUH puh-nee-MIE-yove.] Ya ponimau (I understand).  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   3   }{  DAH (YES).  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   4   }{  [NEE-yet.] Net (No).    }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   5   }{  Baba Yaga (Old witch)!  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   6   }{  Shto eto oni k chertovoyi materi oni delaut (What the hell are they doing)? }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }

{   1   }{  Jdi k čertu spodino! }{    }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   2   }{  Rozumím.   }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   3   }{  Ano.    }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   4   }{  Ne. }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   5   }{  Baba Jaga!  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }
{   6   }{  Co to k čertu dělaj?  }{  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }

**dlg/downtown la/empire_desk_clerk.dlg** 
{   28  }{  I am the key master and you will make me a key! }{  I am the key master and you will make me a key! }{  31  }{  Dementation 2   }{  }{  }{  }{  }{  }{  }{  }{  }

{   28  }{  Já jsem pán klíčů a předáš mi klíč!   }{  Já jsem pani klíčů a předáš mi klíč!   }{  31  }{  Dementation 2   }{  }{  }{  }{  }{  }{  }{  }{  }

**dlg/downtown la/igor.dlg** 
{   31  }{  Virvu nogi (Break their legs)!  }{  Virvu nogi (Break their legs)!  }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }

{   31  }{  Urvu jim hnáty!    }{  Urvu jim hnáty!    }{  #   }{  }{  }{  }{  }{  }{  }{  }{  }{  }

**dlg/main characters/beckett.dlg** 
{   592 }{  I won't be taking a cab though, the sewers are faster.  }{  I won't be taking a cab though, the sewers are faster.  }{  881 }{  G.Story_State < 70 and IsClan(pc, "Nosferatu")  }{  }{  }{  }{  }{  }{  }{  }{  }

{   592 }{  Taxíkem nepůjdu, rychlejší jsou kanalizace. }{  Taxíkem nepůjdu, rychlejší jsou kanalizace. }{  881 }{  G.Story_State < 70 and IsClan(pc, "Nosferatu")  }{  }{  }{  }{  }{  }{  }{  }{  }

**dlg/main characters/gary.dlg** 
{   354 }{  I cleaned your sewers from the Tzimisce and brought you some Masquerade endangering items too.  }{  I cleaned your sewers from the Tzimisce and brought you some masquerade endangering items too.  }{  371 }{  G.Patch_Plus == 1 and pc.HasItem("item_g_warr_clipboard") and pc.HasItem("item_g_warr_ledger_1") and pc.HasItem("item_g_warr_ledger_2") and pc.HasItem("item_g_warrens4_passkey")   }{  pc.RemoveItem("item_g_warr_clipboard"); pc.RemoveItem("item_g_warr_ledger_1"); pc.RemoveItem("item_g_warr_ledger_2"); pc.RemoveItem("item_g_warrens4_passkey")      }{  }{  }{  }{  }{  }{  }{  I went through the tunnels, killing things and collecting stuff for you.    }

{   354 }{  Vyklidil jsem Tzimisce z kanalizace a taky nesu zopár vecí, co ohrožujou Maškarádu.    }{  Vyklidila jsem Tzimisce z kanalizace a taky nesu zopár vecí, co ohrožujou Maškarádu.   }{  371 }{  G.Patch_Plus == 1 and pc.HasItem("item_g_warr_clipboard") and pc.HasItem("item_g_warr_ledger_1") and pc.HasItem("item_g_warr_ledger_2") and pc.HasItem("item_g_warrens4_passkey")   }{  pc.RemoveItem("item_g_warr_clipboard"); pc.RemoveItem("item_g_warr_ledger_1"); pc.RemoveItem("item_g_warr_ledger_2"); pc.RemoveItem("item_g_warrens4_passkey")      }{  }{  }{  }{  }{  }{  }{  Mám za sebou projížďku kanálama, zabíjení příšer a sbíraní vecí pro vás.  }

{   544 }{  I think I killed one back in Santa Monica. What about them? }{  I think I killed one back in Santa Monica. What about them? }{  571 }{  G.Knox_Done == 1    }{  }{  }{  }{  }{  }{  }{  }{  The voices claim I slayed one at the lady by the sea. So?   }

{   544 }{  Myslím, že jsem jednoho zabil v Santa Monice. Co s nima?  }{  Myslím, že jsem jednoho zabila v Santa Monice. Co s nima? }{  571 }{  G.Knox_Done == 1    }{  }{  }{  }{  }{  }{  }{  }{  Hlasy říkaj, že jeden byl poražen u dámy u moře. A?   }

**dlg/main characters/heather.dlg** 
{   585 }{  No, keep your money and stay in school. This must remain a secret, never speak of me.   }{  No, keep your money and stay in school. This must remain a secret, never speak of me.   }{  661 }{  }{  }{  }{  }{  }{  }{  }{  }{  No. Stay quiet about me and continue with boredom school!   }

{   585 }{  Ne, nech si svý peníze a v škole pokračuj. Tohle musí zůstat tajemstvým, nikdy o mě nemluv. }{  Ne, nech si svý peníze a v škole pokračuj. Tohle musí zůstat tajemstvým, nikdy o mě nemluv. }{  661 }{  }{  }{  }{  }{  }{  }{  }{  }{  Ne. O mě ani muk a ty pokračuj v nudném studiu!  }

**dlg/santa monica/stan_gimble.dlg** 
{   162 }{  Amazing! And I just heard the local morgue offers corpses for scientific research tonight.  }{  Amazing! And I just heard the local morgue offers corpses for scientific research tonight.  }{  255 }{  Persuasion 6 & (G.Vandal_Quest == 1 and G.Patch_Plus == 1)  }{  }{  }{  }{  }{  }{  }{  }{  Groovy! How lucky that tonight the clinic freezer has cold bodies for free! }

{   162 }{  Úchvatné! A já slyšel, že místní márnice dnes nabízí mrtvoly na vědecký výzkum protéz.    }{  Úchvatné! A já slyšela, že místní márnice dnes nabízí mrtvoly na vědecký výzkum protéz.   }{  255 }{  Persuasion 6 & (G.Vandal_Quest == 1 and G.Patch_Plus == 1)  }{  }{  }{  }{  }{  }{  }{  }{  Panečku! Jaké štěstí, že santamonická márnice má dnes údy a části těl zdarma!  }

{   256 }{  Indeed, just check in with a guy called Vandal. It will be perfect for a specialist like yourself.  }{  Indeed, just check in with a guy called Vandal. It will be perfect for a specialist like yourself.  }{  201 }{  pc.humanity >= 4    }{  G.Vandal_Quest = 3; G.Gimble_Vandal = 1; pc.SetQuest("Danielle",7); FindPlayer().HumanityAdd( -1 ); G.Gimble_Humanity = 1   }{  }{  }{  }{  }{  }{  }{  A Vandal will receive you with pleasure for your are special.   }
{   257 }{  Indeed, just check in with a guy called Vandal. It will be perfect for a specialist like yourself.  }{  Indeed, just check in with a guy called Vandal. It will be perfect for a specialist like yourself.  }{  201 }{  pc.humanity < 4 }{  G.Vandal_Quest = 3; G.Gimble_Vandal = 1; pc.SetQuest("Danielle",7)  }{  }{  }{  }{  }{  }{  }{  A Vandal will receive you with pleasure for your are special.   }

{   256 }{  Ano, poptejte se na chlápka jménem Vandal.    Pro specialistu jako vy to je perfektní. }{    Ano, poptejte se na chlápka jménem Vandal.    Pro specialistu jako vy to je perfektní. }{    201 }{  pc.humanity >= 4    }{  G.Vandal_Quest = 3; G.Gimble_Vandal = 1; pc.SetQuest("Danielle",7); FindPlayer().HumanityAdd( -1 ); G.Gimble_Humanity = 1   }{  }{  }{  }{  }{  }{  }{  Vandal vás přijme s potěšením, protože jste výmečný.   }
{   257 }{  Zajisté, jenom se poptejte na chlápka jménem Vandal. Pro specialistu jako vy to je perfektní. }{    Zajisté, jenom se poptejte na chlápka jménem Vandal. Pro specialistu jako vy to je perfektní. }{    201 }{  pc.humanity < 4 }{  G.Vandal_Quest = 3; G.Gimble_Vandal = 1; pc.SetQuest("Danielle",7)  }{  }{  }{  }{  }{  }{  }{  Vandal vás přijme s potěšením, protože jste výjimečný. }

**cestina/vdata/hackterminals/scott_laptop.txt** 
            "runtext"   "While researching for a history project in the LA public library, I noticed a Lasombra entering the art room. I sneaked in Obfuscated after him but the room was empty! I waited until he returned and followed him down into the sewers through the hatch I use to enter myself. He climbed to the streets nearby and visited several clubs."
-           "runtext"   "Když jsem dělal na jednom dějepisném projektu ve veřejné knihovně, všimnul jsem si, jak někdo z Lasombry jde do oddělení s uměním. Šel jsem za ním s neviditelností, ale místnost byla prázdná! Počkal jsem, až vyšel ven a sledoval jsem ho až do kanalizace otvorem, který sám používám. On pak vylezl na nejbližší ulici a navštívil několik klubů.."

**cestina/vdata/hackterminals/shrekhub4_terminal1.txt** 
            "name"      "goodies!"
            "description"   "reward"
            "runtext"   "Find a powerful item nearby as reward for your help. >m1tn1ck<"
            "name"      "nadílka!"
            "description"   "odměna"
            "runtext"   "Hledej poblíž mocný předmět jako odměnu za tvou pomoc. >m1tn1ck<"

**cestina/vdata/items/item_w_chang_claw.txt** 
    "printname" "Tiger's Claws" // changed by wesp
    "description"   "These are devious looking metal claws with a wooden handle. They even deal aggravated damage." // changed by wesp
    "printname" "Tigrovy drápy"    // changed by wesp
    "description"   "Jsou to zvráceně vyhlížejíci kovové drápy s dřevěnou rukovětí. Navíc způsobují spalující zranění."   // changed by wesp

**cestina/vdata/signs/newspaper_test.txt** 
        "Text"              "   FAMOUS DOCTOR"
        "Text"              "   DIES IN ACCIDENT"
        "Text"              "         28  FEB  1954  THE  UNRECOGNIZABLE  CORPSE  OF  RENOWNED"
        "Text"              "         SHRINK  DR.  ALISTAIR  GROUT  WAS  FOUND  IN  HIS  BURNING"
        "Text"              "         CAR  AS  IT  CRASHED  IN  THE  HOLLYWOOD  HILLS  TODAY!!!"
        "Text"              "    ========================================== SPECIAL EDITION"

```
    "Text"              "   SLAVNÝ DOKTOR"
    "Text"              "   OBĚTÍ NEHODY"
    "Text"              "         28. ÚNORA 1954  OHOŘELÉ  OSTATKY RENOMOVANÉHO"
    "Text"              "         PSYCHIATRA  DR.  ALISTAIRA  GROUTA  DNES NAŠLI VE VRAKU"
    "Text"              "         AUTA, KTERÉ HAVAROVALO V HOLYWOODSKÝCH KOPCÍCH!!!"
```

========================================== ZVLÁŠTNÍ VYDÁNÍ"

**Comment by soulcharmer** [comment]
**UP_Plus_CZ\vdata\system\loadingtips.txt**

"Text" "Klan Lasombra:
Lasombra pevně věří v nadřazenost silných, podřazenost slabých, a udržuje své prastaré tradice, kdy využívá Sabbat ke svým účelům. Díky své náchylnosti k ovládání temnoty členové Lasombry nevrhají stíny. Jejich bezohledná zvěrstva potvrzují myšlenku, že je snašží žít se svými skutky, když nemusíte čelit svému obrazu v zrcadle."

**dlg/Hollywood/andrei.dlg**

{ 2 }{ Vím, co v LA děláš, ty sabbatská zrůdo. Chcípni! }{ Vím, co v LA děláš, ty sabbatská zrůdo. Chcípni! }{ 0 }{ G.Player_Sabbat == 0 }{ }{ }{ }{ }{ }{ }{ }{ Má hlava zná tvůj záměr, Kainův nohslede. A brzy bude znát i tvou smrt! }

**dlg/downtown la/boris.dlg**

{ 1 }{ Čert to vem! }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 2 }{ Pojď! }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 3 }{ Rozumíš, co říkám? }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 4 }{ Co je to? }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }

**dlg/downtown la/dema.dlg**

{ 1 }{ Táhni k čertu, svině! }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 2 }{ Rozumím. }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 3 }{ Ano. }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 4 }{ Ne. }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 5 }{ Baba Jaga! }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }
{ 6 }{ Co to k čertu dělaj? }{ }{ # }{ }{ }{ }{ }{ }{ }{ }{ }{ }

**dlg/downtown la/empire_desk_clerk.dlg**

{ 28 }{ Jsem pánem klíčů a ty mi jeden předáš! }{ Jsem pání klíčů a ty mi jeden předáš! }{ 31 }{ Dementation 2 }{ }{ }{ }{ }{ }{ }{ }{ }

**dlg/downtown la/igor.dlg** OK

**dlg/main characters/beckett.dlg**

{ 592 }{ Taxíkem ale nepojedu, podzemím to je rychlejší. }{ Taxíkem ale nepojedu, podzemím to je rychlejší. }{ 881 }{ G.Story_State < 70 and IsClan(pc, "Nosferatu") }{ }{ }{ }{ }{ }{ }{ }{ }

**Comment by soulcharmer** [comment]
**dlg/main characters/gary.dlg**

{ 354 }{ Vyčistil jsem tvoje kanály od toho Tzimisce a mám pro tebe i pár nebezpečných hračiček. }{ Vyčistila jsem tvoje kanály od toho Tzimisce a mám pro tebe i pár nebezpečných hračiček. }{ 371 }{ G.Patch_Plus == 1 and pc.HasItem("item_g_warr_clipboard") and pc.HasItem("item_g_warr_ledger_1") and pc.HasItem("item_g_warr_ledger_2") and pc.HasItem("item_g_warrens4_passkey") }{ pc.RemoveItem("item_g_warr_clipboard"); pc.RemoveItem("item_g_warr_ledger_1"); pc.RemoveItem("item_g_warr_ledger_2"); pc.RemoveItem("item_g_warrens4_passkey") }{ }{ }{ }{ }{ }{ }{ Předávám ti nějaké cetky a zprávu z kanálu o mrtvých příšerách. }

{ 544 }{ Myslím, že jsem jednoho zabil v Santa Monice. A co má být? }{ Myslím, že jsem jednoho zabila v Santa Monice. A co má být? }{ 571 }{ G.Knox_Done == 1 }{ }{ }{ }{ }{ }{ }{ }{ Hlasy říkají, že má ruka jednoho zamordovala v dámě u moře. A dále? }

**dlg/main characters/heather.dlg**

{ 585 }{ Ne, ty peníze si nech a pokračuj ve studiu. Tohle musí být naše tajemství, s nikým o mně nemluv. }{ Ne, ty peníze si nech a pokračuj ve studiu. Tohle musí být naše tajemství, s nikým o mně nemluv. }{ 661 }{ }{ }{ }{ }{ }{ }{ }{ }{ Ne. O mně ani muk a pokračuj v nudném studiu! }

**dlg/santa monica/stan_gimble.dlg**

{ 162 }{ Úžasný! A já se zrovna dověděl, že místní márnice dnes nabízí mrtvoly na vědecký výzkum. }{ Úžasný! A já se zrovna dověděla, že místní márnice dnes nabízí mrtvoly na vědecký výzkum. }{ 255 }{ Persuasion 6 & (G.Vandal_Quest == 1 and G.Patch_Plus == 1) }{ }{ }{ }{ }{ }{ }{ }{ Senzace! Jaké štěstí, že nemocniční chladírna má dnes tuháče zdarma! }

{ 256 }{ Přesně tak, ptejte se po chlápkovi, co si říká Vandal. Pro odborníka jako vy to bude to pravý. }{ Přesně tak, ptejte se po chlápkovi, co si říká Vandal. Pro odborníka jako vy to bude to pravý. }{ 201 }{ pc.humanity >= 4 }{ G.Vandal_Quest = 3; G.Gimble_Vandal = 1; pc.SetQuest("Danielle",7); FindPlayer().HumanityAdd( -1 ); G.Gimble_Humanity = 1 }{ }{ }{ }{ }{ }{ }{ Vandal vás přijme s potěšením, protože jste výjimečný. }
{ 257 }{ Přesně tak, ptejte se po chlápkovi, co si říká Vandal. Pro odborníka jako vy to bude to pravý. }{ Přesně tak, ptejte se po chlápkovi, co si říká Vandal. Pro odborníka jako vy to bude to pravý. }{ 201 }{ pc.humanity < 4 }{ G.Vandal_Quest = 3; G.Gimble_Vandal = 1; pc.SetQuest("Danielle",7) }{ }{ }{ }{ }{ }{ }{ Vandal vás přijme s potěšením, protože jste výjimečný. }

**Comment by soulcharmer** [comment]
oops, v UP_Plus_CZ\vdata\system\loadingtips.txt je opravil preklep u lasombry na "snažší" , ale pushnul jsem pres GitHub a cely soubory je ted v UTF.  Mam to revertnout nebo to prevezmes s ostatnima opravama z tohodle tiketu?

**Comment by soulcharmer** [comment]
**cestina/vdata/hackterminals/scott_laptop.txt**

"runtext"   "Když jsem dělal na jednom dějepisném projektu ve veřejné knihovně, všimnul jsem si, jak někdo z Lasombry jde do oddělení s uměním. Šel jsem za ním s neviditelností, ale místnost byla prázdná! Počkal jsem, až vyšel ven a sledoval jsem ho až do kanalizace otvorem, který sám používám. On pak nedaleko vylezl do ulic a navštívil několik klubů."

**cestina/vdata/hackterminals/shrekhub4_terminal1.txt**

"name" "nadílka!"
"description" "odměna"
"runtext" "Poblíž jsem ti nechal jednu vychytávku jako odměnu za pomoc. >m1tn1ck<"

**cestina/vdata/items/item_w_chang_claw.txt**

"printname" "Tigří pařáty" // changed by wesp
"description" "Tohle jsou brutálně vyhlížející kovové drápy s dřevěnou rukojetí. Navíc způsobují spalující zranění." // changed by wesp

**cestina/vdata/signs/newspaper_test.txt**

    "Text"              "   SLAVNÝ DOKTOR"
    "Text"              "   OBĚTÍ NEHODY"
    "Text"              "         28. 2. 1954  OHOŘELÉ  OSTATKY RENOMOVANÉHO"
    "Text"              "         PSYCHIATRA  DR.  ALISTAIRA  GROUTA  DNES NAŠLI VE VRAKU"
    "Text"              "         AUTA, KTERÉ HAVAROVALO V HOLLYWOODSKÝCH KOPCÍCH!!!"

========================================== ZVLÁŠTNÍ VYDÁNÍ"




A to by melo byt pro tento tiket vse.
