### ISSUE TITLE
Toxic waste Romero.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#58]
Preložené ako jedovatej odpad, ale myslím, že toxickej odpad by sa hodil úplne v pohode viac... Čo povieš?

{   81  }{  Kdo ví? Vampírská černá magie, jedovatej odpad, sluneční radiace... Podstatný je, že pořád lezou ven a že já je pak pacifikuju. Všichni jsou spokojení.  }{  Kdo ví? Vampírská černá magie, jedovatej odpad, sluneční radiace... Podstatný je, že pořád lezou ven a že já je pak pacifikuju. Všichni jsou spokojení.  }{  #   }{  npc.SetDisposition("Joy", 1)    }{  G.Romero_Rise = 1   }{  }{  }{  }{  }{  }{  }{      }

**Comment by soulcharmer** [comment]
ok, muze byt :)
