### ISSUE TITLE
dlg debugging

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#6]
Generic

newscaster.dlg

A ha ha ha ha ha...! [Serious again]Goodnight and have a pleasant evening.
A ha ha ha ha ha...! [Serious again]Dobrou noc a příjemný večer.

You too.
Vám taky.

Main characters

Jack_tutorial.dlg

[looking around at the other vampires in the room]Why don't we, uh, step out back here...
[looking around at the other vampires in the room]Raději si stoupneme kousek tady...

I like it where I am. At least I'm out of that theatre.
Líbí se mi, kde jsem. Alespoň už nejsem v tom divadle.

I am where I am. And that's not in the theatre of death.
Jsem, kde jsem. A to není v divadle smrti.

Christ. Stuffy in there, huh? This is much better.
Kriste, tam bylo hustě, viď? Tohle je už lepší.

Santa Monica

mercurio.dlg

No, sorry, I didn't find it.
Ne, promiň, nenašel jsem je.

My hands are as empty as my head.
Mé ruce jsou prázdné jako má hlava.

**Comment by soulcharmer** [comment]
spraveno
