### ISSUE TITLE
Zdvojená replika 776 a 779 Isaac.dlg

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#60]
"Ale nic. Zapomeňte na to. Musím jít."

má tam byť
{	776	}{	Sorry, I think I'll deal with it first.	}{	Sorry, I think I'll deal with it first.	}{	0	}{	not (G.Gargoyle_Convinced == 1 or IsDead("Gargoyle"))	}{	}{	}{	}{	}{	}{	}{	}{	First the stone one, then the secret.	}

**Comment by miracleflame** [comment]
Môj preklad
{	776	}{	Promiňte, myslím, že se s ním nejdřív vypořádám.	}{	Promiňte, myslím, že se s ním nejdřív vypořádám.	}{	0	}{	not (G.Gargoyle_Convinced == 1 or IsDead("Gargoyle"))	}{	}{	}{	}{	}{	}{	}{	}{	Nejprve kameňák, pak tajemství.	}

**Comment by soulcharmer** [comment]
Vloz tam prosim:

{ 776 }{ Pardon, ještě s ním nejsem hotov. }{ Pardon, ještě s ním nejsem hotova. }

malk line je v poho
