### ISSUE TITLE
Citoslovce floating

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#62]
Floating citoslovcia v hre mi prídu hrozne rušivé a absolútne nepotrebné v rámci tituliek či prekladu. Napr. "Gangster: kehem" kedykoľvek v centre LA aj keď nie je počuť samotný zvuk. Preto navrhujem ich odstránenie.

Okrem novopridaných mnou v #54 sú tu aj také, čo sú súčasťou UP alebo pôvodnej hry. Ich efektívne odstránenie z hry sa dá dosiahnuť narušením konzistencie lip súboru (napr. chybný počet znakov vo PHRASE).

@soulcharmer súhlasíš?

**Comment by soulcharmer** [comment]
Rozhodne, kill it with fire :-)

Neni ale ucinnejsi a bezpecnejsi prejmenovat ten .lip na .bkp nebo tak neco?

**Comment by miracleflame** [comment]
Súbor tam musí byť, inak si ho hra naťahá z UP, alebo z vampire foldru, alebo z vpk. Budem testovať riešenie, ktoré som implementoval.

**Comment by miracleflame** [comment]
Považujem za uzavreté, keby bolo treba, tak znovu otvorím.
