### ISSUE TITLE
Prvý Groutov diktafón unifikácia

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#63]
**gog_bloodlines_cz\cestina\sound\area\downtown\malkavian dictation_message_1.lip**

Toto som preložil aj ja, aj Ty. Naše verzie som spojil do niečoho, čo podľa mňa najpresnejšie zodpovedá anglickému textu. Podľa potreby uprav...

EN:
I t   i s   q u i t e   p e c u l i a r   t h e   h a p p e n i n g s   I ' v e   b e e n   m a d e   t o   w i t n e s s   f r o m   m y   s u p e r n a t u r a l   l o n g e v i t y .   I ' m   t h i n k i n g   o f   o n e   u n f o r t u n a t e   p h e n o m e n o n   i n   p a r t i c u l a r   o f   u n i q u e   i n t e r e s t   t o   m y   s t a t i o n . . .   b o t h   a s   a   p r o f e s s i o n a l   a n d   a s   a   s u f f e r e r   o f   t h i s   v a m p i r i c   c o n d i t i o n .   I t   s e e m s   t h e   s t r e a m   o f   t i m e   h a s   b e g u n   t o   e r o d e   t h e   m o o r i n g s   o f   m y   c h o s e n   c o u r s e   o f   s t u d y . . .   f o r   t h e   m e t h o d o l o g i e s   t h a t   g a v e   b i r t h   t o   p s y c h o l o g y   a r e   s l o w l y   d i s a p p e a r i n g .   I   f i n d   m y s e l f   i n   a n   e r a   t h a t   o v e r l o o k s   t h e   p h y s i c a l   c o m p o n e n t   o f   p s y c h o l o g i c a l   p a t h o l o g y   t i m e . . .   a n d   a g a i n   i n   f a v o u r   o f   t h e   s o p h i s t i c   p r a c t i c e s   o f   F r e u d .   P h r e n o l o g y ,   d a c t o p i n d a l i s m ,   a n d   t h e   r e s t   o f   t h e   o l d   g u a r d   i s   f a l l e n   b y   t h e   w a y s i d e . . .   i t s   c h a m p i o n s   a l l   s i l e n c e d   i n   d e a t h   w i t h   m y   u n i q u e   e x c e p t i o n .   W o u l d   t h a t   I   c o u l d   m a k e   m y   v o i c e   h e a r d   a g a i n   a l t h o u g h   i t   m a y   b e   s u s p i c i o u s . . .   s h o u l d   I   r e t u r n   t o   p o p u l a r   m e d i c a l   d i s c o u r s e   f i f t y   y e a r s   a f t e r   m y   a p p a r e n t   d e a t h .   N o ,   b e t t e r   t h a t   I   c o n t i n u e   m y   s t u d i e s   i n t o   t h e   p s y c h o s i s   i n   s e c r e t .   O n e   d a y   m a y   I   h o l d   u p   m y   o w n   c u r e   a s   v a l i d a t i o n   o f   t h e   m e t h o d s .   I   a m   c o n f i d e n t   n o   c u r e   f o r   m y   c o n d i t o n   o r   t h a t   o f   m y   b e l o v e d   w i f e   l i e s   w i t h i n   o u r   f i g u r a t i v e   m i n d s . . .   w a i t i n g   t o   b e   u n l o c k e d   b y   t h e   c o r r e c t   c o m b i n a t i o n   o f   m e m o r i e s   r e c o v e r e d   f r o m   o u r   c h i l d h o o d s .   A n d   I ' m   m o s t   c e r t a i n   t h a t   i t   h a s   n o t h i n g   t o   d o   w i t h   t h e   r e l a t i o n s h i p   b e t w e e n   m y s e l f ,   m y   p a r e n t s ,   a n d   m y   g e n i t a l s .   S o r r y ,   S i g m u n d ,   b u t   I   c h o o s e   t o   s t a y   m y   c o u r s e .   I n   t i m e ,   t o o ,   m a y   y o u r   s t a r   f a d e   a n d   d i s a p p e a r . 

CZ unified:
Je to vskutku mimořádný jev, kterému jsem byl vystaven v pozici svědka s nadpřirozenou dlouhověkostí. Mám na mysli jeden konkrétní neblahý fenomén, který mě zajímá jako profesionála tak i jako postiženého touto vampirickou nemocí. Je zjevné, že tok času začal nahlodávat základy mnou zvoleného oboru studia... jelikož metodologie, které dali vzniknout psychologii se pomalu vytrácejí. Shledávám se v éře, která stále častěji přehlíží fyzickou komponentu duševní patologie... a opět ve prospěch sofistické praxe Freuda. Frenologie, daktopindalizmus a další ze staré gardy upadají v zapomnění... všechny jejich zastánce umlčila smrt, až na výjimku mé maličkosti... Kéž bych mohl znovu nahlas promluvit, i když bylo by asi podezřelé, kdybych se vrátil do odborné lékařské debaty padesát let od své zjevné smrti. Ne, lepší bude pokračovať v mých studiech psychózy v tajnosti. Jednoho dne snad předstoupím s mým vlastním lékem jakožto potvrzením oněch metod. Jsem přesvědčen, že žádny lék na nemoc mou nebo-li mé milované manželky neleží v dosahu našich obrazných myslích... čekajíc jenom na odemčení správné kombinace vzpomínek z dětství. A jsem si naprosto jist, že to nemá žádnou souvislost ve vztahu se mnou nebo mými rodiči či mými genitaliemi. Omlouvám se, Sigmunde, ale rozhodnul jsem se držet svého směru. Časem nechť taky tvá hvězda vyhasne a zmizí."

CZ pôvodný:
Je prazvláštní, čeho všeho jsem ve|svém nadpřirozeném životě svědkem.
Mám na mysli jeden neblahý fenomén,|který mě zajímá jako profesionála, i jako postiženého touto|vampírskou chorobou.
Zdá se, že tok času začal|nahlodávat základy mého oboru, jelikož metodologie, které daly|vzniknout psychologii, se pomalu vytrácejí.
Ocitl jsem se v éře, která stále častěji|přehlíží fyzickou složku duševní patologie... ve prospěch Freudových sofistických metod.
Frenologie, daktopindalismus a další| ze staré gardy upadají v zapomnění, všechny jejich zastánce umlčila smrt,|až na výjimku mé maličkosti...
Kéž bych mohl znovu nahlas promluvit,|i když bylo by asi podezřelé, kdybych se vrátil do odborné lékařské|debaty padesát let od své zjevné smrti.
Ne, raději budu nadále|studovat psychózy v ústraní. Jednoho dne snad vyvinu lék|jako potvrzení svých metod.
Jsem přesvědčen o tom, že léčba chorob,|kterou trpím já a má milovaná žena, nespočívá v našich metaforických myslích,|kde by čekala, až ji někdo rozluští...
jako správnou posloupnost vydolovaných|vzpomínek z dětství, a jsem si naprosto jist, že nemá nic společného s mým vztahem|k rodičům nebo ke svým genitáliím.
Promiň, Sigmunde,|ale budu se držet svého kopyta. Nechť i tvá hvězda jednou vybledne a zmizí.

**Comment by soulcharmer** [comment]
finalni verze:

Je prazvláštní, čeho všeho jsem ve svém nadpřirozeném životě svědkem. Mám na mysli jeden konkrétní neblahý fenomén, který mě zajímá jako profesionála i jako postiženého touto vampírskou chorobou. Zdá se, že tok času začal nahlodávat základy mého oboru, jelikož metodologie, které daly vzniknout psychologii, se pomalu vytrácejí. Ocitl jsem se v éře, která stále častěji přehlíží fyzickou složku duševní patologie... ve prospěch Freudových sofistických metod. Frenologie, daktopindalismus a další ze staré gardy upadají v zapomnění, všechny jejich zastánce umlčela smrt až na výjimku mé maličkosti... Kéž bych mohl znovu nahlas promluvit, i když bylo by asi podezřelé, kdybych se vrátil do odborné lékařské debaty padesát let od své zjevné smrti. Ne, raději budu nadále studovat psychózy v ústraní. Jednoho dne snad vyvinu lék jako potvrzení svých metod. Jsem přesvědčen o tom, že léčba chorob, kterou trpím já a má milovaná žena, nespočívá v našich metaforických myslích, kde by čekala, až ji někdo rozluští... jako správnou posloupnost vydolovaných vzpomínek z dětství, a jsem si naprosto jist, že nemá nic společného s mým vztahem k rodičům nebo ke svým genitáliím. Promiň, Sigmunde, ale budu se držet svého kopyta. Nechť i tvá hvězda jednou vybledne a zmizí.
