### ISSUE TITLE
LIP chunk 1 rewiev

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#64]
**gog_bloodlines_cz\cestina\sound\area\santa_monica\ocean_house\oceanhouse_ghost\
be_careful.lip**
Buď opatrný!
Be careful!

**he_wants_to.lip**
Chce tě zabít!
He wants to kill you!

**help_me.lip**
Pomoz mi!
Help me!

**hes_comming.lip**
Přichází!
He's coming!

**hes_near.lip**
Je blízko!
He's near!

**hes_watching.lip**
Sleduje tě!
He's watching!

**keep_looking.lip**
Hledej dál!
Keep looking!

**gog_bloodlines_cz\cestina\sound\cinematic\santa_monica\haven
female_sire_whisper2.lip**
I wanna show you something!
Chci ti něco ukázat!

**male sire_whisper_3.lip**
Chci ti něco ukázat!
I want to show you something!

**gog_bloodlines_cz\cestina\sound\environmental\people\Police
come_out.lip**
"Vyjděte ven s rukama nad hlavou!"
"Come out with your hands up!"

**drop_weapon.lip**
"Odhoďte zbraně a vyjděte ven!"
"Drop your weapon and come out!"

**under_arrest.lip**
"Jste zatčeni!"
"You are under arrest!"

**gog_bloodlines_cz\cestina\sound\character\conversations
trapped.lip**
Hele, dostali jsme ho. Je v pasti na podlaží!
Hey, we got him now. He's trapped upstairs!

**gog_bloodlines_cz\cestina\sound\character\conversations\beach house\kitchen
calldennis.lip**
Ty, Dennisi!
Yo, Dennis!

**carl001.lip**
Sprav ty světla, k sakru!
Fix the lights, dammit!

**carl002.lip**
Al, sprav ty světla nebo ti ten ovladač narvu do prdele!
Get the lights or I shove that controller up your ass, Al!

**dennis001.lip**
Al, půjdeš rozsvítit ty světla nebo tam mám jít já?
Al, you're going to turn those lights back on or do I have to come in there?

**mike001.lip**
Sprav ty světla, Al!
Fix the lights, Al!

**Comment by soulcharmer** [comment]
Hey, we got him now. He's trapped upstairs!  ->
Hej, už jsme ho chytli. Je zavřenej nahoře!

 Yo, Dennis! ->
Čau, Dennisi!

 Fix the lights, dammit! ->
Sprav sakra ty světla!

 Get the lights or I shove that controller up your ass, Al!  -> (Al je zkracene Allan, coz je asi lepsi nechat neprelozene) ->
Hele, nahoď ty světla nebo ti nacpu ten ovladač do zadku!

 Al, you're going to turn those lights back on or do I have to come in there? ->
Hej, půjdeš nahodit ty světla nebo tam budu muset jít já?

 Fix the lights, Al!  ->
Sprav ty světla!


Jinak to vypada dobre, diky.
