### ISSUE TITLE
LIP chunk 2 review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#65]
**gog_bloodlines_cz\cestina\sound\character\conversations\
mikecarlconversation1.lip**

"Asi jsem si zlomil prsten, když jsem mlátil toho chlápka Mercuria." "Prsten? Ty nosíš prsteny?" "Spousta lidí nosí prsteny!" "Jo, spousta holek nosí prsteny." "Ne jenom holky." "Člověče, jsou jenom dva druhy chlapů, co nosí prsteny a nevybavuju si, že bys ty vyhrál Superbowl." "Jenom chci říct, že ten chlápek z pláže snesl pořádnou nakládačku!" "To jo, ani nevím, jestli jsem někdy viděl někoho takhle zřízeného pořád dejchat. Na rovinu, vu-vůbec se mi to nechce líbit. J-je mi jedno, že šel někdo kolem, podle mě jsme měli toho smrada voddělat dokud byla možnost." "Proč? Jeho prachy máme." "Mám z toho blbý dojmy. Měli bychom slyšet sanitku, někdo ho musel najít." "Hele, videls mě tam? Ty vole že Wůůha jsem mu přikroutil ten Karate kop jak ňáký Miyagi sensei a vůbec." "Jo? A co uděláš až se ten Mercurio nebo někdo jiný vrátí pro svý prachy? Měli jsme ho sundat, ti říkám." "Klídek, čéče. Nikdy jsem tě neviděl tak připosraného." "Hele vole, bacha na hubu! Nejsem připosraný, jenom něco cejtím ve vzduchu. Nevíme, s kým to ten sráč táhne, může bejt od mafie nebo co já vím." "Mafie? Je ti jasné, že jsme v Jižní Kalifornii, že jo?" "Koukej, jediné co chci říct je, že bych spal mnohem lépe, kdybychom ho voddělali. A teď mi koukej dát na ruku nějaký pořádný karty, jasný?"
"Think I broke my ring while I was beating on that Mercurio guy." "Your ring? You wear rings?" "Lots of people wear rings!" "Yeah, lot of girls wear rings." "Not just girls." "Man, there are only two kind of guys that wear rings and I don't remember you winning a Superbowl." "I'm just saying, dude from the beach could take a beating!" "Yeah, I don't think I've ever seen a guy get worked like that and not fall apart. Honestly, I-I don't like it. I-I don't care if someone was coming, I think we should've wasted that good fellow looking mother when we had the chance." "Why? We got his money." "I got a bad feeling. And we should've heard ambulances, someone must have found him." "Ey, you've seen me tonight? I was all like Wootah, did that Karate kick on him like Miyagi sensei and shit." "Yeah? And what you're gonna do if that Mercurio dude or somebody comes back for his money? Should've killed him." "Chill, man. Never seen you so damned scared before." "Ey, watch yourself, man, right! I ain't scared, I'm sensible. We don't know who this mother was running with, could be the mob or something, I don't know." "The mob? You do know that this is southern California, right?" "Look, all I'm saying is I'd sleep a whole lot better if we'd had flushed that guy. You just deal me some damned cards, alright?"

**mikedennis.lip**
"Co je?" "Carl povídá, že jsme měli toho Mercuria hodit žralokům." "Proč jako?" "Prý se týpek objeví ve dveřích a bude chtít svý prachy." "Jenom jsem řekl, že mám blbýho tušáka." "Člověče, říkals to spůsobem, jako že sem nakráčí Tony Soprano nebo něco." "Neřekl..." "Držte huby. Oba dva. Poslouchejte. Za A: Ten sráč chcípnul na pláži a pokud ne, pak je nucen kadit přes hadičku a když ho svědí prdel, poškrábat ho musí pomocná opice. Za B: Jenom za to, že týpek mluvil New Yorkským přízvukem, neznamená to, že je od mafie. A kurva i kdyby byl, pokud vy hovna neumíte zatočit s nejakýma starýma tlustýma páprdama v kombinézách, pak se okamžitě pakujte do prdele z mýho baráku. Za C: Pokud by sem nějakým neuvěřitelným zázrakem přilezl ten vopruz nebo někdo z jeho lidí, osobně tím skurvysynem nakrmím rybičky. Ještě něco snad?" "Ne, nic. Mám ti rozdát karty, Dennisi? "Peněz už mám dost. Mějte oči otevřené. Postarám se o to, aby ten Astrolit nevybouchnul, až si nekterá z vás slečinek příště kýchne." "Ty si šéf, Dennisi." "Já vím."
"What?" "Carl thinks we should have gone shark fishing with that Mercurio guy." "Why?" "Thinks dude will show up here and looking for his money." "All as I said is that I have a bad feeling." "Man, you made it sound like Tony Soprano gonna roll up here and shit." "I didn't say..." "Shut up. Both of you. Listen up. A: That poor dumb bastard died on the beach and if he didn't he now craps in a bag and has a helper monkey scratch his ass when it itches. B: Just because a hood has a New York accent does not mean he is in the mob. And shit, even if he was, if you mothers can't deal with a few fat old fags in jogging suits, you need get the hell out of my house right now. C: If by some holy miracle that prick, or someone affiliated with him, crawls his ass up here, I will personally feed that motherfucker to the fishes. Anything else?" "No, nothing. You want me to deal you in Dennis? "I already got enough money. You keep your eyes open. I'll make sure that Astrolite isn't going to go off the next time one of you fairies sneezes." "You got it Dennis." "I know."

**Comment by soulcharmer** [comment]
Opravene preklady:

"Asi jsem si zlomil prsten, když jsem mlátil toho Mercuria." "Prsten? Ty nosíš prsteny?" "Spousta lidí nosí prsteny!" "Jo, spousta holek nosí prsteny." "Ne jenom holky." "Čéče, jen dva druhy chlapů nosí prsteny a nevybavuju si, že bys ty vyhrál Superbowl." "Chci tím říct, že ten chlápek z pláže měl solidní výdrž!" "To jo, myslím, že jsem ještě neviděl někoho takhle zřízeného pořád dejchat. Na rovinu, ne-nechce se mi to líbit. J-je mi jedno, že šel někdo kolem, podle mě jsme měli toho smrada voddělat dokud byla možnost." "Proč? Jeho prachy máme." "Mám z toho blbej pocit. Měli jsme slyšet sanitku, někdo ho musel najít." "Hej, viděls mě tam? Byl jsem jako ninja, dal jsem mu kopanec jako od mistra Miyagiho." "Jo? A co uděláš, až si ten Mercurio nebo někdo jinej pro ty prachy přijde? Měli jsme ho sundat." "Klídek, čéče. Nikdy jsem tě neviděl tak připosranýho." "Hele vole, bacha na hubu! Nemám strach, ale cejtím něco ve vzduchu. Nevíme, s kým to ten sráč táhne, může bejt třeba od mafie, co já vím." "Mafie? Všiml sis, že tady jsme v Jižní Kalifornii, že jo?" "Hele, prostě by se mi spalo líp, kdybysme toho hňupa odkráglovali. A teď konečně rozdej nový karty, okej?"

"Co je?" "Carl povídá, že jsme měli toho Mercuria hodit žralokům." "Proč jako?" "Že prý se objeví ve dveřích a bude chtít svý prachy." "Jenom jsem řekl, že z toho mám blbej pocit." "Člověče, říkals to, jako by se tu měl objevit Tony Soprano nebo kdo." "To jsem ne--" "Držte huby. Oba. Poslouchejte. Za A: Ten sráč chcípnul na pláži a jestli ne, musí teď srát přes hadičku a když ho svědí prdel, má na to poskoka. Za B: To, že měl přízvuk z New Yorku ještě neznamená, že je od mafie. A i kdyby kurva byl, pokud si vy hovna neumíte poradit s pár tlustýma buznama v teplákovkách, tak se kurva pakujte z mýho domu. A za C: Pokud by se sem nějakým zázrakem ten šmejd nebo někdo od něj dostal, udělám z něj žrádlo pro rybičky osobně. Ještě něco?" "Ne, nic. Mám ti taky rozdat karty, Dennisi?" "Já už mám peněz dost. Pořádně hlídejte. Já se postarám, aby ten Astrolit nevybouchnul, až si nekterá z vás slečinek příště kýchne." "Ty jseš šéf, Dennisi." "Já vím."
