### ISSUE TITLE
LIP chunk Al review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#66]
Niektoré z týchto lipov sú použité ako floats v **cestina\sound\character\male\al\float_*.lip**, tak ich potom treba dať rovno aj tam.

**gog_bloodlines_cz\cestina\sound\character\conversations\beach house\living room\
al001.lip**
Hadouken, píčo!
Hadouken, bitch!

**al002.lip**
Zasraný cheaterský počítač!
Cheatin' ass computer!

**al003.lip**
Kdo si to chce se mnou rozdát? Jo, to jsem si myslel!
Anyone wants some of this? Yeah, that's what I thought!

**al004.lip**
Musím si lopnout nějaké nové hry.
I gotta steal me some new games.

**al005.lip**
Ó ano! Tvá prdel se vyformovala!
Oh yeah! Your ass got perfected!

**al006.lip**
Sakra! Dyť jsem blokoval!
Shit! I was blocking!

**al007.lip**
Ale no tak! Skoušel jsem nové tahy!
Come on! I was tryin' new stuff

**al009.lip**
Ty zapni elektriku, píčo!
You turn on the power, bitch!

**al010.lip**
Tak, tak tedy dobrá, do prdele!
A-a-alright man, shit!

**al011.lip**
Proč já musím pořad chodit spravovat světlo, ty krávo? Al, sprav světla. Al, běž pro pizzu. Umej krev na podlaze, Al. Vole, to abych si najal asistenta nebo co.
Why do I always have to get the lights, man? Al, get the lights. Al, pick up the pizza. Clean up the blood stains, Al. Shit, I need to hire an assistant or something.

**al012.lip**
Zasraná světla! Vypadám snad jako elektrikář nebo co, do prdele? Hajzlové! Toto je naposled, co sem lezu spravovat světla, vole.
Goddamn lights! I look like an electrician or some shit? Assholes! This is the last time I get these lights, man.

**Comment by soulcharmer** [comment]
Hadouken, píčo! -> :)
Hadouken, pyčo!

 Cheatin' ass computer! ->
Ta kraksna podvádí!

 Anyone wants some of this? Yeah, that's what I thought! ->
Chce si to někdo rozdat? Jo, to jsem čekal!

 I gotta steal me some new games. ->
Musím upirátit nový gamesy.

 Oh yeah! Your ass got perfected! ->
Jo! Teď jsem tě vyškolil!

 Shit! I was blocking! ->
Kurva! Však jsem blokoval!

 Come on! I was tryin' new stuff ->
Ale no tak! Zkoušel jsem novej trik.

 You turn on the power, bitch! ->
Sám to běž nahodit, zmrde!

 A-a-alright man, shit!  ->
Tak dobře, čéče, už jdu!

 Why do I always have to get the lights, man? Al, get the lights. Al, pick up the pizza. Clean up the blood stains, Al. Shit, I need to hire an assistant or something.  ->
Proč musím pokaždý spravovat světla já? Ale, zapni světla. Ale, běž pro pizzu. Ale, umej tu krev. Měl bych si najmout asistenta nebo něco.

 Goddamn lights! I look like an electrician or some shit? Assholes! This is the last time I get these lights, man.  ->
Zasraný světla! Jsem snad elektrikář nebo co? Zmrdi! Tohle je naposledy, co nahazuju světla!
