### ISSUE TITLE
LIP chunk elizabeth_dane review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#67]
**gog_bloodlines_cz\cestina\sound\character\conversations\elizabeth_dane\
copconversation2.lip**
"Je to nejaký symbol." "Hele lidi, jste v kontaktě s Deep Water, NVMC nebo s kým? Koho to tam máme?" "Není to úplně povědomé." "Dobrá, podívej Gannete, tohle je něco, co musíme vyřešit dřív, než nám to tady někdo přebere. Chci říct, koukni, tohle nám později ušetří spoustu práce, když to vyřešíme teď, okej, souhlasíš? Pokaždé procházíme tím samým. Dobrá tedy. Zjisti, co to je a ušetříme si spoustu problémů." "Bille, co tam vidíš?" "Hmm?" "Není to nic zdejšího, žádná podobnost se znaky místních gangů, co znám. Nevím, jestli by pobřežní hlídka neznala zda li to nemá souvis s nějakou pirátskou organizací." "Je to králíček." "Co?" "Ten symbol, je to králíček!" "Králíček?" "Ano."
"Some kind of symbol." "Ah, you guys in touch with Deep Water, NVMC or who? Who do we have here?" "Not immediately familiar." "Well look, Gannet, this is something we need to get squared away before anyone puts any stakes down. I mean, look, this'll all save us some work later if we get this shit squared down now, okay, agreed? We go through this every goddamn time. Alright, fine then. Find out and we'll save us all some trouble." "Bill, what do you make of this?" "Huh?" "It's nothing local, no similarity to any local gang signs I know off. I didn't know if the coast guard would know if perhaps it was associated with any pirate organisations." "It's a bunny." "Wha?" "The symbol, it's a bunny!" "A bunny? Yes.

**copconversation3.lip**
"Zdá se, že chybí krabice, všechen ten náklad a chybí jedna malá krabička?" "To bude jenom překlep v protokole." "Jo nebo ji šlohnul někdo z posádky." "Zbláznil ses?" "Pro zatím budeme předpokládat, že kvůli ní přišli." "Píše se tam, co v ní bylo?" "Ne, zdá se, že byla přibalena k té velké rakvě, k sarkofágu, neudává se obsah." "Podezřelé!" "Mohlo by to souviset s drogama?" "Těma jatkama chtěl někdo zanechat určitý vzkaz. Proč se ale zbavovat těl?" "Nevím, nic z toho nedáva smysl." "A co ten sarkofág, už se doň někdo podíval?" "Je na pevno zapečetěný, prakticky zvařený, nenajdeš ani škáru. Normálně bys řekl, že je to v jednom celku." "Hmmm."
"A box missing, looks like, all this cargo and one little box gone?" "That'd be just a typo in the manifest." "Yeah or someone in the crew could've swiped it." "Lost it?" "For now we should assume that's what they came out here for." "Does it say what was in it?" "No, looks like it was packaged with the uh, the big coffin thing, the sarcophagus, no contents listed." "Fishy!" "Could it be a drug thing?" "With a slaughterhouse scene like this someone wanted to get a message across here. Why get rid of the bodies though?" "Dunno, no sense to any of it." "What about the sarcophagus, anybody take a look yet?" "It's sealed up tight, fused together practically, can't even find a seam. You'd almost think it was solid." "Hmmm."

**Comment by soulcharmer** [comment]
Opravy:

"Jakýsi symbol." "Hej, jste v kontaktu s Deep Water, úřadem pro dozor v národních vodách nebo tak někým? Kdo myslíte, že to je?" "Nevypadá to povědomě." "Hele Gannete, tohle bysme měli vyřešit dřív, než do toho začnou strkat nos ostatní. Ušetří nám to práci, když to rozlouskneme rovnou, souhlas? Pokaždý je to to samý. Tak fajn. Zjisti, co to je, a všichni se vyhneme problémům." "Bille, co si o tom myslíš?" "Hmm?" "Není to nic zdejšího, nepodobá se to žádnýmu gangu, co znám. Třeba by pobřežní hlídka věděla, jestli to nepatří nějakým pirátům." "Je to králíček." "Co?" "Ten symbol, je to králíček!" "Králíček?" "Jo."

"Zdá se, že chybí jedna krabice - z celýho nákladu chybí jen jedna?" "To bude jenom překlep v lodním záznamu." "Jo, a nebo ji šlohnul někdo z posádky." "Nebo ztratil?" "Prozatím budeme předpokládat, že kvůli ní tu byli." "Píše se tam, co v ní bylo?" "Ne, zdá se, že byla přibalená k té velké rakvi, k tomu sarkofágu, obsah není uveden." "Divný!" "Že by něco s drogama?" "Touhle krvavou scénou tu chtěl někdo zanechat  vzkaz. Proč se ale zbavovat těl?" "Nevím, nic z toho nedáva smysl." "A co ten sarkofág, už se na něj někdo díval?" "Je zavřený natěsno, jakoby svařený, ani není vidět spára. Skoro vypadá jako monolit." "Hmm."
