### ISSUE TITLE
LIP chunk giovanni bruno.lip review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#68]
**gog_bloodlines_cz\cestina\sound\character\conversations\giovanni\
bruno.lip**
"Vážím si účast vás všech tady. Už to bude pár let, co jsem se s některými z vás viděl. Během toho krátkeho období jsme byli svědky událostí, které vedli k uvoľnení vřelého objetí hlavy naší rodiny v Itálii. Američtí Giovanni si prošli tvrdými časmi, pravda jest! Pád burzy, chabé investice do nekolik kdysi osvědčených a pravých podniků. Stráta mnohých starých dobrých přátel ve Washingtnu, kterí sloužili našim nejlepším zájmům. Avšak slibuji vám, že po dnešním večeru budou všechny tyto neštěstí odpuštěny! Ankaranský sarkofág, jistě se mnozí z vás dozvědeli o jeho krádeži z médií. Pravdou v tohto ohledu je, že byl vzat na základe mého pokynu, ptáte se proč? V mnohém se ponáší na artefakt, o kterém se vypráví, že drží duše celého království vymíceného ve věku faraonů. Již počas mého príhovoru tí nejnadanější z naší rodiny připravují sklizeň této kořisti duší. Přiblížení rodiny Giovanniů o krok blíž k věčné noci je to, na čem jsme celá staletí tvrdě pracovali! Zas jednou jsou američtí Giovanni připraveni v pozici zahájit velkolepý návrat a zaujat vážené místo. A na oslavu této zváštní přiležitosti jsem se rozhodnul uchvátit dva z vás, a také dovolit vám vybrat jednu osobu z této sešlosti, které bude splnomocnění polibku uděleno. Až se ostatní vrátí, upovědomíme Itálii o našich ůspěších a zahájíme uchvácení. Ať je tato noc začátkem výdatného nového století! A nezapomeňme se poďekovat Bohu za tuto příležitost znovu nabudnout váženou tvář našich předků. Amen!"
"I appreciate everyone's attendance here this night. It has been several years since I saw some of you. In that brief period of time several events have seen this family fall from the good graces of the head of the family back in Italy. The American Giovanni have been through hard times, this is true! The fall of the stock market, poor investments in several once tried and true industries. The loss of many old and dear friends in Washington who served our best interests. But I promise you, that after tonight these unfortunate mishaps will all be forgiven! The Ankaran Sarcophagus, you well may have heard about it's theft on the news. The truth of the matter is it was taken on my orders, why? It bears a great resemblance to an artifact said to contain the spirits of an entire kingdom wiped out during the time of the pharaohs. As I speak the most accomplished of our family are preparing to harvest this bounty of souls. Bringing the Giovanni family one step closer to the endless night we have toiled to bring about all these centuries! Once again, the American Giovanni are poised to make a grand return to a position of esteem. And to celebrate this momentous occasion, I have decided to embrace two of you, and to allow you to choose one person at this party to bestow the proxy kiss upon. When the others return, we shall inform Italy about our accomplishments and commence with the embrace. Let this night be the beginning of a prosperous new century! And let us not forget to thank God for this opportunity he's provided to regain face with our honored elders. Amen!"

**Comment by soulcharmer** [comment]
preklad: 

"Vážím si účasti vás všech dnes večer. Některé z vás jsem již několik let neviděl. Během té krátké doby došlo k několika událostem, kvůli kterým tato rodina ztratila přízeň hlavy naší širší rodiny v Itálii. Giovanniové v Americe skutečně prožili krušné časy! Pád burzy, chybné investice v již dříve osvědčených odvětvích. Dále ztráta mnoha starých a dobrých přátel ve Washingtonu, kteří pro nás mnoho udělali. Avšak slibuji vám, že ještě dnes budou tato neštěstí prominuta! Ve zprávách jste mohli zaznamenat zmizení Ankarského sarkofágu. Ve skutečnosti byl zajištěn na můj popud. Ptáte se proč? Velice se totiž podobá aktefaktu, o němž koluje, že obsahuje duše celého jednoho království vyhlazeného za éry faraónů. Již právě teď nejnadanější členové naší rodiny připravují tyto duše ke sklizni. Celá staletí jsme tvrdě pracovali, abychom rodinu Giovanniů přiblížili k věčné noci! Američtí Giovanniové se opět velkolepě vrátí mezi vážené rodiny. A na oslavu této historické události jsem se rozhodl, že uchvátím dva z vás a umožním vám vybrat jednu přítomnou osobu, která bude moci obdržet zmocněný polibek. Až se ostatní vrátí, budeme informovat Itálii o našem úspěchu a potom zahájíme samotné uchvácení. Nechť je dnešní noc začátkem století blahobytu! A nezapomeňme poděkovat Bohu za tuto příležitost znovu získat vážnost v očích našich ctěných předků. Amen!"
