### ISSUE TITLE
LIP chunk murder scene review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#69]
**gog_bloodlines_cz\cestina\sound\character\conversations\murder scene\
coptalk.lip**
"Během svého života ve službě jsem videl mnoho šokujících věcí, ale to molo... to je něco, kvůli čemu přestáváš věřit v lidskost!" "Musím říct, že to je druhá nejhorší věc, jakou jsem kdy viděl." "Ten ubožák tam je roztrhán vejpůj! Podle toho, jak to vypadá, bys řekl, že ho někdo uvázal ke dvěma koním a poštval je od sebe v opačném směru. Co horšího si vůbec mohl vidět nežli tamto?" "Bylo to asi před třema rokma v Malibu, našli jsme jistého chlápka na pláži. Vypadalo to jak - já nevím - zvířecí napadení." "Žralokem?" "Ne. Viděl jsem kousnutí od žraloka, tohle bylo neco jiného. Jako kdyby to něco, co ho zabilo, vědelo co dělá. Hlava chyběla, ruce chyběli, a... a byli tam takové obrovské šrámy, ale..." "Hovadina!" "Ne, ne, tenhle chápek byl doslova rotrhán na cáry! Nejhorší na tom bylo, jak jsem čekal na masárský vůz a cítil jsem, jako že mě něco sleduje. Přísahám teď tady na svůj odznak, že tam něco bylo ve tmě. A na zlomek sekundy jsem myslel, že se rozběhnu do hlídkového vozu a vypadnu sakra pryč z toho místa. Až dodnes mě to nutí zamýšlet se, co tam venku doopravdy je..." "Ha! Možná to byl vlkodlak - Wůůůůů!" "Dobrá, dobrá!" "Nebo upír - bu!" "Kašli na to! Vidíš, toto je přesne to, proč's nebyl pozván na Hernandezovu svadbu, Ted!"
"I've seen a lot of shocking things in my time on the Force, but that pier... that's the kind of thing that makes you lose your faith in humanity!" "I've got to say it's the second worst thing I've ever seen." "Poor bastard down there is torn in two! By the looks of it, you'd think someone tied him to two horses and raced them in opposite directions. What could you have possibly seen that was worse than what's down there?" "It was about three years ago, up in Malibu, we found this guy on the beach. Looked like - I don't know - an animal attack." "Shark bite?" "No. I've seen shark bites, this was something different. Like whatever killed him knew what it was doing. The head was missing, the hands were missing, and... and there were these huge slashes, but..." "Bullshit!" "No, no, this guy was literally slashed to ribbons! The worst part was I was waiting for the meat wagon and I felt like something was watching me. I swear on my badge today that there was something just out of sight. And for a split second I thought about running to the squad car and getting the hell out of that place. To this day, it makes me wonder what's really out there..." "Ha! Maybe it was a werewolf - Whoooo!" "Alright, alright!" "Or a vampire - booh!" "Forget it! See, this is why you didn't get invited to Hernandez's wedding, Ted!"

**Comment by soulcharmer** [comment]
preklad:

"Už jsem ve službě viděl ruzný svinstvo, ale to molo... kvůli takovým věcem ztrácím víru v lidstvo!" "Musím říct, že pro mě to je druhá nejhorší věc, co jsem kdy viděl." "Ten chudák je roztrhanej na kusy! Jako by ho někdo přivázal ke dvěma koňům a každýho poštval opačným směrem. Co horšího jsi mohl kdy vidět!?" "Asi před třemi lety v Malibu jsme našli chlápka na pláži. Vypadalo to - co já vím - na útok zvířete." "Žralok?" "Ne. Rány od žraloka jsem viděl, tohle bylo jiný. Jakoby to, co ho zabilo, vědělo, co dělá. Hlava a ruce tam nebyly a...  měl na sobě velké sečné rány, ale..." "Kecy!" "Ne, vážně, ten chápek byl doslova na cáry! Nejhorší bylo, že když jsem čekal na funebráky, měl jsem pocit, že mě něco sleduje. Přísahám na svůj odznak, že tam bylo něco ve tmě. Na okamžik se mi chtělo utýct do auta a ujet. Dodnes si říkám, co se opravdu skrývá v temnotě..." "Ha! Možná to byl vlkodlak..." "Fajn, dobrý!" "Nebo vampír - bu!" "Trhni si! Abys věděl, kvůli takovým kecům tě Hernandez nepozval na svatbu, Tede!"
