### ISSUE TITLE
LIP chunk parking garage review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#70]
**gog_bloodlines_cz\cestina\sound\character\conversations\parking garage\
ambush1.lip**
"Už to bude." "Pohne se kterýkoliv z tech schizů a začnu pálit." "Nebudou ani tušit, odkud to přišlo, hehehe." "Myslíš, že budou mít něco za lubem?" "Hmmm, doufejme."
"Any second now." "Either schizo moved, I'm going in shooting." "Never know what hit 'em, hehehe." "Think they'll try something?" "Hmmm, let's hope so."

**dirty1.lip**
"Každý rozumí, ano? Pootevřeš kufrík do poloviny a čekáš až udělaj to samý. Budou chtít vidět prachy, ale to se nesmí stát." "Protože je to vycpaný novinama?" "Fakt jo, proto? Měl bych tě praštit! Zas začínáš. Otevři kufřík do poloviny, až budou chtít vidět peníze, hoď ho dolu před jejich chlápka. Jakmile se pro něj sehnou, lehneš k zemi a popadneš jejich kufřík. Budeme připraveni na nich vyletět. Když to schytáš, je to tvá chyba." "Co když bude jejich kufřík plný novin?" "Pak se alespoň pobavíme, až uvidíme tvou negramotní prdel, jak se je snaží číst. Vím, že to maj. Jen to neposer, magore, jinak nás oba oddělaj."
"Everyone understands, right? Take the case halfway, and wait for 'em to do the same. They'll wanna see the money, but we can't let 'em." "'Cause it's filled with newspaper?" "Really, is that why? Ooh, I should smash you! Starting again. Bring the case out halfway, when they wanna see the money, you put it down in front of their guy. Soon as he reaches for it, you duck and grab his case. We'll be ready to open up on 'em. You get hit, it's your own fault." "What if their case is full of newspaper?" "Then at least we get to watch your illiterate ass try to read it later for laughs. I know they got it. Just don't ass it up, fool, or they gonna kill both of us."

**elevator1.lip**
"Dobrá, dávejte pozor, Tong stříli první, jo? Za prvé, jak to já vidím, mám plán, na kterém jsem pracoval, hele, sledujte to." "Kryj mi záda, Scootře, Papa říkal, že tito kašpaři nejsou žádné měkoty. Jak nám nedají, co chceme, okamžite palte, kapiš?" "Já doufám, že dají, jinak bude.. 'Hele, Tongu, máš rád Johna Woo'? Uděláme Živý terč." "Živý terč? Co to sakra je? Nikdy jsem neviděl Živý terč, ani jsem netušil, že to natočil John Woo." "To byl dobrý film, čéče, byl v něm Van Damme a tenhle chlápek s ovesnou kaší." "Já... já... seru ti na to. Prostě buď připraven sundat tyhle voly. Klidne při tom řekni: Hele, máš rád Johna Woo? Kulka do hlavy, kreténe!" "Hele, já to nechápu." "Vole, sklapni, debile!"
"All right, so check this out, Tong takes a shot, yo? First one I see I've this line I've been workin' on, yo, check it." "Watch my back, Scooter, Papa said these jokers ain't playin'. They don't give us the stuff, pop off, you know?" "I hope they do, 'cause (Yo, Tong, you like John Woo)? Hard Target right here." "Hard Target? What the hell does that mean? Never seen Hard Target, I didn't even know it was a John Woo film." "It was a good film, man, it had Van Damme and that oatmeal guy." "I don't... I don't... I don't care. Just be ready to drop these fool. It's cool to say: Yo, you like John Woo? Bullet in the head, asshole!" "Yo, I don't get it." "Man, shut up, stupid!"

**exchange1.lip**
"A jakmile upustí prachy?" "Sehnu se pro ně, přikrčím se a vy začnete pálit. A pokud buduou chtít vidět, co je v kufru?" "Pokud ano, upusť ho jako omylem a přikrč se. Stejný scénář: Začneme pálit. Pravý kufr je tady u nás." "Dobrá, jsem připraven." "Kryjeme ti záda."
"And as soon as they drop the money?" "I bend over, pick it up, duck low and you open fire. What if they want to see what's in the case?" "If they do, drop it by accident, and duck. Same thing: we'll start shooting. We've got the real case right here." "Right, I'm ready." "We've got you covered."

**gang1.lip**
"Co na tom tak trvá?" "Žádná palba, žádny problém." "Sundali by jsme je snadno." "Posledně když to vypuklo, vole, skrčil jsi se za auto a pochcal jsi se." "To byla... krev." "No ano, jasně, protože jsi to schytal a nikomu o tom ani nemukl." "To proto... protože už mi pak bylo líp." "Sakra chlape, jak je možné, že jsem parťak s někým jako ty?"
"What's taking so long?" "No gunshots, no worry." "We could take 'em out, easy." "Last time it went down, man, you ducked behind a car and pissed yourself." "That was... blood." "Oh, yeah right, 'cause you got shot and didn't tell nobody." "That's 'cause... it got better." "Damn, man, how come I gotta get stuck with you?"

**nervous1.lip**
"Je tady moc ticho, ne-nelíbí se mi-mi to tady. V noci jako kdyby tady strašilo." "Hmmf." "Nemáš pocit, jako by tady něco bylo, jako že nás něco sleduje?" "Ne." "Ježí se mi chlupy po celém těle. Přísahám, že tady něco je. Jako by... jak se to řekne?" "Panika?" "Ne, jako jako... kašli na to. A neříkej Johnnymu, že jsem panikařil. Nepanikařím." "Vopruz." "Čuráku!" "Hmmf."
"It's too quiet, I-I don't like this-this place. At night it seems so haunted." "Hmmph." "Don't you feel like something's here, like we're being watched?" "No." "The hairs on my back and my neck are sticking up. I swear there's something here. It's like... what's the word?" "Nervous?" "No, it's-s... forget it. And don't go telling Johnny I was nervous. I'm not nervous." "Annoying." "Dick!" "Hmmph."

**Comment by soulcharmer** [comment]
gog_bloodlines_cz\cestina\sound\character\conversations\parking garage
ambush1.lip
"Už to bude." "Jak se ti úchylové pohnou, začnu pálit." "Nebudou mít páru, co přišlo, hehehe." "Myslíš, že něco zkusí?" "Hmmm, doufám, že jo."

dirty1.lip
"Všechno jasný? Dones kufr na půl cesty a počkej, až udělaj to samý. Budou chtít vidět prachy, ale to se nesmí stát." "Protože je vycpanej novinama?" "Že by, fakt? To je na přeshubu! Tak znova. Ukážeš jim ten kufr jen napůl a až budou chtít vidět prachy, položíš ho před jednoho z nich. Jakmile po něm sáhne, dřepneš a popadneš jeho kufr. Pak na ně vletíme. Jestli to schytáš, je to tvá chyba." "Co když taky přinesou noviny?" "Tak se aspoň pobavíme, až se je pak pokusíš přečíst, ty negramotný jelito. Určitě to maj. Hlavně to neposer, ty hňupe, jinak nás sejmou oba dva."

elevator1.lip
"Hele, koukej, takže Tong bude střílet? Jak uvidím prvního, mám na to plán, sleduj." "Hlavně mě kryj, Scootere, Papa říkal, že tihle zmrdi se s tím neserou. Jak nám nedají matroš, tak střílej, jasný?" "Doufám, že dají, protože - Tongu, máš rád Johna Woo? Uděláme Živej terč." "Živej terč? Co to jako znamená? Neviděl jsem to, ani nevím, že to je biják od Johna Woo." "Byl to dobrej film, kámo, byl v něm Van Damme a ten chlápek s kaší." "Já... já... seru na to. Prostě se ty hajzly připrav. Můžeš jim říct: Hej, koukáte na Johna Woo? Kulka do palice, dementi!" "Hej, to nechápu." "Vole, sklapni, debile!"

exchange1.lip
"A až hodí na zem prachy?" "Sehnu se pro ně, přikrčím se a vy začnete pálit. A když budou chtít vidět, co je v kufru?" "V tom případě to pusť na zem jako by omylem a jdi k zemi. Stejnej scénář: začneme pálit. Pravý kufr máme tady." "Okej, můžeme." "Kryjeme ti záda."


gang1.lip
"Proč to tak trvá?" "Žádná střelba, žádný starosti." "My bysme je sundali raz dva." "Kámo, posledně když to vypuklo, schoval ses za auto a pochcal ses." "To byla... krev." "Jo, jasně, protože tě střelili, ale nikomus to neřekl." "Protože... pak už mi bylo líp." "Sakra, chlape, jak je možný, že vždycky dostanu tebe?"


nervous1.lip
"Je moc ticho, t-to se mi nechce líbit. V noci jakoby tu strašilo." "Hmmf." "Nemáš pocit, jako by tady něco bylo, že nás něco sleduje?" "Ne." "Ježí se mi chlupy na zádech. Přísahám, že tady něco je. Jako by... jak je to slovo?" "Nervózní?" "Ne, je to... kašli na to. A ne že budeš říkat Johnnymu, že jsem nervózní. Nejsem nervózní." "Vopruz." "Debile!" "Hmmf."

**Comment by soulcharmer** [comment]
typo:

 Prostě se ty hajzly připrav ->
 Prostě se na ty hajzly připrav

jako by omylem ->
jakoby omylem
