### ISSUE TITLE
LIP chunk society of leopold review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#71]
**gog_bloodlines_cz\cestina\sound\character\conversations\society of leopold\
bach_death.lip**
Nastal tvůj soudný den!
Your time of judgment is here!

**cafeteria guards.lip**
"Jeden z nás by měl jít dolů zanést nejaké jídlo vězni." "Johansenovi? Ten není o nic lepší než oni, nebýt jeho vlezlého vrtání, žádný artefakt by jsme tu neměli." "Ano, dost komplikovaná situace a zvláštný zvrat událostí. Myslíte, že je uvnitř... něco?" "Je mi to jedno, pokud ano, s Boží pomocí to pošleme s vřískotem zpátky do pekel!" Bratr Krüger říká, že by to mohl být on, syn Adamův, vrah bratra." "Hmmm, pokud nadešel soudný den, ať nám Pán dá sílu prohlédnout je." "Tak? Sebereme nějaké jídlo dolů pro Johansena?" "Tady, vemte moje, už nemám hlad."
"One of us should take some food down to the prisoner." "Johansen? He is no better than they, if not for his meddlesome diggings the artifact would never have come here." "Yes, this complicated matters, interesting turn of events. Do you think it holds... something?" "I care not, if it does then with Gods help we will send it screaming back to hell!" Bruder Krüger says it may be him, the son of Adam, the brother killer." "Hmmm, if this be the end of days, then may the Lord give us strength to see them through." "So? Shall we take some food down to Johansen?" "Here, take mine, I'm no longer hungry."

**caves_2.lip**
"Je pravda co se říká, myslím o něm?" "O bratru Grünfeldovi?" "Ano." "Copak jste slyšeli za povídání, mladý bratře?" "Slyšel jsem mnohé, někteří říkaj, že videli, jak jeho mámu sežrali za živa střigy. A jiní říkaj, že prý zabil staršího vampíra holýma rukama. Dokonce se pošuškává, že je to sám Svatý Leopold, co vstal z mrtvých, aby vedl své odboje do finální bitvy proti armádám temnoty." "Hehehe, ne všechny příběhy, co jste slyšeli, jsou pravdivé. Bratr Grünfeld je dobrý voják, jakým se stanete i vy, pokud budete věřit v Boha a moc stát v jeho armáde." "Taky se říká, že prý zabil někoho z bratrstva, kdo odmítl uposlechnout jeho rozkaz." "Hmmm, některé příbehy co jste slyšeli, jsou pravdivé, mladý bratře."
"Are the stories true, about him I mean?" "Brother Grünfeld?" "Yes." "What stories have you heard, young brother?" "There are many, some say he saw his own mother eat alive by a coven of witches. And others that he once killed an elder vampire with his bare hands. There are even whispers that he is the resurrected St Leopold, come to lead his armies into the final battle against the armies of darkness." "Hehehe, not all stories you hear are true. Brother Grünfeld is a good soldier just as you'll become if you have faith in God and the discipline to stand in his army." "It is also said that he once killed a man of the brotherhood because he refused to follow orders." "Hmmm, some stories you hear are true, young brother."

**cavesjail.lip**
"Šššš, slyšeli jste to?" "Asi jo, půjdu to skontrolovat?" "Ne, pokud tam někdo je, ať přijde on k nám, vede tudy jenom jedna cesta." "Mýlíte se, je i jiná cesta, musíme být opatrní." "Ano, dá se říct, ale neznám jediného člověka, který by dokázal zadržet dych na tak dlouhou dobu." "Není to člověk, koho by jsme se měli obávat." "Aha ano, chápu, co tím myslíte, bratře. Vskutku buďme opatrní."
"Shhh, did you hear something?" "Perhaps, shall I go and investigate it?" "No, if someone is out there let him come to us, there is only one way in here." "You're mistaken, there's another way, we must be cautious." "Yes, I suppose, but I don't know the man who can hold his breath for that long." "It is not man we need to worry about." "Ah yes, I see your point brother. We shall be cautious indeed."

**condotierre_backdoor.lip**
"Sláva Pánu, ten vypadá jako tvrdý muž." "Vy nevíte, kdo to je?" "Ne, měl bych?" "To je Grünfeld Bach." "To jméno zní povědomě." "Jak dlouho jste sloužili u Conditierre?" "Moc dlouho ne, zložil jsem přisahu mminulou zimu." "Chápu. Líbí se vám sloužit u bratrstva?" "Jisteže." "Pak vám radím, držte se dál od bratra Grünfelda."
"The glorious dei, he looks like a hard man." "Don't you know who that is?" "No, should I?" "That's Grünfeld Bach." "The name sounds familiar." "How long have you been with the Conditierre?" "Not very long, I was sworn in just last winter." "I see. Are you enjoying your service into the brotherhood?" "Of course." "Then I recommend staying clear of Brother Grünfeld."

**condotierre_clearing.lip**
"Buďte zdráv veliteli." "Buďte zdráv vojáku." "Něco k hlášení? Gladius dei nám vzkázal, ať jsou naše zraky bystré! Myslí si, že dnes večer budeme mít návštěvníky." "Jistě, pane. Má povinnost je jako vždy chrániť bratrstvo! Na teď se zdá byť vše tiché." "Dobře, dobře." "Zmínil se... o jaké návštěvníky se jedná, pane?" "Jedině o takové, které nás zajímaj." "Ano pane, jistě, pane. Zdar!"
"Greetings commander." "Greetings soldier." "Anything to report? The gladius dei has told us to keep a sharp eye! He thinks we may have some visitors this evening." "Of course, sir. My duty as always is to protect the brotherhood! All seems quiet for now." "Good, good." "Did he mention... ah, what kind of visitors, sir?" "The only kind that matters soldier." "Yes sir, of course, sir. Carry on!"

**monastery_guards.lip**
"Bratr Grünfeld působí dnes večer obzvlášť rozrušeně." "Ano, LaCroix začíná mít otevřenější tahy a bratr Grünfeld strácí trpělivost." "To ano, LaCroix. Jako vždy Grünfeld se zaměřuje jenom na svého odvěkého nepřítele. Doufejme, že jeho fanatizmus bude ve prospěch našeho řádu, a ne pozue jeho neuzavřenou záští z minulosti." "Šššš, zbláznili jste se? Bratr Grünfeld nebude tolerovat takovou nestydatost, držte si jazyk za zuby! Víte na čí přímý příkaz koná?" "Ano, to vím. Nepřináleží mi zpochybňovat etické záměry Svaté Stolice." "Uděláte nejlépe, když si spomenete, kde je vaše místo! Bratr Grünfeld je věrohodný bojovník. Bojoval se Satanovými přisluhovači déle, než jste vy naživu!" "Pak se modlím k Pánu, aby mi uštědřil stejná léta v jeho armádě!" "Amen."
"Brother Grünfeld seems particulary uneasy this evening." "Yes, LaCroix has begone to move more openly, and Brother Grünfeld grows impatient." "Ah yes, LaCroix. As always Brother Grünfeld focusses only on his old nemesis. Let us hope his fanatisism best serves the interests of our order, and not merely his own unresolved grievances." "Shhh, are you mad? Brother Grünfeld will not tolerate such insubordination, hold your tongue! You know upon whose direct autority he acts?" "Yes, I know. Far be it for me to question the ethic of the Holy See." "You would do best to remember your place! Brother Grünfeld is a faithful warrior. He's battled Satan's spawn for longer than you've been alive!" "Then I pray the Lord grant me the same years to fight in his army!" "Amen."

**prayer.lip**
Pane, modlím se k tobě, abys mi dal sílu do boje. Ať prekonám hordy Satanovy i děti jeho. Ať unesu ohnivý meč archandělův a ochráním se štítem víry. A ať jsou má vítězství mnohá a prohry žádná. Ať je království tvé ako v nebi tak i na zemi. A pokud dnes budu smrti čeliti, nechť uvrhnu nejdřív mocného hostitele démonů zpátky to plamenů pekelných odkud vzešel. A na závěr ať spočinu ve svělte tvé slávy. Amen.
Lord, I pray now that you give me strength in battle. That I might overcome the hordes of Satan and his children. That I might wield the flaming sword of the archangel and defend myself with your shield of faith. And that my victories are many and my wounds few. That I might further your kingdom here on earth. And if I meet death tonight, then let it be first that I cast a mighty host of demons back into the lake of fire whence they came. And then rest finally in the light of your glory. Amen.

**Comment by soulcharmer** [comment]
cafeteria guards.lip
"Jeden z nás by měl zanést dolů jídlo vězni." "Johansenovi? Není o nic lepší než oni, nebýt jeho vlezlého hrabání, ten artefakt by se sem nikdy nedostal." "Ano, to věci zkomplikovalo, ale vyvrbilo se to zajímavě. Myslíš, že v něm něco jě?" "Je mi to jedno, ale pokud ano, s boží pomocí to vrhneme zpátky do pekel!" "Bratr Krüger říká, že by to mohl být on, Adamův syn, bratrovrah." "Hmmm, pokud nadejde soudný den, nechť nám Pán dá sílu je prohlédnout." "Tak co? Doneseme Johansenovi nějaké to jídlo?" "Na, vezmi to moje, už nemám hlad."

caves_2.lip
"Jsou ty příběhy o něm pravdivé?" "O bratru Grünfeldovi?" "Ano." "Které příběhy jsi slyšel, mladý bratře?" "Je jich mnoho, například prý viděl vlastní matku, jak byla sežrána sletem čarodějnic. A nebo, že kdysi zabil mocného vampíra holýma rukama. Šeptá se, že on je sám svatý Leopold, který se vrátil, aby vedl svou armádu do poslední bitvy proti hordám z temnot." "Hehehe, ne všechny příběhy jsou pravdivé. Bratr Grünfeld je výtečný bojovník, jakým se můžeš stát i ty, pokud budeš mít víru v boha a disciplínu být v jeho armádě." "Taky se říká, že prý zabil jednoho z bratrů, který odmítl plnit rozkazy." "Hmmm, některé příbehy jsou pravdivé, mladý bratře."

to be continued...

**Comment by soulcharmer** [comment]
cavesjail.lip
"Šššš, slyšeli jste to?" "Asi jo, mám to jít zkontrolovat?" "Ne, jestli tam někdo je, ať přijde k nám, vede sem jen jedna cesta." "To je omyl, je tu další cesta, musíme být opatrní." "To ano, ale neznám člověka, který by dokázal zadržet dech na tak dlouho." "Není to člověk, koho bychom se měli obávat." "Už rozumím, bratře. Opravdu musíme být opatrní."

condotierre_backdoor.lip
"Sláva Bohu, vypadá jako silný muž." "Ty nevíš, kdo to je?" "Ne, měl bych?" "To je Grünfeld Bach." "To jméno mi něco říká." "Jak dlouho sloužíš u kondotiéra?" "Nepříliš dlouho, přísahu jsem složil minulou zimu." "Aha. Líbí se ti služba u bratrstva?" "Zajisté." "Pak se raději drž dále od bratra Grünfelda."


...

**Comment by soulcharmer** [comment]
condotierre_clearing.lip
"Buďte zdráv, veliteli." "Buďte zdráv, vojáku." "Něco k hlášení? Meč boží nám vzkázal, abychom byli pozorní! Domnívá se, že dnes se můžou objevit nezvaní hosté." "Zajisté, pane. Má stráž má za cíl ochránit bratrstvo! Prozatím je všude klid." "Dobrá, dobrá." "Zmínil také... jací hosté?" "Jediní, na kterých záleží, vojáku." "Ano, pane, jistě, pane." "Pokračujte!" 

monastery_guards.lip
"Bratr Grünfeld působí dnes večer obzvláště rozrušeně." "Ano, LaCroix je stále drzejší a bratru Grünfeldovi dochází trpělivost." "Aha, LaCroix. Jako vždy se bratr Grünfeld soustředí jen na svého odvěkého nepřítele. Doufejme, že jeho fanatizmus bude ve prospěch našeho řádu, a ne pouze jeho otevřených křivd." "Šššš, zbláznil ses? Bratr Grünfeld nebude tolerovat takovou neukázněnost, drž jazyk za zuby! Nevíš snad, na čí přímé pověření koná?" "To vím. Zdaleka mi nepřísluší zpochybňovat záměry Svatého Stolce." "Lépe si pamatuj, kde je tvé místo! Bratr Grünfeld je věrný bojovník. Bojuje se Satanovými nohsledy déle, než jsi ty naživu!" "Pomodlím se tedy k Pánu, aby mi umožnil bojovat v jeho armádě stejně dlouho!" "Amen."

...

**Comment by soulcharmer** [comment]
prayer.lip
Pane, modlím se k tobě, abys mi dal sílu k boji. Abych překonal Satanovy hordy i jeho zplozence. Abych mohl třímat ohnivý meč archandělův a ochránit se štítem víry. A abych dosáhl mnoha vítězství a utrpěl  nemnoha zranění. Abych rozšířil tvé království tady na Zemi. A pokud dnes zakusím smrt, nechť se mi předtím podaří uvrhnout celou armádu démonů zpět do ohnivého jezera, odkud vzešli. A poté nechť spočinu ve světle tvé blaženosti. Amen.


hotovo -)

**Comment by soulcharmer** [comment]
preklep v cafeteria guards.lip

Myslíš, že v něm něco jě ->
Myslíš, že v něm něco je

cavesjail.lip

Asi jo, mám to jít zkontrolovat? ->
Zřejmě ano, mám to jít zkontrolovat?


Diky
