### ISSUE TITLE
LIP chunk warehouse review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#72]
**gog_bloodlines_cz\cestina\sound\character\conversations\warehouse\coversations\
conversation1.lip**
"Hele, co se to tady do prdele děje? Marcus na každého ječí a vůbec." "Tys to neslyšel? Připlulo nové zboží - nějakej vážnej hardvér." "Jo, slyšel jsem. A co jako kurva, takový sračky nám sem chodí pořád. Co je dnes na tom jiního?" "Já ti nevím. Marcus je celej napjatej jak kráva. Možná něco slyšel." "Jako co?" "Jako já nevím, ale měj kurva oči na stopkách. Někdo by měl raději říct těm šaškům u vykládky, ať skončí s těmi kartami než přijde Marcus a začnou lítat kusy mozků, víš jako." "Jo, jo máš recht."
"Yo, what the fuck is going on here tonight? Marcus is on everyones face and shit." "Didn't you hear? A new shipment came in - some pretty serious hardware." "Yeah, I heard. But what the fuck, we get that kind of shit near all the time. What's so different about tonight?" "I don't know. Marcus is tense as a motherfucker. Maybe he heard something." "Like what?" "Like I don't know, but keep your fucking eyes open. And someone better tell those clowns in the freight house to quit playing cards before Marcus comes out and starts peeling fucking caps, you know what I'm saying." "Yeah, yeah I hear you."

**conversation2.lip**
"Tak už si vsadíš nebo co?" "Sakra, klídek Holmsi! Jedu." "Hele, Marcus by těd na každýho vylít, že jo? Co to kurva je! Něco dnes visí ve vzduchu, zná toho víc než my." "Já znám, že bys měl držet hubu, Holmsi, u Marcuse ti takový sračky neprojdou." "Jaký pak sračky? Jenom pokládám otázku." "To jsou ty sračky, co ti u něj neprojdou." "Koukejte - oba dva zavřete chrápy a mastěte ty karty. Kde v řiti je Junior?" "Dává bacha na schody uvnitř. Zdá se mi, že Marcus z něj má naděláno, ne?" "Sakra, Junior je snad chytřejší než vypadá."
"You're gonna bet or what?" "Shit, relax Holmes! I'm in." "Yo, Marcus will be getting all crazy on people now, right? What the fuck! Something going down tonight, he knows something we don't." "I know you best keep your voice down, Holmes, Marcus don't play that shit." "What shit? I'm just asking a question." "That's the shit he don't play." "Look - both of you shut up and play your fuckin' cards. Where the hell's Junior?" "He's inside watching the steps. Guess Marcus is kind of scared of him, you know?" "Shit, I guess Junior's smarter than he looks."

**conversation3.lip**
"Hele, viděls tam něco?" "Kde?" "Tamhle mezi těmi vlaky! Přisahám, že jsem tam viděl nějaký pohyb." "Nic tam není, jenom jsi podělanej, malej Johne." "Cože? Sakra, z ničeho nejsem podělanej! Podělám kohokoliv, kdo si přijde pro ránu z tohodle!" "Hele, nemávej tu s tím! Je to tady samá skurvená výbušnina. Snažíš se náš vyhodit do vzduchu nebo co'?" "Tak kdo je teď tady kurva podělanej?" "Sakra malej Johne! Ty jseš docela blbej, víš to?"
"Hey, you see something out there?" "Where?" "Out there in the trains! I swear I saw something moving." "Ain't nothing out here, you're just scared little John." "What? Shit, I ain't scared of nothing! Scared for whoever decides to come and get a piece of this!" "Hey, quit waving that thing around! Fucking explosives are all over the place in here. You trying to blow us up or somethin'?" "Now who's fucking scared?" "Damn little John! You are kind of stupid!"

**gog_bloodlines_cz\cestina\sound\character\conversations\warehouse\goons\
goonconvo.lip**
"Chybí něco z poslední várky?" "To nevím." "Zapoměl jsem se podívat, ale udělám to dnes." "Za co vás chlapy kurva platím? Tohle je velká věc, tak si k sakru koukejte dělat svou práci pořádne, jinak vás zahrabu v poušti a místo vás si najdu někoho, kdo to umí." "Už se to nestane, přisahám, že se na to kouknu dnes." "Mám hlad, objednejme si pizzu." "Objednejme si pizzu? Objednejme si pizzu, říkáš? Kam ji jako maj doručit, demente? Opuštěné sklady 13, tam kde každýho oddělaj na potkání?" "Můžu pro ní odskočit." "Ne, nikdo se odsud ani nehne, dokud máme tohle pod prdelí." "Ale nemaj tady ani automat ani nic'." "Co bys řekl na kulku do žaludku, to tě zasytí, co, ty nenažraný prase!" "To ne šéfe, už nemám hlad." "Celou noc jsme nic nejedli, šéfe, on to tak nemyslel." "Co jsem právě řekl?" "Hele, promiň šéfe, zapomeň na to." "Ne, chci abys zopakoval, co jsem řekl. Řekni to nahlas a zřetelně, jako chlap." "Ře-řekl jsi, že se odsud nikto ani nehne, dokud tady máme zboží." "Přisahám Bohu, ještě jedno odmlouvání, vyříznu vám jazyk a přiklincuju vám ho do tý vaší palice plné hoven. Teď musím na chvilku zavolat svý ženský, takže držte huby, oči venku a také pracky z kapes. Hele, zlato. Dělám přes noc. Ne, dnes ne. Hele, zavři klapačku a zmiř se s tím, je mi to fuk. Jo, t-to se opovaž, sáhneš mi na motorku a spřelámu si nohu na tvý prdeli, až dojdu domů. To mě zkoušíš? Je mi fuk, že děcko je v izbě, ani nevím jestli je má, a ty ženská na mě nezvyšuj hlas! Poslouchej mrcho, takto to prostě je. Zmiř se s tím! Opovaž se a pak... uvidíš! Konec debaty... konec debaty. Mrcho!"
"Anything missing from that last shipment?" "I don't know." "I forgot to look, but I'll do it tonight." "Fuck I pay you guys for? This is the big score, so do your goddamn job right, or I'll bury you in the desert and find someone who can." "Won't happen again, swear I'll check the shipment tonight." "I'm hungry, let's order a pizza." "Order a pizza, order a pizza? Where they gonna deliver it, numbnuts? Thirteen abandoned warehouse full of kill on sight hop-heads way?" "I could pick it up." "No, no one's going anywhere while we're sitting on this shit." "But there is no vending machine or nothin'." "How about I put a bullet in your gut, that fill you up, huh, you goddamn mongrel looking bastard!" "No boss, now I ain't hungry." "We ain't eaten all night's all, boss, he didn't mean anything by it." "What'd I just say?" "Hey, sorry boss, forget I said it." "No, I want you to tell me what I said. Say it clear and firm, like a man." "Y-you said no one's leaving while we got this stuff here." "I swear to god, one of you mouths off again, I'm going to pull out your tongue and nail it to your thick shit filled skulls. Now I gotta call my woman real quick, so keep your mouths shut, your eyes out and your hands away from your pockets. Yo, baby. No late night. Not tonight. Hey, shut up and deal with it, I don't care. Yeah, y-you do that, you touch my bike and I break my foot up in your ass when I get home. You testing me? I don't care if the kid's in the room, I don't even know she's mine, don't you raise your voice to me woman! Listen bitch, that's just the way it is. Deal with it! You do it, then... see what happens! End of conversation... end of conversation. Bitch!"

**gog_bloodlines_cz\cestina\sound\character\conversations\warehouse\truckbay\
fuckup.lip**
Pojeb!
Fuck up!

**truckbayconvo.lip**
"A až přijdou vyzvednout zboží, slíbili, že z nás udělaj, co sami jsou. Víte, co to znamená? To znamená, že nikdy nezemřeme, budeme super silní, umět létat a vůbec." "Budeme moct i létat?" "Tsss, proč ne, nelétaj snad oni ve filmech?" "Jo, asi jo." "A také ten parchant, co ti sundal bráchu, mohl bys vyjet na celou jeho tlupu a kulky ti neudělaj ani hovno. Rozmrdal bych jim jejich prdele, kdybych byl upír." "Jo, to jo, není to špatný." "Musel bys být blázen, abys nedělal s těmato, prý řídí celá města, dochází vám to? Pracovat pro chlápky, co vlastní celé město, můžeš dělat, co chceš, zabít kohokoli, kdo se ti postaví do cesty, lítat po celém placu." "A co ta krev, opravdu budeme muset pít krev?" "Tak to dělaj ve filmech." "To je poněkud hnusný, co když budu mít chuť na sendvič nebo něco." "Jako to mám vědět? Upírům to asi chutná." "Stejně je to hnusný, a co sex? Neříkej mi, že sa mám vzdát šukání, páč má neteř bude mít u mě v baráku kámošku a ta..." "Chlape, jak je to podle tebe poznat, né že by ti měl odpadnout nebo něco?" "Co?" "Stejně ho vůbec nepoužíváš." "Tak to je v hajzlu." "Mějte oči otevřené chlapi, když to poděláme, můžeme se rozloučit s létáním, sexem i s vlastníma prdelama. Tihle Sabbati říkali, že povraždí nás i naše rodiny, pokud to posereme." "Nedával jsem svůj souhl..." "Koukej, prostě sklapni a sejmi každýho, kdo tady nemá co pohledávat."
"And once they come pick up the stash, they promised they'd make us just like them. Know what that means? That means we never die, we get super strong, we can even fly and shit." "We can even fly?" "Shhh, why not, don't they fly in the movies?" "Yeah, I guess so." "And, like, that punk who dropped your brother, you could hit his whole crew and the bullets wouldn't do Jack shit. I'd tear their asses up if I was a vampire." "Yeah, yeah, it's not so bad." "You'd be stupid not to run with this crew, they said they run whole cities, you understand that? Working with a crew that owns a whole city, you could do anything you want, kill anyone who gets in your way, fly all over the place." "But what about blood, do we really gotta drink blood?" "That's how they do it up in the movies." "That's kinda nasty, what if I want a sandwich or somethin'." "How should I know? Probably tastes good to vampires." "It's still nasty, what about sex? Don't tell me I gotta giving up hitting it, cause my cousin got her friend staying at my house and she..." "Man, how do you expect me to know, not like it falls off, right?" "Wha?" "You never use it anyway." "That's messed up." "Just keep your eyes open, man, we screw this shit up, kiss flying, sex and your ass goodbye. These Sabbat guys, they said they'd kill us and our families if we blow it." "I never agreed to..." "Look, just shut up and shoot anybody who ain't supposed to be here."

**Comment by soulcharmer** [comment]
gog_bloodlines_cz\cestina\sound\character\conversations\warehouse\coversations
conversation1.lip
"Hej, co se to tu kurva dneska děje? Marcus na každýho řve a vůbec." "Tys to neslyšel? Dorazilo nový zboží - něco fakt vostrýho." "Jo, slyšel. Ale co má kurva bejt, drahej matroš tu máme každou chvíli. Co je na tom dnes jinýho?" "Co já vím... Marcus je nervní jako prase. Možná něco slyšel." "Co jako?" "Nemám páru, ale měj kurva oči na stopkách. A někdo by měl říct těm šaškům u vykládky, ať zabalí ty karty než na ně Marcus vletí a začnou lítat kusy mozků, víš jak." "Jo, máš recht."

conversation2.lip
"Tak sázíš nebo co?" "Sakra, klídek, Holmsi! Hraju." "Hej, Marcus teď bude pěkně vyšilovat, co? Do prdele! Dneska se něco semele, ví něco, co my nevíme." "Radši bys měl držet jazyk za zuby, Holmsi, Marcus se s tebou srát nebude." "Jak jako? Jen se ptám." "S tvou otázkou se taky srát nebude." "Hele - držte huby oba dva a mastěte ty karty. Kde je kurva Junior?" "Hlídá vevnitř schodiště. Marcus z něj má asi kapku naděláno." "Sakra, Junior je asi chytřejší než vypadá."

conversation3.lip
"Hej, vidíš tam něco?" "Kde?" "Támhle mezi vagónama! Přísahám, že jsem viděl, jak se tam něco pohlo." "Nic tam není, jen jseš podělanej jako malej Jarda." "Cože? Sakra, nejsem podělanej! Jen mám strach o kohokoliv, kdo se tu ukáže a schytá to tímhle!" "Hej, přestaň s tím mávat! Je to tady všude samá  výbušnina. Chceš nás kurva vyhodit do luftu nebo co?" "A kdo je kurva podělanej teď?" "Jako malej Jarda! Jseš fakt pitomec!"

gog_bloodlines_cz\cestina\sound\character\conversations\warehouse\goons
goonconvo.lip
"Chybí něco z poslední várky?" "Nevím." "Zapomněl jsem se podívat, ale udělám to dnes." "Za co vás kurva platím? Tohleto je jackpot, tak koukejte dělat svou práci pořádně, jinak vás pohřbím v poušti a najdu na to někoho schopnýho." "Už se to nestane, přísahám, že se na to dneska kouknu." "Mám hlad, objednejme pizzu." "Objednejme pizzu? Objednejme pizzu!? A kam nám ji jako doručí, ty demente? Opuštěnej sklad 13, plnej zfetovanejch střelců, co zabíjí na potkání?" "Můžu pro ni skočit." "Ne, nikdo se odsud nehne, dokud sedíme na tomhle nákladu." "Ale tady není ani automat na jídlo nebo něco." "A co bys řekl na kulku do žaludku, ta tě snad zasytí, ty nenažraný prase!" "To ne šéfe, už nemám hlad." "On to tak nemyslel, šéfe, nejedli jsme celou noc." "Co jsem vám právě řekl?" "Hele, promiň šéfe, zapomeň na to." "Ne, chci abys zopakoval, co jsem řekl. Chci to slyšet nahlas a zřetelně, jako od chlapa." "Ře-řekl jsi, že se odsud nikdo nehne, dokud tu máme tohle zboží." "Přísahám, že jestli mi bude ještě někdo odmlouvat, vytáhnu mu jazyk a zatluču mu ho do jeho tupý, hovnama naplněný škeble. Teď musím rychle zavolat svý ženský, tak držte huby, pořádně hlídejte a vytáhněte pracky z kapes. Hej, bejby. Dneska to nestihnu. Dnes ne. Hele, sklapni a smiř se s tím, je mi to fuk. Jo, t-to se opovaž, jak mi sáhneš na motorku, rozkopu ti zadek, až přijdu domů. To mě zkoušíš? Mně je fuk, jestli je děcko v pokoji, ani nevím jestli je moje... Nezvyšuj na mě hlas, ženská! Hele, ty mrcho, tak to prostě je. Smiř se s tím! Jestli to uděláš,... uvidíš, co bude! Konec debaty... konec debaty! Mrcho!"

truckbayconvo.lip
"Jak si přijdou pro to zboží, slíbili, že nás změní a budeme jako oni. Víš, co to znamená? Že nikdy nezemřeme, budeme super silní a budeme moct i lítat." "Budeme moct i lítat?" "A proč ne, ve filmech přece taky lítají, ne?" "Jo, asi jo." "A ten parchant, co ti sundal bráchu, mohl bys vyjet na celou jeho bandu a kulky by ti neudělaly ani hovno. Rozpáral bych je na kusy, kdybych byl vampír." "Jo, to jo, to nezní špatně." "Musel bys být blázen, kdyby ses k nim nepřidal, prý maj pod palcem celý města, chápeš to? Makat pro gang, co vlastní celý město, mohli bysme cokoliv, sejmout kohokoliv, kdo bude stát v cestě, lítat všude okolo..." "Ale co ta krev, opravdu budeme muset pít krev?" "Tak to dělaj ve filmech." "To je celkem hnusný, co když dostanu chuť na sendvič nebo něco?" "Jak to mám vědět? Vampírům to asi chutná." "Stejně je to hnus - a co sex? Neříkej mi, že se ho musím vzdát, páč má sestřenka bydlí u nás s kámoškou a..." "Kámo, co já o tom vím, počítám, že ti neupadne, ne?" "Co?" "Stejně ho nepoužíváš." "To je v hajzlu." "Hlavně sleduj, co se tu děje, jestli to posereme, přijdeme o lítání, sex, i vlastní kejhák. Tihle Sabbati říkali, že nás pobijou i s rodinama, jestli to zkurvíme." "Do toho jsem nikdy..." "Hele, sklapni a prostě sejmi každýho, kdo tady nemá co dělat."
