### ISSUE TITLE
LIP last chunk review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#73]
gog_bloodlines_cz\cestina\sound\character\dlg\downtown la\tutorial_security_guard
line11_col_e.lip
"Stůjte! Vy tam - zůstaňte, kde jste! Držte si odstup...."
"Stop! You - just stay back! Keep your distance...."

line21_col_e.lip
"A vy jste kdo k sakru? Máte něco společného s tímhle vším? Poněvač to nahlásím a bude se to tu jen tak hemžit jednotkami SWAT!"
"Now who the hell are you? You involved in all this? Cuz I'm gonna radio this in and SWAT will be all over this place!"

line31_col_e.lip
"Ne. Totiž, já,... - beztak jsem si zapoměl vzít vysílačku."
"No. Well, I, uh - I left my radio in the Caprice anyway."

line41_col_e.lip
"P-odívejte. Dostávám stovku na hodinu, jen aby sledoval jak prach sedá na díly aut. Nehodlám schytat kulku pro tuhle práci."
"L-look. I'm making eight-fifty an hour watching car parts collect dust. I'm not about to take a bullet for this job."

line51_col_e.lip
"Ď-díky? Podívejte pane, nevím, co chcete, ale nehodlám schytat kulku pro tuhle práci."
"Th-thank you? Look sir, I don't know what you want but I'm not about to take a bullet for this job."

line51_col_f.lip
"Ď-díky? Podívejte dámo, nevím, co chcete, ale nehodlám schytat kulku pro tuhle práci."
"Th-thank you? Look lady, I don't know what you want but I'm not about to take a bullet for this job."

line61_col_e.lip
"Jo OK, dobrá - tudy. Tohle vás zavede do skladu, možná se bude dát tamtudy proplížit."
"Yeah OK, alright - this way. This'll lead us up in the warehouse, we can maybe sneak out that way."

gog_bloodlines_cz\cestina\sound\character\dlg\downtown la\chunk3
line461_col_e.lip
"Zmizte odsud, varuji vás!"
"Get out, I'm warning you!"

line471_col_e.lip
"Je mi to líto, ale nahoru těd nikdo nesmí."
"Sorry, no one's allowed up right now."

line481_col_e.lip
"Nemůžu vás tam pustit."
"Can't let you up at the moment."

line491_col_e
"Nemám teď otevírat nikomu, je mi líto, šéfe."
"Not supposed to open the doors for anyone, sorry there, chief."

line491_col_f.lip
"Nemám teď otevírat nikomu, je mi líto, slečno.."
"Not supposed to open the doors for anyone, sorry there, missy."

line501_col_e.lip
"Obávám se, že teď vás tam nemůžu pustit."
"Fraid I can't let you in at the moment."

line511_col_e.lip
"Hmm? Aha, jděte nahoru."
"Hmm? Oh, go on up."

line521_col_e.lip
"Jděte nahoru..."
"Go on up. . ."

line531_col_e.lip
"Už vás očekává."
"He's expecting you."

line541_col_e.lip
"Hmm? Aha, to jste vy."
"Hmm? Oh, it's you."

gog_bloodlines_cz\cestina\sound\character\dlg\giovanni\bodyguard5
line1_col_e.lip
"Je mi líto, ale teď jsem nemůžete."
"Sorry, you can't come in here right now."

gog_bloodlines_cz\cestina\sound\character\dlg\santa monica\rosa
line221_col_e.lip
Je to tady nebezpečné. Dávej si pozor. Zítra se už nemusíš probudit.
It's dangerous around here. Be careful. You may not wake up tomorrow.

**Comment by soulcharmer** [comment]
opravy:


gog_bloodlines_cz\cestina\sound\character\dlg\downtown la\tutorial_security_guard

line21_col_e.lip
"A vy jste k sakru kdo? Máte v tomhle všem prsty? Ohlásím to a zásahovka tu bude raz dva!"

line31_col_e.lip
"Ne. Já vlastně... vlastně jsem nechal tu vysílačku v autě."

line41_col_e.lip
"Po-Poslyšte, dostávám dvě stovky na hodinu, abych koukal, jak tu na ty krámy padá prach. Nehodlám kvůli téhle práci schytat kulku."

line51_col_e.lip
"Dě-děkuju? Poslyšte pane, nevím, co chcete, ale nehodlám kvůli téhle práci schytat kulku."

line51_col_f.lip
"Dě-děkuju? Poslyšte dámo, nevím, co chcete, ale nehodlám kvůli téhle práci schytat kulku."

line61_col_e.lip
"Jo, dobrá - tudy. Vede to do skladu, možná bude možné se tamtudy proplížit."

gog_bloodlines_cz\cestina\sound\character\dlg\downtown la\chunk3

line471_col_e.lip
"Je mi to líto, ale nahoru teď nikdo nesmí."

line481_col_e.lip
"Nemůžu vás tam teď pustit."

line491_col_f.lip
"Nemám teď otevírat nikomu, je mi líto, slečno."

gog_bloodlines_cz\cestina\sound\character\dlg\giovanni\bodyguard5
line1_col_e.lip
"Je mi líto, ale teď sem nemůžete."

gog_bloodlines_cz\cestina\sound\character\dlg\santa monica\rosa
line221_col_e.lip
"Je tady nebezpečno. Dávej si pozor. Zítra se už nemusíš probudit."

**Comment by miracleflame** [comment]
Niektoré tie moje chyby boli na zaplakanie.

For the record, väčšinu .lip súborov pre tutorial_security_guard nebolo potrebné prekladať, stačí, že to je v dlg, tak som to premazal... 
A "gog_bloodlines_cz\cestina\sound\character\dlg\santa monica\rosa\line221_col_e.lip" nie je nijako zadefinovaný v dlg, takže sa nikdy nezobrazí. V repa som ho už musel niekedy odstrániť.

**Comment by soulcharmer** [comment]
Ja ty preklady vytahnul z toho dlg. Pokud to nebyly lipy, ktere mely zabranit probliknuti anglickeho textu, jak se tam vubec dostaly?

**Comment by miracleflame** [comment]
Ten tutorial_security_guard je súčasťou Unofficial Patch. Zahrnul som ho do prekladu ešte v čase, keď som úplne nerozumel mechanizmu. Pre správne fungovanie lipsyncu stačí, že sú v angličtine.

rosa\line221_col_e.lip je tiež súčasťou UP, ale zjavne bug, možno nejaký bordel z minulých verzií. Opýtam sa Wespa.
