### ISSUE TITLE
UP+ vdata chunk 1 review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#74]
**system\charcreatewizard.txt**
"Text" "You just started playing that new cool computer game but it is full of bugs. Do you..."
"Text" "Práve začínáš hrát báječnou novou videohru, jenom že je plná chyb. Co uděláš?"
"Text" "1. Get onto several forums and complain about the issues."
"Text" "1. Navštívím forum a sepíšu stěžnost."
"Text" "2. Email the developers themselves to get the game fixed."
"Text" "2. Pošlu e-mail samotným vývojářům, aby hru opravili."
"Text" "3. Decide to look into the code yourself to patch it up."
"Text" "3. Pokusím se povrtat ve zdrojáku a spravit si to vlastnoručne."
"Text" "You're heading downtown to meet with some Nosferatu in the alley behind that Chinese restaurant. He has some valuable information to sell. You're not expecting any trouble, but you can never be too careful. Do you..."
"Text" "Jsi na ceste do centra s úmyslem setkat se s nejakým Nosferatem v uličce za čínskou restaurací. Má na prodej vzácné informace. Nečekáš, že budou potíže, ale opatrnosti není nikdy dost. Co uděláš?"
"Text" "1. Take no weapons that might spook your contact, trusting in your supernatural strength to handle any problems?"
"Text" "1. Nebudu mít u sebe žádne zbraně, které by mohli můj kontakt rozladit, veřím svým nadpřirozeným schopnostem, že zvládnou jakýkoliv problém."
"Text" "2. Hide a blackjack in your coat to give you a little edge?"
"Text" "2. Ukryju si v kabátě obušek, abych měl nejakou poistku."
"Text" "3. Jam a Smith & Wesson into your waistband, just to be sure?"
"Text" "3. Zastrčím si za opasek Smith & Wesson, jen tak pro jistotu."
"Text" "You're in an all-night pawnshop, feeling the need for some protection, but very low on cash. You can only afford to purchase one item. Is it..."
"Text" "Jsi ve 24/7 zástavárně a potřebuješ nejakou ochranu, jenže máš málo peněz. Můžeš si dovolit koupit jenom jedinou věc. Co to bude?"
"Text" "1. A book entitled 'Kickboxing in Ten Easy Lessons'"
"Text" "1. Kniha s názvem 'Kickboxing v deseti jednoduchých lekcích'"
"Text" "2. A well-worn baseball bat."
"Text" "2. Stará dobrá baseballová pálka."
"Text" "3. A cheap Saturday night special."
"Text" "3. Levná nabitá osmatřicítka."

**system\clandoc000.txt**
"Blood_Healing" "1" // changed by wesp
"Léčení krví" "1" // changed by wesp

refer to #11 comments

**Comment by soulcharmer** [comment]
opravy - ta prvni veta je dobry inside joke :) 

"Text" "Právě začínáš hrát jednu báječnou novou videohru, jenže je v ní plno chyb. Co uděláš?"
"Text" "1. Navštívím diskuzní fóra a postěžuji si tam."
"Text" "2. Pošlu e-mail vývojářům, aby hru opravili."
"Text" "3. Podívám se do zdrojového kódu a napíšu si opravu."

"Text" "Jsi na cestě do centra potkat se s jedním Nosferatu v temné uličce. Má na prodej cenné informace. Nečekáš potíže, ale opatrnosti není nikdy dost. Co uděláš?"
"Text" "1. Nebudu si brát zbraň, která by ho mohla vyplašit. Veřím, že se svou nadpřirozenou sílou si poradím."
"Text" "2. Schovám si do kabátu obušek pro každý případ."
"Text" "3. Pro jistotu strčím za opasek pistoli."

"Text" "Jsi v nonstop zástavárně, sháníš něco na osobní ochranu, ale nemáš moc peněz. Budou stačit jen na jednu věc. Kterou zvolíš?"
"Text" "1. Kniha 'Kickbox v deseti lekcích'"
"Text" "2. Stará dobrá baseballovka."
"Text" "3. Laciný příruční revolver."
