### ISSUE TITLE
UP+ vdata histories review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#75]
**cestina\vdata\system\histories000.txt**

```
"Name" "Environmental Activist"
"Description" "You were a member of Greenpeace in life, always fighting to protect the environment, riding with the whales and climbing nuclear reactors. Knowing about cause and effect was important then.
Swap the priority order of your Abilities to Knowledges, Talents, Skills."
"ShortDescription" "Alternate starting traits priorities."
"Name" "Environmentálni Aktivista"
"Description" "Jako pro bývalého člena hnutí Greenpeace za života, bylo pro tebe samozřejmé bojovat za ochranu životního prostředí, vlavat s velrybami a šplhat po jadrových reaktorech. Znát příčinu a následek bylo tehdy důležité.
Změní důležitost dovedností tvé postavy na pořadí Znalosti, Vlohy, Schopnosti."
"ShortDescription" "Změněné startovní priority u dovedností postavy."

        "Name"              "Old Timer"
        "Description"           "You are the old fashioned type and don't care about all this new technology. Thus it costs you more to raise your Computer knowledge, but you start with a bonus in Scholarship."
        "ShortDescription"      "Advantage: +1 to Scholarship."
        "ShortPenaltyDescription"   "Penalty: Raising Computer costs more."
        "Name"              "Stará škola"
        "Description"           "Jsi staromódní typ a nezajímají tě všechny ty technologické výkvety doby. Proto tě také stojí více zvyšování znalosti Počítače, ale začínáš s bonusem ve Vzdělání."
        "ShortDescription"      "Výhody: +1 do Vzdělání."
        "ShortPenaltyDescription"   "Nevýhody: Zvyšování Počítače stojí víc."

        "Name"              "Juvenile Hall Disciplinarian"
        "Description"           "Already as a teen you loved to demonstrate your influence and power over others. 
        Swap the priority order of your Attributes to Physical, Mental, Social."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"              "Vedoucí mládežníckeho sboru"
        "Description"           "Už v mládí bylo vidět tvé sklony demonstrovat svůj vplyv a moc nad ostatními. 
        Změní důležitost atributů tvé postavy na pořadí Kondice, Rozum, Vystupování."
        "ShortDescription"      "Změněné startovní priority u atributů postavy."

        "Name"              "Video Game Publisher"
        "Description"           "You relish a sad pleasure in ruining promising game developing studios with impossible deadlines.
        Swap the priority order of your Attributes to Mental, Social, Physical."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"              "Vydavatel videoher"
        "Description"           "Máš smutnou zálibu zruinovat slibná vývojářská studia nestihnutelným datem uzávěrky.
        Změní důležitost atributů tvé postavy na pořadí Rozum, Vystupování, Kondice."
        "ShortDescription"      "Změněné startovní priority u atributů postavy."

        "Name"              "Rehab Counselor"
        "Description"           "You always had an open ear for other people's problems, even if you had to listen to some scumbags sitting in prison.
        Swap the priority order of your Abilities to Skills, Knowledges, Talents."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"              "Rehabilitační kouč"
        "Description"           "Vždy si umíš vyslechout problémy jiných lidí, a to dokonce i když musíš poslouchať lotry ve věznici.
        Změní důležitost dovedností tvé postavy na pořadí Schopnosti, Znalosti, Vlohy."
        "ShortDescription"      "Změněné startovní priority u dovedností postavy."

        "Name"              "Purveyor of Vice"
        "Description"           "Smoking, drinking, drugs, you did it all while you were still alive. Now in death only blood is left to turn you on.
        Swap the priority order of your Abilities to Skills, Knowledges, Talents."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"              "Zásobovatel neřesti"
        "Description"           "Kouření, chlastání, drogy, to všechno máš za sebou ještě za živa. Nyní po smrti tě dokáže nakopnout už jenom krev.
        Změní důležitost dovedností tvé postavy na pořadí Schopnosti, Znalosti, Vlohy."
        "ShortDescription"      "Změněné startovní priority u dovedností postavy."

        "Name"              "Baglady"
        "Description"           "Your life was a big mess which left you stranded on the streets with nothing but cheap booze. And now you look even worse!
        Swap the priority order of your Abilities to Talents, Knowledges, Skills."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"              "Somračka"
        "Description"           "Tvůj život byl jeden veliký omyl, který tě nakonec vykopnul na ulici s lahví levného chlastu. A teď vypadáš dokonce ještě hůř!
        Změní důležitost dovedností tvé postavy na pořadí Vlohy, Znalosti, Schopnosti."
        "ShortDescription"      "Změněné startovní priority u dovedností postavy."

        "Name"              "Dive Bar Bouncer"
        "Description"           "Nobody could pass you when you stood in a doorway and you had a lot of fun throwing people out. Now it will be even easier to hurt people.
        Swap the priority order of your Abilities to Talents, Knowledges, Skills."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"              "Barový vyhazovač"
        "Description"           "Když jsi se postavil do dveří, nikdo neprošel a užil jsi si hodně zábavy vyhazováním lidí. Nyní bude ubližování ještě snažší.
        Změní důležitost dovedností tvé postavy na pořadí Vlohy, Znalosti, Schopnosti."
        "ShortDescription"      "Změněné startovní priority u dovedností postavy."

        "Name"      "Megalomaniac"
        "Description"   "You have a big ego. Because of your confidence in yourself and your abilities, people either really hate you, or are drawn to you. You start with an extra point of Charisma but can never raise Subterfuge above four."
        "ShortDescription"  "Advantage: +1 to Charisma."
        "ShortPenaltyDescription"   "Penalty: Subterfuge maximum of 4."
        "Name"      "Egomaniak"
        "Description"   "Máš velké ego. Kvůli tvému sebevědomí a schopnostem tě lidi buď nenávidí nebo je přitahuješ. Začínáš s bodem navíc v Charizmě, ale Lstivost nemůžeš navyšit nad čtyři."
        "ShortDescription"  "Výhody: +1 do Charizmy."
        "ShortPenaltyDescription"   "Nevýhody: Lstivost nejvíc 4."

        "Name"      "All-Star Athlete"
        "Description"   "You were an excellent athlete who excelled at all physical activities. However, you're not naturally the sharpest tool in the shed. Compound that with the fact that you spent most of your time and energy exercising, you really don't know much about anything else. You gain a bonus to Strength but can never raise your Intelligence higher than four."
        "ShortDescription"      "Advantage: +1 to Strength."
        "ShortPenaltyDescription"   "Penalty: Intelligence maximum of 4."
        "Name"      "Hvězdný atlét"
        "Description"   "Jako bývalá hvězda atletiky vynikáš ve všech fyzických oblastech. Avšak přirozeně nejsi zrovna z nejbystřejších jedinců. Dej si to dohromady s tím, že většina tvého času a energie se stratila v cvičení, opravdu nemáš páru téměř o ničem jiném. Získáváš bonus do Síly, ale nemůžeš navýšit Inteligenci nad štyři."
        "ShortDescription"      "Výhoda: +1 do Síly."
        "ShortPenaltyDescription"   "Nevýhoda: Inteligence nejvíc 4."

        "Name"      "Close to the Beast"
        "Description"   "After you were Embraced, you were naturally more in tune with the Beast within and that affinity is now physically apparent. You start with one level more in Protean, but others, especially kine, will find your appearance distasteful."
        "ShortDescription"  "Advantage: +1 to Protean."
        "ShortPenaltyDescription"   "Penalty: Appearance maximum of 3."
        "Name"      "Skoro bestie"
        "Description"   "Po tvém Uchvácení došlo k přirozenénu zladění s tvou bestii uvnitř a tento vztah je zjevný i na pohled. Začínáš s jedním bodem navíc v Zvířeckosti, avšak ostatní, obzvlášť upíři, tě budou vnímat s odporem."
        "ShortDescription"  "Výhody: +1 do Zvířeckosti."
        "ShortPenaltyDescription"   "Nevýhody: Vzhled nejvíc 3."

        "Name"      "Subtly Insane"
        "Description"   "Your insanity does not hinder your ability to interact with others too greatly. At first glance, most wouldn't even second-guess your mental stability. Your unique form of dementia flares up more easily when provoked in combat but you can't ever raise your Dodge above three."
        "ShortDescription"  "Advantage: +1 to Dementation."
        "ShortPenaltyDescription"   "Penalty: Dodge maximum of 3."
        "Name"      "Nepatrná pomatenost"
        "Description"   "Tvá pomatenost nemá zásadný vplyv na schopnost bavit se s ostatními. Na první pohled by většina ani nespochybňovala tvůj mentální stav. Jedinečná forma demence vystoupí do popředí, když je vyprovokována bojem, ale nemůžeš navýšit Uhýbání nad tři body."
        "ShortDescription"  "Výhody: +1 do Demence."
        "ShortPenaltyDescription"   "Nevýhody: Uhýbání nejvíc 3."

        "Name"      "Well Educated"
        "Description"   "You were very privileged and gained excellent education all-around. You have a bonus in a variety of abilities but you're mild tempered and weak-willed. You can't ever raise Dominate and Intimidation above three."
        "ShortDescription"      "Advantage: Bonus in all Knowledge traits."
        "ShortPenaltyDescription"   "Penalty: Dominate and Intimidation maximum of 3."
        "Name"      "Dobré vzdělání"
        "Description"   "Tvá privilegovanost ti zaručila excelentní vzdělání a rozhled. Získáváš bonus do různych schopností, ale jsi mírné povahy a bez průbojnosti. Nemůžeš navýšit Dominaci ani Donucování nad tři body."
        "ShortDescription"      "Výhody: Bonus do všech oblastí Znalosti."
        "ShortPenaltyDescription"   "Nevýhody: Dominace a Donucování nejvíc 3."

        "Name"      "Affinity for Magic"
        "Description"   "You always liked magical illusions, and even performed some tricks yourself as a kid. Now you are amazed that magic is real and thus can easier advance in Thaumaturgy. On the other hand you have difficulties learning all other things."
        "ShortDescription"      "Advantage: Raising Thaumaturgy costs less."
        "ShortPenaltyDescription"   "Penalty: Less experience gained."
        "Name"      "Sklony k magii"
        "Description"   "Vždy tě oslovovali magické iluze a již jako dítěti se ti dařili různe kousky a triky. Teď je nadšení umocněno poznáním, že magie je skutečná a proto se ti lépe napředuje v Divotvorství. Na druhé straně se ti hůř poznávaj ostatní věci."
        "ShortDescription"      "Výhody: Navyšování Divotvorství stojí méně bodů."
        "ShortPenaltyDescription"   "Nevýhody: Získáváš méně skušenosti."

        "Name"      "Presentable"
        "Description"   "The Nosferatu blood from your sire was rather weak and the blood curse did not take too strong a hold on you. You're only deformed where the moon doesn't shine, but it is one-and-a-half times more difficult for you to learn the Obfuscate Discipline of your clan."
        "ShortDescription"      "Advantage: +1 to Charisma."
        "ShortPenaltyDescription"   "Penalty: Raising Obfuscate costs more."
        "Name"      "Reprezentant"
        "Description"   "Krev Nosferatu tvého stvořitele byla poněkud řídká a prokletí tě nezasáhlo tak bolestivě. Tvé znetvoření je patrné jen tu a tam, avšak je pro tebe o polovinu náročnější ovládnout rodovou disciplínu Mizení."
        "ShortDescription"      "Výhody: +1 do Charizmy."
        "ShortPenaltyDescription"   "Nevýhody: Navyšování Mizení stojí víc bodů."

        "Name"      "Starving Artist"
        "Description"   "You were a starving artist. You lived with the clothes on your back and because of your poor background, you do not have any compunction against wearing ugly clothes. You do have a special eye for small details though."
        "ShortDescription"  "Advantage: +1 to Perception."
        "ShortPenaltyDescription"   "Penalty: Appearance maximum of 4."
        "Name"      "Hladový umělec"
        "Description"   "Tvou minulostí byla dráha hladovějícího umělce. Obnošené hadry a návyky z chudoby mají za následek, že nemáš žádne zábrany nosit ošklivé věci. Ovšem máš opravdu dobré oko na detaily."
        "ShortDescription"  "Výhody: +1 do Vnímání."
        "ShortPenaltyDescription"   "Nevýhody: Vzhled nejvíc 4."

        "Name"      "Black-Hearted"
        "Description"   "You were a black-hearted, violence loving, badass when you were alive, and you're still an evil maniac in unlife. You have a Humanity of five but start with a bonus to your Firearms skill."
        "ShortDescription"      "Advantage: +1 to Firearms."
        "ShortPenaltyDescription"   "Penalty: Humanity -2."
        "Name"      "Černé srdce"
        "Description"   "Za života v tobě bilo černé srdce prahnoucí po násilí a tvrdosti a také v neživotě je z tebe zlověstný maniak. V Lidskosti máš jen pět bodů, no získáváš bonus do Zbraní na dálku."
        "ShortDescription"      "Výhody: +1 do Zbraní na dálku."
        "ShortPenaltyDescription"   "Nevýhody: Lidskost -2."

        "Name"      "Occult Nut"
        "Description"   "Who would ever have thought that any of it could be real? You loved dark fantasies and considered yourself Occult-savvy. Now that you're among the Kindred, you find that you actually know some of this stuff and are really excited about learning more about your new state of unlife. You gain a bonus to scholarship and earning experience but others find you disdainful and their reaction towards you is lowered."
        "ShortDescription"      "Advantage: +1 to Scholarship, more experience gain."
        "ShortPenaltyDescription"   "Penalty: Charisma maximum of 3."
        "Name"      "Magor okultista"
        "Description"   "Kdo by si to kdy pomyslel, že to bude pravda? Miluješ temné fantazie a považuješ se za zběhlého okultistu. Teď, když patříš k upírům, zjišťuješ, že mnohé věci jsou ti známe a s nadšením se učíš ještě víc o neživote. Dostáváš bonus do Vzdělání a získané skušenosti, jenže ostatní na tebe nahlíží s opovržením a jejich reakce jsou méně přívětivé."
        "ShortDescription"      "Výhody: +1 do Vzdělání, víc bodů zkušenosti."
        "ShortPenaltyDescription"   "Nevýhody: Charizma nejvíc 3."

        "Name"      "Academic"
        "Description"   "You were the Academic type, as was your Brujah sire, living up to the old Brujah image of the poet-warrior. Your attributes are prioritized differently, with Mental being the most important, then Social, followed by Physical."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"      "Akademik"
        "Description"   "Jsi akademický typ, stejně jako tvůj stvořitel Brujah a žiješ podle starého Brujahského imidžu jako básnický bojovník. Priority u dovedností tvé postavy jsou jiné, přičemž Rozum je nejdůležitější, pak vystupování a nakonec Kondice."
        "ShortDescription"      "Změněné startovní priority u dovedností postavy."

        "Name"      "Generalissimo"
        "Description"   "Discipline and order, tactics and warfare: these are the reasons why you joined the army. Not only did you fit in perfectly, you excelled in the military. Swap the priority order for your Attributes to Physical, Mental, and Social."
        "ShortDescription"      "Alternate starting traits priorities."
        "Name"      "Generál"
        "Description"   "Disciplína a pořádek, taktika a válčení: toto jsou důvody, proč jsi členem armády. Nejen, že ti to perfektně sedí, v armáde přímo exceluješ. Prohodí se priority u dovedností tvé postavy na Kondice, Rozum a Vystupování."
        "ShortDescription"      "Změněné startovní priority u dovedností postavy."

        "Name"      "Ex-SWAT"
        "Description"   "While in the Police force, you've developed quite a skill with firearms. You start with a bonus to the firearms skill. However, you quit the forces after receiving a crippling injury while in the line of duty. Your Dexterity cannot be raised above one."
        "ShortDescription"      "Advantage: +2 to Firearms."
        "ShortPenaltyDescription"   "Penalty: Dexterity maximum of 1."
        "Name"      "Ex-SWAT"
        "Description"   "Za svého působení v policejním zboru se ti rozvinuli střelecké schopnosti. Začínáš s bonusem ve Střelných zbraních. Naneštěstí máš doživotní zranení nohy ako důsledek přestřelky ve výkoně služby. Tvá Obratnost nemůže být navýšena nad jeden bod."
        "ShortDescription"      "Výhody: +2 do Střelných zbraní."
        "ShortPenaltyDescription"   "Nevýhody: Obratnost nejvíc 1."

        "Name"      "Peeping Tom"
        "Description"   "It's not your fault you were born lacking in the appearance department. Since nobody likes you, your unfulfilled and repressed sexual desires have turned you into quite the little pervert. Now in your unlife, you find that you digest the vitae from member of the opposite gender more efficiently."
        "ShortDescription"      "Advantage: Extra blood from women."
        "ShortPenaltyDescription"   "Penalty: Charisma maximum of 3."
        "Name"      "Šmírák"
        "Description"   "Nemůžeš za to, že jsi se narodil jako nepřítažlivý ošklivák. Nikomu jsi se nelíbil a tvé nenaplněné a potlačované sexuální potřeby z tebe udělali malého perverzáka. Nyní v neživotě zjišťuješ, že vysávání životní síly z opačného pohlaví ti jde nadmíru dobře."
        "ShortDescription"      "Výhody: Více krve ze žen."
        "ShortPenaltyDescription"   "Nevýhody: Charizma nejvíc 3."

        "Name"      "Pot Head"
        "Description"   "Scientists say that smoking pot can make you more stupid. That may explain your terrible memory as you often forget names and other details. However, you have a very relaxed attitude towards life, or the unlife. You gain a bonus to frenzy checks."
        "ShortDescription"      "Advantage: Less likely to frenzy."
        "ShortPenaltyDescription"   "Penalty: Intelligence maximum of 3."
        "Name"      "Hulič"
        "Description"   "Podle výskumníků kouření trávy spůsobuje hloupnutí. To by vysvětlovalo tvou příšernou paměť, protože jsi neumíš zapamatovat jména a jiné maličkosti. Avšak život umíš brát s obrovským nadhledem a pohodou, nebo také i neživot. Získáváš bonus do odolnosti vůči Běsu."
        "ShortDescription"      "Výhody: Menší pravděpodobnost běsu."
        "ShortPenaltyDescription"   "Nevýhody: Inteligence nejvíc 3."

        "Name"      "Deaf"
        "Description"   "You were born practically deaf. Not only did you overcome your disability, you enjoy helping others cope and get ahead in life. You start with a Humanity of 8. Also, while you do not wish to be presumptuous, but you have a vague feeling that Lady Luck smiles upon you."
        "ShortDescription"      "Advantage: +1 to Humanity."
        "ShortPenaltyDescription"   "Penalty: Perception maximum of 3."
        "Name"      "Hluchoněmec"
        "Description"   "Od narození neslyšíš ani prd. Nejen, že se umíš se svým omezením vyspořádat, také tě baví pomáhat jiným s jejich nesnázemy. Začínáš s Lidskostí 8. Také si nechceš dělat iluze, ale máš pocit, že štěstěna stojí na tvé straně."
        "ShortDescription"      "Výhody: +1 do Lidskosti."
        "ShortPenaltyDescription"   "Nevýhody: Vnímání nejvíc 3."
```

**Comment by soulcharmer** [comment]
"Name" "Environmental Activist"
"Description" "You were a member of Greenpeace in life, always fighting to protect the environment, riding with the whales and climbing nuclear reactors. Knowing about cause and effect was important then.
Swap the priority order of your Abilities to Knowledges, Talents, Skills."
"ShortDescription" "Alternate starting traits priorities."
"Name" "Ekologický Aktivista"
"Description" "Tvá minulost je spjata s hnutím Greenpeace a byla spojena s ochranou životního prostředí, ježděním s velrybami a šplháním po atomových elektrárnách. Tehdy pro tebe bylo důležité rozlišovat příčiny a následky.
Změní důležitost dovedností tvé postavy na pořadí Znalosti, Vlohy, Schopnosti."
"ShortDescription" "Změněné startovní priority u dovedností postavy."

**Comment by soulcharmer** [comment]
"Name"              "Old Timer"

        "Name"              "Stará škola"
        "Description"           "Jsi staromódní typ a moderní technologie tě moc nezajímají. Proto je pro tebe obtížnější zdokonalovat se v práci s počítači, ale začínáš s bonusem ve Vzdělání."
        "ShortDescription"      "Výhody: +1 do Vzdělání."
        "ShortPenaltyDescription"   "Nevýhody: Zvyšování Počítače stojí víc."

**Comment by soulcharmer** [comment]
"Name"              "Juvenile Hall Disciplinarian"

"Name"              "Tyran z pasťáku"
"Description"           "Už jako teenagerovi se ti líbilo dávat najevo svůj vliv a moc nad ostatními.
Změní důležitost atributů tvé postavy na pořadí Kondice, Rozum, Vystupování."
"ShortDescription"      "Změněné startovní priority u atributů postavy."

**Comment by soulcharmer** [comment]
"Name"              "Vydavatel videoher"
"Description"           "Máš krutou zálibu v likvidování slibných vývojářských studia šibeničními termíny.
Změní důležitost atributů tvé postavy na pořadí Rozum, Vystupování, Kondice."
**"ShortDescription"      "Změněné výchozí priority u atributů postavy."**   <-- prosim zmen vsude

"Name"              "Rehabilitační instruktor"
"Description"           "Vždy ti šlo naslouchání problémům jiných lidí, i když to někdy byly pěkní hajzlové zavření v kriminálu.
Změní důležitost dovedností tvé postavy na pořadí Schopnosti, Znalosti, Vlohy."

**Comment by soulcharmer** [comment]
"Name"              "Purveyor of Vice"

"Name"              "Hříšník"
"Description"           "Cigarety, chlast, drogy - to všechno už máš vyzkoušeno z předchozího života. Teď po smrti už tě nezajímá nic jiného než krev.
Změní důležitost dovedností tvé postavy na pořadí Schopnosti, Znalosti, Vlohy."
"ShortDescription"      "Změněné startovní priority u dovedností postavy."


"Name"              "Baglady"

"Name"              "Somračka"
"Description"           "Tvůj život byl jeden velký průšvih, který tě zanechal na ulici jen s lahví laciného chlastu. A teď vypadáš dokonce ještě hůř!
Změní důležitost dovedností tvé postavy na pořadí Vlohy, Znalosti, Schopnosti."


"Name"              "Dive Bar Bouncer"

"Name"              "Barový vyhazovač"
"Description"           "Když ses postavil do dveří, nikdo se přes tebe nedostal. Byla pro tebe sranda vyhazovat lidi na ulici a teď to půjde ještě snadněji.
Změní důležitost dovedností tvé postavy na pořadí Vlohy, Znalosti, Schopnosti."

**Comment by soulcharmer** [comment]
"Name"      "Megalomaniac"

"Name"      "Megalomaniak"
"Description"   "Máš velké ego. Díky své pevné důvěře v sebe a své schopnosti tě lidé buď výhradně nenávidí nebo uznávají. Začínáš s bodem navíc v Charizmě, ale Lstivost nemůžeš navýšit nad čtyři body."
"ShortDescription"  "Výhody: +1 do Charizmy."
**"ShortPenaltyDescription"   "Postih: Lstivost nejvýše na úrovni 4."**    <-- Vymen prosim "nevyhody" za "postih" vsude (pocitam, ze nikde neni vic nez jeden)

"Name"      "All-Star Athlete"

"Name"      "Hvězdný atlet"
"Description"   "Jako bývalá hvězda atletiky vynikáš ve všech fyzických aktivitách. Na druhou stranu ale nepatříš k těm nejbystřejším mezi všemi. Když se to dá dohromady s faktem, že trénink ti zabral většinu času, opravdu se nevyznáš skoro v ničem jiném. Získáváš bonus do Síly, ale nemůžeš navýšit Inteligenci nad čtyři body."
"ShortDescription"      "Výhoda: +1 do Síly."
"ShortPenaltyDescription"   "Postih: Inteligence nejvýše na úrovni 4."

"Name"      "Close to the Beast"

"Name"      "Krůček od bestie"
"Description"   "Po uchvácení se bestie v tvém nitru přirozeně sladila s tvým tělem a tato afinita je patrná na první pohled. Začínáš s jedním bodem navíc ve Zvířeckosti, avšak ostatní, zvláště smrtelníci, tě budou vnímat s odporem."
"ShortDescription"  "Výhody: +1 do Zvířeckosti."
"ShortPenaltyDescription"   "Postih: Vzhled nejvýše na úrovni 3."

**Comment by soulcharmer** [comment]
"Name"      "Subtly Insane"

"Name"      "Poněkud šílenec"
"Description"   "Tvé šílenství nemá zásadní vliv na schopnost komunikovat s ostatními. Na první pohled by většina ani nepochybovala o tvé mentální stabilitě. Tvá jedinečná forma demence se projevuje při vyprovokování v boji, ovšem Uhýbání nemůžeš zvýšit nad tři body."
"ShortDescription"  "Výhody: +1 do Dementace."
"ShortPenaltyDescription"   "Postih: Uhýbání nejvvýše na úrovni 3."

"Name"      "Well Educated"

"Name"      "Vzdělanec"
"Description"   "Dostalo se ti privilegia vynikajícího vzdělání. Získáváš bonus do různych schopností, ale také máš mírnou povahu a slabou vůli. Nemůžeš zvýšit Dominanci ani Donucování nad tři body."
"ShortDescription"      "Výhody: Bonus do všech Znalostí."
"ShortPenaltyDescription"   "Postihy: Dominance a Donucování nejvýše na úrovni 3."

"Name"      "Affinity for Magic"

"Name"      "Sklony k magii"
"Description"   "Vždy tě fascinovaly čarodějnické iluze a už jako dítěti se ti dařily různé triky. Teď je tvé nadšení umocněno poznáním, že magie je skutečná a proto snadněji zlepšuješ Divotvorství. Na druhou stranu je pro tebe těžší poznávat jiné věci."
"ShortDescription"      "Výhody: zvyšování Divotvorství stojí méně."
"ShortPenaltyDescription"   "Postih: Získáváš méně bodů zkušeností."

**Comment by soulcharmer** [comment]
"Name"      "Presentable"

"Name"      "Příjemný zjev"
"Description"   "Krev tvého nosferatského stvořitele byla poněkud slabá a prokletí tě nezasáhlo příliš tvrdě. Tvé znetvoření je patrné jen na místech, kam slunce nesvítí, ale je pro tebe o polovinu náročnější zdokonalovat klanovou disciplínu Mizení."
"ShortDescription"      "Výhody: +1 do Charizmy."
"ShortPenaltyDescription"   "Postih: Zlepšování Mizení stojí víc bodů."

"Name"      "Starving Artist"

"Name"      "Hladový umělec"
"Description"   "Tvou minulostí byla kariéra hladového umělce. Tvůj chudý původ a obnošené oblečení mají za následek, že nemáš žádné zábrany nosit ošklivé věci. Na druhou stranu máš opravdu dobré oko na detaily."
"ShortDescription"  "Výhody: +1 do Vnímání."
"ShortPenaltyDescription"   "Postih: Vzhled nejvýše na úrovni 4."

"Name"      "Black-Hearted"

"Name"      "Zloduch"
"Description"   "Za života tě bavilo vyžívat se násilí a po smrti ti to zůstalo. Začínáš jen s pěti body v Lidskosti, ale získáváš bonus do Zbraní na dálku."
"ShortDescription"      "Výhody: +1 do Zbraní na dálku."
"ShortPenaltyDescription"   "Postih: -2 do Lidskosti."

**Comment by soulcharmer** [comment]
"Name"      "Occult Nut"

"Name"      "Magor do okultizmu"
"Description"   "Kdo by si kdy pomyslel, že něco z toho může být skutečné? Dříve tě bavily temné fantazie a považuješ se za znalce okultizmu. Teď když jsi mezi našinci, zjišťuješ, že leccos z toho opravdu ovládáš a nemůžeš se dočkat, až se o svém novém neživotě dozvíš víc. Získáváš bonus do Vzdělání a do získávání bodů zkušeností, ale ostatní tebou pohrdají a vesměs s tebou nechtějí nic mít."
"ShortDescription"      "Výhody: +1 do Vzdělání, více bodů zkušeností."
"ShortPenaltyDescription"   "Postih: Charizma nejvýše na úrovni 3."

"Name"      "Academic"

"Name"      "Akademik"
"Description"   "Jsi akademický typ, stejně jako tvůj brujahský stvořitel, který žije podle prastaré tradice klanu jako bojovník a současně básník. Priority dovedností tvé postavy jsou změněny na pořadí Rozum, Vystupování a Kondice."
"ShortDescription"      "Změněné výchozí priority u dovedností postavy."

"Name"      "Generalissimo"

"Name"      "Velitel"
"Description"   "Disciplína, pořádek, taktika a vedení války; pro tyto důvody se ti zalíbila armáda. Nejenže ti skvěle sedla, ale armáda ti dala příležitost opravdu vyniknout. Priority dovedností tvé postavy jsou změněny na pořadí Kondice, Rozum a Vystupování."
"ShortDescription"      "Změněné výchozí priority u dovedností postavy."

**Comment by soulcharmer** [comment]
"Name"      "Ex-SWAT"

"Name"      "Fízl od zásahovky"
"Description"   "Za svého působení v policejním sboru ti šla velmi dobře střelba. Začínáš s bonusem ve Střelných zbraních. Tvá kariéra u policie ale naneštěstí skončila po přestřelce ve službě, ze které máš trvalé následky. Svou Obratnost nemůžeš navýšit nad jeden bod."
"ShortDescription"      "Výhody: +2 do Střelných zbraní."
"ShortPenaltyDescription"   "Postih: Obratnost nejvýše na úrovni 1."

"Name"      "Peeping Tom"

"Name"      "Šmírák"
"Description"   "Nemůžeš za to, že tě příroda neobdařila dobrým vzhledem. Protože tě nikdo nechtěl, tvé nenaplněné a potlačované sexuální touhy z tebe udělaly docela velkého úchyláka. Teď po smrti zjišťuješ, že vstřebáváš životní sílu od osob opačného pohlaví s vyšším účinkem."
"ShortDescription"      "Výhody: Více krve z žen."
"ShortPenaltyDescription"   "Postih: Charizma nejvýše na úrovni 3."

"Name"      "Pot Head"

"Name"      "Hulič"
"Description"   "Podle vědců může kouření trávy způsobovat hloupnutí. To by vysvětlovalo tvou příšernou paměť, kdy často zapomínáš jména a podobné detaily. Na druhou stranu bereš život (a nakonec i neživot) s velkým nadhledem. Získáváš bonus do odolnosti vůči běsu."
"ShortDescription"      "Výhody: Menší pravděpodobnost propadnutí běsu."
"ShortPenaltyDescription"   "Postih: Inteligence nejvýše na úrovni 3."

"Name"      "Deaf"

"Name"      "Nedoslýchavý"
"Description"   "Od narození máš velmi postižený sluch. Ale nejenže se ti podařilo se se svým hendikepem vyrovnat, také tě baví pomáhat ostatním s jejich problémy. Tvá výchozí Lidskost je 8. A ačkoliv nechceš působit domýšlivě, máš také vágní dojem, že i Štěstěna stojí na tvé straně."
"ShortDescription"      "Výhody: +1 do Lidskosti."
"ShortPenaltyDescription"   "Postih: Vnímání nejvýše na úrovni 3."

**Comment by soulcharmer** [comment]
@miracleflame - konecne hotovo, prosim o finalni kontrolu a zapracovani

**Comment by miracleflame** [comment]
good job, to bola morda, čo?

ešte som dal k niečomu poznámku...
"Name" "Subtly Insane"

"Name" "Poněkud šílenec" **<- významovo sa sem najviac hodí "nepatrný", lebo to neni na prvý pohľad patré.. čo povieš?**
"Description" "Tvé šílenství nemá zásadní vliv na schopnost komunikovat s ostatními. Na první pohled by většina ani nepochybovala o tvé mentální stabilitě. Tvá jedinečná forma demence se projevuje při vyprovokování v boji, ovšem Uhýbání nemůžeš zvýšit nad tři body."

**Comment by soulcharmer** [comment]
Ten realny efekt v boji bych nenazval jako "nepatrny", ale muzeme zkusit neco jineho, co bude znit lip a prihodneji:

"Kapku magor"

muze byt :)?

**Comment by miracleflame** [comment]
To môžeš povedať aj o origináli, že by si reálny efekt nenazval zrovna subtle, ale tak to niekto nazval no. Veď je to na tebe, ja tam dám, čo rozhodneš.

**Comment by soulcharmer** [comment]
Koukam, ze magora uz mezi profily mame, tak dejme

"Kapku mešuge"

diik
