### ISSUE TITLE
UP+ vdata chunk 3 review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#76]
**UP_Plus_CZ\vdata\system\loadingtips.txt**
Here, you will be unable to attack or use your vampiric Disciplines, with the exception of using Bloodbuff while lockpicking.
Nebudeš v něm moci ani útočit ani používat vampírské disciplíny s výjimkou Hlasu krve za účelem páčení.
"Text" "One of the vampire's greatest feats is the ability to reconstitute their broken body. By focusing the blood they can close buckshot wounds and regrow lost appendages.
"Text" "Jedna z nejmocnejších vampiristických schopností je regenerace svého poškozeného těla. Soustředením krve dokáží uzavřít díry po kulkách a obnovit ztracené tkanivo.
"Text" "The vampire may push its body to the peak of human prowess for a short time, for a price in blood. Bloodbuff represens the vampire's innate ability to enhance the physical attributes.
"Text" "Vampíři můžou na krátkou dobu přivést své tělo na hranici fyzických možností, ovšem za cenu krve. Hlas krve představuje přirozenou vampírskou schopnost vylepšiť atributy Kondice.
One of these are the flesh eating Nagaraja.
Patří k nim i masožravý rod Nagaraja.
Čím vyšši je tvá bojová schopnost, tím větší poškození zbraň způsobí.

**UP_Plus_CZ\vdata\system\stats.txt**
```
"HelpTextH1" "Level 1: Veil of Madness" // changed by EntenSchreck
"HelpTextH3" "Level 3: Voice of Bedlam" // changed by wesp
"HelpTextH4" "Level 4: Vision of Death" // changed by wesp
"HelpTextH5" "Level 5: Berserk Insanity" // changed by wesp
"HelpTextL1" "Activation Cost: 1 blood. The victim's emotions intensify until it becomes temporarily incapacitated by either hysterical laughter or compulsive crying for about 15 seconds. Taking any action against the victim might end the effect prematurely." // changed by EntenSchreck and wesp
"HelpTextL2" "Activation Cost: 2 blood. Anyone near you suffers mild hallucinations and a -2 penalty to Firearms, Melee, Brawl, Combat Defense, and Feeding Defense for about 20 seconds." // changed by wesp
"HelpTextL3" "Activation Cost: 2 blood. The Victim will hear a Voice in his head driving him crazy for about 20 seconds thus making him completely helpless." // changed by EntenSchreck and wesp
"HelpTextL4" "Activation Cost: 3 blood. The victim is shown his greatest waking Nightmares, eventually causing a heart attack. May have a lesser effect on supernaturals." // changed by EntenSchreck and wesp
"HelpTextL5" "Activation Cost: 4 blood. The victim goes insane, attacks at random for about 30 seconds and then drops dead. May have a lesser effect on supernaturals." // changed by EntenSchreck and wesp from Dementate 4

            "HelpTextH1"    "Úroveň 1: Maniodeprese"  // changed by EntenSchreck
            "HelpTextH3"    "Úroveň 3: Blázinec " // changed by wesp
            "HelpTextH4"    "Úroveň 4: Vidina Smrti"  // changed by wesp
            "HelpTextH5"    "Úroveň 5: Zběsilost" // changed by wesp
            "HelpTextL1"    "Aktivace: 1 dávka. Emoce oběti se zintenzivní natolik, že že na krátkou chvíi není schopna ničeho jiného než hysterického smíchu nebo kompulzivního pláče zhruba po dobu 15 sekund. Jakákoliv akce proti ní účinek předčasně ukončí." // changed by EntenSchreck and wesp
            "HelpTextL2"    "Aktivace: 2 dávky. Všichni v tvém okolí jsou zasaženi mírnými halucinacemi. Dostanou postih dvou bodů do střelných a kontaktních zbraní, do Zápasu, obrany proti zranění a obrany proti vysátí krve v boji zhruba po dobu 20 sekund." // changed by wesp
            "HelpTextL3"    "Aktivace: 2 dávky. Oběť usliší ve své hlavě hlas, který ji přivede k šílenství, čím se zhruba na dobu 20 stává úplne bezbrannou." // changed by EntenSchreck and wesp
            "HelpTextL4"    "Aktivace: 3 dávky. Oběti se zjeví před očima její nehrůznejší noční můry, což jí spůsobí zástavu srdce. Na nadpřirozené bytosti mívá Vidina smrti slabší účinek." // changed by EntenSchreck and wesp
            "HelpTextL5"    "Aktivace: 4 dávky. Oběť zešílí a náhodne útočí na všechny naokolo asi po dobu 30 sekund a pak zemře. Na nadpřirozené bytosti mívá Záchvat šílenství slabší účinek."    // changed by EntenSchreck and wesp from Dementate 4

            "HelpTextH1"    "Level 1: Command" // changed by EntenSchreck and wesp
            "HelpTextH3"    "Level 3: Sleep"    // changed by EntenSchreck
            "HelpTextL1"    "Activation Cost: 1 blood. The target sinks into a mesmerizing trance or starts to dance for about 15 seconds." // changed by wesp
            "HelpTextL2"    "Activation Cost: 2 blood. All enemies within a small radius will think you've disappeared. This effect wears off after about 5 seconds."   // changed by wesp
            "HelpTextL3"    "Activation Cost: 2 blood. The Target will fall asleep for about 20 seconds or longer becoming completely incapacitated."   // changed by EntenSchreck and wesp
            "HelpTextL4"    "Activation Cost: 3 blood. You impose your will on the victim to suffer a fatal fit."   // changed by EntenSchreck and wesp from Dominate 3
            "HelpTextL5"    "Activation Cost: 4 blood. The victim will desperately attack anyone who means you harm for about 30 seconds, until it eventually dies of cardiac arrest."  // changed by EntenSchreck from Dominate 4

            "HelpTextH1"    "Úroveň 1: Povel" // changed by EntenSchreck and wesp
            "HelpTextH3"    "Úroveň 3: Spánek"   // changed by EntenSchreck
            "HelpTextL1"    "Aktivace: 1 dávka. Cíl na krátkou chvíli upadne do hlubokého tranzu nebo začne tančit asi po dobu 15 sekund."   // changed by wesp
            "HelpTextL3"    "Aktivace: 2 dávky. Cíl zaspí asi na dobu 20 sekund nebo déle, čím se stává úplne bezbranným."    // changed by EntenSchreck and wesp

            "HelpTextH4"    "Level 4: Blood Theft"  // changed by wesp
            "HelpTextH4"    "Level 4: Krádež krve" // changed by wesp
            "HelpTextL4"    "Activation Cost: 3 blood. The blood of the target will be drained and sent to you. Then the victim dies."  // changed by wesp
            "HelpTextL4"    "Aktivace: 3 dávky. Všechna krev z cílu je na dálku vysána a dodána tobě. Poté oběť padá mrtvá."    // changed by wesp

```

**Comment by soulcharmer** [comment]
UP_Plus_CZ\vdata\system\loadingtips.txt
Here, you will be unable to attack or use your vampiric Disciplines, with the exception of using Bloodbuff while lockpicking. ->
Zde nemůžeš útočit ani používat vampírské disciplíny s výjimkou Hlasu krve na Páčení.


"Text" "One of the vampire's greatest feats is the ability to reconstitute their broken body. By focusing the blood they can close buckshot wounds and regrow lost appendages. 
"Text" "Jedna z nejpozoruhodnějších vampírských schopností je regenerace fyzických zranění. Soustředením krve dokáže vampír zahojit rány od kulek a obnovit ztracené končetiny.

"Text" "The vampire may push its body to the peak of human prowess for a short time, for a price in blood. Bloodbuff represens the vampire's innate ability to enhance the physical attributes.
"Text" "Za cenu krve vampíři dokáží na krátkou dobu vybičovat své tělo na hranici fyzických možností. Hlas krve představuje přirozenou vampírskou schopnost k vylepšení atributů Kondice."

One of these are the flesh eating Nagaraja. ->
Patří k nim i masožravý klan Nagaraja.

**a jeste bonusova oprava:**
Ve vampírském světě probíhají fámy o jakýchsi podřadných klanech nebo liniích ->
"Ve vampírském světě kolují fámy o podřadných klanech a liniích

Čím vyšši je tvá bojová schopnost, tím větší poškození zbraň způsobí.  ->
Čím vyšší je tvá bojová schopnost, tím větší poškození zbraň způsobí.

**Comment by soulcharmer** [comment]
UP_Plus_CZ\vdata\system\stats.txt jeste dodelam.

**Comment by soulcharmer** [comment]
"HelpTextL1"    "Aktivace: 1 dávka. Vybičuje emoce zasažené oběti natolik, že po dobu asi 15 sekund nedokáže dělat nic jiného než se hystericky smát nebo usedavě plakat. Jakákoliv akce proti zasaženému účinek předčasně ukončí." // changed by EntenSchreck and wesp
            "HelpTextL2"    "Aktivace: 2 dávky. Všechny v tvém okolí zasáhnout mírné halucinace. Dostanou postih dvou bodů asi na 20 sekund do schopností Střelné zbraně, Kontaktní zbraně, Zápas, Obrana proti zranění a Obrana proti vysátí krve v boji." // changed by wesp
            "HelpTextL3"    "Aktivace: 2 dávky. Zasažená oběť začne slyšet cizí hlas ve své hlavě a asi na 20 sekund bude zcela bezbranná." // changed by EntenSchreck and wesp
            "HelpTextL4"    "Aktivace: 3 dávky. Oběti se zjeví před očima její nehrůznejší noční můry, což jí způsobí zástavu srdce. Na nadpřirozené bytosti mívá Vidina smrti slabší účinek." // changed by EntenSchreck and wesp
            "HelpTextL5"    "Aktivace: 4 dávky. Oběť zešílí, začne náhodně útočit kolem sebe a po půlminutě zemře. Na nadpřirozené bytosti mívá Zběsilost slabší účinek."    // changed by EntenSchreck and wesp from Dementate 4



           "HelpTextL1"    "Aktivace: 1 dávka. Zasažená oběť na krátkou chvíli upadne do hlubokého tranzu nebo začne tančit asi po dobu 15 sekund."   // changed by wesp
            "HelpTextL3"    "Aktivace: 2 dávky. Zasažená oběť náhle usne asi na 20 sekund nebo déle, čímž se stane neschopnou boje."    // changed by EntenSchreck and wesp

            "HelpTextL4"    "Aktivace: 3 dávky. Krev zasažené oběti se na dálku vysaje do tebe. Pak oběť umírá."    // changed by wesp
