### ISSUE TITLE
LIP translator skript

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#8]
na konverziu vrchného riadku do spodného rozsekaného.

**Comment by soulcharmer** [comment]
.lipy maji kombinovane kodovani, dokonce i "file" je detekuje jako binary data.

dalsi krok: oddelit Unicode line a zbytek, a detekovat kodovani u obou casti pres uchardet nebo pres

iconv -f UTF-8 textfile.txt -o /dev/null ; echo $?

pak uz by to mela byt hracka.

**Comment by soulcharmer** [comment]
charmer@dhcp-4-221 ~/gog_bloodlines_cz/cestina/sound/character/dlg/chinatown/garyphone$ uchardet line101_col_e.lip
ISO-8859-3

Na unicode phrase funguje:

:%s/\%x00//g

"That 'symbol' represents a NULL character, with ASCII value 000." <- proto asi uchardet jenom na phrase vraci ASCII a ne UTF-16...

**Comment by miracleflame** [comment]
Podarilo sa mi zistiť, že lipy sa dokážu zobrazovať v hre aj bez nulových znakov v spodnom riadku... stačí že sedí výsledný súčet znakov... a dokonca zvláda aj implementovanú diakritiku pokiaľ PHRASE nasleduje CHAR a nie UNICODE...

Za objav tohto jednoduchého riešenia vďačíme takej úžasnej náhode, ktorá bola postavená na všetkých týchto faktoroch:
1. preložil som aj whispery z UP Plus
2. preklad som neponechal iba vo vrchnom riadku, ale dal som ho rovno aj do spodného
3. prehnal som to fontfriendly konverziou
4. aplikoval som si UP Plus fontfriendly do mojej testovacej hry
5. testoval som zrovna niečo úplne iné a zrovna za malkaviana
6. jeden kokrétny whisper mal správny súčet znakov aj po preklade
7. zrovna tento jeden konkrétny whisper sa sám od seba prehral pri mojom krátkom testovaní
8. moja priateľka sa unúvala oznámiť mi, že sa to tam zjavilo a dokonca s diakritikou zatiaľ, čo ja som bol na záchode

**Comment by soulcharmer** [comment]
https://github.com/soulcharmer/gog_bloodlines_cz/commit/f0f86afa1c6f85cc64275a29ec6ec841ad568279

vyzaduje nainstalovane Ruby.

@miracleflame : prosim otestuj nejprve v jinem adresari, kam nakopirujes nejakou cast stromu cestina/sound. Nebo muzes nejake lipy v cestine zazalohovat a vyeditovat si promennou "folder" ve skriptu.

 .lipy vyzaduji uvozovky u PLAINTEXT i PHRASE.  Zatim tam neni podpora pro multiline phrase.

Diky

**Comment by miracleflame** [comment]
bugy:
1. súčet znakov v spodnom riadku vyrátava o jedno číslo vyššie než treba n+1
2. záverečné čísla za úvodzovkami konvertuje z desatinnej podoby do celočíselnej, prípadne odstraňuje nuly... príklad z 1c25b42 sound\character\dlg\generic\newscaster\line1_col_e.lip
"  0.032 33.392 --> " 32 33.392

**Comment by soulcharmer** [comment]
fixed: https://github.com/soulcharmer/gog_bloodlines_cz/commit/3d104faa8fd202f1fdf28a66e2a3b90ad1e21972

1. vkladal se radek s odseknutym newline, ale delka se pocitala z celeho retezce :-X
2. chybka v regularnim vyrazu matchujicim phrase...

mam u sebe commit se smazanymi soubory .bkp, ale jelikoz nam ty chyby vyse rozhasili lipy, asi by se hodilo nejprve tu zalohu obnovit a spustit skript znovu...

Diky

**Comment by miracleflame** [comment]
Teraz skript tvrdí, že súbory spracoval, ale spodný riadok ostáva nedotknutý.

**Comment by soulcharmer** [comment]
jo, spatne matchovani fraze - to jsou ty hacky delane po pulnoci...

Zkus ted

**Comment by miracleflame** [comment]
Teraz je skript dokonale bezchybný, aspoň zatiaľ sa mi nepodarilo objaviť žiadny zádrhel.. Po FF dumpe je v hre všetko krásne preložené s diakritikou, intro, TV, hlasy v hlave a dokonca aj konverzácie medzi policajtami či ganstermi nad plážou, teda klobúk dolu, lebo tam to bolo multi-úvodzovkové tie ich konverzácie a skript si s tým poradil úspešne! Na multi-line radio lipy si myslím netreba rozširovať skript, tých zopár súborov zvládneme aj ručne.

**Comment by miracleflame** [comment]
Mimochodom objavil som [Vampire the Masquerade Bloodlines (PC) Mod Development Guide](http://docs.google.com/Doc?id=dhgs89mq_12hbmgkpd9) a vďaka nemu iný [LIP edit skript](https://docs.google.com/document/d/1nOenp-PVoezGg2QR4RXqfZz6CccNUXaA5hwYE16OIvg/edit?authkey=CKOyk8oP&ts=57ab8c8a)

Na prístup k dokumentu si treba vyžiadať approval, ktorý som bez problémov dostal do 24 hodín. Ale inak som ten skript nahral aj [sem](https://uloz.to/!KnVt9wphn/lipedit-py)

Može sa hodiť archivovať do repozitára toolov k prekladu VTMB.

**Comment by miracleflame** [comment]
Medzi lipmi sa môžu vyskytnúť aj také, ktorých vrchný riadok môže obsahovať za úvodzovkami jednu medzeru naviac - pravdepodobne copy/paste chyba. Táto medzera sa prenáša aj do spodného riadku a suma sa kalkuluje s ňou, čo je chyba. Dal by sa nejako jednoducho skript upraviť tak, aby reálne kalkuloval spodný riadok od prvej úvodzovky po poslednú? (niekedy býva viac úvodzoviek).
Eliminovalo by to tieto chyby bez potreby prehľadávať stovky lipov.

**Comment by soulcharmer** [comment]
hm, ten skript nema parsovat vychozi radku, ma pouze prekladat tu horni na dolni, jinak bychom tam mohli mit plno dalsich vyjimek...

Nejsem si jist, nakolik ta mezera navic neco ovlivnuje nebo cemu vadi, ale kdyz uz neco, spravne reseni by melo byt rucne to jednou spravit a pak uz na to nesahat. Ale prijde mi, ze ty mezery nic nerozbijeji. Kdyby jo, stalo by to za samostatny skript, ktery bude kontrolovat integritu vychoziho retezce pred prekladem.

**Comment by miracleflame** [comment]
Medzera naviac spôsobuje nesprávne vypočítanú sumu, kvôli čomu sa text nezobrazí v hre.
Asi úplne stačí niečo na detekciu lipov, ktoré tú medzeru majú.. nebude ich veľa, ak ešte vôbec nejaké.. ručne by som to poopravoval, keby som vedel ktoré.

**Comment by soulcharmer** [comment]
Ok, pridal jsem tam:
                                   if line =~ /^" .*"/ then puts "extra space in: " + f.to_s end

takze ted kdyz das

$ ./translate_lip.rb | grep extra

vyjede ti to jen jen soubory, ktere maji v plaintext hned za uvozovkou mezeru.

Testni to prosim a kdyztak zavri tiket. Diik

**Comment by miracleflame** [comment]
Náhodne som doplnil medzeru za úvodzovky v konkrétnom súbore a nechal zbehnúť 
./translate_lip.rb | grep extra

až na to, že proces prebehol bez výstupu som nespozoroval zmenu.. v súboroch sa nezmenilo nič, až na to, že vytvoril *.bkp... inak to by nemusel stále robiť, aj tak to vždy hneď mažem.. zálohu mám keď tak svoju, alebo sa dá stiahnuť z gitu, hociktorý commit v prípade núdze.

**Comment by soulcharmer** [comment]
dej priklad souboru, kde ta mezera navic je - mozna je to zase neco extra... To vytvareni zaloh uz v pristim commitu zakomentuju.

**Comment by miracleflame** [comment]
Tak napr. gog_bloodlines_cz\cestina\sound\character\dlg\downtown la\tutorial_security_guard\line11_col_e.lip som si pridal medzeru na koniec plaintextu za úvodzovku. Nebudem kvôli tomu vytvárat commit, jednoducho som si tam pridal medzeru, zbehol ./translate_lip.rb | grep extra a nič som nepobadal.

**Comment by miracleflame** [comment]
To áno, promiň, tiež som to mohol napísať zrozumiteľnejšie.
Super, teraz to funguje ako má, vyplul mi zoznam asi 40 lipov, ktoré opravím...
Tak ja tento tiket zatváram, asi dodatočné úpravy nebudú potrebné.
