### ISSUE TITLE
UP+ LIP whispers review

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#82]
sound\whispers\ambiguous\bone.lip
"Bone round in melody and word layed in rain..."
"Kosti se točí v melodii a slovo padá do deždě..."

sound\whispers\ambiguous\cemetery.lip
"Cemetery runoff congealing at the door..."
"Uprchlík ze hřbitova se cápá po dveřích..."

sound\whispers\ambiguous\maggots.lip
"Maggots love you. Trust me."
"Červy tě milují. Věř mi."

sound\whispers\ambiguous\moon.lip
"Mast lay shrouded and the moon is melting..."
"Žalud leží zahalený a měsíc taje..."

sound\whispers\ambiguous\peppers.lip
"Try the corpse in the oven with peppers and fur..."
"Zkus mrtvolu v troubě s papričkama a kožešinou..."

sound\whispers\ambiguous\souls.lip
"Souls draped in rotten tatters and Father dances in the dark..."
"Duše zahalené shnilými cáry a Otec tančí ve tmě..."

sound\whispers\ambiguous\tallow.lip
"Make the tallow from the fat of a hangman."
"Udělej svíčku z tuku oběšence."

sound\whispers\danger\crouch.lip
"Evil crouches..."
"Zlo se plíží..."

sound\whispers\danger\death.lip
"Death..."
"Smrt..."

sound\whispers\danger\die.lip
"DIE!"
"UMŘI!"

sound\whispers\danger\grave.lip
"I smell a rancid grave."
"Čichám shnilý hrob."

sound\whispers\danger\in_for_it.lip
"You're in for it now..."
"Teď si koleduješ..."

sound\whispers\danger\reaper.lip
"Rustling robes of the Reaper..."
"Kápě Smrťákova šustí..."

sound\whispers\danger\theyre_coming.lip
"Hah hah hah hah... They're coming."
"Ha ha ha ha... Už přicházejí.

sound\whispers\deluded\blind.lip
"All are blind whose eyes are closed."
"Slepí jsou ti, jejiž oči jsou zavřené."

sound\whispers\deluded\calf.lip
"Look at it, bent like a calf for the butcher."
"Dívej se na to, poklekni jako dobytek u řezníka."

sound\whispers\deluded\mistress.lip
"The drove is a terrible mistress."
"Hejno je hrozná milenka."

sound\whispers\deluded\wishes_words.lip
"Whishes and words sprout from the same seed..."
"Přání i slova klíčí ze stejného semínka..."

sound\whispers\distrust\dark_light.lip
"A dark light from your death..."
"Temné světlo z tvé smrti..."

sound\whispers\distrust\hemlock.lip
"Hemlock for the deceivers..."
"Bolehlav na podvodníky..."

sound\whispers\distrust\shadow.lip
"It casts a crooked shadow."
"Vrhá pokřivený stín."

sound\whispers\distrust\two_mouths.lip
"It has two mouths to lick from."
"Má dvě pusy na vylizování."

sound\whispers\gibberish\atlantic.lip
"Deep of the Atlantic, the Ark, dreaming, sleeping..."
"Hlubiny Atlantiku, Archa, sní, spí..."

sound\whispers\gibberish\elkabo.lip
"Elkabo, elkabo, pixy queen where all is green..."
"Elkabo, elkabo, královná skřítků kde vše je zelené..."

sound\whispers\gibberish\eyes.lip
"Can't see, can't see! Where have my eyes gone to?"
"Nevidím, nevidím! Kam se poděli mé oči?"

sound\whispers\gibberish\heloise.lip
"Heloise said you... Cranberry sauce... Hotel foxtrot..."
"Heloisa říkáš... Brusinková omáčka... Hotel foxtrot..."

sound\whispers\gibberish\mother.lip
"Stop doing that. Mother shan't be too pleased. None too pleased..."
"Přestaň s tím. Matka nebude příliš nadšena. Vůbec nebude nadšena..."

sound\whispers\lying\asps.lip
"It's a tangle of asps."
"Je to klubko zmyjí."

sound\whispers\lying\putrid.lip
"Those lips bleed a putrid poison."
"Z těchto rtů krvácí páchnoucí jed."

sound\whispers\lying\swine.lip
"Sealed with the kiss of swine..."
"Prokletí polibkem svině..."

sound\whispers\lying\tails.lip
"Rat tails, cat tails, coat tails, all tales."
"Křysí ocasy, kočičí ocasy, kozí ocasy, všechno ocasy."

sound\whispers\lying\tongues.lip
"A trick with two tongues..."
"Třik se dvěma jazyky..."

sound\whispers\quest\not_fair.lip
"It's not fair! I wanted too."
"To není fér! Já chtěl taky."

sound\whispers\quest\pennies.lip
"Pennies for your eyes in its pockets..."
"Penízky pro tvé oči v kapse..."

sound\whispers\quest\troubled.lip
"Why is it troubled?"
"Proč se to trápí?"

sound\whispers\threat\arsenic.lip
"Ask about the free arsenic."
"Ptej se na arzén zdarma."

sound\whispers\threat\beast.lip
"Blood brings the vicious beast..."
"Krev přivolá zlověstnou bestii..."

sound\whispers\threat\daggers.lip
"I see daggers hang on his breath."
"Vidím jak dýky visí z jeho dechu."

sound\whispers\threat\flame.lip
"The very thought falls to the flame..."
"Myšlenka samotná padá do plamene..."

**Comment by soulcharmer** [comment]
opravy:

sound\whispers\ambiguous\bone.lip
"Kost se ztočila v melodii a slovo ulehlo v dešti..."

sound\whispers\ambiguous\cemetery.lip
"Voda ze hřbitova mrzne u dveří..."

sound\whispers\ambiguous\maggots.lip
"Červi tě milují. Věř mi."

sound\whispers\ambiguous\moon.lip
"Pylon zůstává zahalen a měsíc se rozpouští..."

sound\whispers\ambiguous\peppers.lip
"Zkus mrtvolu v troubě s paprikou a srstí..."

sound\whispers\ambiguous\souls.lip OK
"Duše zahalené shnilými cáry a Otec tančí ve tmě..."

sound\whispers\ambiguous\tallow.lip
"Vyrob svíčku z tuku oběšence."

sound\whispers\danger\crouch.lip
"Zlo se krčí..."

sound\whispers\danger\death.lip OK
"Smrt..."

sound\whispers\danger\die.lip
"ZEMŘI!"

sound\whispers\danger\grave.lip
"Cítím ztuchlý hrob."

sound\whispers\danger\in_for_it.lip
"Teď si to slízneš..."

sound\whispers\danger\reaper.lip
"Šustící talár zubaté..."

sound\whispers\danger\theyre_coming.lip
"Ha ha ha ha... Už se blíží."

sound\whispers\deluded\blind.lip
"Slepí jsou ti, jejichž oči jsou zavřené."

sound\whispers\deluded\calf.lip
"Podívej, ohnutý jako tele pro řezníka."

sound\whispers\deluded\mistress.lip
"Dav je ukrutná milenka."

sound\whispers\deluded\wishes_words.lip
"Tužby a slova pochází ze stejného sémě..."

sound\whispers\distrust\dark_light.lip
"Temné světlo tvé smrti..."

sound\whispers\distrust\hemlock.lip
"Bolehlav pro podvodníky..."

sound\whispers\distrust\shadow.lip OK
"Vrhá pokřivený stín."

sound\whispers\distrust\two_mouths.lip
"Má dvoje ústa na naslinění."

sound\whispers\gibberish\atlantic.lip
"Hlubiny Atlantiku, Archa, snící, spící..."

sound\whispers\gibberish\elkabo.lip
"Elkabo, elkabo, královna víl, kde vše je zelené..."

sound\whispers\gibberish\eyes.lip
"Nevidím, nevidím! Kam se poděly mé oči?"

sound\whispers\gibberish\heloise.lip
"Heloise říkala, že... Brusinková omáčka... Hotelový foxtrot..."

sound\whispers\gibberish\mother.lip
"Přestaň. Matka nebude nadšena. Ani trochu."

sound\whispers\lying\asps.lip OK
"Je to klubko zmyjí."

sound\whispers\lying\putrid.lip
"Z těch rtů vychází páchnoucí jed."

sound\whispers\lying\swine.lip
"Ocejchován polibkem svině..."

sound\whispers\lying\tails.lip
"Ocasy krysí, ocasy kočičí, ocasy ze srsti, všechno je pověsti."

sound\whispers\lying\tongues.lip
"Trik se dvěma jazyky..."

sound\whispers\quest\not_fair.lip
"To není fér! Já chci též."

sound\whispers\quest\pennies.lip
"Penízky za tvé oči v jeho kapsách..."

sound\whispers\quest\troubled.lip OK
"Proč se to trápí?"

sound\whispers\threat\arsenic.lip OK
"Ptej se na arzén zdarma."

sound\whispers\threat\beast.lip OK
"Krev přivolá zlověstnou bestii..."

sound\whispers\threat\daggers.lip
"Vidím dýky visící z jeho dechu."

sound\whispers\threat\flame.lip
"Myšlenka sama padá do plamenů..."

**Comment by miracleflame** [comment]
Medzičasom som niektoré moje preklady upravil.. pozri ešte raz na tieto dva:
"Žádej arzén zdarma."
"Vidím jak dýky koukaj z jeho dechu."

"Ocasy krysí, ocasy kočičí, ocasy ze srsti, všechno je pověsti."
Tu mi niečo nesedí, alebo to nechápem... nemá tam byť "jsou pověsti" alebo "je pověstí"?

**Comment by soulcharmer** [comment]
"Žádej arzén zdarma." - ok, muze byt

 "Vidím jak dýky koukaj z jeho dechu." - "koukaj" nezapada do slovniku prastarych duchu :-) Nechal bych "visici"

"Ocasy krysí, ocasy kočičí, ocasy ze srsti, všechno je pověsti." - oops preklep
"Ocasy krysí, ocasy kočičí, ocasy ze srsti, všechno jen pověsti."

**Comment by miracleflame** [comment]
Dobre...
Inak ja si myslím, že tieto podarené hlášky spísal celý tím ako kolekciu svojich vlastných hlasov, ktoré niekedy v živote počuli v hlave. .)
