### ISSUE TITLE
Translate LIP float female asian

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#83]
cestina\sound\character\female\asian\*

**Comment by miracleflame** [comment]
-"W-where am I?"
 +"Kde-kde to jsem?"

-"Wha-what's going on?"
 +"Co-co se to děje?"

-"Oh my goodness!"
 +"Ach, božíčku!"

-"Ah! Help!"
 +"Áá! Pomoc!"

-"Oh! Oh no!"
 +"Oh! To ne!"

-"No speak English."
 +"Nemluvit anglicky."

-"No no, I don't know you."
 +"Ne ne, neznát tě."

-"Excuse me? No."
 +"Pardon? Ne."

-"How did I get here?"
 +"Jak jsem se tu vzala?"

-"What? What?"
 +"Co? Cože?"

-"Oh, where am I?"
 +"Oh, kde to jsem?"

-"Please, oh, ugh, ah, no, ah oh."
 +"Prosím,...."

-"God, please, stop, no, no the voices."
 +"Bože, prosím, přestaňte, ne, ne ty hlasy."

-"Oh, no, no, oh god, oh no, no, god stop."
 +"Oh, ne, ne, ó bože, to ne, ne, bože, přestaňte..."

-"Oh, my, goodnes."
 +"Ó svatá dobroto."

-"Stop!"
 +"Stůj!"

-"Wait!"
 +"Čekej!"

-"Ohhhh well, he's gone!"
 +"No dobrá, je pryč!"

-"Bye bye, don't know where he went."
 +"Pa pa, nevím kam odešli."

-"Ohhh, where's he gonna go now?"
 +"Óóó, kampak pojedou teď?"

-"I know you're here."
 +"Vím, že tu si."

-"Come out!"
 +"Vylez!"

-"Come on!"
 +"No tak!"

-"What was that?"
 +"Co to bylo?"

-"Who's there?"
 +"Kdo je tam?"

-"I know somebody's there."
 +"Vím, že tam někdo je."

**Comment by miracleflame** [comment]
@maarten93 naasajnoval som ťa na tento tiket, ale môžeš ich brať rad radom všetky tohto typu. @soulcharmer súhlasil s mojm návrhom, že by si tieto texty skontrolované a opravné mohol znovu hodiť do komentára, aby to @soulcharmer potom už len preletel očami. Díky moc.

**Comment by maarten93** [comment]
ok

**Comment by maarten93** [comment]
Dnes už se k tomu asi nedostanu, ale mám jeden dotaz to jsou všechno reakce na hráčovu postavu a jde někde zjistit kdy takto npc reagují?

**Comment by miracleflame** [comment]
Odhadom podľa názvov súborov d6274e06a7d36f8c49465547a88f943c8e7d9847
Veľkú časť z nich by mal obnoviť až patch 9.7, toto je predpríprava, update je za rohom, vlastne už ho spracovávam.
comfort - keď postava narazí na plačúcu postavu
disorientated - keď sa postava preberie z účinkov tranzu alebo také niečo
fear - keď sa bojí
flee - keď sa snaží utiecť
float - bežné hlášky po narazení do postavy, či v jej tesnej blízkosti
idle_agitated - keď postave niečo bráni v pohybe, obvykle iná postava
lost - niečo ako disorientated
madness - pravdepodobne učínky silnejších disciplín Dementace
suspect_giveup - keď postava vzdá hľadanie ukrytého protivníka
target_acquired - odhalenie protivníka
target_giveup - viď suspect_giveup
target_lost - stratenie stopy protivníka
target_suspect - podozrenie na prítomnosť protivníka
upset - netuším

**Comment by maarten93** [comment]
-"Oh my goodness!"
+"Ach, proboha!"

-"Ah! Help!"
+"Áá! Pomoc!"

-"Oh! Oh no!"
+"ah! To ne!"

-"No speak English."
+"Nemluvit anglicky."

-"No no, I don't know you."
+"Ne, neznám vás."

-"Excuse me? No."
+"Promiňte? Ne."

-"How did I get here?"
+"Jak jsem se sem dostala?"

-"What? What?"
+"Co? Cože?"

-"Oh, where am I?"
+"ah, kde to jsem?"

-"Please, oh, ugh, ah, no, ah oh."
+"Prosím, ah fuj brr ne ah. "   Tady nevím jak to napsat, nespíš je to vyjádření stachu, odporu a hnusu, po použití nějaké disciplíny(dementace)

-"God, please, stop, no, no the voices."
+"Bože, prosím, Ať ty hlasy přestanou."

-"Oh, no, no, oh god, oh no, no, god stop."
+"ach, ne, ne, bože, to ne, ne, bože, dost..."

-"Oh, my, goodnes."
+"ach panebože."

-"Stop!"
+"Stůj!"

-"Wait!"
+"Počkej!"

-"Ohhhh well, he's gone!"
+"No dobře, je pryč!"

-"Bye bye, don't know where he went."
+"Sbohem, nemám tušení kde je."

-"Ohhh, where's he gonna go now?"
+"ach, kde může být?"

-"I know you're here."
+"Vím, že tu jsi."

-"Come out!"
+"Vylez!"

-"Come on!"
+"No tak!"

-"What was that?"
+"Co to bylo?"

-"Who's there?"
+"Kdo je tam?"

-"I know somebody's there."
+"Vím, že tam někdo je."

**Comment by miracleflame** [comment]
Super... dve veci...
1. čo sa týka citosloviec, mám dojem, že sme sa so @soulcharmer dohodli, že ich nebudeme prekladať a ponecháme len zvuk + necitoslovný text 
2. prosím, obsiahni v komentári úplne všetko, aj nezmenený text, nech si nemusí @soulcharmer skladať dohromady môj+tvoj komentár a hľadať rozdiely. Dík.

**Comment by maarten93** [comment]
-"W-where am I?"
+"Kde-kde to jsem?"
+"K-kde to jsem?"

-"Wha-what's going on?"
+"Co-co se to děje?"

-"Oh my goodness!"
+"Ach, božíčku!"
+"Ach, proboha!"

-"Ah! Help!"
+"Áá! Pomoc!"

-"Oh! Oh no!"
+"Oh! To ne!"

-"No speak English."
+"Nemluvit anglicky."

-"No no, I don't know you."
+"Ne ne, neznát tě."

-"Excuse me? No."
+"Pardon? Ne."
+"Promiňte? Ne."

-"How did I get here?"
+"Jak jsem se tu vzala?"
+"Jak jsem se sem dostala?"

-"What? What?"
+"Co? Cože?"

-"Oh, where am I?"
+"Oh, kde to jsem?"

-"Please, oh, ugh, ah, no, ah oh."
+"Prosím,...."
+"Prosím,....ne"

-"God, please, stop, no, no the voices."
+"Bože, prosím, přestaňte, ne, ne ty hlasy."
+"Bože, prosím, Ať ty hlasy přestanou."

-"Oh, no, no, oh god, oh no, no, god stop."
+"Oh, ne, ne, ó bože, to ne, ne, bože, přestaňte..."
+"ach, ne, ne, bože, to ne, ne, bože, dost..."

-"Oh, my, goodnes."
+"Ó svatá dobroto."
+"ach panebože."

-"Stop!"
+"Stůj!"

-"Wait!"
+"Čekej!"

-"Ohhhh well, he's gone!"
+"No dobrá, je pryč!"
+"No dobře, je pryč!"

-"Bye bye, don't know where he went."
+"Pa pa, nevím kam odešli."
+"Sbohem, nemám tušení kde je."

-"Ohhh, where's he gonna go now?"
+"Óóó, kampak pojedou teď?"
+"ach, kde může být?"

-"I know you're here."
+"Vím, že tu si."
+"Vím, že tu jsi."

-"Come out!"
+"Vylez!"

-"Come on!"
+"No tak!"

-"What was that?"
+"Co to bylo?"

-"Who's there?"
+"Kdo je tam?"

-"I know somebody's there."
+"Vím, že tam někdo je."

**Comment by soulcharmer** [comment]
vsechno dobry, jen u nekterych prekladu chybi na zacatku velke pismeno. A drobne upravy:

-"Please, oh, ugh, ah, no, ah oh."
+"Prosím,...."
+"Prosím,....ne"
+"Prosím,... ne."

-"God, please, stop, no, no the voices."
+"Bože, prosím, přestaňte, ne, ne ty hlasy."
+"Bože, prosím, Ať ty hlasy přestanou."
+"Bože, prosím, přestaň, ne, ne, ty hlasy."

-"Bye bye, don't know where he went."
+"Pa pa, nevím kam odešli."
+"Sbohem, nemám tušení kde je."
+"Sbohem, ani nevím, kde je."


diky
