### ISSUE TITLE
Translate LIP float female bluebood

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#84]
cestina\sound\character\female\blue_blood\

**Comment by miracleflame** [comment]
-"Not now!"
 +"Teď ne!"

-"Excuse me..."
 +"Omluvte mě..."

-"Oh my god!"
 +"Bože můj!"

-"Oh my goodness!"
 +"Proboha!"

-"I am talking here."
 +"Já tady s nekým mluvím."

-"Can't you se I'm talking here?"
 +"Nevidíte, že s někým mluvím?"

-"Go back to the punch bowl."
 +"Vraťte se k míse s punčem."

-"Not now."
 +"Teď ne."

-"No, go away."
 +"Ne, jdi pryč."

-"No, don't bother me."
 +"Ne, neobtěžuj mě."

**Comment by maarten93** [comment]
Not now!"
+"Teď ne!"

-"Excuse me..."
+"Omluvte mě..."

-"Oh my god!"
+"můj Bože!"

-"Oh my goodness!"
+"Proboha!"

-"I am talking here."
+"zrovna s někým mluvím."

-"Can't you se I'm talking here?"
+"Nevidíte, že s někým mluvím?"

-"Go back to the punch bowl."
+"Vraťte se k míse s punčem."      Není to někaký Slang, nebo se tím opravdu myslí mísa s punčem?   

-"Not now."
+"Teď ne."

-"No, go away."
+"Ne, jděte pryč."

-"No, don't bother me."
+"Ne, neobtěžujte mě."

**Comment by maarten93** [comment]
-"Not now!"
+"Teď ne!"

-"Excuse me..."
+"Omluvte mě..."

-"Oh my god!"
+"Bože můj!"
+"můj Bože!"

-"Oh my goodness!"
+"Proboha!"

-"I am talking here."
+"Já tady s nekým mluvím."
+"zrovna s někým mluvím."

-"Can't you se I'm talking here?"
+"Nevidíte, že s někým mluvím?"

-"Go back to the punch bowl."
+"Vraťte se k míse s punčem."  Není to někaký Slang, nebo se tím opravdu myslí mísa s punčem?

-"Not now."
+"Teď ne."

-"No, go away."
+"Ne, jdi pryč."
+"Ne, jděte pryč."

-"No, don't bother me."
+"Ne, neobtěžuj mě."
+"Ne, neobtěžujte mě."

**Comment by soulcharmer** [comment]
vsechny opravy okej, jen u

-"Go back to the punch bowl."
+"Vraťte se k míse s punčem."
+"Vraťte se k míse na punč."

bych preferoval ten prvni preklad, pokud ta misa neni prazdna :)

Diky
