### ISSUE TITLE
Translate LIP float female citizen

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#85]
cestina\sound\character\female\citizen\*

**Comment by miracleflame** [comment]
-"Help me, help me, please, help, please..."
 +"Pomozte mi, pomozte mi, prosím, pomozte, prosím..."

-"HELP!!!"
 +"POMOC!!!"

-"Oh my god! Oh..."
 +"Můj bože!"

-"Oh god!"
 +"Ó bože!"

-"What ever."
 +"Nezájem."

-"Buy a watch."
 +"Kup si své hodinky."

-"I'll scream..."
 +"Začnu křičet..."

**Comment by maarten93** [comment]
-"Help me, help me, please, help, please..."
+"Pomozte mi, pomozte mi, prosím, pomozte, prosím..."
+"Pomozte mi, pomozte mi, prosím, pomoc, prosím..."

-"HELP!!!"
+"POMOC!!!"

-"Oh my god! Oh..."
+"Můj bože!"

-"Oh god!"
+"Ó bože!"

-"What ever."
+"Nezájem."

-"Buy a watch."
+"Kup si své hodinky."

-"I'll scream..."
+"Začnu křičet..."
+"Budu křičet..."

**Comment by maarten93** [comment]
-"Help me, help me, please, help, please..."
+"Pomozte mi, pomozte mi, prosím, pomozte, prosím..."

-"HELP!!!"
+"POMOC!!!"

-"Oh my god! Oh..."
+"Můj bože!"

-"Oh god!"
+"Ó bože!"

-"What ever."
+"Nezájem."

-"Buy a watch."
+"Kup si své hodinky."

-"I'll scream..."
+"Začnu křičet..."

**Comment by soulcharmer** [comment]
ok, dobry, akorat

-"Buy a watch."
+"Kup si své hodinky."
+"Kupte si hodinky."

diky
