### ISSUE TITLE
Translate LIP float female hookers

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#86]
cestina\sound\character\female\hooker#\*

**Comment by miracleflame** [comment]
-"Hey puppy, need a date?"
 +"Čau štěňátko, chceš rande?"

-"Hey there, need a date?"
 +"Ahoj, chceš rande?"

-"Need company?"
 +"Chceš společnost?"

-"Hey baby, need company?"
 +"Čau zlato, chceš společnost?"

-"Hey there, need a date?"
 +"Ahoj, chceš rande?"

-"Hey, need a date?"
 +"Čau, chceš rande?"

-"Hey there, need a date?"
 +"Ahoj, chceš rande?"

-"Need some company?"
 +"Chceš trochu společnosti?"

-"Hey baby, need company?"
 +"Čau zlato, chceš společnost?"

-"Hey, you need company?"
 +"Čau, hledat společnost?"

-"Hey baby, need some company?"
 +"Čau zlato, chceš trochu společnosti?"

-"Hey baby, you need some company?"
 +"Čau zlato, chceš trochu společnosti?"

-"Hey baby, need a date?"
 +"Čau zlato, chceš společnost?"

-"Hey baby, only 20 dollar."
 +"Čau zlato, jen 20 dolar."

**Comment by maarten93** [comment]
-"Hey puppy, need a date?"
+"Čau štěňátko, chceš rande?"

-"Hey there, need a date?"
+"Ahoj, chceš rande?"
+"Nazdárek, nechceš jít na rande?"

-"Need company?"
+"Chceš společnost?"


-"Hey baby, need company?"
+"Čau zlato, chceš společnost?"
"Hej baby, hledáš společnost?"

-"Hey there, need a date?"
+"Ahoj, chceš rande?"

-"Hey, need a date?"
+"Čau, chceš rande?"

-"Hey there, need a date?"
+"Ahoj, chceš rande?"

-"Need some company?"
+"Chceš trochu společnosti?"
+"Chceš nějakou společnost?"

-"Hey baby, need company?"
+"Čau zlato, chceš společnost?"

-"Hey, you need company?"
+"Čau, hledat společnost?"
+"Čau, nehledáš společnost?"

-"Hey baby, need some company?"
+"Čau zlato, chceš trochu společnosti?"

-"Hey baby, you need some company?"
+"Čau zlato, chceš trochu společnosti?"

-"Hey baby, need a date?"
+"Čau zlato, chceš společnost?"

-"Hey baby, only 20 dollar."
+"Čau zlato, jen 20 dolar."
+"Rychlovka za 20 dolarů."

**Comment by maarten93** [comment]
zdá se mi, že nato že jsou to prostitutky se zde vyjadřují až moc kulantně, ale asi to nejde moc změnit protože by to nesedělo s dabingem?

**Comment by miracleflame** [comment]
Presne tak, je to transkripcia dabingu.

**Comment by soulcharmer** [comment]
Tady to kapanek potunime:

-"Hey puppy, need a date?"
+"Čau štěňátko, chceš rande?" 
+"Čau šviháku, co takhle rande?"

-"Hey there, need a date?"
+"Ahoj, chceš rande?"
+"Nazdárek, nechceš jít na rande?"
+"Ahojky, nehledáš rande?"

-"Need company?"
+"Chceš společnost?"
+"Nehledáš společnost?"

-"Hey baby, need company?"    <-- tahle je tam 2x?
+"Čau zlato, chceš společnost?"
+"Hej baby, hledáš společnost?"
+"Hej zlato, nehledáš společnost?"

-"Hey there, need a date?"
+"Ahoj, chceš rande?"
+"Ahoj, co takhle rande?"

-"Hey, need a date?"
+"Čau, chceš rande?"
+"Čau, co třeba rande?"

-"Hey baby, you need some company?"
+"Čau zlato, chceš trochu společnosti?"
+"Čau baby, nehledáš společnost?"
+"Ahoj zlato, nehledáš společnost?"

-"Hey baby, need a date?"
+"Čau zlato, chceš společnost?"
+"Čau baby, chceš dostaveníčko?"
+"Čau zlato, co takhle rande?"

-"Hey baby, only 20 dollar."
+"Čau zlato, jen 20 dolar."
+"Čau zlato, jen za 20 dolarů."
+"Rychlovka za 20 dolarů."
+"Čau zlato, jen 20 dolarů."


diky

**Comment by miracleflame** [comment]
Nezabudni, že tieto treba unisex
+"Čau šviháku, co takhle rande?" sa na holku nehodí

**Comment by soulcharmer** [comment]
no jestli jsou vsechny unisex, tak se tam nehodi ani to stenatko.

Ale "kotě" by tam byt mohlo, paradoxne  :-)

**Comment by miracleflame** [comment]
Niekde na Planet Vampire niekto upozornil, že správny transscript by mal byť Pappy ako polohispánske taťka, ale Wesp sa nakoniec priklonil k mojej verzii práve preto, že šteniatko je relatívne unisex... prečo by nebolo rovnako ako kotě?

**Comment by soulcharmer** [comment]
protoze stenatko se takhle v cestine nepouziva, aspon o tom nevim :)
