### ISSUE TITLE
Translate LIP float female root/Jezebel

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#87]
Jezebel používa tie isté floats ako generic female 
cestina\sound\character\female\*
cestina\sound\character\female\unique\*
cestina\sound\character\female\Jezebel\*

**Comment by miracleflame** [comment]
-"Looks like I lost 'em."
 +"Zdá se, že je pryč."

-"Where'd they go?"
 +"Kde je?"

-"They're gone!"
 +"Je pryč!"

-"Hey, stop right there!"
 +"Hej, zůstaň, kde jsi!"

-"Don't move!"
 +"Ani hnout!"

-"I know you're around here."
 +"Vím, že tu někde jsi."

-"Come out!"
 +"Vylez!"

-"Come on out!"
 +"No tak vylez!"

-"Who's there?"
 +"Kdo je tam?"

-"What was that?"
 +"Co to bylo?"

-"I heard something."
 +"Něco jsem slyšela."

-"Oh- oh... Stop..."
 +"...přestaňte..."

-"Ah- oh... please, stop..."
 +"...prosím, přestaňte..."

-"Ah- oh... Stop... I wanna go home... Please, no, no..."
 +"... Přestaňte... Já chi domů... Prosím, ne, ne..."

-"Please don't hurt me!"
 +"Prosím, neubližujte mi!"

-"I haven't done anything. Please!"
 +"Nic jsem neudělala. Prosím!"

-"Oh my god, I gotta het out of here!"
 +"Můj bože, padám odsud!"

-"Oh my god!"
 +"Můj bože!"

-"Whoa! Ah! I gotta get out of here! I gotta go..."
 +"...Padám odsud! Padám..."

-"Hey, what's wrong?"
 +"Hej, co se děje?"

-"Oh, don't forget milk."
 +"Ach, nezapomeň na mléko."

-"Argh! Fuck! Shit!"
 +"Kurva! Do prdele!"

-"Goddamnit!"
 +"K sakru!"

-"Where am I?"
 +"Kde to jsem?"

-"What am I doing here?"
 +"Co tady dělám?"

-"I'm not listening to you. Shut up, Shut up!"
 +"Neposlouchám tě. Sklapni, sklapni!"

-"Wha- what? Stop!"
 +"Co- cože? Přestaň!"

-"Wha- the voices- get out- get out of my head now- get- out- of my- get out of my..."
 +"Co- hlasy- vypadněte- vypadněte z mý hlavy hned- vy- pad- ni- z mý hlavy..."

**Comment by maarten93** [comment]
-"Looks like I lost 'em."
+"Zdá se, že je pryč."

-"Where'd they go?"
+"Kde je?"

-"They're gone!"
+"Je pryč!"

-"Hey, stop right there!"
+"Hej, zůstaň, kde jsi!"

-"Don't move!"
+"Ani hnout!"

-"I know you're around here."
+"Vím, že tu někde jsi."

-"Come out!"
+"Vylez!"

-"Come on out!"
+"No tak vylez!"

-"Who's there?"
+"Kdo je tam?"

-"What was that?"
+"Co to bylo?"

-"I heard something."
+"Něco jsem slyšela."

-"Oh- oh... Stop..."
+"...přestaňte..."

-"Ah- oh... please, stop..."
+"...prosím, přestaňte..."

-"Ah- oh... Stop... I wanna go home... Please, no, no..."
+"... Přestaňte... Já chi domů... Prosím, ne, ne..."

-"Please don't hurt me!"
+"Prosím, neubližujte mi!"

-"I haven't done anything. Please!"
+"Nic jsem neudělala. Prosím!"

-"Oh my god, I gotta het out of here!"
+"Můj bože, padám odsud!"

-"Oh my god!"
+"Můj bože!"

-"Whoa! Ah! I gotta get out of here! I gotta go..."
+"...Padám odsud! Padám..."
+"...Musím se odsud dostat! Padám pryč..."

-"Hey, what's wrong?"
+"Hej, co se děje?"

-"Oh, don't forget milk."
+"Ach, nezapomeň na mléko."

-"Argh! Fuck! Shit!"
+"Kurva! Do prdele!"

-"Goddamnit!"
+"K sakru!"

-"Where am I?"
+"Kde to jsem?"

-"What am I doing here?"
+"Co tady dělám?"

-"I'm not listening to you. Shut up, Shut up!"
+"Neposlouchám tě. Sklapni, sklapni!"

-"Wha- what? Stop!"
+"Co- cože? Přestaň!"

-"Wha- the voices- get out- get out of my head now- get- out- of my- get out of my..."
+"Co- hlasy- vypadněte- vypadněte z mý hlavy hned- vy- pad- ni- z mý hlavy..."

**Comment by soulcharmer** [comment]
par oprav:

-"Looks like I lost 'em."
+"Zdá se, že je pryč."
+"Vypadá to, že je pryč."

-"Hey, stop right there!"
+"Hej, zůstaň, kde jsi!"
+"Hej, už ani krok!"

-"I know you're around here."
+"Vím, že tu někde jsi."
+"Vím, že tu jsi."

-"Ah- oh... Stop... I wanna go home... Please, no, no..."
+"... Přestaňte... Já chi domů... Prosím, ne, ne..."
+"... Přestaňte... Já chci domů... Prosím, ne, ne..."

-"Oh my god, I gotta het out of here!"   <- sem patri "get"
+"Můj bože, padám odsud!"
+"Můj bože, Musím se odsud dostat!"
+"Můj bože, musím se odsud dostat!"

-"Whoa! Ah! I gotta get out of here! I gotta go..."
+"...Padám odsud! Padám..."
+"...Musím se odsud dostat! Padám pryč..."
+"...Musím se odsud dostat! Musím pryč..."

-"Oh, don't forget milk."
+"Ach, nezapomeň na mléko."
+"Nezapomeň na mléko."


-"Wha- the voices- get out- get out of my head now- get- out- of my- get out of my..."
+"Co- hlasy- vypadněte- vypadněte z mý hlavy hned- vy- pad- ni- z mý hlavy..."
+"Co-ty hlasy- vypadni- vypadni z mý hlavy hned- vy- pad- ni- z mý hlavy..."
+"Co- hlasy- zmizte- hned zmizte z mý hlavy- vy- pad- ně- te-..."


diky
