### ISSUE TITLE
Translate LIP float female patron

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#88]
cestina\sound\character\female\patron*\*

**Comment by miracleflame** [comment]
-"Hey, cutie."
 +"Čau, zlato."

-"Like what you see?"
 +"Líbí se ti, co máš před očima?"

-"I'm with somebody."
 +"Jsem tu s někým."

-"What?!"
 +"Cože?!"

-"Eh, not interested."
 +"Eh, nezájem."

-"What ever."
 +"Nezájem."

-"Buy a watch."
 +"Kup si své hodinky."

-"I'll scream..."
 +"Začnu křičet..."

-"I'll never forget this night."
 +"Nikdy nezapomenu na tuto noc."

-"I feel a chill."
 +"Je mi chladno."

-"Yeah?"
 +"Jo?"

-"So what are you gonna do tonight, hm?"
 +"Co máš ty dnes večer v plánu, hm?"

-"What do you want?"
 +"Co chceš?"

-"What's the emergency?"
 +"Kdepak hoří?"

-"Evening."
 +"Večír."

-"I'm eating."
 +"Já jím."

-"Uhh, I'm busy here..."
 +"Nemám čas..."

**Comment by maarten93** [comment]
-"Hey, cutie."
+"Čau, zlato."

-"Like what you see?"
+"Líbí se ti, co máš před očima?"
+"Líbí se ti to,co vidíš?"

-"I'm with somebody."
+"Jsem tu s někým."
+"S někým tady jsem."

-"What?!"
+"Cože?!"

-"Eh, not interested."
+"Eh, nezájem."
+"Eh, nemám zájem."

-"What ever."
+"Nezájem."
+"To je jedno."

-"Buy a watch."
+"Kup si své hodinky."
+"Kupte si hodinky."

-"I'll scream..."
+"Začnu křičet..."
+"Budu křičet..."

-"I'll never forget this night."
+"Nikdy nezapomenu na tuto noc."
+"Nikdy nezapomenu na dnešní noc ."

-"I feel a chill."
+"Je mi chladno."
+"Cítím mrazení."

-"Yeah?"
+"Jo?"

-"So what are you gonna do tonight, hm?"
+"Co máš ty dnes večer v plánu, hm?"
+"Co budeš dnes večer dělat, hm?"

-"What do you want?"
+"Co chceš?"

-"What's the emergency?"
+"Kdepak hoří?"

-"Evening."
+"Večír."

-"I'm eating."
+"Já jím."

-"Uhh, I'm busy here..."
+"Nemám čas..."
+"Jsem zaneprázdněná.."

**Comment by soulcharmer** [comment]
-"Hey, cutie."
+"Čau, zlato."

-"Like what you see?"
+"Líbí se ti, co máš před očima?"
+"Líbí se ti to,co vidíš?"
+"Líbí se ti, co vidíš?"

-"I'm with somebody."
+"Jsem tu s někým."
+"S někým tady jsem."
+"Někoho mám."

-"What?!"
+"Cože?!"

-"Eh, not interested."
+"Eh, nezájem."
+"Eh, nemám zájem."

-"What ever." - float hláška návštevnice klubu pri konfrontácii
+"Nezájem."
+"To je jedno."
+"Nezájem."

-"Buy a watch."
+"Kup si své hodinky."
+"Kupte si hodinky."

-"I'll scream..."
+"Začnu křičet..."
+"Budu křičet..."

-"I'll never forget this night."
+"Nikdy nezapomenu na tuto noc."
+"Nikdy nezapomenu na dnešní noc ."
+"Na dnešní noc nikdy nezapomenu."

-"I feel a chill."
+"Je mi chladno."
+"Cítím mrazení."
+"Je mi zima."

-"Yeah?"
+"Jo?"

-"So what are you gonna do tonight, hm?" - zvuková maľba vety v dabingu dáva primárny dôraz na slovo you
+"Co máš ty dnes večer v plánu, hm?"
+"Co budeš dnes večer dělat, hm?"
+"Tak co máš dneska v plánu?"

-"What do you want?"
+"Co chceš?"

-"What's the emergency?"
+"Kdepak hoří?"
+"Co se děje?"

-"Evening."
+"Večír."
+"Zdravím."

-"I'm eating."
+"Já jím."

-"Uhh, I'm busy here..." - float hláška jediacej návštevnice jedálne
+"Nemám čas..."
+"Jsem zaneprázdněná.."
+"Nemám čas..."
