### ISSUE TITLE
Translate LIP float male asian

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#90]
cestina\sound\character\male\asian

**Comment by miracleflame** [comment]
-"No English, no English."
 +"Ne anglicky, ne anglicky."

-"No speak English."
 +"Nemluvit anglicky."

-"Hey you!"
 +"Hej ty!"

**Comment by maarten93** [comment]
-"No English, no English."
+"Ne anglicky, ne anglicky."

-"No speak English."
+"Nemluvit anglicky."

-"Hey you!"
+"Hej ty!"

**Comment by soulcharmer** [comment]
dobry, diky
