### ISSUE TITLE
Translate LIP float male blueblood

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#91]
cestina\sound\character\male\blue_blood

**Comment by miracleflame** [comment]
-"Oh dear... Are you not well?"
 +"Propána... Není vám dobře?"

-"Breathe..."
 +"Dýchejte..."

-"What's the matter?"
 +"Co je vám?"

-"Oh, dear god... it's- it's- it's terrible... God in heaven!"
 +"Ó, dobrý bože... to je- to je strašlivé... dobrotivý bože!"

-"Oh, dear... Oh my!"
 +"Probůh... panebože!"

  -"Ahhh! Oh heavens! Ohh, it's terrible!"
 +"Nebesa! To je strašné!"

-"Oh, sweet mother of god!"
 +"Óó, svatá matičko boží!"

-"I beg your pardon."
 +"Račte prominout."

-"Sorry, I'm afraid I can't help."
 +"Omlouvám se, nemůžu vám pomoct."

-"Good evening to you."
 +"Přeji vám hezký večer."

-"Good evening to you, all the same."
 +"Taky vám přeju hezký večer."

-"I'm sorry, I- I can't help you."
 +"Omlouvám se, já- nemůžu vám pomoct."

-"No, I- I really don't understand you."
 +"Ne, já- já vám opravdu nerozumím."

  -"Urm... Eww... Oh my, how did I end up here?"
 +"Panečku, jak jsem se dostal sem?"

-"Oh dear... Excuse me... I don't quite know where I am."
 +"No tohle... promiňte... nevím přesně, kde to jsem."

-"Oh dear god, the voices..."
 +"Dobrotivý bože, ty hlasy..."

-"Oh... What?... Oh dear... Oh dear god, the voices..."
 +"Cože?... Propána... dobrotivý bože, ty hlasy..."

-"Oh... Oh.. Oh... Oh dear god... it's terrible... help."
 +"Panebože... to je strašné... pomoc."

-"Oh my..."
 +"No tohle..."

-"Hello? Who's there?"
 +"Haló? Kdo je tam?"

-"Who's there? Hello?"
 +"Kdo je tam? Haló?"

-"I knew I've heard something."
 +"Věděl jsem, že něco slyším.

**Comment by maarten93** [comment]
"Oh dear... Are you not well?"
+"Propána... Není vám dobře?"

-"Breathe..."
+"Dýchejte..."

-"What's the matter?"
+"Co je vám?"
+"Co se děje?"

-"Oh, dear god... it's- it's- it's terrible... God in heaven!"
+"Ó, dobrý bože... to je- to je strašlivé... dobrotivý bože!"
+"Ach, bože... to je- to je hrozné... Bože na nebesích!"

-"Oh, dear... Oh my!"
+"Probůh... panebože!"

-"Ahhh! Oh heavens! Ohh, it's terrible!"
+"Nebesa! To je strašné!"
+"Ach nebesa! To je hrozné!"

-"Oh, sweet mother of god!"
+"Óó, svatá matičko boží!"
+"Ach, svatá matko boží!"

-"I beg your pardon."
+"Račte prominout."
+"Promiňte."

-"Sorry, I'm afraid I can't help."
+"Omlouvám se, nemůžu vám pomoct."
+"Omlouvám se, ale obávám se, že vám nemohu pomoct."

-"Good evening to you."
+"Přeji vám hezký večer."

-"Good evening to you, all the same."
+"Taky vám přeju hezký večer."
+"Taky vám přeji hezký večer."

-"I'm sorry, I- I can't help you."
+"Omlouvám se, já- nemůžu vám pomoct."
+"Je mi líto, já- nemůžu vám pomoci."

-"No, I- I really don't understand you."
+"Ne, já- já vám opravdu nerozumím."

-"Urm... Eww... Oh my, how did I end up here?"
+"Panečku, jak jsem se dostal sem?"
+"Panečku, jak jsem se sem dostal?"

-"Oh dear... Excuse me... I don't quite know where I am."
+"No tohle... promiňte... nevím přesně, kde to jsem."
+"Propána... promiňte... vůbec nevím, kde to jsem."


-"Oh dear god, the voices..."
+"Ach můj Bože, ty hlasy..."
+"Ach můj bože, ty hlasy..."

-"Oh... What?... Oh dear... Oh dear god, the voices..."
+"Cože?... Propána... dobrotivý bože, ty hlasy..."
+"Cože?... Propána... ach můj bože, ty hlasy..."

-"Oh... Oh.. Oh... Oh dear god... it's terrible... help."
+"Panebože... to je strašné... pomoc."

-"Oh my..."
+"No tohle..."

-"Hello? Who's there?"
+"Haló? Kdo je tam?"

-"Who's there? Hello?"
+"Kdo je tam? Haló?"

-"I knew I've heard something."
+"Věděl jsem, že něco slyším.

**Comment by soulcharmer** [comment]
jen par drobnych uprav:


-"Sorry, I'm afraid I can't help."
+"Omlouvám se, nemůžu vám pomoct."
+"Omlouvám se, obávám se, že vám nemohu pomoct."
+"Promiňte, ale nemohu Vám pomoci."

-"Good evening to you, all the same."
+"Taky vám přeju hezký večer."
+"Taky vám přeji hezký večer."
+"I tak Vám přeji hezký večer."

-"Urm... Eww... Oh my, how did I end up here?"
+"Panečku, jak jsem se dostal sem?"
+"Panečku, jak jsem se sem dostal?"
+"Propána, jak jsem se sem dostal?"

-"Oh dear... Excuse me... I don't quite know where I am."
+"No tohle... promiňte... nevím přesně, kde to jsem."
+"Propána... promiňte... vůbec nevím, kde to jsem."
+"Propána... promiňte... nějak nevím, kde to jsem."


diky
