### ISSUE TITLE
Translate LIP float male bum

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#92]
cestina\sound\character\male\bum

**Comment by miracleflame** [comment]
-"Ohh, it's terrible!"
 +"To je strašné!"

-"Take a walk, pal."
 +"Odkráčej, kámo."

-"Go away."
 +"Jdi pryč."

-"Get lost."
 +"Strať se."

-"This is my stuff, man, get away from my stuff."
 +"To jsou mý věci, čéčé, padej od mých věcí."

-"Get away from my stuff."
 +"Padej od mých věcí."

**Comment by soulcharmer** [comment]
-"Ohh, it's terrible!"  - ok
+"To je strašné!"

-"Take a walk, pal."   - potrebujeme nejspis unisex, ze?
+"Dej si odchod."

-"Go away."
+"Běž pryč."

-"Get lost."
+"Zmizni."

-"This is my stuff, man, get away from my stuff."
+"To jsou mý věci, čéčé, nech je na pokoji."

-"Get away from my stuff."
+"Nech moje věci být."


diky
