### ISSUE TITLE
Translate LIP float male citizen*

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#93]
cestina\sound\character\male\citizen*

**Comment by miracleflame** [comment]
-"Oh no! Whaa..."
 +"To ne! Ááá..."

-"Oh dear!"
 +"Panečku!"

-"Oh no!"
 +"To ne!"

-"Oh good heavens!"
 +"Ó, nebesa!"

-"Erm, right."
 +"Jistě."

-"A- e- right."
 +"Jistě."

-"Hey, sorry man."
 +"Hele, promiň, člověče."

-"Sorry, man."
 +"Promiň vole."

-"Out of my way."
 +"Z cesty."

-"It's not my problem."
 +"To není můj problém."

-"Pfff...I don't think so, buddy."
 +"Pfff...nemyslím si, kámo."

-"Hey buddy, go your own way."
 +"Hele, jdi si po svým."

-"I don't think so."
 +"Nemyslím si."

-"Pffft, not today."
 +"Pffft, ne dnes."

-"Just...Back off!"
 +"Prostě...dej pokoj!"

-"Don't touch me, hm?"
 +"Nedotýkej se mě, hm?"

-"Tonight's the night out, huh?"
 +"Dnes večer na lovu, co?"

-"Lovely evening!"
 +"Krásnej večer!"

-"One, two, ah, damn it! One, two, three, four, uff, ah whatever, dude..."
 +"Jedna, dvě, ale, sakra! Jedna, dve, tři, čtyři, uff, kašlat na to, vole..."

**Comment by maarten93** [comment]
-"Oh no! Whaa..."
+"To ne! Ááá..."

-"Oh dear!"
+"Panečku!"
+"Propána!"

-"Oh no!"
+"To ne!"

-"Oh good heavens!"
+"Ó, nebesa!"
+"Pane Bože!"


-"Erm, right."
+"Jistě."

-"A- e- right."
+"Jistě."

-"Hey, sorry man."
+"Hele, promiň, člověče."
+"Hele, promiň, čéče."

-"Sorry, man."
+"Promiň vole."

-"Out of my way."
+"Z cesty."
+"Uhni mi z cesty."


-"It's not my problem."
+"To není můj problém."

-"Pfff...I don't think so, buddy."
+"Pfff...nemyslím si, kámo."

-"Hey buddy, go your own way."
+"Hele, jdi si po svým."

-"I don't think so."
+"Nemyslím si."

-"Pffft, not today."
+"Pffft, ne dnes."

-"Just...Back off!"
+"Prostě...dej pokoj!"
+"Prostě...Odprejskni!"

-"Don't touch me, hm?"
+"Nedotýkej se mě, hm?"
+"Nedotýkej se mě, jasný?"

-"Tonight's the night out, huh?"
+"Dnes večer na lovu, co?"

-"Lovely evening!"
+"Krásnej večer!"
+"Krásný večer!"

-"One, two, ah, damn it! One, two, three, four, uff, ah whatever, dude..."
+"Jedna, dvě, ale, sakra! Jedna, dve, tři, čtyři, uff, kašlat na to, vole..."

**Comment by soulcharmer** [comment]
-"Oh no! Whaa..."
+"To ne! Ááá..."
+"To snad ne! Ááá..."

-"Oh dear!"
+"Panečku!"
+"Propána!"

-"Oh no!"
+"To snad ne!"

-"Oh good heavens!"
+"Ó, nebesa!"
+"Pane Bože!"

-"Erm, right."
+"Jistě."
+"Ehm, jistě."

-"A- e- right."
+"Jistě."
+"...jistě."

-"Hey, sorry man."
+"Hele, promiň, člověče."
+"Hele, promiň, čéče."

-"Sorry, man."
+"Promiň vole."
+"Promiň, vole."

-"Out of my way."
+"Z cesty."
+"Uhni mi z cesty."
+"Uhni."

-"It's not my problem."
+"To není můj problém."

-"Pfff...I don't think so, buddy."
+"Pfff...nemyslím si, kámo."
+"Pfff... to neklapne, kámo."

-"Hey buddy, go your own way."
+"Hele, jdi si po svým."

-"I don't think so."
+"Nemyslím si."
+"To neklapne."

-"Pffft, not today."
+"Pffft, ne dnes."
+"Pfff, dnes ne."

-"Just...Back off!"
+"Prostě...dej pokoj!"
+"Prostě...Odprejskni!"
+"Odprejskni!"

-"Don't touch me, hm?"
+"Nedotýkej se mě, hm?"
+"Nedotýkej se mě, jasný?"
+"Nesahej na mě, jasný?"

-"Tonight's the night out, huh?"
+"Dnes večer na lovu, co?"

-"Lovely evening!"
+"Krásnej večer!"
+"Krásný večer!"
+"Krásná noc!"

-"One, two, ah, damn it! One, two, three, four, uff, ah whatever, dude..."
+"Jedna, dvě, ale, sakra! Jedna, dve, tři, čtyři, uff, kašlat na to, vole..."
+"Jedna, dvě... sakra! Jedna, dvě, tři, čtyři... uf, kašlu na to, vole..."

diky
