### ISSUE TITLE
Translate LIP float male giovanni_guest_2

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#95]
cestina\sound\character\male\giovanni_guest_2

**Comment by miracleflame** [comment]
-"Hey, how've you been?"
 +"Hej, jak se vede?"

-"So how is Bruno?"
 +"Tak jak se má Bruno?"

-"So how is Bruno doing?"
 +"Tak jak se vede Brunovi?"

-"So nice to see you again."
 +"Je hezké znovu se vidět."

-"Hey, how've you been?"
 +"Hej, jak se vede?"

-"It's so nice to see you again."
 +"Rád tě opět vidím."

**Comment by soulcharmer** [comment]
dobry, diky
