### ISSUE TITLE
Translate LIP float male italian_accent

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#96]
cestina\sound\character\male\italian_accent

**Comment by miracleflame** [comment]
-"Hey, hey you, stop!"
 +"Hej, hej ty, stůj!"

-"Hey, hey, hey, stop right there!"
 +"Hej, hej, hej, zůstaň, kde jsi!"

-"Freeze asshole!"
 +"Ani hnout, zmrde!"

-"I do not know!"
 +"Já nevím!"

-"They're gone!"
 +"Je pryč!"

-"I can not find them!"
 +"Nevím, kde je!"

-"Who's there?"
 +"Kdo je tam?

"Where are you?"
 +"Kde jseš?"

-"Wait- hey- I heard something."
 +"Počkat- hej- Něco jsem slyšel."

-"Hey- hey- what was that?"
 +"Hej- hej- co to bylo?"

-"Who's there?"
 +"Kdo je tam?"

**Comment by soulcharmer** [comment]
-"Hey, hey, hey, stop right there!"
+"Hej, hej, hej, zůstaň, kde jsi!"
+"Hej, hej, hej, už ani krok!"

jinak dobry, diky
