### ISSUE TITLE
Translate LIP float male museum_guard

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#97]
cestina\sound\character\male\museum_guard

**Comment by miracleflame** [comment]
-"Out of my way, sorry, excuse me,..."
 +"Z cesty, promiňte, omlouvám se..."

-"Out of my way..."
 +"Z cesty..."

-"Get out of my way..."
 +"Uhněte mi z cesty..."

-"He got away!"
 +"Je pryč!"

-"Call for backup!"
 +"Přivolejte posily!"

-"Must've fled the scene!"
 +"Už musí být mimo místa činu!"

**Comment by soulcharmer** [comment]
-"Out of my way, sorry, excuse me,..."
+"Z cesty, promiňte, omlouvám se..."
+"Promiňte, uhněte, omlouvám se..."

-"Out of my way..."
+"Z cesty..."
+"Uhněte..."

-"Get out of my way..."
+"Uhněte mi z cesty..."

-"He got away!"
+"Je pryč!"

-"Call for backup!"
+"Přivolejte posily!"
+"Zavolejte posily!"

-"Must've fled the scene!"
+"Už musí být mimo místa činu!"
+"Už není na místě činu!"
