### ISSUE TITLE
Translate LIP float male officer

### ISSUE THREAD

**Issue by miracleflame** [soulcharmer/gog_bloodlines_cz#98]
cestina\sound\character\male\officer

**Comment by miracleflame** [comment]
lipy označené BUGGED  (všetky target_reacquired_*.lip) sú podľa dizajnu hry prehrané asi na stotinu sekundy v momente, keď NPC objaví PC po tom, čo už raz boli v boji, ale PC sa ukryl a NPC prešiel do stavu hľadania... Po stotine sekundy sa však hneď pustí aj target_acquired_*.lip a pôvodný zvuk target_reacquired sa tým pádom neprehrá a floating titulky zobrazia dve podobné hlášky, pričom počuť je iba druhú z nich. Flag BUGGED by mal zabezpečiť, že sa lip corruptne a nezobrazí, čo je želaný stav, pretože dizajn prehrávania je podľa Wespa neopraviteľný.

**Comment by miracleflame** [comment]
-"I'm on a break."
+"Mám přestávku."

-"Move along."
+"Pokračujte."

-"Sorry, I'm busy."
+"Promiňte, jsem zaneprázdněn."

-"Uhh, I'm busy."
+"Jsem zaneprázdněn."

-"You want a jaywalking ticket?"
+"Chcete pokutu za potulku?"

-"Move along."
+"Pokračujte."

-"Uhh, call it in."
+"Zavolejte si na centrálu."

-"I'm off duty."
+"Nemám službu."

-"Yeah, I'm on a break."
+"Jo, ale já mám přestávku."

-"Go ahead and walk on away now."
+"Pokračujte pryč odsud."

-"This is closed crime scene."
+"Tohle je uzavřená oblast místa činu."

-"Didn't I tell you to get away from there?"
+"Neříkal jsem vám, aby jste odsud odešli?"

-"You're gonna have to move along now."
+"Budete muset hned odejít."

-"Nothing back there for you to see."
+"Není tady pro vás nic k vidění."

-"This is closed crime scene."
+"Tohle je uzavřená oblast místa činu."

-"Didn't I tell you to get away from there?"
+"Neříkal jsem vám, aby jste odsud odešli?"

-"You're gonna have to move along now."
+"Budete muset hned odejít."

-"You can't get back here, I'm sorry."
+"Dozadu nemůžete jít, je mi líto."

-"Move along, nothing to see here."
+"Pokračujte, není tady nic k vidění."

-"Suspect lost."
+"Podezřelý zmizel."

-"Suspect's fled the scene."
+"Podezřelý utekl z místa činu."

-"Going to need some backup."
+"Budu potřebovat zálohu."

-"Suspect's fled the scene."
+"Podezřelý utekl z místa činu."

-"Suspect lost."
+"Podezřelý zmizel."

-"I don't know."
+"Já nevím."

-"I don't know where they went."
+"Nevím, kde je."

-"Police!"
+"Policie!"

-"Stop right there!"
+"Zůstaňte, kde jste!"

-"Freeze!"
+"Ani hnout!"

-"I said freeze!"
+"Řekl jsem ani hnout!"

-"Don't move!"
+"Stůjte!"

-"Stop right there!"
+"Zůstaňte, kde jste!"

-"Cop down!"
+"Policajt zasažen!"

-"Suspect lost."
+"Podezřelý zmizel."

-"Suspect's fled the scene."
+"Podezřelý utekl z místa činu."

-"Who's there?"
+"Kdo je tam?"

-"What was that?"
+"Co to bylo?"

**Comment by soulcharmer** [comment]
nejake opravy:


-"Sorry, I'm busy."
+"Promiňte, jsem zaneprázdněn."
+"Promiňte, nemám čas."

-"Uhh, I'm busy."
+"Jsem zaneprázdněn."
+"... mám práci."

-"You want a jaywalking ticket?"
+"Chcete pokutu za potulku?"
+"Chcete pokutu za nedovolené přecházení?"

-"Uhh, call it in."
+"Zavolejte si na centrálu."
+"Zavolejte na centrálu."

-"Yeah, I'm on a break."
+"Jo, ale já mám přestávku."
+"Jo, mám přestávku."

-"Go ahead and walk on away now."
+"Pokračujte pryč odsud."
+"Seberte se a běžte pryč."

-"This is closed crime scene."  (2x?)
+"Tohle je uzavřená oblast místa činu."
+"Toto je místo činu s omezeným vstupem."

-"Didn't I tell you to get away from there?"  (2x?)
+"Neříkal jsem vám, aby jste odsud odešli?"
+"Neříkal jsem, že máte jít pryč?"

-"Nothing back there for you to see."
+"Není tady pro vás nic k vidění."
+"Tam není nic pro vás."

-"You can't get back here, I'm sorry."
+"Dozadu nemůžete jít, je mi líto."
+"Nezlobte se, ale dozadu nemůžete."

-"Going to need some backup."
+"Budu potřebovat zálohu."
+"Budu potřebovat posily."

-"I don't know."
+"Já nevím."
+"Co já vím."

-"Stop right there!"
+"Zůstaňte, kde jste!"
+"Už ani krok!"

-"Cop down!"
+"Policajt zasažen!"
+"Máme oběť!"




diky
